### ISSUE TITLE
Change travis ruby version to 2.3

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1000]
### Descriptive summary

The Sufia engine is now being tested on ruby 2.3.1. We should begin testing scholar on ruby 2.3.

**Comment by hortongn** [comment]
@crowesn This PR is probably a good opportunity to add a .ruby-version file to our repo.  It will help make sure everyone is using 2.3.1 locally.

**Comment by hortongn** [comment]
@crowesn FYI https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released
