### ISSUE TITLE
Integrate Kaltura as provider for browse-everything

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1008]
### Descriptive summary

Integrate Kaltura into browse-everything

### Related work

https://github.com/projecthydra/browse-everything/pull/137

https://developer.kaltura.com/console/#/user.loginByLoginId

**Comment by scherztc** [comment]
Size: 4

**Comment by crowesn** [comment]
## Kaltura Authentication

I chatted with Glen about this issue this afternoon; about our constraints Kaltura re authentication. (kaltura does not have oauth - we're basically connecting to the api using the uc 6+2, scraped from the current_user credentials. I had the idea while walking to my car that maybe we could use UC shibboleth as a kind of poor-man's oauth for connecting to kaltura in browse-everything. 

Why don't we start the kaltura api connection workflow by requiring everyone to authenticate (again) via shibboleth and using the 6+2 returned by that action to send on to kaltura. This solves a couple issues with our current implementation: admin accounts and proxy accounts connecting to kaltura via browse everything.

*Scholar 2: in a kaltura session through browse-everything, we send the user.email from current user session, regardless of whether it's an admin account or a non-uc account.*

If we required shibboleth authentication as part of connecting to kaltura in browse-everything, we would be able to trust that the credentials we send to the kaltura api are authenticated. 

Glen said that he thought that we could manually end the shibboleth session on login to scholar so that we don't have clashes between sessions if we were to do this.

### Some gotchas
* Non-uc accounts would be precluded from connecting to kaltura but I think that's okay because they wouldn't have any content on kaltura anyway.
* Accounts acting as proxy for others would only be able to connect to their own kaltura content, not to the parent's content. (maybe this is a feature?)

Please chime in @uclibs/developers
