### ISSUE TITLE
Handle illegal characters more gracefully on input forms.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1010]
### Descriptive summary

A user reported the "file not found" general error message on submit.  I was able to observe her and saw that she had unusual characters in the title field.  I suggested she remove the characters and the input process then completed successfully.

She was using a copy and paste method to copy the title from the first slide of a powerpoint into the input form.  I did the same thing and incurred the same error on scholar-dev.  Attached is a screenshot of the error message.  I think the bad character may have been a line break or return character.  The error message says: msg'=>'Illegal character ((CTRL-CHAR, code 11)

The source powerpoint can be found attached to this work: https://scholar.uc.edu/show/bc386k63b

### Expected behavior
Scholar@UC should either strip the character or replace it with a space, or alert the user in a non-destructive way that they must delete the character.

### Actual behavior
The RSolr Error becomes a File Not Found Error in production.  It is unclear that the user can backspace and be returned to the input form.

### Steps to reproduce the behavior

1. Open the power point attached to the work above.  Copy the three lines of title information on the first slide. 
2. Create a new generic work on scholar-dev.  Paste the title information into the title field or the description field.  The error will occur upon submit.  Probably would happen with any text field on the input form.

![badcharacterinputerror](https://cloud.githubusercontent.com/assets/3521707/20773604/98af7b04-b720-11e6-9aa0-65d92613fa05.jpg)

**Comment by newmanld** [comment]
Similar error occurs in Scholar 3.x.  See attached screenshot.  
![badcharacterinputerror-scholar3](https://cloud.githubusercontent.com/assets/3521707/20773761/6f279388-b721-11e6-9185-19bd03196bcf.jpg)

**Comment by newmanld** [comment]
See #1022

**Comment by hortongn** [comment]
FYI, downloading the PowerPoint and copying/pasting the title into a new work did not recreate the error for me.  Maybe it has something to do with being on a Mac or Mac Office, etc.  However, I could recreate the error by

1. creating a blank Word doc
1. type a simple word
1. press ctrl-enter (this will jump you to a new page and create the invisible vertical tab)
1. type another simple word
1. highlight all text in the document and copy to the clipboard
1. paste the contents into the title of a new work and submit

**Comment by hortongn** [comment]
In 2.x-stable, we can create a new method in the ParamsHelper to scan params for vertical tabs and filter them out.
