### ISSUE TITLE
Research - how to group

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1017]
How do groups work in Sufia 7? Can users make groups?

**Comment by scherztc** [comment]
Size: 2

**Comment by scherztc** [comment]
After talking with Mike Giarlo there is one default group that comes from Devise.  Registered.  Penn State did some work in the past with using LDAP groups inside of Scholarsphere to have College and Departmental groups.  As far as user created groups, that is still in the works. 

So there is no UX for group creation or adding members.
