### ISSUE TITLE
png files will not attach

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1021]
### Descriptive summary

I tried to attach a png file to a new work.  It was flagged with 'unknown error'.

### Expected behavior
The png file should be handled like jpgs.  Thumbnails should also be generated.

### Actual behavior
Although only with one file so far (will do more testing), the png file was essentially rejected.

**Comment by newmanld** [comment]
I now have success with one png file but failure with another.  I will keep researching.

**Comment by newmanld** [comment]
Problematic png:
![1476129119847](https://cloud.githubusercontent.com/assets/3521707/20944217/92051ae8-bbd0-11e6-9798-b320a5245f8b.png)

**Comment by newmanld** [comment]
png that attached without issue (after I downloaded it first to my desktop): https://www.drupal.org/files/issues/sample_7.png

**Comment by crowesn** [comment]
I'm unable to locally reproduce this error in OSX: Firefox/Chrome. 

Curly is tied up with another issue - was this bug encountered on Curly?

**Comment by newmanld** [comment]
This bug was encountered by me on Curly, and it may be limited to using a windows PC – I uploaded what I thought was the same png file (downloaded from same source) on OSX and did not have the problem.

**Comment by crowesn** [comment]
Okay, working on getting my windows vm up, @scherztc please let me know when you're finished with experimental stuff on Curly.

**Comment by scherztc** [comment]
Size: 2
