### ISSUE TITLE
Handle illegal characters more gracefully on input forms - Scholar 3.x

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1022]
### Descriptive summary

A CTRL-CHAR - probably other characters too, in a title and other metadata fields, will cause the input form to fail.

### Expected behavior
Scholar@UC should either strip the character or replace it with a space, or alert the user in a non-destructive way that they must delete the character.

### Actual behavior
The user receives an RSOLR:error

### Steps to reproduce the behavior
Here's one example with an attached file, where if you cut and paste the title from the attached powerpoint you will re-create the error:
 https://scholar.uc.edu/show/bc386k63b

Open the power point attached to the work above. Copy the three lines of title information on the first slide.

Create a new generic work on scholar-dev. Paste the title information into the title field or the description field. The error will occur upon submit. Probably would happen with any text field on the input form.
### Related work

See #1010

**Comment by newmanld** [comment]
![scholar3 xcharbug](https://cloud.githubusercontent.com/assets/3521707/20939272/2ca19b36-bbbc-11e6-943d-ab4e2a80156a.jpg)

**Comment by scherztc** [comment]
Size: 4

**Comment by hortongn** [comment]
FYI, downloading the PowerPoint and copying/pasting the title into a new work did not recreate the error for me.  Maybe it has something to do with being on a Mac or Mac Office, etc.  However, I could recreate the error by

1. creating a blank Word doc
1. type a simple word
1. press ctrl-enter (this will jump you to a new page and create the invisible vertical tab)
1. type another simple word
1. highlight all text in the document and copy to the clipboard
1. paste the contents into the title of a new work and submit

**Comment by newmanld** [comment]
Notes that may or may not help:

I can confirm that both the person who first had the problem, and me - when I replicated the problem, were using Windows PCs.  (Windows 7 enterprise is what's on my desk.)  

If I cut&paste the title into various applications I can see the charcter showing up differently:

In Notepad++ it shows two characters bolded and marked as VT:  
   Beyond a College Paper:**VT**Teaching Best Practices**VT**in Visual Communication

In Word, setting my preferences to 'show all characters', it shows up as a symbol that I recognize as a return character.

In notepad, it shows up as a different unrecognizable symbol.

In the dos terminal window, it shows up as ^K.

**Comment by crowesn** [comment]
https://github.com/projecthydra/active_fedora/issues/1154

**Comment by hortongn** [comment]
We can maybe put that change in our app as a monkey patch until it gets released in rsolr.
