### ISSUE TITLE
Proxy Submission transfer incomplete

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1023]
### Descriptive summary

As a proxy, when I submit a work on behalf of an owner, the owner will see this message in user activity:
"User &lt;proxy email address&gt; has transferred &lt;work title&gt; to user &lt;owner email address&gt;"
However, the owner does not have edit access until the proxy edits the work and saves it again.  I have replicated this twice.

### Expected behavior
The owner should gain edit access when the work is first created by the proxy - not after the proxy edits the work a second time.

### Actual behavior
It appears (validated twice - more testing is in order), that a second edit is needed before the owner gains edit access.

**Comment by hortongn** [comment]
Note: This bug only exists for works with **no** attached files.  If a proxy creates a work **with** attached files, the owner gets edit rights without the proxy having to edit and save the work again.
