### ISSUE TITLE
Proxy access removal is incomplete

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1024]
### Descriptive summary

As an owner, if I remove someone as my proxy, they can no longer submit new works on my behalf, but they can still edit works that they submitted as my proxy.

### Expected behavior
When I remove someone as my proxy, they should lose edit access to works they earlier submitted, as well as lose the ability to edit works that they submitted as my proxy.

### Actual behavior
A former proxy can no longer submit works on the owner's behalf, but can still edit works that they submitted as a proxy.  They are still listed as an Editor on the Share tab if the owner edits the work.

### Steps to reproduce the behavior

1. As an owner assign a proxy
1. As the proxy submit a work on behalf of the owner
1. As the owner remove the proxy.

**Comment by newmanld** [comment]
See also #1025

**Comment by newmanld** [comment]
One additional comment.  When a proxy submits a work on behalf of an owner, the owner sees an entry on their dashboard that says that they proxy has transferred the work to them.  The proxy then is at the same time automatically made an editor on the work.  So, it is theoretically possible that an owner could have assigned the proxy to be an editor on works which the proxy did not submit.  When the owner removes a proxy, it may be impossible for Scholar@UC to distinguish at that point why they are an editor.  Therefore I will ask the P.O.s to tell us if the owner should be prompted, when they remove a proxy, something like the following:

You are removing &lt;proxy name&gt; as your proxy.  They will no longer be able to submit works on your behalf.  Should they also be removed as an editor on the works they previously submitted (or where you assigned edit rights)?  Yes/No

**Comment by newmanld** [comment]
See related card in Trello.

**Comment by jamesvanmil** [comment]
https://trello.com/c/vsFjyksS/59-as-a-submitter-if-i-revoke-someone-as-my-proxy-i-should-be-prompted-as-to-whether-they-should-also-be-removed-as-an-editor-of-wo

**Comment by jamesvanmil** [comment]
Per discussion with Linda proceeding without giving the user the option to cancel the Proxy removal, which is consistent with current behavior in both Curate and Sufia.

Clicking the X to remove proxy access from a user will trigger a model which will give the user the option of running a job to remove the user as editor of their works.

**Comment by jamesvanmil** [comment]
Okay to proceed as noted above, per discussion on 2017-02-16

**Comment by hortongn** [comment]
Tested this again now that the LDP::Gone error has been resolves and I verified that this bug has also been resolved (in both Sufia and our app).  So marking as closed.

**Comment by hortongn** [comment]
Meant to comment and close a different issue.  Re-opening this

**Comment by hortongn** [comment]
Just verifying that the behavior reported above still exists with Sufia 7.3.0.rc3.  So this is still an issue that needs to be resolved.
