### ISSUE TITLE
Test mobile responsive views

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1030]
### Descriptive summary

Any feature that may have a different behavior with mobile responsive view should be identified and tested at lower res.

* Perhaps we can set a viewport with narrow width with extended height

**Comment by lisa3711** [comment]
I can do this? I would like to try "Blisk" for this... :-)

**Comment by lawhorkl** [comment]
testing this while reviewing #1045 see issue comments for any bugs found

**Comment by lawhorkl** [comment]
some issues found with mobile scholar should be discussed as they are not bugs per say, but bad formatting of the views within sufia

**Comment by lawhorkl** [comment]
![image](https://cloud.githubusercontent.com/assets/12615997/23038943/cd5a6226-f459-11e6-85c1-962daa44db7c.png)

**Comment by lawhorkl** [comment]
![image](https://cloud.githubusercontent.com/assets/12615997/23039346/41b2b44c-f45b-11e6-8ae8-f274ad18001f.png)

**Comment by lawhorkl** [comment]
![image](https://cloud.githubusercontent.com/assets/12615997/23039984/a411f6be-f45d-11e6-9636-94d746d19ae1.png)

![image](https://cloud.githubusercontent.com/assets/12615997/23039992/ab8ad9d8-f45d-11e6-868c-372958a6acf0.png)

![image](https://cloud.githubusercontent.com/assets/12615997/23040003/b5073eb6-f45d-11e6-83c3-f61a6d9e207f.png)
