### ISSUE TITLE
Allow developer access to Fedora interface

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#104]
The web interface is currently locked down and gives a 403 Forbidden message.

**Comment by jamesvanmil** [comment]
Need to assess how to balance security and access before implementation

**Comment by scherztc** [comment]
In the fedora XAML polices there is an allow setting:  

/usr/local/fedora/data/fedora-xacml-policies/repository-policies

there are two policies:
allow-apim-if-scholar.xml
allow-apia-if-scholar.xml

We need to add an allow to each policy on each environment:

<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">TUNNEL SERVER</AttributeValue>

We made the changes to the files in our ID Vault
https://git.uc.edu/UCLIBS/config_vault.

**Comment by scherztc** [comment]
1.  Agree on TUNNEL SERVER.
2.  Configure TUNNEL SERVER.
3.  Copy XACML files to environments.
4.  Document on Wiki :  Fedora Manager Procedures.

**Comment by hortongn** [comment]
With changes made to the XACML policies, we can access the Fedora GUI by creating a SOCKS proxy using an ssh tunnel.  Until we get a wiki page created, the details are below.

`ssh -D 9999 -C larry.libraries.uc.edu`

After entering your password, the tunnel will be in place.  The next step is to configure Firefox to use a SOCKS proxy:

1. Firefox> Edit> Preferences> Advanced tab> Network tab> Settings button.
2. Select Manual proxy configuration
3. SOCKS Host: localhost Port: 9999
4. SOCKS v5
5. No Proxy for: localhost, 127.0.0.1

Any site you visit in Firefox will now first pass through Larry.  So other website will see your traffic as if Larry is the source.  You will then be able to access the Fedora GUI for dev, QA, and production.

To turn off the proxy, switch to "No proxy" in Firefox's Network settings and then log out of your ssh session to Larry

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/wiki/Access-the-Fedora-Manager-Tools

**Comment by jamesvanmil** [comment]
Need to settle on an appropriate server to use as a proxy (e.g., not Larry), and deploy changes to qa and production.

**Comment by scherztc** [comment]
+1

**Comment by scherztc** [comment]
After talking with Dennis, he recommended that we use proxy.libraries.uc.edu (10.40.2.183).  If everyone is okay with this, then I will email him requesting accounts for (hortongn, scherztc, tallman, newmanld).

**Comment by hortongn** [comment]
Would someone be able to directly ssh to proxy.libraries.uc.edu from off campus or would it require them to be on the VPN first?

**Comment by scherztc** [comment]
You would have to be on vpn first. We do not allow the ssh port through the firewall. -D.Gavin

**Comment by scherztc** [comment]
Added proxy address to config_vault.

**Comment by hortongn** [comment]
All Fedora boxes are now configured to allow access from proxy.libraries.uc.edu.  The details below should probably be written up in wiki documentation.

1. Create an ssh tunnel to the UCL proxy server: `ssh -D 9999 -C proxy.libraries.uc.edu`
2. After entering your password, the tunnel will be in place.  

The next step is to configure Firefox to use a SOCKS proxy:

3. Firefox> Edit> Preferences> Advanced tab> Network tab> Settings button.
4. Select Manual proxy configuration
5. SOCKS Host: localhost Port: 9999
6. SOCKS v5
7. No Proxy for: localhost, 127.0.0.1

You can then access the Fedora web interface:
* Dev Fedora: https://curate-devdb.uc.edu
* QA Fedora: https://curate-qadb.uc.edu/fedora
* Production Fedora: https://curate-db.uc.edu/fedora
