### ISSUE TITLE
Fix Mobile issues

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1045]
### Descriptive summary

As a:  Mobile User.  I want to:  clean up 

F.1-  After failed login, names appear on mobile 
F.2- Mobile display in Dashboard shows About, Help, Contact opened as first thing on page. This is not shown at all on deskotp display 
F.4 - Weird display on edit Profile. So that:  mobile experience is better.  Criteria:  Approval of PO and DEV

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by lawhorkl** [comment]
##List of current display issues to be fixed:

*bugged secondary navbar on all pages (mobile):
![image](https://cloud.githubusercontent.com/assets/12615997/22797455/47814c60-eecc-11e6-9d3a-8b9ceda22c00.png)
