### ISSUE TITLE
Add the following HTML to the File Format Advice

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1048]
### Descriptive summary

Add the following HTML to the File Format Advice page, immediately before &lt;h4&gt;Preservation Files&lt;/h4&gt;  

 - &lt;h5&gt;Accessibility&lt;/h5&gt;        
&lt;p&gt;How you create your access files can have a great impact on those with disabilities. Scholar@UC encourages submitters to create accessible content for all. Some resources for creating accessible content can be found on the [Disability Services’ Faculty Resources](http://www.uc.edu/aess/disability/faculty_resources.html alt=”UC Faculty Resources on creating accessible content”) page. Additional resources are available from the [National Center on Disability and Access to Education](href=”http://ncdae.org/resources/cheatsheets/” alt=”Cheatsheets for creating accessible content.”).&lt;/p&gt;

**Comment by newmanld** [comment]
The external links in the new paragraph on accessibility are not formatted correctly and are thus not working.   We will need to fix and re-deploy.  See https://scholar.uc.edu/format_advice_request
