### ISSUE TITLE
Limit maximum upload/download size to 3GB per file

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1055]
Port behavior from Scholar 2

**Comment by crowesn** [comment]
Download: https://github.com/uclibs/curate/pull/91/
Upload: https://github.com/projecthydra-labs/hyrax/issues/119

**Comment by newmanld** [comment]
See https://groups.google.com/forum/#!topic/hydra-tech/b4HZty52lZg

**Comment by scherztc** [comment]
Still need to deal with SOLR file_size_is.

**Comment by hortongn** [comment]
@scherztc I've already opened another issue for the file_size_is bug (#1283).  So closing this.
