### ISSUE TITLE
Work creator does not persist on edit action

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1096]
### Descriptive summary

The creator does not carry over to edit form when editing an existing work. After clicking edit, the form is displayed with blank creator field

### Expected behavior

Existing creator attribute should carry over to edit form.

### Actual behavior

Creator field is blank in edit form, prevents saving.

### Steps to reproduce the behavior

1. Create a new work
1. Edit that work

### Related work

I think this may be associated with #1088

**Comment by crowesn** [comment]
This was mis-diagnosed: default User object has no name attributes defined, resulting in blank values populating the form.

**Comment by scherztc** [comment]
Size: 2
