### ISSUE TITLE
Research performance of nested works

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1101]
### Descriptive summary

Test on Curly

**Comment by scherztc** [comment]
Use the Marine Life collection to test building complex collections as Works within Works.
Test performance thresh hold when you increase the number of items in a work.
Do a Project Hydra review to see if there is any documented limits.

**Comment by scherztc** [comment]
Collection Extensions: https://wiki.duraspace.org/display/samvera/Code+for+Indexing
