### ISSUE TITLE
Research work-type facets vs resource-type facets

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1102]
In scholar 2.0: We have a facet for work type, with an additional, un-faceted field for genre.

In Scholar 3, we will need a facet for work types, and the Metadata folks are recommending mapping the genre field to resource type, retaining the facet, and expanding its use to other work types (beyond Document and Image).

We need to research and consider how to add work-type facets, and how they balance against resource-type selection and facets.

**Comment by scherztc** [comment]
Genre :  Needs to be a nested controlled language that will be different for each work type  
Use Genre for resource_type / work_type.

**Comment by scherztc** [comment]
Make sure that Student Works have a resource_type that shows up as a facet.
Exclude Student Work from Work Type facets.
Explore mediation.

**Comment by newmanld** [comment]
Consensus from the Product Owners is that we should keep Student Work as a separate work type, and drive a facet from it like we do each other work type (including ETDs).  They see Student Work as a facet as more useful than the format/genre for this category of works, and do not recommend that we try to also facet these works by format (documents, video, images, etc.).  

Our work types will therefore remain a mixed list of format (article, document, images, ...) and category ('Student Work',  'Thesis or Dissertation'), and that is ok with the P.O.s.  

Genre can still be a controlled language field, not faceted, and the controlled list can be, if needed, different for each work type as determined by metadata SMEs.

**Comment by scherztc** [comment]
Thank you for clearing up the Student Work type.  I can now begin coding the facet issue.

**Comment by scherztc** [comment]
Migrate genre list for work types that have it in Scholar 2.x to resource_type in Scholar 3.0.

Document and Image.
