### ISSUE TITLE
Display bug on fixed sidebar work create/edit page

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#1108]
### Descriptive summary

The sidebar needs a stop point so that it is not eclipsed by the footer thus making the save button inaccessible.

### Expected behavior
It should stop before the footer.
### Actual behavior
It does not.
### Steps to reproduce the behavior
1. Go to create/edit work page
2. Scroll down to the bottom of the page fully

![screen shot 2017-01-31 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/12615997/22483656/2c407dba-e7cc-11e6-953e-ee841f0ecd49.png)

**Comment by scherztc** [comment]
Add as SUFIA issue when we complete our application solution.

**Comment by crowesn** [comment]
I can't recreate this bug on my local, tested in chrome and firefox; perhaps fixed with sufia upgrade?
