### ISSUE TITLE
Research possible bug with denying orcid connection

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1112]
There was an incident when I was developing in which I clicked 'deny' instead of 'authorize' when connecting to an orcid record. I'm unsure if this was due to my numerous orcid test accounts or possibly being signed in on their sandbox site, but either way I want to dig deeper into this.

**Comment by crowesn** [comment]
We want to see what happens when a user clicks 'deny' instead of 'authorize' when signing into orcid. Correct?

**Comment by 13miciunasl** [comment]
Correct. I haven't been able to reproduce that behavior yet, so its looking like this may have been caused by already being signed in to orcid without realizing it.

**Comment by crowesn** [comment]
Would you mind confirming what happens when the user selects deny for either create or connect action?

**Comment by scherztc** [comment]
Size: 2
