### ISSUE TITLE
Reinstate spec for proxy creator auto-populate

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1113]
### Descriptive summary

Specs for creator proxy auto-populate have been erroneously shed.

https://github.com/uclibs/scholar_uc/commit/cdecdbe677c30c132ea46d4a285f878147c21256#diff-97c9d8786f5638fd05970e327a539efbL24

### Related work

#1096

**Comment by scherztc** [comment]
Size: 2
