### ISSUE TITLE
Brand and update footer

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1118]
### Descriptive summary

Update footer to conform with attached wireframe. Changes include branding, layout and size.

1. Desktop resolution
![footer-desktop](https://cloud.githubusercontent.com/assets/1069588/23513774/3a5774a2-ff33-11e6-9454-5a4926a97a95.png)

1. Mobile resolution
![footer-mobile](https://cloud.githubusercontent.com/assets/1069588/23513776/3c6310a8-ff33-11e6-8afc-6079cc7ad8f6.png)

**Comment by 13miciunasl** [comment]
Pending branding approval

**Comment by crowesn** [comment]
[Desktop-home-unauthenticated.pdf](https://github.com/uclibs/scholar_uc/files/784178/Desktop-home-unauthenticated.pdf)

**Comment by crowesn** [comment]
![uc_id_primarywhitered](https://cloud.githubusercontent.com/assets/1069588/23131870/ab17edca-f759-11e6-9a22-80c4e6a64fb5.png)

**Comment by 13miciunasl** [comment]
Does this look done to you?

![screen shot 2017-02-20 at 11 02 26 am](https://cloud.githubusercontent.com/assets/9759017/23132812/d163d0b8-f75c-11e6-9a26-c159f6dd7c91.png)

**Comment by crowesn** [comment]
I think we want all the text to be gray?



--

Sean Crowe
Digital Analyst and Developer Librarian

Digital Projects and Repositories.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edu<mailto:sean.crowe@uc.edu>
gchat: crowesn






On Feb 20, 2017, at 11:08 AM, 13miciunasl <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this look done to you?

[screen shot 2017-02-20 at 11 02 26 am]<https://cloud.githubusercontent.com/assets/9759017/23132812/d163d0b8-f75c-11e6-9a26-c159f6dd7c91.png>

**Comment by 13miciunasl** [comment]
Alright, is this good?

![screen shot 2017-02-20 at 11 41 33 am](https://cloud.githubusercontent.com/assets/9759017/23134111/90bf422c-f761-11e6-8801-3769e330f518.png)

**Comment by 13miciunasl** [comment]
I realize the hydra link is red, but it isn't obvious enough when its grey. At least in my opinion

**Comment by crowesn** [comment]
The center elements look misaligned. Are you using 4 columns?


--

Sean Crowe
Digital Analyst and Developer Librarian

Digital Projects and Repositories.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edu<mailto:sean.crowe@uc.edu>
gchat: crowesn






On Feb 20, 2017, at 11:42 AM, 13miciunasl <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright, is this good?

[screen shot 2017-02-20 at 11 41 33 am]<https://cloud.githubusercontent.com/assets/9759017/23134111/90bf422c-f761-11e6-8801-3769e330f518.png>

**Comment by 13miciunasl** [comment]
I got the center elements aligned with the 4 columns

![screen shot 2017-02-21 at 9 30 32 am](https://cloud.githubusercontent.com/assets/9759017/23169086/6dd7452c-f818-11e6-85a5-a1975a81ad20.png)

**Comment by crowesn** [comment]
@13miciunasl this should be ready for work.
