### ISSUE TITLE
Brand and update nav bar

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1119]
### Descriptive summary

Update branding, layout and size for nav bar, to conform with attached wireframe.

Nav height: 70px
uc logo (white png): 
![uc_id_secondarywhite](https://cloud.githubusercontent.com/assets/1069588/23512199/d4f6ef3e-ff2d-11e6-81a0-adc90287edef.png)
^^ invisible image

### States

Desktop resolution
1. Home page - unauthenticated
![top-nav](https://cloud.githubusercontent.com/assets/1069588/23512299/242ed3aa-ff2e-11e6-9bfa-03d08fa1b44d.png)

1. Home page - authenticated
![top-nav-authenticated-home](https://cloud.githubusercontent.com/assets/1069588/23512342/46da5820-ff2e-11e6-93f9-3fb4e8e55518.png)

1. Secondary pages - unauthenticated
![top-nav-unauthenticated-secondary](https://cloud.githubusercontent.com/assets/1069588/23512564/04d3706e-ff2f-11e6-8485-d7a6f40d70b7.png)

1. Secondary pages - authenticated
![top-nav-authenticated-secondary](https://cloud.githubusercontent.com/assets/1069588/23512533/e610cdde-ff2e-11e6-8a69-173f3adffd58.png)

Mobile resolution
1. Home page - unauthenticated
![mobile-top-nav-unauthenticated-home](https://cloud.githubusercontent.com/assets/1069588/23513608/92b1ccac-ff32-11e6-9063-4182657c2f30.png)

1. Home page - authenticated
![mobile-top-nav-authenticated-home](https://cloud.githubusercontent.com/assets/1069588/23512674/6cc6237e-ff2f-11e6-9af2-2df5b32f9389.png)

1. Secondary - unauthenticated
![mobile-top-nav-unauthenticated-secondary](https://cloud.githubusercontent.com/assets/1069588/23513551/70121148-ff32-11e6-9f75-99067145cbee.png)

1. Secondary - authenticated
![mobile-top-nav-authenticated-secondary](https://cloud.githubusercontent.com/assets/1069588/23513484/333830a4-ff32-11e6-84e8-1faf555e44be.png)

### Related work

#1118

**Comment by 13miciunasl** [comment]
Includes browse button see: #1014

**Comment by crowesn** [comment]
Recreate standard UC top nav bar. 

See [libraries' homepage](http://libraries.uc.edu) for working example (note that we substitute the search box with login button).

![uc header](https://cloud.githubusercontent.com/assets/1069588/23081099/608544e0-f521-11e6-93aa-8afb37c0a656.png)

**Comment by crowesn** [comment]
[Desktop-home-unauthenticated.pdf](https://github.com/uclibs/scholar_uc/files/784175/Desktop-home-unauthenticated.pdf)

**Comment by crowesn** [comment]
@lawhorkl this should be ready for work, let me know if you have any questions.

**Comment by lawhorkl** [comment]
@crowesn is there a copy of the UC logo being used that I can include in the application?

**Comment by crowesn** [comment]
@lawhorkl it's in the body of this issue, hiding.

**Comment by lawhorkl** [comment]
@crowesn not seeing it
