### ISSUE TITLE
Brand and update home page

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1120]
### Descriptive summary

Refactor homepage to conform with attached wireframe. Where possible, migrate functionality from default sufia homepage, such as featured works, etc.

* Jumbotron background
https://flic.kr/p/3kBWs4

attribution:
```ruby
<%= link_to 'Photo', 'https://flic.kr/p/3kBWs4', target: '_blank' %> by fusion-of-horizons | <%= link_to 'CC-BY', 'https://creativecommons.org/licenses/by/2.0/', target: '_blank' %>
```

1. Desktop resolution
![desktop-home-authenticated](https://cloud.githubusercontent.com/assets/1069588/23523792/423a2dd6-ff56-11e6-956a-44ca3e7b569b.png)

1. Mobile resolution
![mobile-home-unauthenticated](https://cloud.githubusercontent.com/assets/1069588/23524039/fc9b0a1a-ff56-11e6-9743-59ccaeb6d634.png)

### Related work
#1119 
#1118

**Comment by crowesn** [comment]
See tentative wireframe.
[Desktop-home-unauthenticated.pdf](https://github.com/uclibs/scholar_uc/files/784162/Desktop-home-unauthenticated.pdf)

**Comment by 13miciunasl** [comment]
Where can I get that background image?

**Comment by crowesn** [comment]
Mobile view: 

![mobile-home-unauthenticated](https://cloud.githubusercontent.com/assets/1069588/23177865/6a6ebc58-f836-11e6-8948-62237820f4e1.png)

**Comment by crowesn** [comment]
background image: 
https://flic.kr/p/3kBWs4

**Comment by crowesn** [comment]
Libraries lock-up
![uc_libraries_vert_redblack](https://cloud.githubusercontent.com/assets/1069588/23178023/e424dd52-f836-11e6-9527-86bae2ae9e39.png)

**Comment by crowesn** [comment]
cc-by citiation style: https://wiki.creativecommons.org/wiki/Best_practices_for_attribution
I prefer the example under "This is a pretty good attribution".

**Comment by lawhorkl** [comment]
Breakdown of homepage partial:
- layouts/homepage.html.erb: overall container partial
--sufia/homepage/marketing.html.erb: marketing text activated on a conditional
--controls.html.erb: secondary navbar navigation overlaying header image
--sufia/homepage/accouncement.html.erb

**Comment by crowesn** [comment]
Final mock for beta:

![desktop-home-unauthenticated](https://cloud.githubusercontent.com/assets/1069588/23479910/0940db46-fe94-11e6-82a3-837c11ec17ea.png)

**Comment by crowesn** [comment]
Mobile view final mock for beta: 

![mobile-home-unauthenticated](https://cloud.githubusercontent.com/assets/1069588/23480388/b7966dcc-fe95-11e6-8298-4fd2fc25d35c.png)

**Comment by crowesn** [comment]
@lawhorkl I've added updated mocks to the issue, this should be ready to go.

**Comment by crowesn** [comment]
More files here: https://uc.box.com/s/m9cmsqafvixh80im5na0bfc1e7wd773s. The images that were used for the Featured researcher, work and collection should be in this folder: 6715 ScholarAtUC-SplashPage-FinalSent Folder\Links.
