### ISSUE TITLE
User lookup on Batch Edit

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1122]
When editing a batch of works, on the permissions tab, user look-up functionality isn't enabled for the "Enter User" field, as it is on the individual work create/edit form.

<img width="1170" alt="screen shot 2017-02-06 at 2 29 13 pm" src="https://cloud.githubusercontent.com/assets/2651187/22662892/a77754b2-ec78-11e6-9095-102becbcbeef.png">

**Comment by scherztc** [comment]
Confirmed working in Scholar 3
