### ISSUE TITLE
Resource type on Batch create

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1123]
When adding new works via batch create, after uploading files, the UI prompts you to select the resource type for the work. With the implementation of multiple work types, this should instead be a selection between the available work types.

<img width="824" alt="screen shot 2017-02-06 at 2 31 05 pm" src="https://cloud.githubusercontent.com/assets/2651187/22663017/0e446bee-ec79-11e6-89fe-c77417cdae9a.png">

**Comment by crowesn** [comment]
Re suggestion to select from available work-types:

The user is prompted to select a work-type as first step when starting batch creation. 

* Would offering work-type selection at the file-level be confusing?
* If so, we could opt to hide the :resource_type select completely completely, opting instead to rely on assertion that work-type is set at beginning of work-flow.

**Comment by crowesn** [comment]
Overrides:

https://github.com/projecthydra/sufia/blob/master/app/jobs/batch_create_job.rb
