### ISSUE TITLE
New page - Instructions for Students

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1127]
### Descriptive summary

This new page will not be listed in the Help menu, but will be linked from the new help page for student works, specified by #1126 

See text below.  It is desired that references to login buttons, Add New, Create Student work, etc. use the same styles and appear in the same way, but they should themselves not be clickable buttons.  These instances have been bolded and have (_button_) in italics after them.  

This page will need to be revised for the Scholar 3.x input form.

Title (two lines, centered): 
**Student Self Submissions to Scholar@UC
Instructions for Students**

Body of page:
Works that are deposited in Scholar@UC should be related to scholarship and research and be consistent with the Scholar@UC [Mission and Collection Policy](https://scholar.uc.edu/coll_pol_request). Students should work with a faculty advisor to share scholarly output and creative works, such a capstone projects. **All official theses and dissertations must be submitted directly to the Graduate School and not Scholar@UC.** If you have any questions or problems with these instructions, please contact [scholar@uc.edu](mailto:scholar@uc.edu).

1. Go to http://scholar.uc.edu and click on the **Log In** (_button_) button (upper right corner).

2. Click on the **Log in using your UC Central Login** (_button_) button.  Use your 6+2 and password to login. Upon your first login, you will be prompted to edit your profile. Basic information will be pre-supplied through the UC Central Login system. You will also be shown a welcome page until you check the box &quot;I don’t need to see this.&quot; After you complete this process you will be directed to the Scholar@UC browse page.

3. Click on the **Add New** button  and select &quot;**Add a Work**.&quot; 
![image](https://cloud.githubusercontent.com/assets/3521707/22705843/1cfd499a-ed3b-11e6-8261-94e22bb6637a.png)

4. Click on the **Add New** button for the **Student Work** type.
![image](https://cloud.githubusercontent.com/assets/3521707/22705889/3ce3183e-ed3b-11e6-899c-303adaaa9fa3.png)

5. Please see the File Format Advice at the end of these instructions. Add a file to your work by:
    - Uploading a file. If your file exceeds 3.0 GB, do not upload and contact [scholar@uc.edu](mailto:scholar@uc.edu).
    - Adding an external link. Please use permanent links whenever possible. Permanent links are usually advertised as such &ndash; links that will not change as content moves.
    - Pulling in a cloud file. If your project files are saved in Dropbox, Google Drive, Kaltura, or Box, you can retrieve the files without having to first download them to your local device.

![image](https://cloud.githubusercontent.com/assets/3521707/22705957/9057d19e-ed3b-11e6-902c-5a19259e90d3.png)

6. Describe your work using the Basic Description section, some fields are required. Specific field notes below.
    - Type of Work &ndash; select the predominant format of your work.
    - Creator &ndash; you will automatically be tagged as a creator, but you may add collaborators as needed.
    - Faculty Advisor or Sponsor &ndash; enter the name of your faculty advisor. (Last name first.)
    - College and Program or Department &ndash; please select your degree granting College and enter the name of your degree program.
    - If this work is associated with a degree, please enter that information. For example, &quot;BSIT&quot; (for Bachelor of Science in Information Technology).

7. It is recommended that you describe your work using the Additional Description section. You will have to click on &quot;Show Additional Description.&quot; Your faculty advisor may have specific recommendations about how you describe your work.
    - For example, use the subject field for your area of study, e.g. biology, literature, etc.

8. You may assign a Digital Object Identifier to your work. A DOI is intended to reference stable content and is a permanent URL that you may share and use in publications.

9. Add your faculty advisor or sponsor as a Content Editor. Search for them by name or by email address. If your advisor has not yet logged in to Scholar@UC, you will not find them &ndash; contact them and ask them to login.
![image](https://cloud.githubusercontent.com/assets/3521707/22706072/f1b6f078-ed3b-11e6-9053-3161b4841b93.png)

10. Discuss with your advisor whether they will approve your submission before it is made public &ndash; in this case mark this work as &quot;private&quot; in the Access Rights section.
    - For various reasons, such as potential commercialization, you may wish the work to remain private, be accessible only to UC users, or to assign an embargo period so that your work would automatically become public after a certain time period. Please make sure your faculty advisor knows your wishes so that you work isn’t made public prematurely.

If your advisor has given you permission to publish without their review, then do not mark the work as &quot;private&quot;, but choose between Open Access, accessible only to UC users, or assign an embargo period. You may want to discuss this choice with your advisor.

11. You may choose to assign a Creative Commons license to your work or choose &quot;All rights reserved.&quot; A Creative Commons license is an easy way to communicate how you would like people to use or share your work. You may find it useful to use the **License Wizard**(_button_) which will guide you through the selection process. We suggest discussing this choice with your advisor.

12. You must agree to the [Non-Exclusive Distribution License](https://scholar.uc.edu/distribution_license_request) which grants UC the right to preserve, provide access (under the licensing terms chosen), and enhance the work with additional metadata. The license also states that you have not violated the intellectual property of another and that your work contains no [restricted data, as defined by UC](https://www.uc.edu/content/dam/uc/infosec/docs/policies/Data_Protection_Policy_9_1_1.pdf). **Note: You will retain fully copyright for the work and you can share or submit the work with additional repositories and websites.**

13. Click **Create Student Work** (_button_) to submit your work. Send an email to your faculty advisor with a link to the permanent URL of the work. In your email, inform them that you have submitted the final version work for their review. The advisor will check to make sure the appropriate fields are completed and take the steps necessary to make the work available through the appropriate Creative Commons license which you have chosen.

Particularly for capstone projects, where successful completion is part of a degree requirement, you may lose edit access to your work once it is submitted. Your faculty advisor will retain editing rights as a Content Editor. If you need to change metadata or files from your work, contact your faculty advisor first. If you are unsuccessful, please contact [scholar@uc.edu](mailto:scholar@uc.edu).

**File Format Advice**
The file format you use will affect its preservability. Some specific guidance is offered below; you will find additional details on our [File Format Advice](https://scholar.uc.edu/format_advice_request) page. If you have any questions, please contact [scholar@uc.edu](mailto:scholar@uc.edu).
- Most common formats used on the web are
  - highly compressed, making it easy to share content over the internet; compression means some information has been removed to make the file smaller; and
  - brittle. Formats used on the web change over time and are dependent on browser technology. For example, the introduction of HTML5, which natively supports videos, has drastically reduced the use of Flash Video (FLV) while increasing the use of MPEG-4 (MP4).
- For long term preservation, the use of uncompressed formats is important. The content if uncompressed is a true master copy, which can be used to create new derivative files as web formats change over time.
-  It's also important to use open (non-proprietary) and stable formats, when possible. This means the format itself is openly documented, widely used, and has likely been in use for many years. For example, it’s preferable to use an uncompressed WAV file for a sound recording over Windows Media Audio.
-  PDF or PDF/A is the best format for documents 
  - [http://bentley.umich.edu/uarphome/bestprac/pdfafaqs.php)](http://bentley.umich.edu/uarphome/bestprac/pdfafaqs.php)
- If uploading music scores, it may be desirable to upload them in a musical notation format (such as Sibelius) if the creator is encouraging reuse. However, they should also be uploaded as PDF (or PDF/A) to ensure their long-term preservation and access.

**Comment by newmanld** [comment]
The above reflects the attached PDF.
[studentSelfSubmissions_scholar_studentInstructions.pdf](https://github.com/uclibs/scholar_uc/files/758781/studentSelfSubmissions_scholar_studentInstructions.pdf)

**Comment by newmanld** [comment]
Although the above reflects what the DR T.F. approved, it's a long page.  Let's try to incorporate the File Format Advice at the end, which is not specific to student works, into the File Format Advice page itself, making it only necessary to link to that page in number 5.  See also #1048.

**Comment by newmanld** [comment]
Note the instances of Scholar@UC automatically made a clickable link by markdown.  Ignore that.

**Comment by newmanld** [comment]
Body of Page - step 1 - probably does not make sense here to say "Go to http://scholar.uc.edu and click on the Log In (button) button (upper right corner)."  Made sense for a PDF that was handed to people, but as this is a page within Scholar@UC, it makes less sense.  Also should have been https:.  Let's change this (or suggest alternate methods)
Log In to Scholar@UC (upper right corner of https://scholar.uc.edu).

Please note that the folks who drafted this wanted this to be an image of the login button.  _(button)_

**Comment by newmanld** [comment]
See places that the folks who drafted this page wanted an image of a button.  Noted as (_button_).  See also on attached PDF.

**Comment by 13miciunasl** [comment]
That sounds fine, but I am a bit confused about your first point. Do you want to get rid of the whole "Go to scholar.uc.edu...." line or just edit it to "Click on the Log in button (insert picture of button)"?

**Comment by 13miciunasl** [comment]
Here are the changes you requested
![screen shot 2017-02-14 at 11 03 28 am](https://cloud.githubusercontent.com/assets/9759017/22937036/4d3d45a0-f2a5-11e6-9434-c91a6ad2e5dc.png)

**Comment by 13miciunasl** [comment]
Changed it to use styled buttons instead of images
![screen shot 2017-02-14 at 2 16 58 pm](https://cloud.githubusercontent.com/assets/9759017/22944919/597ec5da-f2c0-11e6-8138-337c7de92314.png)
![screen shot 2017-02-14 at 2 17 08 pm](https://cloud.githubusercontent.com/assets/9759017/22944923/5bda25cc-f2c0-11e6-8b0a-6fb233670da5.png)

**Comment by 13miciunasl** [comment]
@newmanld

**Comment by newmanld** [comment]
Looks good!
