### ISSUE TITLE
Update our overridden homepage layout view with recent Sufia change

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1147]
After we overrode the homepage layout, Sufia changed 
https://github.com/uclibs/scholar_uc/blob/develop/app/views/layouts/homepage.html.erb#L12
to
https://github.com/uclibs/scholar_uc/blob/develop/app/views/layouts/homepage.html.erb#L12

See https://github.com/projecthydra/sufia/commit/fbcdaa76c757c6c79b8010e6ee5901c7cde680ed

**Comment by crowesn** [comment]
I'm thinking we can roll this into https://github.com/uclibs/scholar_uc/issues/1120, since we're doing a complete refresh.
