### ISSUE TITLE
Editing a work doesn't show the current license

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1149]
### Descriptive summary

When editing an existing work, the license dropdown doesn't show the existing (selected) license.  I did some testing and verified that this bug was introduced in the commit to add new work types.  It is *not* caused by the commit that defaults the license to "all rights reserved"

### Steps to reproduce the behavior

1. create a work, choose a license, and save
1. click on the edit button
1. see that the license you picked in step one is not selected in the drop down list

**Comment by crowesn** [comment]
This appears to be limited to <> Generic Work
