### ISSUE TITLE
Acquire coat rack

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1150]
### Descriptive summary

We need a coat rack.

* Should be freestanding
* Not ugly

**Comment by hortongn** [comment]
As an employee
I want to take my coat off and hang it up
so that I don't get too hot in the office
Done looks like: my coat is on a rack

**Comment by newmanld** [comment]
See poll in dcr-staff slack channel

**Comment by newmanld** [comment]
Two coat racks ordered.  Close issue when received and assembled!

**Comment by newmanld** [comment]
Shipping Confirmation
Hello Linda Newman,
2 "Tangkula Metal Coat Rack..." have shipped.
