### ISSUE TITLE
double chevrons on Filter Your Works partial

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#1153]
### Descriptive summary

The chevrons used in the Filter Your Works are doubled.

### Expected behavior
There should be just one chevron for each option, properly aligned.
### Actual behavior
There are two generated for each section, with the double begging slightly misaligned.
![image](https://cloud.githubusercontent.com/assets/12615997/23039541/c72b1182-f45b-11e6-96de-1dede0318971.png)

### Steps to reproduce the behavior

Go to My Works page

**Comment by hortongn** [comment]
This will be fixed in https://github.com/projecthydra/sufia/pull/3086

**Comment by hortongn** [comment]
fixed in projecthydra/sufia#3086
