### ISSUE TITLE
DOIs that include brackets [ ] generate an exception

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1154]
### Descriptive summary

Students entering works into production Scholar were getting Page Not Found errors when saving some works.  It looks like the problem is caused when existing DOIs are entered into a work and the DOI includes square brackets like [ and ].  

The work is still saved, but cannot be viewed or edited via the GUI anymore.  So there are now some works in Scholar that need to be fixed via the console.

An example (valid) DOI that was used is
http://dx.doi.org/10.3417/0026-6493(2006)93[49:ARAEOB]2.0.CO;2

A work around is to encode the brackets into something like
http://dx.doi.org/10.3417/0026-6493(2006)93%5B49:ARAEOB%5D2.0.CO;2
However, the DOI then displays using the encoded version.

We need to:
1) determine what characters are valid for DOIs
2) patch Scholar to properly handle DOIs using special characters (encode them before saving and decode to display)
3) make sure that existing works display properly once we've fixed the problem

Example works with bad DOIs:
/works/articles/2n49t357x
/works/articles/2n49t356n
/works/articles/bc386v894
/works/articles/bc386v87k
/works/articles/bc386v851
/works/articles/bc386v04t

@jamesvanmil

**Comment by jamesvanmil** [comment]
Advice on character encoding for DOIs is available here: https://www.doi.org/syntax.html

With a list of recommended characters at 2.5.2.4, here: https://www.doi.org/doi_handbook/2_Numbering.html#2.2

Table 1: Mandatory Encoding

Character	Encoding
%	(%25)
"	(%22)
#	(%23)
SPACE	(%20)
?	(%3F)


Table 2: Recommended Encoding

Character	Encoding
<	(%3C)
>	(%3E)
{	(%7B)
}	(%7D)
^	(%5E)
[	(%5B)
]	(%5D)
`	(%60)
|	(%7C)
\	(%5C)
+	(%2B)

**Comment by jamesvanmil** [comment]
Addressing with https://github.com/uclibs/hydra-remote_identifier/pull/1

**Comment by hortongn** [comment]
Fixed via https://github.com/uclibs/hydra-remote_identifier/pull/1
