### ISSUE TITLE
Generate count of number of UC people with ORCIDs

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1167]
### Descriptive summary

In anticipation of the deploy of ORCID functionality, the ORCID implementation group would like to know how many people at UC have ORCIDs, if the API will tell us this, by UC email and/or UC affiliation.
This is not functionality to be added to Scholar@UC itself.

### Expected behavior
Using the query capability of the ORCID API, generate a report showing this count.  If allowed by API, list ORCIDs and names.  

### deadline
Before deploy to production of Scholar 2.4.

**Comment by crowesn** [comment]
I have an xml file with the results of our search - there are currently 82 UC affiliates in the orcid database. Looking at a quick xslt to list the names and orcid IDs.

**Comment by newmanld** [comment]
Excellent!
