### ISSUE TITLE
Misaligned license widget and select

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1172]
### Descriptive summary

License widget button and select should be aligned in the same row, with help text spanning both above.

Current:

![screen shot 2017-03-01 at 10 19 49 am](https://cloud.githubusercontent.com/assets/1069588/23466282/a5ab6e6e-fe68-11e6-9d5c-631816c2415d.png)

**Comment by scherztc** [comment]
Size: 2
