### ISSUE TITLE
Need a proxy help statement in the proxy assign section of the dashboard.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1173]
### Descriptive summary

As a: Submitter. I would like to see a help statement on the Dashboard where I assign a proxy. So that I know what a proxy is and what they can do on my behalf. 
### Expected behavior

Done looks like: a brief help statement or link to a help statement appears in the proxy area on the dashboard.

Text from Scholar 2 that needs to be modified to reflect proxies and not delegates.
----------
Please Note: Your delegates can do anything on your behalf in Scholar@UC. Be selective in who you give delegate access.
Delegate accounts in Scholar@UC work very similar to delegate accounts in Gmail. If you authorize a delegate they can view, edit, or delete all of your existing works and files. Delegates can also create new works and upload files on your behalf. The delegate relationship can be revoked by the owner at any time.

You can use groups or work-specific editors for more fine-grained access control.
----------
### Actual behavior

<img width="1023" alt="screen shot 2017-03-01 at 2 40 12 pm" src="https://cloud.githubusercontent.com/assets/5084562/23477749/01a85438-fe8d-11e6-96d5-5846ed161ddb.png">

Link to related issues or prior related work here.

**Comment by crowesn** [comment]
Modfiy text to reflect current proxy behavior.
