### ISSUE TITLE
Change password mechanism for generic accounts

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1174]
### Descriptive summary

As a non-UC user: I want to be able to change my password. Should we change labeling on Forget Password mechanism or should we provide new link with new mechanism for changing password.

### Expected behavior

Done looks like: we re-label the Forget Password link to Change Password or we develop a change password mechanism for generic accounts.

----------
### Actual behavior

We have a Forget Password mechanism only.

**Comment by crowesn** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password

**Comment by crowesn** [comment]
Stand-up discussion established that we can relabel and rely on devise *forgot your password* workflow to achieve this function.

**Comment by scherztc** [comment]
Size: 2
