### ISSUE TITLE
Convert all existing CC3 licenses to CC 4

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1175]
### Descriptive summary

With the consent of the Scholarly Communications Specialist, I want to convert all existing CC 3 licenses to CC 4 licenses as a pre-mgration task.

### Expected behavior

That there are no CC3 licenses in Scholar 3.0.

**Comment by crowesn** [comment]
Script to run on rails console
```
# update-license.rb
#
# Run on console with `rails -r path_to_file/update-license.rb`

licenses = {
"http://creativecommons.org/licenses/by/3.0/us/" => "http://creativecommons.org/licenses/by/4.0/",
"http://creativecommons.org/licenses/by-sa/3.0/us/" => "http://creativecommons.org/licenses/by-sa/4.0/",
"http://creativecommons.org/licenses/by-nc/3.0/us/" => "http://creativecommons.org/licenses/by-nc/4.0/",
"http://creativecommons.org/licenses/by-nd/3.0/us/" => "http://creativecommons.org/licenses/by-nd/4.0/",
"http://creativecommons.org/licenses/by-nc-nd/3.0/us/" => "http://creativecommons.org/licenses/by-nc-nd/4.0/",
"http://creativecommons.org/licenses/by-nc-sa/3.0/us/" => "http://creativecommons.org/licenses/by-nc-sa/4.0/",
"All rights reserved" => "http://rightsstatements.org/vocab/InC/1.0/"
}

work_types = [Article, Image, Dataset, Document, Video, GenericWork, Etd, StudentWork]

work_types.each do |work_type|
  work_type.all.each do |work|
    licenses.each do |key, value|
      if work.rights == key
        work.rights = value
        if work.save!
          puts "Changed: #{work.id} --- #{key} > #{value}"
        else
          puts "Error: #{work.id}"
        end
      end
    end
  end
end
```

**Comment by crowesn** [comment]
@uclibs/developers 
Question about logistics: when should this conversion take place? If we do it in production before migration, outside of some kind of content freeze, we'd run the risk of having new works entered with 3.0 licenses.

We probably don't want to upgrade to the 3.0 licenses in Scholar 2, correct?

**Comment by hortongn** [comment]
@crowesn I agree that we probably don't want to do the license migration under Scholar 2.  That would mean having to update the license dropdown menu, which would require a new deploy.  So I think we are stuck on CC3 with Scholar 2.
