### ISSUE TITLE
Unable to update editors via the Batch Edit UI

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1176]
### Descriptive summary

As a User:  I want to allow for batch editorship changes to my works.  So that I can more efficiently add more editors to my work.

### Expected behavior

Use batch changes in dashboard or sharing tab to add more than one editor to more than one work.

### Actual behavior

Multipl eEditorship changes are done on a per work basis with a drop down and add button.

<img width="754" alt="screen shot 2017-03-01 at 3 03 22 pm" src="https://cloud.githubusercontent.com/assets/5084562/23478737/43d44cd8-fe90-11e6-8ac9-bb4665d5bc93.png">

**Comment by scherztc** [comment]
Managing Content Use Cases Submission 2

**Comment by jamesvanmil** [comment]
Adding multiple editors appears as a feature in the batch UI, but it doesn't work. Making this an issue to fix the bug.

**Comment by scherztc** [comment]
@jamesvanmil :  Can you determine the status of this in hyrax 2?

**Comment by scherztc** [comment]
Batch EDIT in Dashboard.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
