### ISSUE TITLE
Add the ability to create Sub-Collections

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1187]
### Descriptive summary

Include a concise description of the issue and any relevant tracebacks if you're reporting a bug.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by scherztc** [comment]
The Works within Works test will determine if this a 3.0 issue or an issue that we wait for the development of Display Sets from Project Hydra.

**Comment by scherztc** [comment]
Blocked by: https://github.com/uclibs/scholar_uc/issues/1192

**Comment by scherztc** [comment]
Blocke: https://github.com/uclibs/scholar_uc/issues/1101

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
