### ISSUE TITLE
Generate manifest from production scholar@uc and then create csv for three student owners

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1203]
### Descriptive summary

Mark K. has been running the curation project to direct students to submit the works of faculty.  Next step, for completed works, is to change the owner and make the work public.  To help Mark K. get a list to us of which works these are, and for each work, who should be the new owner, I propose that we generate a csv file for him.  There are three student submitters whose credentials I will provide offline.

### Expected behavior
A subset of the manifest is created that contains only the works with owner/submitter of the three student assistants.  Provide an extra blank column for new owner.

**Comment by jamesvanmil** [comment]
@crowesn doesn't have appropriate permissions to run through this yet - we're doing a walkthrough together.

**Comment by newmanld** [comment]
If @vanmiljf has permissions and @crowesn does not, work with @hortongn to provide permissions?
