### ISSUE TITLE
Modify Batch Create Form for base metadata fields

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1214]
### Descriptive summary
The current batch create form is out of sync with the metadata profile of Scholar 3.

There will be some complex logic needed or simplified set of requirements to make sure the form renders useful for all work types.

**Comment by newmanld** [comment]
I'm re-opening this issue.  I just used Batch create with 4 images.  They all had the same geographic subject, which was one word - Bonaire.  When I submitted the form with that field, I received this error message "You attempted to set the property `geo_subject' to a scalar value. However, this property is declared as being multivalued."  I removed that field from my form and the batch submission went through.

**Comment by newmanld** [comment]
Batch create does not seem to save Rights or Date Created.
