### ISSUE TITLE
Display collection owner on catalog index view

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1225]
In curate/scholar 2, catalog index view shows the following fields per object.

#### Works (all types)
* title
* creator
* description

#### Collections
* title
* description
* *owner*

In Sufia/scholar3, field display for catalog index is set globally for all types (works and collections) in ```app/controllers/catalog_controller.rb```. 

If we display owners (:depositor), the field will show not just for collections but also works.
Currently in scholar 3, collections can have a :creator, but this isn't a required field for collections and is not available to collections in scholar 2.

### Related work

#1179

**Comment by newmanld** [comment]
Collection was a facet.  Now it is not and we have no apparent way to limit the Catalog browse to collections.  Is this documented in a separate issue?  DId we explictly remove Collection as a facet?

**Comment by crowesn** [comment]
@newmanld decision to keep :submitter and :creator in catalog view pending further comment.
