### ISSUE TITLE
FAQ Data protection policy link broken

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1229]
The data protection policy link links to a dead page.
New one is most likely this: http://www.uc.edu/content/dam/uc/infosec/docs/policies/Data_Governance_and_Classification_Policy_9.1.1.pdf

**Comment by hortongn** [comment]
@13miciunasl The new data protection link should be `https://www.uc.edu/content/dam/uc/infosec/docs/policies/Data_Governance_and_Classification_Policy_9.1.1.pdf`

The following files should be all of the places in Scholar where the old link needs to be replaced with the above:

* app/views/curation_concern/base/_legally_binding_text.html.erb
* app/views/page_requests/_terms_text.html.erb
* app/views/page_requests/coll_policy.html.erb
* app/views/page_requests/faq.html.erb

**Comment by flutterflies** [comment]
The link is working as expected in Scholar 3
