### ISSUE TITLE
Field labels in the catalog index should match their work show labels

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1242]
### Descriptive summary

The catalog index view always uses the labels "Description" and "Creator" even when a work's show view uses the labels "Abstract" or "Author".  The labels in the catalog index and work show page should match, if possible.

Ref: https://github.com/uclibs/scholar_uc/commit/7d2eb77f86525a4232cc75d0116617193efd81c3

**Comment by lawhorkl** [comment]
THis seems to be set in the `catalog_controller` as removing one of the entries removes the field from the catalog show view, however when I change the value of the `label` attribute in the `add_index_field` entries, it does not update the label within the associated views.

I am unassigning this as I will not be available to work on this next week.

**Comment by jamesvanmil** [comment]
After digging into the index presenter, we decided this is best addressed by changing the labels to "Description/Abstract" or "Creator/Author" - the alternative is popping open the presenters to make them more sensitive to work type.
