### ISSUE TITLE
Mock up Featured Researcher, Featured Work, Featured Collection for Beta Preview

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1268]
### Descriptive summary

For the Beta preview, on whichever server we use, we need mocked up content for Featured Researcher, Featured Work, Featured Collection.  The Product Owners will help identify and/or create this content.  As we are still in the mode of frequently wiping out content on our sandbox implementation, we need to be ready to do this when we will not be wiping the content, or can easily re-create it.

### Expected behavior
The front page of Scholar@UC 3.0 has populated content for Featured Researcher, Featured Work, Featured Collection.
### Actual behavior
Some content areas are blank today.
### Steps to reproduce the behavior
For featured researcher, P.O.s have suggested https://scholar.uc.edu/people/zk51vj49v

### Related work

Link to related issues or prior related work here.

**Comment by crowesn** [comment]
Researcher image must be square, 270px by 270px. I suggest that we point the featured researcher pic to a scholar blog post with the featured text, etc.

**Comment by newmanld** [comment]
@lawhorkl  - I remember you saying that there's something built into the UI for a featured researcher (and featured work, collection, although collection is pointing to Admin Set)?  Can you point us to the right documentation so we can determine if best to use that facility or a blog post as @crowesn suggests?

**Comment by crowesn** [comment]
@newmanld @lawhorkl 
It's instructive to look at scholarshere because they have used the builtin featured research functionality: https://scholarsphere.psu.edu/

**Comment by newmanld** [comment]
As I understand it we want 'Featured Researcher' to go to a blog post.   I'll identify 3 of our scholar story blog posts and create 270x270 pics and put in Slack for P.O. review.

**Comment by newmanld** [comment]
This is done for Featured Researcher and Featured Work.  Waiting for #1270 and #1320 and #1284 to be able to feature a collection.

**Comment by hortongn** [comment]
@newmanld @crowesn Can this issue be safely closed now?

**Comment by crowesn** [comment]
I think so.

**Comment by newmanld** [comment]
Closing.
