### ISSUE TITLE
Collection discovery in the UI

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1277]
### Descriptive summary
Collections should be more discoverable.

Hyrax 1.0 shows Collection as a separate facet (as well as a facet under the Type facet).  This is one possible solution.  Work with Display Sets may also in the future add more discoverability to the Hydra code.

**Comment by scherztc** [comment]
Add to trello and I will ask the PO's.
Closing this issue. 
Issues only make it into Github when they have been approved by PO and Dev team.

**Comment by newmanld** [comment]
Concensus of P.O.s at meeting on 2017-04-19 - Collections should be more discoverable but this can be a post Scholar Beta preview issue to resolve.  Leave as facet under Work Type for Scholar 3.0 beta preview.

**Comment by scherztc** [comment]
Collections are faceted under work types.  This is good for now.  
When Hyrax 2 comes out we'll see how they facet collection extensions.
