### ISSUE TITLE
Make the list of contributors easier to find

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1281]
The only links to the /users page is from an existing user's profile page.  We need a more visible way for people to link to the page of Scholar contributors.

The link(s) should be visible to both logged-in and anonymous users.

On work show pages, clicking on the work creator's name should link to their profile page (not a list of all their works)

Note: The contributor page already has it's own search box.

**Comment by hortongn** [comment]
@uclibs/developers Thoughts on adding a link to the Contributors page on the same menu with About|Help|Contact?  See below.  I personally don't like it (4 items looks nicer than 5), but I'm examining all options we can give the POs.

The link(s) to Contributors needs to be available when the user isn't logged in.  So the dashboard isn't an option.

![index user scholar uc](https://cloud.githubusercontent.com/assets/5639859/24980524/a762421e-1fa6-11e7-9c91-296d70c8d227.png)

Also:

![scholar uc](https://cloud.githubusercontent.com/assets/5639859/24980801/cbbd1fe8-1fa7-11e7-8806-fc27a196b759.png)

**Comment by newmanld** [comment]
@hortongn - I think this is a good option to present to P.O.s.

**Comment by hortongn** [comment]
Looking for input on this change from the product owners and developers...

We need to add a link for our Contributors page somewhere on Scholar's layout.  The Contributors page shows a list of all users who have contributed content to Scholar.  This is equivalent to our "People" tab in our current Scholar implementation.  

Below is the approach I've taken to finding a place for the link.  I would appreciate feedback on this solution.  The changes are pretty simple:

## Replace the "Home" link on the home page's menu bar with the "Contributors" link.  There's no need for a "Home" link on the home page because you're already there.  It's redundant.

![scholar uc 1](https://cloud.githubusercontent.com/assets/5639859/25098905/4369f010-2378-11e7-8646-3ce253bc3929.png)

## Replace the "Home" link in the navigation bar (the grey bar just under the UC logo) with the "Contributors" link.  The "Home" link is moved to the left of the "Login" link in the upper-right corner.

![index catalog scholar uc copy](https://cloud.githubusercontent.com/assets/5639859/25099409/24407a2c-237a-11e7-9b8e-5b185081633e.png)

## An example of how the "Home" link looks when a user is logged in:

![index catalog scholar uc](https://cloud.githubusercontent.com/assets/5639859/25099491/7f47a59e-237a-11e7-9068-628f281f734a.png)

## Finally, a view of the Contributors page itself

![index user scholar uc](https://cloud.githubusercontent.com/assets/5639859/25099544/be475686-237a-11e7-82be-97f1164adc9e.png)

A variation on this is to get rid of the "Home" link altogether.  We don't have a "Home" link in our current Scholar and just rely on people clicking the Scholar logo to go home.  Scholar users typically have very little reason to go back to the home page once they've begun browsing or searching.

**Comment by crowesn** [comment]
I think we should keep home link where it is and add contributors to the set of options.
I think 5 options is okay especially if it prevents us from crowding the nav toolbar.

I feel pretty strongly about this, for what it's worth.

**Comment by newmanld** [comment]
The P.O.s already advised us that the Home link (which we don't have on Scholar 2.x) was not necessary.  I hadn't noticed that it crept back in.  The Scholar@UC logo should always be a link to home.  So I think this solution is worth presenting, with and without Home Link, and showing any other options for where Contributors might go.  Knowing that we may be highlighting Contributors more with a possible Research Directory integration justifies a prominent placement - but something for the P.O.s to mull  over.  @scherztc will you inform the P.O.s of these options - and/or does someone need to add to Trello card?

**Comment by scherztc** [comment]
No interest in using the browse button for works, contributors, and collections?

![bootstrap-dropdown-buttons](https://cloud.githubusercontent.com/assets/5084562/25100718/2d739fa2-237f-11e7-980f-bac372519b89.png)

**Comment by newmanld** [comment]
To me Contributors deserves higher placement than in a drop-down menu - but we need the P.O.s to drive decisions.  @scherztc - with discussion over Collections as a facet, Contributors being more discoverable - do we need a quick F2F meeting/conference call with our P.O.s?

**Comment by crowesn** [comment]
Ultimately, I could live without the home link, mostly concerned about overcrowding the nav toolbar.
I like having the explicit home link since we have two icons on the top left that link to different places (uc.edu, scholar).

**Comment by newmanld** [comment]
Per P.O. meeting on 2017-04-19 -
     Remove Home link from navigation bar
     Rename 'Contributors' to 'People'
     Add to navigation bar where Home link was previously, in left-most position.

**Comment by hortongn** [comment]
Add a blurb on the People page that explains the list only contains users with content in Scholar.
