### ISSUE TITLE
Update all About and Help page content

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1297]
We've made several changes/fixes recently to the About and Help pages on Scholar 2.x.  We need to make sure the pages in Scholar 3.0 match (including content and links).

Any screenshots used on those pages should be updated to match Scholar 3.0 style and graphics.

Pages:

* https://scholar.uc.edu/about_request
* https://scholar.uc.edu/terms_request
* https://scholar.uc.edu/coll_pol_request
* https://scholar.uc.edu/creators_rights_request
* https://scholar.uc.edu/data_help_request
* https://scholar.uc.edu/faq_request
* https://scholar.uc.edu/format_advice_request
* https://scholar.uc.edu/student_works_help
* https://scholar.uc.edu/advisor_guidelines
* https://scholar.uc.edu/student_instructions

**Comment by scherztc** [comment]
Also,  Make sure to correct typo on About page reported by Mark's student.
