### ISSUE TITLE
Add rake task to generate new user accounts

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1298]
Can be done after the beta preview.

Related work in 2.x: https://github.com/uclibs/scholar_uc/commit/e86e2f7fa7ec61de368fbcbed3aa9b90ea02f8d7

**Comment by hortongn** [comment]
This issue requires a port of https://github.com/uclibs/scholar_uc/commit/e86e2f7fa7ec61de368fbcbed3aa9b90ea02f8d7 from `2.x-stable` to `develop`.  The profile and person code can be removed.

**Comment by jamesvanmil** [comment]
Let's target this to batch user creation and creation of proxy relationships

Related to #1572
