### ISSUE TITLE
Hide Admin sets in the UI until we have more than one admin set

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1307]
### Descriptive summary

Scholar 3 will go to Beta preview with only one default administrative set.  The places administrative set now appears on the input form (individual and batch) and work show page are confusing. Per P.O.s meeting on 2017-04-19 
  priority 1 - suppress choice of administrative set on the relationships tab on the work input form (individual and batch).
 priority 2 - suppress display of administrative set on the work show page.  (It shows up under Descriptions and Relationships).  Priority 2 not a deal breaker for Beta preview, but desirable to resolve.

### Expected behavior
User does not see wording referring to Administrative Sets until a choice of Administrative Sets is reasonable for the user.

**Comment by crowesn** [comment]
I don't see admin set info on work show page.

**Comment by crowesn** [comment]
I don't see admin set info in work show page - maybe hidden as part of relationship partial changes.
<img width="1200" alt="screen shot 2017-04-25 at 8 25 40 pm" src="https://cloud.githubusercontent.com/assets/1069588/25413088/876ab2ee-29f5-11e7-8d6f-b6c9ede8cd40.png">

**Comment by newmanld** [comment]
Interesting - you still see it live here, although maybe that relationship partial change hasn't been merged: htt
![image](https://cloud.githubusercontent.com/assets/3521707/25436618/cf9a97ca-2a61-11e7-9e1d-6417c3e34a36.png)
p://curly.libraries.uc.edu:3001/concern/documents/rj4304706
