### ISSUE TITLE
Prepare sandbox server for beta preview

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1313]
### Todo:
* ~~Install standalone version of Solr~~
* ~~Install standalone version of Fedora~~
* ~~Get the app running on port 80~~
* ~~Install and configure ffmpeg so video and audio can be processed~~
* ~~Set the application URL to scholar-beta.uc.edu~~
* ~~turn on virus scanning~~
* ~~get contact form working without captcha~~
* ~~Make sure emails are sent properly and reliably~~
* ~~Schedule cron job for releasing embargos~~
* ~~Create an admin~~
* ~~Set up default workflows and admin sets + allows_access_grant~~
* ~~Get share tab working~~
* ~~Schedule cron job to alert us if the app is not running~~
* ~~Install SSL certificate (will require using a WEBrick alternative like Puma)~~
* turn on background jobs (Sidekiq)
* Create some content
* Create featured work/collection/researcher
* APIs
    * ~~test DOI credentials~~
    * ~~Add note about ORCID during beta~~
    * ~~production keys for browse everything (turn off Kaltura) - SSL needed first~~

**Comment by scherztc** [comment]
Add API keys for Cloud providers.

**Comment by scherztc** [comment]
Collections Permalinks using localhost:  
Link to this page: http://localhost:3000/collections/9g54xh70s

**Comment by newmanld** [comment]
The application URL will be scholar-beta.uc.edu not scholar-beta.libraries.uc.edu

To add to @schertz' comment above, it is not just Collections permalinks but all permalinks that are showing localhost:3000 in the address.  Will setting the application URL will fix this?

**Comment by hortongn** [comment]
@newmanld Yes, we can set the URL in a single config setting and it will change all references of localhost to scholar-beta.uc.edu.

Is there an ETA on when the new URL will be ready?

**Comment by hortongn** [comment]
Aside from setting up keys for browse everything and enabling Sidekiq, everything is pretty much done for scholar-beta.uc.edu.

We should create a few example works and set up featured works, collections, etc.

We can merge in more completed issues after the PRs are closed.

**Comment by hortongn** [comment]
I'm putting details about the beta server environment here:
https://github.com/uclibs/scholar_uc/wiki/Scholar-Beta-Environment

**Comment by hortongn** [comment]
Closing this issue since it looks like everything needed for the beta server is done.  WIll create a separate issue to test and enable Sidekiq for scholar-beta.
