### ISSUE TITLE
Adjust Metadata and behavior on ETD input form

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1314]
### Descriptive summary

On ETD individual work input form, to be consistent with Scholar 2.x and metadata decisions, some adjustments are needed:

* Publisher default text should be "University of Cincinnati"

* Publisher help text should be "Enter the publisher associated with the ETD, typically the University of Cincinnati."

* Publisher is not repeatable.    (Repeatable on all other work types.)
 
* College should not have any default text associated with submitter's identity information, but does use the same drop-down list.

* Degree Program should not have any default text associated with submitter's department information.

(An ETD administrator, not the author, will submit ETDs, thus the reason not to associate default text in College and Degree Program with the submitter.)

* Degree Program help note should say "Enter the degree program associated with the ETD."

* Change Degree to not be repeatable.
   
* Type (genre) does not exist on ETD form in Scholar 2.x.  Confirm with Metadata SME that it is needed in 3.x.  If not needed, remove from metadata spreadsheet as well as code for ETD input form.  If needed, change help information to not refer to a Select option - since this is free text.  Suggested: "Enter a type matching your work.  Examples: Document, Article, Dataset, Image, Video, Other"
       
* Change label of geo_subject to "Geographic Subject" per other work types.   Add help notes and examples to be the same help and example text as on other work types.

* On entry for Committee Member on metadata spreadsheet, add applicable information to columns for RDF Mapping, Solrized, Gem.

**Comment by newmanld** [comment]
(Per #1285?) Type is now a drop-down list, but Help text says "If you are unsure about the type, please select 'Other'" and 'Other' is not in the list?

**Comment by newmanld** [comment]
Please update metadata spreadsheet before closing this issue.

**Comment by hortongn** [comment]
Reopening this issue until the metadata spreadsheet is updated.
