### ISSUE TITLE
Adjust metadata on Student Work input form

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1315]
* Change Degree to not be repeatable.

* Type of Work is no longer a drop down list.  Confirm with Metadata SME that this is intended, and if so, change help text and add examples to reflect this.  Suggested "Enter a type matching your work.  Examples: Document, Article, Dataset, Image, Video, Other"     

(Per P.O.s decision was made earlier to not drive facet from Type of Work.  Therefore it is correct that this field is not required and not shown by default.)

**Comment by crowesn** [comment]
Point 2 is address in https://github.com/uclibs/scholar_uc/pull/1285

**Comment by newmanld** [comment]
Type of Work is now a drop-down list.  'Other' no longer appears.  If this was intended, then we simply need to update the metadata spreadsheet to reflect the drop down list values and intended help text and then this issue can be closed.  

Degree is still not repeatable (in what has been merged and deployed to sandbox today) but that is referenced by #1327.

**Comment by hortongn** [comment]
@newmanld Sorry.  GitHub automatically closes an issue when we merge the related pull request.  I'm reopening the issue now.

**Comment by newmanld** [comment]
Entering a value in the Degree field now gives this error message "You attempted to set the property `degree’ to a scalar value. However, this property is declared as being multivalued.”

**Comment by scherztc** [comment]
@crowesn : I created a new tab in the Metadata spreadsheet to represent the genre controlled vocabulary. 
 https://docs.google.com/spreadsheets/d/1biO5sm4WVK9p01jCFDzNqTQ1mF_33MEHbpCjIVaOU3M/edit#gid=1170925358

Is that all that is needed to close this issue?

**Comment by crowesn** [comment]
I think so?
