### ISSUE TITLE
Embargo and Lease date dialogue not appearing on Batch Create

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1336]
### Descriptive summary

When using the batch create feature, if I select Embargo, the date and other dialogue options are not appearing. 

 I submitted a batch of works with Embargo selected.  No date choices appeared, throughout the input process, even after uploading files and completing metadata.  When completing the submission process, these works had a Private status.

### Expected behavior
Users should see the same dialogue after selecting Embargo as happens with individual work upload, and an embargo date should be enforced:
>Embargo
>>Restricted to  <drop down with a choice of 'Private' or 'University of Cincinnati'>
>>       <date field that defaults to tomorrow's date> 
>>      then open it up to
>>             <drop down with a choice of 'Public' or 'University of Cincinnati'>
### Actual behavior
No dialogue appears after selecting Embargo.  Embargo with batch create seems to work the same as Private.

It appears that the similar date dialogue is missing when the Lease option is selected.  Note that per #1334, we will be suppressing the lease option.  

It appears that the same problem exists with Hyrax  v1.0.0.rc1 - deserves additional testing.  See https://github.com/projecthydra-labs/hyrax/pull/490 and https://github.com/projecthydra-labs/hyrax/issues/107 for possible related work that may still not exactly document this issue.

**Comment by newmanld** [comment]
On closer look - the works I submitted via batch create with embargo selected were embargoed with the next day's (i.e. tomorrow) date.  This is the default date that would have populated the date field had it appeared.

**Comment by hortongn** [comment]
Verified that the HTML controls for how to behave during and after embargo are present on the page.  They just aren't displaying check the user selected Embargo on the batch create form.  Likely a JavaScript issue.

**Comment by hortongn** [comment]
This commit introduced the embaro bug on the batch create page: https://github.com/projecthydra/sufia/commit/c838900cf5614cf6041f6880ff5d8c79fbf99f67

**Comment by newmanld** [comment]
Share tab changes again.
