### ISSUE TITLE
Advisor needs to be multi_valued for Student Works on the batch create form

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1351]
Advisor needs to be multi-valued on the batch create form.  

Causes a Scalar input error on submission.

**Comment by newmanld** [comment]
I did not get the Scalar error with Advisor field on submission (individual not batch) a short time ago, but I did with Degree.  But per our metadata template Advisor should be repeatable.  I missed this apparently when submitting #1315.
