### ISSUE TITLE
Hyrax: Port Scholar@UC from Sufia to Hyrax

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1375]
### Descriptive summary

See : https://github.com/projecthydra-labs/hyrax/releases/tag/v1.0.0.rc1

Models
Routes
Controllers
Other Steps
AdminSet Workflow
Data Migration

Run Test suite.

**Comment by hortongn** [comment]
Everything has been ported to the point where we can run the test suite and start the application.  I've opened new issues for all remaining tasks.
