### ISSUE TITLE
Get Google Drive working properly with Browse Everything

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1379]
When selecting files from Google Drive with Browse Everything, the file list only shows files that have been shared with the user.  All of those files are listed as 0 bytes in size and they never actually attach to the work.

Determine if this same behavior is found on production Scholar and figure out if our application or the Browse Everything gem needs to be fixed.

Note: we are using a foorked version of browse_everything that includes our Kaltura integration.

**Comment by scherztc** [comment]
In the process of fixing problems with Google APIv3 in browse_everything.
This PR fixes the fact that we weren't even getting the download link or size in our application: https://github.com/samvera/browse-everything/pull/178/files

I think we still need to fix the fact that we are seeing shared files with 0 bytes.

**Comment by scherztc** [comment]
See : https://github.com/samvera/hyrax/issues/1684

**Comment by scherztc** [comment]
https://github.com/samvera/browse-everything/pull/178

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/604
