### ISSUE TITLE
Fix cloud uploads for batches

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1381]
When doing a batch upload, choosing cloud files using browse everything results in an error.

**Comment by scherztc** [comment]
https://github.com/psu-stewardship/scholarsphere/commit/5529a5027

**Comment by hortongn** [comment]
I've tested this again.  We no longer get an error when trying to create a batch with browse everything, but the works never get created.  Scholar behaves like everything went well and returns the user to their dashboard, but the works never show up.

**Comment by hortongn** [comment]
We can see the error when running Scholar locally can trying to create a batch with browse-everything:

`ActiveRecord::RecordNotFound in Hyrax::BatchUploadsController#create`

`Couldn't find Hyrax::UploadedFile with 'id'=https://public.boxcloud.com/d/1/XSGASETdg2RwbtQcpUZCAxEbSUDnLJ2U6XbXRM8s7_yKop30E_mvZk8reXkA9Q1eu2aw-qnEqUY70ZSOF5HGlpiGGBhGlrj0skREH7G8sq3pwWLKK7G3f3sZIUITdx-JzTZMTn80eQGK2c1TXn5xiIhBYBRVKX3-wFCjuavgM6HHwxSVumy39CsRhs-7PV3P8jT2EYU0Eq_teoeds88MLjanNz9e7tVtJbu-n59BHVJ3h8ay6JS-f2-Zj-wLNxmtam4yn8olNQeEInTBiTG8iC30v5TloiLRoe1SBhZZtEPwJc4h-ek-oSJQVGezWAt6l56GfgUKum8Mmic5adbaRu4Gzt74kgcFI77-fNuHFNiMOdDyPQFiCtsYYjwXZO0IYFQsLEk8J7FsJCbauft7kh0zlLdroU3S6JNlr1Ubnb6JdPREyUUHzrOna7XhrXI9bk6lIAgMSXWl2iHvlTJ6M-LfUr5xjMk8cYXd3xyPn02CdDkt4B2n3YVwii1ifv0X2_91WyygGpdUDewnNGxJUWkykWub769uei1VhSLqoS6hPbCr4-YSVvXPdNsgEDr0RxfZhAeLtnAcGqwrV2Q37sLEuY_miPrd6mh_Qu2JWPOhj-uFNmmf5xtN4_t974kqK4Fx2_SVlZkBMiqcGOGQjVXOCT8Yelo7-gDs06npXP9GBdPb8HrDs0Ps7vGZLPEOBvASszd3IDL96mGTxUQwiQP_5D4b06kmb4vE8MoImBIV-rxkco890cGi2bsIxi9jp2EqFwU4CBGfeRRLaIrGuye3nbBVMvExmBw9YSU565jDpH43YENfdSidmnpcZnMcUHCs4QZzh-vivMt2cxUaby-PWyP6jJtFnxwQmhXHnJg5qFy2Opdg9x5IGY_FMNeK1zrCm5Z07bCXrqEtDBnkWqGNRGRRPeg0NCBYLW7a4SsF_aoJwQNJH-a92Y9IgB1RsP-w5aZNo-8JXlJDpStSbQOuu-518rBCbKdixxjt1Yz71GgSR5ngoTA2ru-oH-kcrZM2p5BkfcMS8cweyqw3OpKJP5NW9WQGQ_CRujTo5rCa/download`

**Comment by hortongn** [comment]
This will be fixed in Scholar 3.1.  I've opened a new issue to disable cloud uploads for batches for now (see #1674)

Code found in Hyrax for creating single works here
https://github.com/samvera/hyrax/blob/v1.0.4/app/controllers/concerns/hyrax/works_controller_behavior.rb#L29-L40
should be implemented for batch uploads as well.  Without it, the `create_with_remote_files` actor cannot find the URLs to the cloud files.  `create_with_remote_files` expects to see `remote_files` within the attributes, but right now they show up as `uploaded_files` as if they are local, not remote.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
