### ISSUE TITLE
Configure cache management for RIIIF

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1387]
### Descriptive summary

We are going to need some sort of cron script to purge derivatives created by riiif on our web/application server.

### Expected behavior
Derivates get purged on some time frame.

### Actual behavior

Derivates continue to stay in tmp folder.

**Comment by scherztc** [comment]
@jayanthdeejay This file resolver caches the network files, so you will want to clear out the old files or the cache will expand until you run out of disk space. Using a script like this would be a good idea: https://github.com/pulibrary/loris/blob/607567b921404a15a2111fbd7123604f4fdec087/bin/loris-cache_clean.sh By default the cache is located in tmp/network_files. You can set the cache path like this: Riiif::Image.file_resolver.cache_path = '/var/cache'

**Comment by jayanthdeejay** [comment]
@scherztc That's the script that I was referring to this morning to make changes such that we can clear the cache files. But, I couldn't test it as I didn't find the default cache location on my local box. I don't know when these cache files get generated. So, thought of talking to you about it when we met. We can brainstorm and come up with the ideal time frame to clear cache and modify that script to suit our needs.
