### ISSUE TITLE
DOI URL vs identifier input error

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1389]
### Descriptive summary

Josh has identified a set of works with DOIs that have a full URL instead of just the identifier. e.g. ```http://doi...``` instead of just ```doi...```

These are existing DOIs that were cut and pasted into the form at creation (not resulting from the minting process).

Noted that there is no way in the GUI to edit an existing DOI on a work.

Probably needs to be edited on the console. 

### List of errant works

~~1.	Characterization of Multiswirling Flow https://scholar.uc.edu/works/articles/bc387z375

2.	Supersonic Jet Noise Reduction by Chevrons and Fluidic Injection https://scholar.uc.edu/works/articles/bc3881488

3.	Pediatric Sleep-Related Breathing Disorders: Advances in imaging and computational modeling https://scholar.uc.edu/works/articles/bc388152v

4.	Investigation of slurry concentration effects on solid particle erosion rate for an impinging jet https://scholar.uc.edu/works/articles/bc388155p

5.	Computational Modeling of Airway Obstruction in Sleep Apnea in Down Syndrome https://scholar.uc.edu/works/articles/bc3881623

6.	Coronary artery anomalies in Turner Syndrome https://scholar.uc.edu/works/articles/bc3881666

7.	A numerical investigation of wear caused by dilute slurry injected into an annulus through rectangular apertures https://scholar.uc.edu/works/articles/bc388165x~~

8.	Does particulate matter along roadsides interfere with plant reproduction? A comparison of effects of different road types on Cichorium intybus pollen deposition and germination https://scholar.uc.edu/works/articles/bc388170s

9.	Patterns in pharyngeal airflow associated with sleep-disordered breathing https://scholar.uc.edu/works/articles/bc388099j

10.	Large Eddy Simulation of the pharyngeal airflow associated with Obstructive Sleep Apnea Syndrome at pre and post-surgical treatment https://scholar.uc.edu/works/articles/bc3880988

11.	Numerical simulation of microparticles penetration and gas dynamics in an axi-symmetric supersonic nozzle for genetic vaccination https://scholar.uc.edu/works/articles/bc388096q

12.	Surface Streamer Discharge for Plasma Flow Control Using Nanosecond Pulsed Power https://scholar.uc.edu/works/articles/bc3881003

13.	Computational Fluid Dynamics Analysis of Upper Airway reconstructed from Magnetic resonance imaging data https://scholar.uc.edu/works/articles/bc388024g

14.	Large Eddy Simulation and Reynolds-Averaged Navier-Stokes modeling of flow in a realistic pharyngeal airway model: An investigation of obstructive sleep apnea https://scholar.uc.edu/works/articles/bc388029v

15.	Influence of Gender on Pharyngeal Airway Length in Obese Adolescents https://scholar.uc.edu/works/articles/bc388038t

16.	Role of Subglottal Shape in Turbulence Reduction https://scholar.uc.edu/works/articles/bc3880350

17.	Effect of exhaust nozzle geometry on combustor flow field and combustion characteristics https://scholar.uc.edu/works/articles/bc387z617

18.	Measurements of the acoustic attenuation by single layer acoustic liners constructed with simulated porous honeycomb cores https://scholar.uc.edu/works/articles/bc387z642

19.	Transient plasma ingnition https://scholar.uc.edu/works/articles/bc387z63s

20.	Characteristics and Control of a Multiswirl Spray Combustor https://scholar.uc.edu/works/articles/bc387z67w

21.	An experimental and computational study of a multi-swirl gas turbine combustor https://scholar.uc.edu/works/articles/bc387z749

22.	Aeroacoustics of Turbulent Jets: Flow Structure, Noise Sources, and Control https://scholar.uc.edu/works/articles/bc387z731

23.	Compact incinerator afterburner concept based on vortex combustion https://scholar.uc.edu/works/articles/bc387v678

24.	Active control of liquid-fueled combustion using periodic vortex-droplet interaction https://scholar.uc.edu/works/articles/bc387v68j

25.	Control of thermoacoustic instabilities and emissions in an industrial-type gas-turbine combustor https://scholar.uc.edu/works/articles/bc387v70k

26.	Use of chemiluminescence and neural networks in active combustion control https://scholar.uc.edu/works/articles/bc387v49b

### This one is a little bit different

27.	Experimental Comparison of Axial Turbine Performance Under Steady and Pulsating Flows https://scholar.uc.edu/works/articles/bc3881534

**Comment by newmanld** [comment]
It appears that we fixed individual works from the console.  But we have not updated help text to remind people not to include "doi:" - or, within Scholar 3, figured out how to let people edit DOIs when the DOIs were not minted within Scholar@UC.  So I'm re-opening this with a request to:

Fix https://scholar.uc.edu/works/articles/bc388699s

Consider changes possible for Scholar 3 and write up a new issue to implement changes.
