### ISSUE TITLE
Status of a work should show "Open Access" after embargo

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#139]
DEFECT - Status of a work should show "Open Access" after embago release date passed  https://jira.duraspace.org/browse/HYDRASIR-532 (change public facing label to just say open access)

**Comment by scherztc** [comment]
Embargo Date Occurs - 

The public user should see no distinction between open access and embargo.
   set label to Open Access.
The owner should see that the work had been embargoed, but is currently open access.
  preferred - if we can keep the Open Access with Embargo until date
  or 
  acceptable - set it to open access.

**Comment by scherztc** [comment]
Allow for research of 

1. worker notifying owner of embargoed expiration and changes work access level for public user.
2. check work embargo_date on display and change access level and display different.

**Comment by scherztc** [comment]
Consider all the scenarios related to file dependencies.

**Comment by scherztc** [comment]
https://github.com/projecthydra-labs/worthwhile/commits/master/app/controllers/embargoes_controller.rb

**Comment by jamesvanmil** [comment]
Lukas currently working on:

* Mailer
* Changing visibility status when embargo expires
