### ISSUE TITLE
Box.com Browse everything - bookmarks causing issues

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1402]
In Scholar 2.4, Bookmark links from Box.com are displaying in the Browse Everything interface as files. The user is able to attempt to attach the file, but the upload fails with the following:

`undefined method `download_url' for nil:NilClass`

Would be best to suppress these bookmarks from the Browse Everything display

**Comment by scherztc** [comment]
I am not sure of the status of Box in BrowseEverything.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
