### ISSUE TITLE
Hyrax: verify and fix single works

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1403]
Find and fix the problems with creating, editing, and viewing single works

**Comment by scherztc** [comment]
Landing page 
New work page
Route

**Comment by scherztc** [comment]
I was able to deal with the multiple title problem per a recommendation from Samvera Slack:

**Comment by scherztc** [comment]
Next I am dealing with a mime_type rails 5 depreciation in the Work Show page:

To respond to a custom format, register it as a MIME type first: http://guides.rubyonrails.org/action_controller_overview.html#restful-downloads. If you meant to respond to a variant like :tablet or :phone, not a custom format, be sure to nest your variant response within a format response: format.html { |html| html.tablet { ... } }

**Comment by scherztc** [comment]
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::WEB_CONSOLE_V2` to `Mime[:web_console_v2]`. (called from ___sers_scherztc__rvm_gems_ruby_______scholar_gems_web_console_______lib_web_console_templates_console_js_erb___4248900124870137668_70264892268420 at /Users/scherztc/.rvm/gems/ruby-2.4.1@scholar/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb:491)

**Comment by scherztc** [comment]
This can be closed now, we are able to ingest single works successfully.
