### ISSUE TITLE
Hyrax: verify and fix layout issues

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1407]
Find and fix the problems with the layout and design (including toolbars and footer)

**Comment by lawhorkl** [comment]
taking this

**Comment by lawhorkl** [comment]
issues found:
* Application title set to `blacklight`

**Comment by lawhorkl** [comment]
We have decided as per our planning/swarm conversation, we have elected to remove the locale selector for now.

**Comment by lawhorkl** [comment]
![image](https://cloud.githubusercontent.com/assets/12615997/26419296/35c60cfa-408d-11e7-9551-915429e986d1.png)

**Comment by lawhorkl** [comment]
Unable to replicate navbar issues (perhaps due to other fixes?).

@crowesn 's suggestion about the duplicate keys resolved the locales issue.

The coloring of the nav menus are the same on develop, not changing.

Title of application set in `blacklight.en.yml`
