### ISSUE TITLE
APA Citation bug

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1411]
Reported by Katie Foran-Mulcahy:

_One error I found is that the citations piece is buggy.  Something weird happening with periods pretty consistently with APA citation when I’ve viewed several different works:_

![image001](https://cloud.githubusercontent.com/assets/5639859/26220907/979b186c-3be2-11e7-9bc1-97dbb3a03b76.png)

![image002](https://cloud.githubusercontent.com/assets/5639859/26220909/99b57d18-3be2-11e7-88d8-5643f8c991db.png)

**Comment by jamesvanmil** [comment]
Question for those in tune with the Hyrax development cycle - should I just fix this with a PR in Hyrax?

**Comment by crowesn** [comment]
Holding for possible backport of fix to hyrax 1.0 
https://github.com/samvera/hyrax/pull/1372

**Comment by hortongn** [comment]
Closing this because the fix has been backported into Hyrax 1-0-stable.  Should be released with Hyrax 1.0.4.

Good job @crowesn
