### ISSUE TITLE
Dates in Citation bug

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1413]
Dates do not appear in citation. This is a side effect of the introduction of `alt_date_created`.

To fix we should:

1. Set the work presenter class in the citations controller to match the work type. It currently defaults to inherited class for all of our worktypes.
1. Set `#date_created` on the work type presenters to return `#alt_date_created`

**Comment by crowesn** [comment]
Why not override date_created to return alt_date_created in the model? In this way we could avoid a controller override.
