### ISSUE TITLE
Evaluate Imagemagick install

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1447]
Seeing the following error on scholar-beta:

`mogrify -flatten /tmp/mini_magick20170606-1508-n9emv5.tif` failed with error: mogrify: /tmp/mini_magick20170606-1508-n9emv5.tif: unknown field with tag 37724 (0x935c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/715. mogrify: /tmp/mini_magick20170606-1508-n9emv5.tif: Unknown tag 37724. `TIFFSetField' @ error/tiff.c/TIFFErrors/499.

I think this could be fixed by upgrading imagemagick - let's evaluate and decide on an approach.

**Comment by crowesn** [comment]
Unable to reproduce on Scholar-beta

**Comment by crowesn** [comment]
This is a warning from mogrify (not an error) - wonder if there is a way to keep the app from crapping out on it.

**Comment by crowesn** [comment]
This is a known issue: https://github.com/samvera/hydra-derivatives/issues/107

**Comment by flutterflies** [comment]
Working fine for me locally with hyrax 1.0.4 and ImageMagick 7.0.6
