### ISSUE TITLE
Change Video Work Type to Media Work Type

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1450]
### Descriptive summary

Change the Video Work Type to a Media Work Type.
Keep the metadata.

This is not just a label change.

**Comment by lawhorkl** [comment]
Meant to be Video worktype.

**Comment by newmanld** [comment]
This issue was motivated by this Beta Feedback.  "Create a new work type for audio works."  The P.O.s recommended using the term "Media' instead of "Video" to make it clear that this work type supports both audio and video.
