### ISSUE TITLE
Need contextual help for Attaching a file to new works

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1452]
### Descriptive summary

Add some contextual to encourage adding files on the (single work) input forms.

**Comment by newmanld** [comment]
This Beta feedback is behind this issue: "It's not required to attach a file when creating a work. Also, it's not readily apparent that you need to go to the files tab to upload the actual item when creating a work. I think a lot of users might add a work and forget to attach file. Or they might not initially understand to do that."  The P.O.s recommended that we somehow highlight the importance (but not requirement) to add files.  The UI work as to where to do this has not been determined - perhaps under the "Save Work Requirements" we can highlight the step without requiring it.

**Comment by lawhorkl** [comment]
@newmanld here is my first draft for the contextual help. I did my best to cover specific elements while keeping the language simple and polite:

> Note: While attaching a file is not required to create a work in Scholar@UC, attached files allow you to share greater amounts of information in whichever format is required for your purposes. It is recommended that you attach files to your work, unless the content of the work is hosted remotely, either by the use of preexisting DOIs, related links, or other attached works. 

> To attach a file, fill out the required metadata fields, and then navigate to the Files tab and select the desired files to be attached.

**Comment by newmanld** [comment]
How about this variation (edits welcome as it may need to be shorter?):

Attaching a file is not required to create a work in Scholar@UC, but is highly recommended.  Scholar@UC exists to share and preserve the intellectual output of University of Cincinnati scholars and researchers.  Scholar@UC may not be able to preserve your work without digital files.   Pre-prints are encouraged if publisher agreements do not permit you to upload a published article.   If you submit a work without files, use the External Link field to point to where the content may be found.

To attach a file, complete the required metadata fields, and then navigate to the Files tab and select the files to be attached.

**Comment by newmanld** [comment]
Slightly shorter:
Attaching a file is highly recommended but not required.  Scholar@UC exists to share and preserve the intellectual output of University of Cincinnati scholars and researchers.  Scholar@UC may not preserve your work without digital files.   Pre-prints are encouraged if a publisher does not permit sharing a published article.   Use the External Link field to point to related content found outside of Scholar@UC.

To attach a file, complete the required metadata fields and navigate to the Files tab to select the files to be attached.

**Comment by hortongn** [comment]
I'm good with Linda's edits

**Comment by lawhorkl** [comment]
Screenshot and demo of new help text: 
![image](https://user-images.githubusercontent.com/12615997/28784225-c5f468a2-75e0-11e7-9c86-dfb3565a9944.png)
