### ISSUE TITLE
Review Hyrax Configuration Options

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1454]
Review the Hydra Configuration Options.

**Comment by flutterflies** [comment]
![untitled222](https://user-images.githubusercontent.com/12132647/30341587-903b0422-97c4-11e7-88e4-a97a30e8077f.png)

**Comment by newmanld** [comment]
@scherztc @flutterflies the above configuration options are correct - with the possible exception of ability to assign uploaded items to an admin set.  We have disabled the admin set options from appearing on the Sharing tab or in discovery, so this configuration option may not matter, whether set to yes or no?
