### ISSUE TITLE
Update Visibility dialogue on input forms

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1473]
### Descriptive summary

As a content submitter, I want to understand my rights as a creator, and see concise information explaining the difference between Open Access, limited to University of Cincinnati, Embargo, and Private.  If the term "Open Access" is used throughout the UI,, it should also be used on the input forms.

### Expected behavior
A link is available to the Creator Rights page that opens up in a new tab or window.  The Visibility  dialogue is revised as suggested below.

### Actual behavior
There is no link on the input forms to the Creator Rights help page.  The term "Public" is used on the input form but "Open Access" is used many other places in the UI.  There is no color coding, and no explanation for Embargo and Private.

### Related work
This issue will reverse #1333. 

See https://github.com/samvera/hyrax/issues/1030.  "Example 2" is the apparent winner. https://user-images.githubusercontent.com/101482/26990065-3c3bf7b4-4d0a-11e7-9ad2-a0ea13299c40.png  
![image](https://user-images.githubusercontent.com/3521707/27245406-4ee596f4-52b9-11e7-93ac-d2d64a3cd573.png)

To meet expected behavior above, and be consistent with the expected direction of the Hyrax code, P.O.s have confirmed:
On all input forms (individual and batch), use the dialogue shown in the image above, with same color coding and wording and "Check deposit agreement" added to required steps, except that
* the Lease option will still be suppressed, 
* Add Files will not be required on the the individual work input forms (continues to be required on batch input forms and the Visibility dialogue should enforce this for batch).
* change “Make available to all (read more)” to “Make available to all (see [Creator's Rights](https://scholar-beta.uc.edu/creators_rights) for more information)”,
* The link to Creator’s Rights will be a relative link and will open in a new page or tab.

See also #1452.  Although we do not require files, the P.O.s are asking for brief contextual help to remind users to upload files.   Where to put this help has not been determined.

**Comment by hortongn** [comment]
Below is the current status of the Visibility pane after I made the recommended changes above.
I'll wait for feedback before finalizing these changes.  @newmanld

![new article scholar uc](https://user-images.githubusercontent.com/5639859/28220684-6b6d0844-688e-11e7-8afa-3f2552df90b5.png)
