### ISSUE TITLE
On batch create, Share Tab is showing up twice

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1482]
### Descriptive summary

When doing batch create, after selecting a work type, the Share Tab displays twice.
### Expected behavior
Identical tabs should not be duplicated

### Actual behavior
Share tab is duplicated.  Reported from bugs form on Scholar-Beta feedback.
### Steps to reproduce the behavior
Select Batch create
Select any work type

Link to related issues or prior related work here.

**Comment by 13miciunasl** [comment]
Unable to replicate

**Comment by crowesn** [comment]
![screen shot 2017-07-10 at 10 50 21 am](https://user-images.githubusercontent.com/1069588/28024046-9e1855f2-655d-11e7-8d31-ccc2e775b6b1.png)
