### ISSUE TITLE
Sharing icons (Facebook, Twitter, Google+, Tumbler working inconsistently.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1483]
### Descriptive summary

From Beta Feedback: "When attempting to share, google+ and tumblr do not work. Facebook shares but provides no feedback to the user about failing or not. Twitter works perfectly."
### Expected behavior
The URL of the work should be included in the post - this seems to be only happening with Twitter?

### Actual behavior
Tumbler is reporting "https://www.tumblr.com/widgets/share/tool/banned?".
Facebook and Google+ are not retaining a link to the work.
Twitter is pulling in a name and url to be the content of a tweet, for example "Scholar Beta Testing https://scholar-beta.uc.edu/concern/documents/8336h203f"
### Steps to reproduce the behavior
From any work, test the sharing options.

**Comment by crowesn** [comment]
Tumblr: validates links before posting, will fail if localhost or not dereferenceable (beta is not NAT'd)
Facebook: *does* retain link but only displays base URL in the message; no positive feedback after submission
Google+: validates links before posting, will fail if localhost or not dereferencable (beta is not NAT'd)
Twitter - no problem

The failures are related to our test environment. The UI isn't idea but it's also likely outside of our control.
