### ISSUE TITLE
Export to Mendeley not working

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1484]
### Descriptive summary

From Beta feedback, "I want to store the work in mendeley with its metadata. I attempted to download a video, a picture and a powerpoint but no metadata populated in mendley for all the artifacts."

### Expected behavior
Metadata from scholar@UC should populate as a citation in Mendeley.

### Actual behavior
As reported by user, metadata is missing.

### Steps to reproduce the behavior

Go to the show page of any work and test the Mendeley option.  An install of Mendeley may be required.

**Comment by hortongn** [comment]
It appears that Mendeley can't find the metadata fields because they need to be added as meta tags in the HTML's <head> section.  

e.g. `<meta name='citation_author' content='Hendrix, Scott'/>`

**Comment by hortongn** [comment]
In Scholar 2.x, the <meta> tags required by Mendeley are added by Curate:
https://github.com/uclibs/curate/blob/develop/app/repository_models/curation_concern/with_meta_tags.rb#L26-L79

Neither Hyrax or Sufia 7.3 have those tags in the HTML they produce.
Even the current version of ScholarSphere (which is based on Sufia 6.x) does not have those tags.

**Comment by hortongn** [comment]
Mendeley seems to pay attention to these tags:

```
<meta name='DC.Title' content='the work title'/>
<meta name='DC.Creator' content='the author'/>
<meta name='DC.Description' content='the description or abstract'/>
<meta name='DC.Publisher' content='the publisher'/>
<meta name='DC.Source' content='the source'/>
<meta name='DC.Date' content='the year ###'/>
```
