### ISSUE TITLE
Verify social media sharing on production

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1485]
### Descriptive summary

Some of the social media widgets won't work outside of production - make sure to verify functionality on deployment.

### Related work

Related #1483

**Comment by newmanld** [comment]
See also #1483

**Comment by hortongn** [comment]
I don't think we can test this until we can deploy to a server available off-campus.  So I'm moving this out of this sprint.

**Comment by crowesn** [comment]
Work
https://scholar-qa.uc.edu//show/ft848q61x

I noticed that the shared url includes the localization param. I'm inclined to backlog an issue for this and move on.

# Facebook
* :title
* :alt-description
* direct url with base url as link text

<img width="583" alt="screen shot 2017-09-18 at 9 22 16 pm" src="https://user-images.githubusercontent.com/1069588/30571813-22183aca-9cb8-11e7-8760-9ff5c4af218d.png">

# Twitter
* :title
* :alt-description
* direct URL

<img width="695" alt="screen shot 2017-09-18 at 9 22 28 pm" src="https://user-images.githubusercontent.com/1069588/30571815-223aa038-9cb8-11e7-85d8-9dbc97514571.png">

# Google
* :title
* :alt-description
* direct url with base url as link text
<img width="434" alt="screen shot 2017-09-18 at 9 22 48 pm" src="https://user-images.githubusercontent.com/1069588/30571814-2239b6dc-9cb8-11e7-9400-6b39dc8b0cd0.png">

# Tumblr
* :title
* :alt-description
* direct url with base url as link text
<img width="543" alt="screen shot 2017-09-18 at 9 25 54 pm" src="https://user-images.githubusercontent.com/1069588/30571816-22423e42-9cb8-11e7-80f1-335f2f267cfa.png">

**Comment by newmanld** [comment]
@crowesn - please add more information about what backlogging the issue means when we go to production with Hyrax 1.x.  (And do you mean this issue - 1485, or backlogging 1639? - You've closed, not backlogged 1485.)  How will the social media icons that have been problematic in Hyrax 1.x (Facebook, others?) behave in production if this issue is backlogged and/or closed?

**Comment by crowesn** [comment]
@newmanld I closed this issue because we have verified that the social media widgets behave as expected: They connect to their respective social apps and they include the title, description, and url to the work or fileset.

I discovered what I think is a non-priority issue, which is that the URL includes a param with the locale: `?locale=en`. I don't see the unnecessary param as a critical problem, or directly related to verifying the functionality of the widgets, so I added that to scholar 3.0 milestone, we should focus on our other critical issues.

**Comment by newmanld** [comment]
@crowesn: Agreed.  Now that I understand that social media widgets are behaving as requested by this issue (1485), I will re-close it.  In regard to #1639, let's put the comment about it not being a priority issue for production 3.0 in the comment field on #1639, and I think it could be in the Scholar 3.x milestone.   (I understand the Scholar 3.0 milestone to contain issues we are expecting to close by the time we go to production).
