### ISSUE TITLE
On the Collection show page, I want the option to create a new work

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1508]
### Descriptive summary

As a: User, I want to: have an easy option for creating a new work from a new collection. So that: a first option that displays after creating a collection is a choice to create a new work. Acceptance Criteria: Approval of PO's and DEV team.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
