### ISSUE TITLE
Get rid of ?locale=en in URLs

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1536]
I think we want to disable whatever is needed to stop Scholar from appending ?locale=en to the end of all our URLs.  We certainly don't want it on the end of our permalinks for works, etc.

Research what is needed to disable this and if there's a big downside to it, discuss options with the rest of the team.

**Comment by crowesn** [comment]
Local still shows in permalinks for filesets:
![screen shot 2017-09-19 at 11 36 08 am](https://user-images.githubusercontent.com/1069588/30601056-fcdb3970-9d2e-11e7-8780-bf787a388f14.png)
