### ISSUE TITLE
DEV:  Universal Viewer / RIIIF not working.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1537]
### Descriptive summary

The Universal Viewer is not finding the IIIF files on the scholar-dev.uc.edu environment.  The first place to look is removing this localhost line from the config file.  

https://github.com/uclibs/scholar_uc/blob/develop/config/environments/development.rb#L36

There still might be a deeper problem but start here.

**Comment by scherztc** [comment]
<img width="819" alt="screen shot 2017-07-03 at 11 55 13 am" src="https://user-images.githubusercontent.com/5084562/27800265-9a9338f6-5fe6-11e7-8909-410537852533.png">

**Comment by scherztc** [comment]
Russell Koonts [10:24 AM] 
Not sure if this is a hyrax or universalviewer question, but I’ll start here.  Moved our hyrax development site off of a local VM to our development server.  Now when trying to access images in the universalviewer via the server’s url, the images show up as errors.  Developer console shows a Failed to load Resource: net::ERR_CONNECTION_REFUSED error (localhost:3000/…).  This has been explained to me as the browser looking for localhost:3000 on my laptop.  Is there a way to set the default host in the development environment to the server’s url?

Justin Coyne [10:26 AM] 
@rkoonts I wonder if that URL is indexed in the solr documents?


Russell Koonts [10:44 AM] 
@jcoyne Turns out it was our proxy_pass and proxy_set_header weren’t set up completely.  Now that they are, all is fine.  Your recommendation got us looking at the server conf file in order to proxy solr and we realized it wasn’t correct.

**Comment by hortongn** [comment]
@scherztc This is where the derivatives path is getting set on scholar-dev
https://github.com/uclibs/scholar_uc/blob/develop/config/initializers/hyrax.rb.bamboo#L124
Bamboo sets it to /srv/apps/scholar-derivatives

**Comment by hortongn** [comment]
@scherztc I did a diff on the config files on scholar-dev and scholar-beta and didn't find any differences that might be causing the problem.

**Comment by scherztc** [comment]
Special apache encoding note: https://github.com/curationexperts/riiif#special-note-for-passenger-and-apache-users
