### ISSUE TITLE
Research Application and Content Data Migration Tools

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1543]
### Descriptive summary

Include a concise description of the issue and any relevant tracebacks if you're reporting a bug.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
Fedora 3 to Fedora 4 migration tool: https://github.com/samvera-labs/fedora-migrate

**Comment by scherztc** [comment]
Video -> Media work types are going to be a concern.

**Comment by hortongn** [comment]
Another tool that may be useful for our migration:
https://github.com/fcrepo4-labs/fcrepo-import-export

If the Fedora migrate tools doesn't work well for us, this import tool will at least help us import into Fedora 4.

This tool will take a filesystem's hierarchical directory tree of files/RDF and import it into Fedora.

**Comment by hortongn** [comment]
From the Fedora 4 wiki: Concept Mapping - Fedora 3 to 4
https://wiki.duraspace.org/display/FEDORA4x/Concept+Mapping+-+Fedora+3+to+4

"Upgrading/migrating from Fedora 3 to 4? Wondering what has changed and what has stayed the same? Look no further - this page will outline the main differences and map important concepts between Fedora 3 and 4."

**Comment by newmanld** [comment]
May be useful info here, for either migration from 3 to 4, or for future batch loads of new content into Scholar 3.x: https://wiki.duraspace.org/display/FEDORA4x/Import+and+Export+Tools

**Comment by crowesn** [comment]
Look at mapping scholar2 models to scholar3

**Comment by hortongn** [comment]
Very detailed presentation from Code4Lib on Hydra migration from Fedora 3 to Fedora 4:
http://2016.code4lib.org/slides/Workshop-Fedora4-Hydra-Migration.pdf
