### ISSUE TITLE
Add eAccessibility Concern to footer

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1549]
### Descriptive summary

A new link is now required on all UC webpages called 'eAccessibility Concern'.
We have also missed a required link to 'Alerts'

### Expected behavior
Link 'eAccessibility Concern' to https://www.uc.edu/ucit/community/accessibility/eAccessibility-form.html
Link 'Alerts' to https://www.uc.edu/alert.html

### Related work
For comparison, check the footer at https://uc.edu and https://libraries.uc.edu/.  Instructions above use https not http links where possible - because that seems best practice - even though non-https links are used in the footer at those two comparison sites.  Suggest changing all external links in footer to https when the link will still work.  Comments welcome here on whether links to non-Scholar sites should be http or https.

**Comment by newmanld** [comment]
I think there are also changes to the footer instigated by #1419

**Comment by newmanld** [comment]
Am wondering if we should have all required UC links in one line beginning with 'Alerts' and ending with 'University of Cincinnati', as shown on uc.edu and libraries.uc.edu.  This would make it more obvious that we are complying with required UC links.  Adjust our links (Scholar@UC Terms of Use, Deployed on ..., Made possible by the Samvera Project, proposed 'based on Hyrax') to be above on separate line(s).  Share screenshots of layouts in Slack?

**Comment by lawhorkl** [comment]
One line footer with all UC links from uc.edu
