### ISSUE TITLE
Resolve Views and Downloads

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1558]
### Descriptive summary

Views and Downloads are consistently zero on My Dashboard.  Depends on Google Analytics?  See #1065 and #1557 

Does Hyrax support a count of views and downloads for an individual work, as well as all of my works?

**Comment by crowesn** [comment]
Requires #1065

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/wiki/Analytics-workaround-for-non-production-environments
