### ISSUE TITLE
Error when attempting to page through the catalog

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1559]
Clicking 'next page' on the catalog page results in an error. This is apparently only a problem on scholar-dev, and not in the local environment.
![screen shot 2017-07-19 at 1 53 06 pm](https://user-images.githubusercontent.com/9759017/28381794-fa534d80-6c89-11e7-99fb-a390c49b809a.png)

**Comment by crowesn** [comment]
Strange: error only present on pages 3-48.

**Comment by crowesn** [comment]
bug no longer present.
