### ISSUE TITLE
Display every descriptive metadata field

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#156]
There are several descriptive metadata fields we are asking users to input but we do not display them on the public display of the work -- they are only visible on the private display of the work to someone with edit rights for the work.

Descriptive metadata (this does not include role assignments such as who is a member of a group or an editor) should display.

A UX question is whether we need a 'brief' and a 'full' display -- we should find out if we get Early Adopter feedback on this point.

We are getting feedback that Early Adopters want all descriptive metadata fields to be searchable, therefore they will need to be displayable so that the user understands why they retrieved a result.

This will need to be added as a Use Case -- I did not find it written up as of today.

**Comment by newmanld** [comment]
For Article -- missing descriptive fields are Date Created, Alternate title, Geographic Subject, Time Period, ISSN, Note, Required Software.

**Comment by newmanld** [comment]
For dataset -- missing descriptive fields are Date Created, Geographic Subject, Time Period.

**Comment by newmanld** [comment]
For image -- missing descriptive fields are Alternate title, Date Created, Genre, Source, View Date,  Preferred citation, Inscription, Culture, Note, Geographic Location, Geographic Subject, Time Period, Measurements, Material Substance, Required software.

**Comment by newmanld** [comment]
For Document -- missing descriptive fields are Creator, Date Created, Alternate title, Geographic Subject,  Time period, Note, Required software.

**Comment by newmanld** [comment]
For Generic work -- missing descriptive fields are Creator, Date Created, Alternate title, Geographic Subject, Time period, Note, Required software

**Comment by newmanld** [comment]
here's a spreadsheet: https://docs.google.com/spreadsheets/d/1biO5sm4WVK9p01jCFDzNqTQ1mF_33MEHbpCjIVaOU3M/edit#gid=0

The first column, 'label' has the values we're using in the UI.

**Comment by newmanld** [comment]
I was unable to test DOIs on our sandbox but I'm relatively confident that they are displaying on all work types.

**Comment by hortongn** [comment]
Merged to develop branch
