### ISSUE TITLE
Push rails 5 changes from our Orcid fork upstream

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1565]
### Descriptive summary

Package and contribute changes to the orcid gem upstream. Pay mind to rails4 vs rails5 functionality.

**Comment by crowesn** [comment]
Jeremy Friesen has been cherry picking commits from our update. This may be moot.

**Comment by scherztc** [comment]
Issue has been created ORCID upstream and we will close this issue.
