### ISSUE TITLE
Create model/attributes map for scholar 2>3

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1571]
### Descriptive summary

We need a manifest of all models with attributes from Scholar 2 to compare and map to Scholar 3

e.g. Users, GenericFile, etc.

Link to related issues or prior related work here.

**Comment by lawhorkl** [comment]
The following comments are only for hosting the wiki images.

**Comment by lawhorkl** [comment]
![image](https://user-images.githubusercontent.com/12615997/29133646-27b8814a-7d02-11e7-85e3-cdbe50ec3822.png)

**Comment by lawhorkl** [comment]
As per @jamesvanmil 's verbal instructions I am closing this. May reopen if its determined that we actually need it.
