### ISSUE TITLE
Production: Allow Encoded Slashes in Apache Virtual Host for RIIIF

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1581]
### Descriptive summary

RIIIF requires that Apache's Virtual Host settings Allow Encoded Slashes.

AllowEncodedSlashes NoDecode

We will need to change this in our Puppet or System deploy tasks to set in etc/conf/http.d

**Comment by scherztc** [comment]
https://github.com/curationexperts/riiif#special-note-for-passenger-and-apache-users

**Comment by hortongn** [comment]
This is built into our puppet scripts now and has been set in our new production environments
