### ISSUE TITLE
Migration mega-issue

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1585]
### Migrate WorkLoader class - DONE
  * @jamesvanmil
  * #1300 
### Extend WorkLoader class to handle work relationships - DONE
  * @jamesvanmil
  * #1608
### Create WorkLoader for Collections - DONE
  * @jamesvanmil
  * #1596 
### Extend WorkLoader class to simulate proxy deposit - DONE
  * Need to talk with @newmanld about the importance of preserving depositor info
  * This will not be part of the code - any proxy deposit info will be wrangled as part of the content migration package
### Extend WorkLoader class to handle multiple versions of a single file
  * @jamesvanmil
  * #1609 
### Migrating users - needs to be complete before content migration can happen
  * @13miciunasl 
  * Migrating rake task
    * #1298 
    * include batch
    * include proxy
    * add additional user fields
    * profile pics? (@jamesvanmil will check on scope)
  * export user information 
### Assesment of needs
  * How many files in Scholar 2 are using versioning?: 113 (as of 2017-08-28)
  * How works in Scholar 2 were deposited using proxy ability?: 573 (as of 2017-08-28)
  * How many users have uploaded a profile picture?: 35 (as of 2017-08-28)
### Exporting files - DONE
  @jayanthdeejay 
  #1594 
  * use the pids to find in the filesystem
  * multiple versions
    * can we easily get them and distinguish versions
    * should we bother?
  * are profile pictures within this scope?
### Exporting metadata
  * extend existing manifest to output the csv needed for rake ingest

**Comment by jayanthdeejay** [comment]
In our application, the setting to automatically compute checksum is disabled for input datastream. Refer `<param name="autoChecksum" value="false">` in fedora.fcfg file
