### ISSUE TITLE
Get rails console working on QA and production servers

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#16]
If the self-registration system we have now is not working, we have been able to get it working by restarting the application.  But some users have been stuck with incomplete logins.  They can login, but cannot edit their profile or add records.  We need to figure out how to delete these users (since they cannot get to their profile page, they cannot de-activate their own account).

**Comment by hortongn** [comment]
QA and production need additional RedHat package and ruby needs to be recompiled to get rails console working.  Needs UCit to make changes

**Comment by hortongn** [comment]
Document the process of deleting a user via rails console

**Comment by hortongn** [comment]
This is now working on QA.  Andy will schedule a change request to take care of it on production.

**Comment by hortongn** [comment]
Change request is scheduled for 8am 8/13/15

**Comment by hortongn** [comment]
Rails console is now working on all servers
