### ISSUE TITLE
Share tab not showing (again)

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1600]
### Descriptive summary

Share tab is missing on work forms. I think we established that a value in the workflow needs to be set to display the sharetab. 

Related: https://github.com/uclibs/scholar_uc/issues/1311#issuecomment-296737502

Should we save this in our default workflow?

**Comment by crowesn** [comment]
https://github.com/uclibs/scholar_uc/blob/develop/config/workflows/default_workflow.json#L7

**Comment by scherztc** [comment]
I set that value on scholar-dev and re-started it, but still did not see the Share tab. 
 This was a CC thing, maybe hyrax is handling it different. 
 Maybe it is time to revisit hard coding the tab back in. https://github.com/uclibs/scholar_uc/pull/1248

**Comment by crowesn** [comment]
I have a fix for this - it's a workflow problem.
