### ISSUE TITLE
ArgumentError, when adding a relationship to a work

### ISSUE THREAD

**Issue by jayanthdeejay** [uclibs/scholar_uc#1611]
### Expected behavior

Should redirect to work show page.

### Actual behavior

![ErrorSS](https://user-images.githubusercontent.com/2188493/29983742-394784b2-8f25-11e7-8e2e-7867078c3c51.png))

### Steps to reproduce the behavior

Edit an existing work -> Relationships.click -> Search for a work 
-> "look up an existing work" -> Add.click
-> Save.click

### Related work

Link to related issues or prior related work here.

**Comment by jayanthdeejay** [comment]
https://github.com/samvera-labs/hyku/issues/1289

**Comment by jayanthdeejay** [comment]
### Request

#### Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"9mSmVbPjzXOuzjgVzyiZpOmekE0Nn7nnKtLnNvsqm994ekvCM9/o3yYJQky7O63K2o83OrkGWIAVk/vEVT8QvQ==",
 "document"=>
  {"title"=>"Fedora An Architecture for Complex Objects and their Relationships",
   "creator"=>["Me, Not", ""],
   "college"=>"Engineering and Applied Science",
   "department"=>"CS",
   "alt_description"=>"None",
   "rights"=>"http://rightsstatements.org/vocab/InC/1.0/",
   "publisher"=>[""],
   "alt_date_created"=>"",
   "alternate_title"=>[""],
   "genre"=>"",
   "subject"=>[""],
   "geo_subject"=>[""],
   "time_period"=>[""],
   "language"=>[""],
   "required_software"=>"",
   "note"=>"",
   "related_url"=>[""],
   "existing_identifier"=>"",
   "doi_assignment_strategy"=>"not_now",
   "admin_set_id"=>"admin_set/default",
   "member_of_collection_ids"=>[""],
   **"work_members_attributes"=>{"0"=>{"id"=>"z603qx40z"}}**,
   "visibility"=>"open",
   "visibility_during_embargo"=>"restricted",
   "embargo_release_date"=>"2017-09-06",
   "visibility_after_embargo"=>"open",
   "version"=>"W/\"6827150a64c0f38fe00cf2a66ea30bb996232191\""},
 "find_child_work"=>"",
 "new_user_name_skel"=>"",
 "new_user_permission_skel"=>"none",
 "agreement"=>"1",
 "locale"=>"en",
 "id"=>"3t945q76s"}


As far as I understand, the property **work_members_attributes** should be able to handle an enumerable value but has been declared as singular. 

~/scholar/app/controllers/concerns/scholar/works_controller_behavior.rb
    ```ruby
    def update
      super
    ```


~/scholar/spec/helpers/change_manager/change_manager_helper_spec.rb
    ```ruby
    describe ChangeManager::ChangeManagerHelper do
      let!(:editors) { { "0" => { 'type' => 'person', 'name' => 'new_editor@example.com', 'access' => 'edit' } } }
    ```

~/scholar/app/forms/hyrax/forms/batch_edit_form.rb
    ```ruby
    def self.build_permitted_params
        super + [:visibility_during_embargo, :embargo_release_date,
                 :visibility_after_embargo, :visibility_during_lease,
                 :lease_expiration_date, :visibility_after_lease, :visibility] -
          [{ work_members_attributes: [:id, :_destroy] }]
      end
    ```

**Comment by mjgiarlo** [comment]
I suspect this was fixed in Hyrax's `master` branch but not backported.
