### ISSUE TITLE
Precompile assets in production mode

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1638]
We are currently having to run `rake assets:precompile` when in production mode to get the assets properly compiled.  We may be able to tweak the setting below to get rails to do this for us automatically.

https://github.com/uclibs/scholar_uc/blob/develop/config/initializers/assets.rb#L12

**Comment by jayanthdeejay** [comment]
https://stackoverflow.com/questions/8821864/config-assets-compile-true-in-rails-production-why-not

**Comment by hortongn** [comment]
After doing some research on precompiling assets, it looks like the way we're currently doing it with `rake assets:precompile` during our deploys is the best practice.

So no changes are need.  Closing this issue.
