### ISSUE TITLE
Based on Early Adopter feedback, further improve input forms

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#164]
Further improve (after work done on issue 211) input forms to make them more intuitive, and factoring in  feedback from Early Adopters (See Use Cases repository), determining which feedback is actionable.  See also issue #163

**Comment by jamesvanmil** [comment]
From the early adopter use cases, I can and will incorporate these two use cases into my work on issue #211, with a target for demo-ing on Feb. 3:

[Submission 10 - Determining Creative Commons license](https://github.com/uclibs/scholar_use_cases/blob/master/terms-licenses-rights/TOU-rights_use_cases.md#submission-10---determining-creative-commons-license)

[Submission 34 - Input Form](https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-34---input-form--early-adopter)

Other use cases should be reviewed for feasibility and difficulty. Linda - I'm going to kick this issue back to you until we undertake that work.

**Comment by newmanld** [comment]
See Issues 263, 264 and 265.  More to come.

**Comment by jamesvanmil** [comment]
All issues in backlog!
