### ISSUE TITLE
Production: move logs to shared NFS storage

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1657]
Move the location of the application and sidekiq logs from the log/ directory to /mnt/common/log/.

Each web server should continue to generate it's own file, but in a common directory.  E.g. `/mnt/common/log/production-pwl1.log` and `/mnt/common/log/production-pwl2.log`

**Comment by crowesn** [comment]
@hortongn is this resolved?

**Comment by hortongn** [comment]
Not resolved yet.  Someone needs to come up with the right config options to set a custom path for log files.  The path should probably be a Bamboo variable.

I think the end goal is for our log files to reside on the common Isilon share somewhere like `/mnt/common/scholar-logs`.  Each web server would write it's logs to that directory.
