### ISSUE TITLE
Permalink url is showing double slashes on QA

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1661]
### Descriptive summary

Permalinks are showing double slashes e.g. https://scholar-qa.uc.edu//show/1c18df78n

<img width="797" alt="screen shot 2017-09-27 at 2 37 53 pm" src="https://user-images.githubusercontent.com/1069588/30931104-a336de2e-a391-11e7-846d-34986c5ac186.png">

**Comment by flutterflies** [comment]
The issue here was the base url being defined with a trailing `/`. Removing the `/` from the configuration setting has resolved the issue.
