### ISSUE TITLE
"Filter your works" dropdown behaves strangely on the "My works" page

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1666]
The values of the dropdown appear below the entire sidebar

![screen shot 2017-09-27 at 12 40 23 pm](https://user-images.githubusercontent.com/9759017/31020911-3f41b142-a502-11e7-9bdf-d5e3ff562a8a.png)

**Comment by 13miciunasl** [comment]
This is a problem with vanilla Hyrax

**Comment by scherztc** [comment]
Is this fixed in Hyrax 2?
