### ISSUE TITLE
Unable to successfully add an editor to a work

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1667]
Adding an editor to a work via the 'share' tab appears as though it works, but does not actually add the editor

**Comment by jayanthdeejay** [comment]
When an editor is added in Share tab while creating the work, the editor does not get added initially but after the work gets created and if I add the editor again by by editing the work that was just added, it gets added. I'll continue to investigate this further on Monday.

**Comment by jayanthdeejay** [comment]
Just found that when an editor is added for the first time to any article, it doesn't get added. But if you retry, it gets successfully added. On top of that, for any new/existing articles here after, if you try to add an editor, they get added successfully. It's only the first time that doesn't work.

**Comment by crowesn** [comment]
I can't duplicate this issue on scholar-dev or local (using develop branch).

**Comment by scherztc** [comment]
Locally in production mode, I was able to assign a user EDIT access to a work on ingestion.  I am also running redis and sidekiq.  When I logged in as the Editor, I was able to see the following in the share tab.
![screen shot 2017-10-05 at 4 48 53 pm](https://user-images.githubusercontent.com/5084562/31251947-9bab0fba-a9ed-11e7-82fd-afb37a7e6a93.png)

**Comment by scherztc** [comment]
It also showed up in My Dashboard as a Works Shared with Me.
![screen shot 2017-10-05 at 4 56 13 pm](https://user-images.githubusercontent.com/5084562/31252112-290ac38c-a9ee-11e7-85a7-386b4e9c5562.png)

**Comment by crowesn** [comment]
Closing this because we haven't been able to duplicate the problem on local or QA.
