### ISSUE TITLE
Sort_fields is deprecated and will be removed from blacklight 7.x.

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1669]
### Descriptive summary

DEPRECATION WARNING: sort_fields is deprecated and will be removed from blacklight 7.x.

**Comment by jayanthdeejay** [comment]
https://github.com/samvera/hyrax/commit/8ab573513d3ea6f73bc4d61c8cee7f8911633bdf

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
