### ISSUE TITLE
Console recipe for adding user avatars

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1697]
### Descriptive summary

We need a console recipe for adding an avatar to existing users, given file_path in Scholar 3.

* variables: `:user`, `:filepath`

**Comment by 13miciunasl** [comment]
def add_avatars(user, filepath)
	f = File.open(filepath)
	u = User.where(id: user).first
	
	u.avatar = f
	u.save!
end

**Comment by crowesn** [comment]
Success on local. @jamesvanmil ?
