### ISSUE TITLE
Wording on homepage is off

### ISSUE THREAD

**Issue by flutterflies** [uclibs/scholar_uc#1700]
### Descriptive summary

The wording in the **What is Scholar@UC** section on the home page is a bit wonky. 

```Scholar@UC is a collaborative between UC Libraries and IT@UC```

![image](https://user-images.githubusercontent.com/12132647/31671139-4144a2fa-b327-11e7-8ac5-de2725fc4201.png)

**Comment by lawhorkl** [comment]
I'm not exactly sure what should be changed? Looks fine to me.

Specific changes should be listed in an issue.

**Comment by flutterflies** [comment]
`Scholar@UC is a collaborative between UC Libraries and IT@UC` 

In this sentence `collaborative` is an adjective but it has no noun to modify.  It needs to have a noun (i.e. project, effort) or it needs to be turned into a noun (i.e. collaboration)

**Comment by crowesn** [comment]
Make it "project"

**Comment by lawhorkl** [comment]
@crowesn as in `collaborative project`? Otherwise I will go with Katie's recommendation.

**Comment by crowesn** [comment]
@newmanld collaboration or collaborative project?

**Comment by newmanld** [comment]
Collaboration.

A better word might be partnership.   If we are changing, consider rewriting to be consistent with the About page.

Scholar@UC is an open source, agile development project supported in partnership by the University of Cincinnati Libraries and UC Information Technologies, with support from the Office of Research.

Or:
Scholar@UC is supported in partnership by the University of Cincinnati Libraries and UC Information Technologies, with support from the Office of Research.

**Comment by newmanld** [comment]
Still passive voice – if that bothers anyone look for a good way to make it active voice, please suggest, such as the following (although I’m not sure this is better):

                The University of Cincinnati Libraries and UC Information Technologies, with support from the Office of Research, are partnering to support Scholar@UC.

**Comment by newmanld** [comment]
Substitute “IT@UC” for “UC Information Technologies” – I guess that’s still the correct name.  Should also make that change on the About page.

From: Newman, Linda (newmanld)
Sent: Tuesday, October 24, 2017 4:05 PM
To: 'uclibs/scholar_uc'; 'uclibs/scholar_uc'
Cc: 'Mention'
Subject: RE: [uclibs/scholar_uc] Wording on homepage is off (#1700)

Still passive voice – if that bothers anyone look for a good way to make it active voice, please suggest, such as the following (although I’m not sure this is better):

                The University of Cincinnati Libraries and UC Information Technologies, with support from the Office of Research, are partnering to support Scholar@UC.

**Comment by lawhorkl** [comment]
Unassigning as I will be leaving after today

**Comment by jamesvanmil** [comment]
@13miciunasl on the home page would you please change:

"Scholar@UC is a collaborative between UC Libraries and UC Information Technologies, with support from the Office of Research."

to: 

"The University of Cincinnati Libraries and UC@IT, with support from the Office of Research, are partnering to support Scholar@UC."

Also please change "UC Information Technologies" to "UC@IT" on the about page.
