### ISSUE TITLE
Production:  Set Repository Managers

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1712]
There are a few accounts that will be migrated over that will need to be elevated to Repository Manager.  There is some admin documentation.

**Comment by hortongn** [comment]
For each user we want to make an admin, the following three lines can be run in rails console

```
admin = Role.create(name: "admin")
admin.users << User.find_by_user_key( "admin@example.com" )
admin.save
```

Just replace `admin@example.com` with the email of the user.

Change happens immediately.  No need to restart rails.
