### ISSUE TITLE
Separate multiple creator/authors with something other than a comma on catalog view

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1721]
The way multiple authors are displayed is ambiguous. Example: 

Snider, Sean, Nyland, John, and Olivera, Michael

The names should be separated instead by line breaks or semi-colons (or something else)

**Comment by jamesvanmil** [comment]
We used linebreaks in Scholar 2, but there was an easy option in blacklight 6 that didn't support linebreaks - so I went with semicolons

**Comment by hortongn** [comment]
@jamesvanmil I tested this solution and the Creator/Author now line reads this way:

`Person, Fourth; Author, Another; Horton, Glendon, and Doe, John`

Is in intentional that the last and second to last author are still separated by a comma?
