### ISSUE TITLE
Medium show view is missing :geo_subject

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1722]
### Descriptive summary

Media works are missing :geo_subject in the show view. The work has content in the element but it doesn't show.

https://scholar-prod.uc.edu/concern/media/05741v352

Check the [presenter](https://github.com/uclibs/scholar_uc/blob/develop/app/presenters/medium_presenter.rb).

**Comment by crowesn** [comment]
Also maybe make sure all the fields are showing that should: https://docs.google.com/spreadsheets/d/1FmNkbACv36fHUIY7WN88AvZ9iemlAadoTwt4KoEVxUc/edit#gid=0

**Comment by jamesvanmil** [comment]
Confirmed that geo_subject is the only one missing
