### ISSUE TITLE
browse_everything:kaltura displays files that don't belong to current user

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1731]
### Descriptive summary

Logged in under shibboleth, Kaltura driver is displaying media that does not belong to current user. Did not test download of files out of concern for privacy.

### Expected behavior

Kaltura driver should display only the current user's media items.

### Actual behavior

Displays media that doesn't belong to user.

<img width="596" alt="screen shot 2017-11-08 at 1 22 03 pm" src="https://user-images.githubusercontent.com/1069588/32567002-db18ec30-c487-11e7-8c32-80a8fca029b0.png">

**Comment by crowesn** [comment]
Noticed that sometimes the drive will display media limited to the user's stuff. Also, Sometimes the connection is secure and sometimes not - could be related to load balancing? 

Encountered browseverything/kaltura bug in both secure and insecure sessions.

<img width="534" alt="screen shot 2017-11-08 at 1 30 09 pm" src="https://user-images.githubusercontent.com/1069588/32567372-17c30192-c489-11e7-8afd-57ee34c0d494.png">
^no ssl session

**Comment by newmanld** [comment]
Today, on QA, (using Chrome) logged in with my QA Shibboleth credentials (same userid), when I selected Kaltura as a cloud provider, I only saw a list of private videos that are in fact owned by me.  I didn't see anyone else's content.  Repeated this with a second work type, and then a 3rd work type.

But then went to IE, and the first time, saw a list of other folks' titles, which however did not include my videos.  Cancelled, and on same input form, selected Browse cloud files again, and the second time it only showed my videos.  Third time only showed my videos.

So 5 out of 6 times only showed my videos, and one time showed other folks' videos and not my videos.

**Comment by newmanld** [comment]
Tried several more times, multiple browsers, and did not repeat the one time of seeing an unfamiliar video list.

**Comment by scherztc** [comment]
I have a PR on the Browse_Everything Kaltura driver to clear the session each time and pass "INVALID USER" to the query if the user is not part of UC.  The previous query was returning everything when using $current_user.nil.

https://github.com/uclibs/browse-everything/pull/4

**Comment by scherztc** [comment]
Updated PR: https://github.com/uclibs/browse-everything/pull/4/files

**Comment by scherztc** [comment]
Before deploying, we need to bundle update and commit the latest GEMFILE.lock

**Comment by scherztc** [comment]
Before we do a hard close on this issue, I have one more bit of code that may fix this bug.
I removed the Session start initializer from the driver code because the application was doing this with the config/initializer @session = ::Kaltura::Session.start.  I want to try putting it back and testing on QA.

**Comment by scherztc** [comment]
If we aren't going to worry about Kaltura , we could unpin browse_everything from our repo and just the Samvera repo.

**Comment by newmanld** [comment]
If the code Thomas mentions in the comment above on Mar 2 does not solve the authentication issue, then I think we should move this out of the milestone with a note that we need OAUTH or a better authentication method before considering again.  So this shouldn't take a great deal of time to resolve one way or another at this time.

**Comment by crowesn** [comment]
I think there is official code for kaltura clients here: https://github.com/kaltura/KalturaGeneratedAPIClientsRuby

**Comment by hortongn** [comment]
We should explore the code Sean links to above as a replacement for the kaltura gem we're currently using.  The gem we use now has failing tests under the version of ruby we're running.  The library Sean mentioned at least passes all tests under our ruby version (I cloned and ran the tests locally).

I did some testing on scholar-qa and I always saw just my own Kaltura videos when browsing cloud files.  So the files listing is working for me, but I did have multiple times when creating a work with kaltura files failed with `ActiveRecord::RecordNotFound (Couldn't find Hyrax::UploadedFile with 'id'=https://cdnapisec.kaltura.com/p/1492301/sp/149230100/playManifest/entryId/0_k77gupl3/format/download/protocol/https/flavorParamIds/0)`.  All the end user sees is a page with a 404.

I don't think our kaltura solution is stable enough for a production environment.  I don't think it will be until we find a replacement for our current kaltura gem.

@uclibs/developers

**Comment by scherztc** [comment]
Okay.  I appreciate the follow up testing for my own sanity. If we are going to list the concerns for Linda's white page, what would they be:

1. Unmaintained Kaltura library gem with failing test and outdated ruby support.
2. No OAuth for individual session authentication.
3. Only system wide production API keys and limited development environment.
4. Difficult to integrate Scholar with the KAF which is the recommended Kaltura application interface.

Any more?

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/605
