### ISSUE TITLE
Fix LibreOffice derivatives

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1734]
### Descriptive summary

When LibreOffice is generating derivatives for files, it often gets stuck and never finishes.  Seems to happen most of the time with .xlsx files, but may be others too.

There also seems to be a problem with LibreOffice generating multiple derivatives at once.  It may be best to limit the derivatives job queue to just one at a time

**Comment by scherztc** [comment]
Dev

ffmpeg version N-86442-g8aa60606fb-static
fits 0.8.5
GPL Ghostscript 8.70 (2009-07-31)
Version: ImageMagick 6.9.8-10 Q16 x86_64 2017-06-12

LibreOffice : NONE


New Production

ffmpeg version N-87043-gf0f48884b0-static
fits 0.8.5
GPL Ghostscript 9.07 (2013-02-14)
Version: ImageMagick 6.9.9-18 Q16 x86_64 2017-10-05
LibreOffice 5.4.2.2 22b09f6418e8c2d508a9eaf86b2399209b0990f4

**Comment by hortongn** [comment]
Confirming that fixing #1735 did NOT fix this issue.  Uploading excel files caused Sidekiq workers to get permanently stuck trying to process the derivatives.

Best suggestion for a next step is for someone to spin up up a vagrant environment and try a different version of LibreOffice to see if it has the same problem.

To manually convert an xlsx test file to pdf:
`/opt/libreoffice5.4/program/soffice.bin --invisible --headless --convert-to pdf --outdir /tmp testfile.xlsx`

**Comment by hortongn** [comment]
@jamesvanmil These spreadsheets seem to have problems
* Firefox_Reqs.xlsx
* Buildings_Database.xlsx
* BD_Totales__1_.xlsx

The LibeOffice filter that seems to hang when trying to convert the xls to a PDF is `calc_pdf_Export`

**Comment by jamesvanmil** [comment]
I was able to replicate this error locally with an `.xlsx` file, and I was able to make it succeed with a different `.xslx` file.

**Comment by jamesvanmil** [comment]
Updated to LibreOffice 6.0.1 - getting error messages now!

**Comment by jamesvanmil** [comment]
@newmanld @scherztc - I think the impact of this problem is limited:

* Thumbnails for spreadsheets are largely cosmetic, and often don't represent the data set well.
* This is only happening to a limited set of `*.xlsx` files.

I recommend closing the issue, and opening an issue on samver/hydra-derivatives

**Comment by scherztc** [comment]
Since no version of LibreOffice will fix this, I am in favor of punting this to Hydra-Derivatives: https://github.com/samvera/hydra-derivatives and moving the issue to the 4.1 milestone.

**Comment by newmanld** [comment]
I think we first need a review of where we have caches of content in Scholar@UC without thumbnails – how much content is affected -- and if we have an interim, manual solution for that content.

How is this related to #1735 - #1735 does refer to a fix on QA?

**Comment by hortongn** [comment]
This issue and #1735 are unrelated except for the fact that both issues are about thumbnails not being generated properly.  

#1735 is fixed on scholar-dev and scholar-qa.  The fix has not been applied to production yet.

**Comment by newmanld** [comment]
Thanks for that clarification re #1735 @hortongn.   Reading the original issue statement on this issue (#1734) it says “Seems to happen most of the time with .xlsx files, but may be others too.”– have we determined whether there are other formats affected, or verified that this is only .xlsx files?   If only .xlsx files deferment to 4.1 milestone is appropriate.
