### ISSUE TITLE
Fix derivatives for some PDFs

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1735]
### Descriptive summary

Some PDFs are generating blank thumbnails.  It happens even if the thumbnail is regenerated.

There may be something specific about the formatting of these PDFs.  The fix likely involves a change to software on the servers.

Examples:
* https://scholar-prod.uc.edu/concern/student_works/bc387f771?locale=en
* https://scholar-prod.uc.edu/concern/student_works/bc387f57j?locale=en
* https://scholar-prod.uc.edu/concern/student_works/bc387f29c?locale=en

**Comment by scherztc** [comment]
Getting different results on DEV - 

https://scholar-dev.uc.edu/concern/articles/5d86p020k?locale=en
https://scholar-dev.uc.edu/concern/generic_works/d791sg16q?locale=en
https://scholar-dev.uc.edu/concern/generic_works/02870v844?locale=en

**Comment by hortongn** [comment]
@scherztc scholar-dev has not yet been rebuilt like our production and QA environments.  So dev is running different versions Imagemagick, etc.

**Comment by scherztc** [comment]
I will compare versions and double check hydra derivatives to see what switches they are using with the binaries.

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/blob/21117ad865f62a15668ad59f474764856a56dbdf/app/services/hyrax/file_set_derivatives_service.rb

**Comment by scherztc** [comment]
Dev

ffmpeg version N-86442-g8aa60606fb-static
fits 0.8.5
GPL Ghostscript 8.70 (2009-07-31)
Version: ImageMagick 6.9.8-10 Q16 x86_64 2017-06-12

LibreOffice : NONE


New Production

ffmpeg version N-87043-gf0f48884b0-static
fits 0.8.5
GPL Ghostscript 9.07 (2013-02-14)
Version: ImageMagick 6.9.9-18 Q16 x86_64 2017-10-05
LibreOffice 5.4.2.2 22b09f6418e8c2d508a9eaf86b2399209b0990f4

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/commit/b4eb94c3bdf530430e96868217a72689217f0b57

**Comment by scherztc** [comment]
This command produces a JPG for all three environments:

soffice --invisible --headless --convert-to jpg --outdir /Users/scherztc/Desktop /Users/scherztc/Desktop/White_Derivative.pdf



#{Hydra::Derivatives.libreoffice_path} --invisible --headless --convert-to #{format} --outdir #{outdir} #{Shellwords.escape(path)}

**Comment by scherztc** [comment]
gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -dLastPage=1 -sOutputFile=Thumbnail.jpeg -dJPEGQ=100 -g250x250 -dUseCropBox=true  -dPDFFitPage=true -q  [InputFile].pdf -c quit

**Comment by hortongn** [comment]
These are the steps needed to fix ghostscript on our servers so PDFs can generate thumbnails.  This works in the vagrant environment and will therefore work on the servers.  I'll test the fix on scholar-dev next.

1. `sudo yum -y remove ghostscript`

1. `wget https://downloads.sourceforge.net/project/ghostscript/GPL%20Ghostscript/9.07/ghostscript-9.07.tar.gz`

1. `tar -xzf ghostscript-9.07.tar.gz`

1. `cd ghostscript-9.07`

1. `./configure --prefix=/usr`

1. `make`

1. `make so`

1. `sudo make install`

1. `sudo make soinstall`

1. `sudo install -v -m644 base/*.h /usr/include/ghostscript`

1. `sudo ln -v -s ghostscript /usr/include/ps`

1. `wget https://rpmfind.net/linux/centos/7.4.1708/os/x86_64/Packages/graphviz-2.30.1-19.el7.x86_64.rpm`

1. `sudo rpm -ivh graphviz-2.30.1-19.el7.x86_64.rpm --nodeps`

1. `cd /opt/staging/imagemagick/`

1. `sudo rpm -Uvh *.rpm --nodeps`

**Comment by hortongn** [comment]
Installed the PDF thumbnail fix on scholar-dev and tested with 4 PDFs that are problematic on production.  All now have proper thumbnails.  See https://scholar-dev.uc.edu/concern/documents/7s75dc38h?locale=en

**Comment by hortongn** [comment]
PDF thumbnail fix has been installed on scholar-qa: https://scholar-qa.uc.edu/concern/documents/8s45q876k?locale=en

**Comment by hortongn** [comment]
I've updated the Puppet scripts to include the fix needed for PDF thumbnails.

Remaining steps:
1) Install the fix on production (change request required)
2) Regenerate thumbnails for existing (broken? all?) PDFs

**Comment by hortongn** [comment]
Example of a rake task for regenerating derivatives.  May be useful for when we need to regenerate PDF thumbnails before closing this issue.

**Comment by scherztc** [comment]
Re-compile Ghostscript on production.
Run Rake task to re-generate PDF thumbnails.
