### ISSUE TITLE
StudentWorks :genre field blank

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1738]
### Descriptive summary

It looks like the "Report" option was dropped it the genre controlled vocab select in Scholar 3.

We need to:

1. Add `Report` to list of options for `:genre`
1. Set `:genre` to 'Report" for all student works

**Comment by jamesvanmil** [comment]
It's still listed in the vocab: https://github.com/uclibs/scholar_uc/blob/d0b5d70285ae7bbcb1355fd749415c9673c89f23/config/authorities/genre_types_student_work.yml#L30-L31

And I'm seeing it in the options on the form.

I'll write a recipe to update the fields.

**Comment by jamesvanmil** [comment]
No PR for this, script is done - awaiting review and execution
