### ISSUE TITLE
No paragraph breaks in collection description

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1740]
### Descriptive summary

A large block of description content which included paragraph breaks in scholar 2 is displaying with no paragraph breaks on scholar 3.

https://scholar.uc.edu/collections/05741w32f

Requested that the content show paragraph breaks for ease of reading.

### User comment

>I checked out the upgraded Schultz Archive on UC Scholar and have one immediate concern. 
 
>There’s a 771 word introductory essay on the cover page which, in the new version, appears as one giant chunk of text with no paragraph breaks.  It’s very ungainly and offputting, especially as it’s the first thing a visitor to the site would see.
 
>Is there any way we can make this opening statement more attractive and readable?  I feel it’s a pretty serious issue.

<img width="1042" alt="screen shot 2017-11-13 at 1 50 41 pm" src="https://user-images.githubusercontent.com/1069588/32743259-e3e9e3be-c879-11e7-854d-3fbc10d3e5cc.png">

**Comment by newmanld** [comment]
When I login as an administrator and edit the collection, the paragraph breaks are there.

**Comment by hortongn** [comment]
The paragraph breaks are also there if you view the page source.  I think we just need some code that converts line breaks to HTML breaks on the collection show page.
