### ISSUE TITLE
Improve UX for selecting and deselecting a collection on the Relationships Tab

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1756]
### Descriptive summary

On the Relationships tab, on the Work submit and edit form (both batch and individual), it is not obvious how to select and deselect a collection.  

User feedback indicates that it is not clear, when collection(s) the user owns are first listed (under "Member of collection ids"), that works are not already members of the collection(s).  It is not clear that they need to highlight the collection name (with mouse or keyboard controls) to establish the relationship between the work and the collection.

It is also not obvious how to use CTRL (or Command on a Mac) to deselect a collection, on submission or edit.   Users that are very familiar with multi-select keyboard behavior may intuit this, but most users will not, making this UX dysfunctional enough to be considered a bug.

There could be an accessibility issue here.  With a combination of tab and down arrow, I could select a collection.  I could not figure out how to de-select a collection without using the mouse.  CTRL,Space and CTRL,ALT,Space didn't work.

### Expected behavior
"Member of collection ids" is re-phrased, as the work may not yet be a member.  Help and/or tips are provided to explain the selection list, and how to select and deselect a collection, including keys for both windows and macs, and keyboard alternatives to the mouse.

Alternatively, this area of the work submit/edit form is re-designed, looking for inspiration from the Collections Extensions code going into Hyrax 2.1.

**Comment by jamesvanmil** [comment]
@flutterflies let's close this in the current sprint by adding help information:

"To select or de-select one or more collections, hold Control or Command while clicking"

It looks like we've brought a few `_relationships_*` partials in for override, but I'm not certain if these are the ones we need to change to add this info: https://github.com/uclibs/scholar_uc/tree/develop/app/views/hyrax/base

**Comment by jamesvanmil** [comment]
closed by #1785
