### ISSUE TITLE
Searching for users is slow on scholar.uc.edu

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1775]
### Descriptive summary

On the work share tab and on a user's dashboard when trying the add a new proxy, the "search for a user" feature is very slow.  Typing in a couple letters or a name takes close to a minute to return results.  The search just spins in the meantime and probably gives the user the impression that it can't find any users.

The slowness doesn't occur on scholar-qa or scholar-dev.  

It *may* be slow because of the number of registered users on scholar.uc.edu.  Someone could register 100+ fake accounts on scholar-qa to see if the same slowdown occurs.

**Comment by hortongn** [comment]
@jayanthdeejay Maybe instead of altering the database query, we should just hide users on the view?  Maybe wrap the view code below in a `<% if number_of_works(user) > 0 %>`?  (I'm not sure if that will still be slow or not, but at least it won't affect the proxy search).

https://github.com/uclibs/scholar_uc/blob/develop/app/views/hyrax/users/index.html.erb#L18-L30

**Comment by jayanthdeejay** [comment]
I tested what you suggested last week and there was a significant increase in the performance in displaying the users page locally. I could not obviously measure the performance.

**Comment by hortongn** [comment]
👍  Sounds like filtering at view might be the way to go.

I did notice on production that we have over 3,500 user objects.  Most of then are "guest" users generated by the `devise-guest` gem.  So that may be why performance is such a problem on production when filtering out non-owners.
