### ISSUE TITLE
Research page turner for paginated documents

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1795]
### Descriptive summary

Add a page turner for ebooks and other paginated documents.

**Comment by crowesn** [comment]
https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks#loading-a-book-from-a-file-input

**Comment by crowesn** [comment]
Branch on curly with [cozy-sun-bear](https://github.com/mlibrary/cozy-sun-bear/) integration: https://github.com/uclibs/scholar_uc/tree/cozy-sunbear

Our test integration will display epubs in the fileset show view. Images appear to be broken - [solution?](https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks#loading-a-book-from-a-file-input)

**Comment by scherztc** [comment]
@crowesn :  Since this was a research task, can we close it?
