### ISSUE TITLE
Update Featured researcher

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1807]
### Descriptive summary

Use TinyMCE Editor to embed photo in featured researcher on deploy of scholar 3.1 release.

Related

@newmanld Can you put the source photo in a comment on this issue?

**Comment by newmanld** [comment]
This is the source photo (you don't need to login): https://libapps.libraries.uc.edu/scholarblog/wp-content/uploads/2017/11/DrNanNiu.png
This is the blog post we should link to: http://libapps.libraries.uc.edu/scholarblog/scholar-story-nan-niu-phd/
I'll add a photo here without the overlay naming Dr. Niu, in case you need it. 
![niunan270x270](https://user-images.githubusercontent.com/3521707/35301128-c21c9bb6-0058-11e8-865a-1a820c71b356.jpg)

**Comment by crowesn** [comment]
Thanks, @newmanld
