### ISSUE TITLE
Characters of the File Name

### ISSUE THREAD

**Issue by changy66** [uclibs/scholar_uc#1812]
### Descriptive summary

There is an error "Internal Server Error" when upload a new file to a work if the file name is Chinese characters.

### Actual behavior
![image](https://user-images.githubusercontent.com/20506541/35353628-bc97af38-0115-11e8-974d-a3d2e896b43e.png)

**Comment by scherztc** [comment]
<img width="548" alt="screen shot 2018-04-10 at 4 56 23 pm" src="https://user-images.githubusercontent.com/5084562/38583155-29ffa5ca-3ce0-11e8-83e6-a20d776d27c9.png">

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
