### ISSUE TITLE
Can't change visibility for embargoed works

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1815]
### Descriptive summary

Once a work has been embargoed, visibility setting can't be changed in the GUI.

### Expected behavior

Work Edit controls with visibility setting `embargoed` should have controls to change visibility.

### Actual behavior

* Visibility pane excludes other visibility options.
* Has text:
     `This work is under embargo. You can change the settings of the embargo here, or you can visit the Embargo Management Page to deactivate it. `
* *Embargo management page* is 404

### Steps to reproduce the behavior

1. Create work with all requirements
1. Set visibility to embargoed
1. Save page
1. Edit page and examine visibility pane.

### Related work

https://github.com/uclibs/scholar_uc/wiki/Scholar-3.0-(Hyrax)-Test-Script#embargo

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
