### ISSUE TITLE
Can't edit work with unresolvable DOI

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1816]
### Descriptive summary

The error is related to her work having a DOI.  
```
`F, [2018-01-31T12:13:59.610877 #8627] FATAL -- : [31bfbfab-c29f-4d71-9a9d-5ab67bf72d8b] Hydra::RemoteIdentifier::RemoteServiceError (response.code: 400
response.body: “error: bad request - _status: invalid identifier status change”
```

From the log:
```
request.uri: “https://xxx:xxx@ezid.cdlib.org/id/doi:10.7945/C2Z97T”
request.payload: “_target: https://scholar.uc.edu/show/pz50gw09d\n_status: unavailable\ndatacite.creator: Newman, Linda, Neeser, Amy, Johnston, Lisa, Koshoffer, Amy\ndatacite.title: Digital_o
bject_identifiers_for_datasets_four_institutional_repositories\ndatacite.publisher: University of Cincinnati\ndatacite.publicationyear: 2018"
```

### Expected behavior

Embargo or private works created with reserved DOI should be able to update-able (regardless of DOI status.)

### Actual behavior

Embargoed and private works with DOIs seem to have un-resolvable DOIs, which is preventing updates to the work.

**Comment by jamesvanmil** [comment]
Good news is that I was able to replicate this in dev

**Comment by jamesvanmil** [comment]
Found the issue:

When updating the metadata on a DOI, you're only allowed to flip a `reserved` doi to `public`, not to `unavailable`. When saving the work with a reserved DOI, without changing the visibility to `public`, this code causes it to attempted to save as `unavailable`:

```ruby
      def doi_status
        if visibility == Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC
          "public"
        elsif locally_managed_remote_identifier?
          "unavailable"
        else
          "reserved"
        end
      end

      def locally_managed_remote_identifier?
        return true unless identifier_url.nil?
        false
      end

```

We need to do better modeling locally of whether the identifier is `reserved`, so we can send the appropriate request.
