### ISSUE TITLE
Large File Ingest broken for 10 GB files.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1817]
### Descriptive summary

We need to look at Browse_Everything. for 10 GB files.
We need to test fits -s Don Norman video from console.
We need to revisit our large file ingest recipe from the console.

### Expected behavior

All three ingest methods work successfully.

### Actual behavior

ImportUrlJob times out on Sidekiq.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by jayanthdeejay** [comment]
https://github.com/uclibs/scholar_uc/blob/6b479d2189950e6efed40d4f93f805a332ee9e1e/app/assets/javascripts/hyrax/uploader.js#L32

I believe we have set a limit on file size (<3GB).

**Comment by scherztc** [comment]
Examine the 3 GB limit in UX and see if we can increase.

**Comment by scherztc** [comment]
Development method for console ingestion for large files.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
