### ISSUE TITLE
Error when clicking faceted field from collection gallery view

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1819]
### Descriptive summary

Getting an exception when navigating to a collection, switching to gallery view, and clicking a facet.

### Steps to reproduce the behavior

1. Go to a collection and select gallery view, e.g.: https://scholar.uc.edu/collections/d504rk335?locale=en&view=gallery
1. Click a Creator name, or any other field that leads to a search, e.g.: https://scholar.uc.edu/files/d504rk335?action=index&controller=catalog&f%5Bcreator_sim%5D%5B%5D=Kim%2C+Bora&locale=en&only_path=true

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
