### ISSUE TITLE
Video downloaded from Kaltura has confusing file extension

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1820]
### Descriptive summary

A video downloaded from Kaltura via cloud files has a `*copy` file extension, instead of a file extension matching the file type. This is happening with a downloaded file from a WebEx recording

### Expected behavior

The file should have an extension matching the file type.

### Actual behavior

The file has a `*.copy` file extension.

### Steps to reproduce the behavior

1. Ingest a cloud file using Kaltura
1. Download the file
1. If it doesn't work, make a WebEx recording, then download that file

**Comment by scherztc** [comment]
This is a Kaltura hosted problem.  They way they have the WebEx hook to automatically move the content from WebEx to Kaltura creates this .copy file as the source flavor.  The original format is a .arf file.  I don't think it is worth it to build in checks and flavor conversions in our application.  I am in favor of closing this issue or moving it to another milestone.
