### ISSUE TITLE
Create process for automating embargo releases

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1833]
### Descriptive summary

Hyrax 1.x does not include a method (rake task or other) for changing works or files that are embargoed to a different visibility status when the embargo date expires.    Initial review indicates that Hyrax 2.x does not either - further confirmation needed.

### Expected behavior
When an embargo date for a work or file expires, the work and/or file is changed (from the contributor's perspective, automatically) to the intended visibility (the two choices are Open Access and UC-only).  Any attached files that are private but not embargoed stay private.  If the visibility status changes from embargo to Open Access (not UC-only), the correct handshake takes place with the EZID system for changing a reserved DOI to a public DOI. (See also #1834) 

### Actual behavior
Nothing happens when the embargo date expires, and if we discover this, we must manually change the visibility status through the console, and manually login to the EZID system to change the DOI status from reserved to public.

### Related work
See automated processes formerly in place with our Scholar 2.x app on top of Curate.

**Comment by hortongn** [comment]
A couple of use cases that Penn State's solution doesn't cover:

* The service finds all works with an embargo, removes the embargo, and then copies the visibility to the work's attached files.  However, if a work is `public` and has an attached file that is `embargoed`, the service will not remove the embargo from the file.  In addition to cycling through all work types, we probably need to cycle through all FileSets as well.

* The service only tries to remove embargoes expiring on the date given.  If the rake task gets missed or fails on a particular date, embargoes with that date may never get removed.  The service should probably find all works/files with an expiration date equal to **or earlier than** the date given.
