### ISSUE TITLE
Update the manual test script

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1836]
### Descriptive summary

Update https://github.com/uclibs/scholar_uc/blob/develop/TEST-SCRIPT.md to test functionality that currently isn't covered.

Look over the app and find areas we are not currently covering in our manual tests.

Examples of tests to add:
* Cloud uploads
* Batch ingest
* Batch edit
* Transfering work ownership

**Comment by scherztc** [comment]
See : https://github.com/uclibs/scholar_uc/pull/1876

We still need to add Transferring work ownership.
