### ISSUE TITLE
Control characters like vertical tabs causing Solr indexing to fail

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1841]
### Descriptive summary

The solr reindex task on production was failing because it was hitting vertical tabs in metadata.  We used to have this problem in Scholar 2.x and used a monkey patch (https://github.com/uclibs/curate/blob/develop/config/initializers/rsolr_sanitize_monkey_patch.rb) to sanitize problematic control characters before indexing.  That patch got removed in Scholar 3.x, but it looks like we may still need it.

Replicate a problem work by adding control characters like `\t`, `\n`, and `\r`to metadata.  Running a reindex task should fail.

**Comment by scherztc** [comment]
bundle exec rake solr:reindexnow

**Comment by scherztc** [comment]
I tested some of the control characters in my local environment and used this rake task :

**Comment by scherztc** [comment]
See : https://github.com/uclibs/scholar_uc/commit/f319965549b9184900dab28d92ac399fcb2fff57

**Comment by scherztc** [comment]
Could not reproduce.
