### ISSUE TITLE
Load Current ETDs

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1858]
- [ ] Obtain files and metadata
- [ ] Metadata work for backfile
- [ ] Batch load to prod
- [ ] Establish ongoing workflow

**Comment by scherztc** [comment]
@crowesn : Can we close this one with a count/status update?

**Comment by crowesn** [comment]
@scherztc This issue is for current ETDs - content swat was for historical ETDs from proquest.

**Comment by scherztc** [comment]
Content transfer under discussion with grad school
*  Credentials
*  Follow up after commencement
*  Archive material conversation (Retrospective)
*  Permanently embargoed works
*  Start with what we need to do to load the current stuff (Download OhioLink / Sierra)
*  Workflow review
*  WorldCat

**Comment by jamesvanmil** [comment]
Awaiting UCL admin approval before loading

**Comment by jamesvanmil** [comment]
Closed with submission of report concerning progress in this milestone. Any further work will be managed elsewhere.
