### ISSUE TITLE
Review faculty CV project output

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1861]

**Comment by scherztc** [comment]
Review Spreadsheet
Console work.
*  Clean up College and Departments
*  Make Public 
*  Change owner from submitter to faculty. (Make sure faculty have accounts.)
*  Make sure student is not editor.
*  Remove Repository Manager as editor.

**Comment by jamesvanmil** [comment]
@newmanld & @jamesvanmil to meet

**Comment by jamesvanmil** [comment]
Closed with submission of report concerning progress in this milestone. Any further work will be managed elsewhere.
