### ISSUE TITLE
Move all IR content from the DRC to Scholar@UC

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1863]
### Descriptive summary

We have some remaining examples of content in the DRC that should be moved/copied to Scholar@UC if it can be fully supported now.

A database or spreadsheet of all works needs to be maintained to prepare for a future replacement of the DRC handle server.

**Comment by scherztc** [comment]
Review how we copied the Senior Dissertations from DRC to Fedora.
   Handle server.
   @newmanld Test Mapping: Export from DRC and manual enter in Scholar.
   Google Doc move to Box.

**Comment by scherztc** [comment]
Determine priority for 
 *    CCM Programs and CCM Recordings
 
Review all collections in DRC

**Comment by jamesvanmil** [comment]
@newmanld starting with Elliston - moving forward soon

Other collections require parent collections - some are proceeding now; others waiting for UCRATE

**Comment by jamesvanmil** [comment]
Closed with submission of report concerning progress in this milestone. Any further work will be managed elsewhere.
