### ISSUE TITLE
Download option in Image Viewer doesnt work

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1867]
### Descriptive summary

In the current version of Scholar@UC based on Hyrax 1.x the is a download button in the image viewer.  It doesn't worked.  This may be improved or resolved in Hyrax 2.x where the Image Viewer is incorporated into the release.  

### Expected behavior
Download button gives options for size, and then allows the user to export an image.

### Actual behavior
A message appears that says "No download options are available."

### Steps to reproduce the behavior

Go to a work with an image, such as https://scholar.uc.edu/show/bc386t80f
Select the download button in the lower left-hand corner of the image viewer.

### Related work
Public files can be downloaded from the file listing further down on the work show page.  An adequate solution may be to suppress this button.

**Comment by scherztc** [comment]
https://github.com/pulibrary/pul_uv_rails
