### ISSUE TITLE
Improve UX of People Listing

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1868]
### Descriptive summary

The People listing should be reviewed for UX.  See https://scholar.uc.edu/users?locale=en

It's not clear that the user name and user email are linked to the user profile.

Issue #1895 covers
The sort options on the People display don't fully work and it is not clear which columns can be sorted.
"Contributor" could be a better column header than "User Name."

~When paging through the People display, an inconsistent number of names are shown - this may be a side effect of hiding users with zero works.~ (Split into issue #1883)

~The People listing also suffers from the "infinite pagination" bug which was documented here: https://github.com/uclibs/scholar_uc/issues/1781.~ (Split into issue #1890)

**Comment by hortongn** [comment]
I created a separate issue for the bug "When paging through the People display, an inconsistent number of names are shown".  I'll assign that issue to me. (#1883)

**Comment by scherztc** [comment]
Sort Options :  The only sort option that functions is User_ID (login).  That appears to be the only sort that works in Hyrax 2 (curly.libraries.uc.edu:2002/users and nurax).  Here is a current Hyrax issue regarding sort. https://github.com/samvera/hyrax/issues/2858

**Comment by newmanld** [comment]
Inconsistencies:
A presence of a down arrow when one clicks on a column title seems to indicate that the column can be sorted, but it does not show up unless you click on the column title. Is this intuitive?

The sort option under User Name (which we are renaming Contributor) doesn't work.  This sort should be by last name, then first name (and we do have that information for the user, as I understand.)

The Sort option under Email address does work, but I've proposed in #1897 that we remove Email Address (i.e. User ID) from this page.

The Sort option under College & Department does not work.

'Works created' doesn't show the down arrow so presumably is not meant to be sortable.
