### ISSUE TITLE
New users are not shown the welcome page

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1869]
### Descriptive summary

While examining #1866, we realized that new users are not seeing the Welcome page.  The welcome page should display when new users log in.  They should see the page until they check a box that they should not see it anymore.

It appears that new users do receive a welcome email, but they are not seeing the page in the browser.  Code is in place to display a welcome page, but it's definitely not working.

We don't seem to test that the welcome page displays in our specs or the manual test script.  So the bug has gone unnoticed probably since we launched Scholar 3.

**Comment by scherztc** [comment]
Original Scholar 3 Overwrite : https://github.com/uclibs/scholar_uc/commit/7d2c429c781a4eb02e5896709ee17f02b0e240fe
