### ISSUE TITLE
Embed Option in Image Viewer doesn't work.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1880]
### Descriptive summary

When viewing an image in Scholar@UC that displays in the Universal Viewer, an option appears bottom left to copy embed code.  For this work: https://scholar.uc.edu/show/8g84mm26k, the Embed code looks like this:  
`<div class="uv" data-locale="en-GB:English (GB),cy-GB:Cymraeg" data-config="" data-uri="/concern/images/8g84mm26k/manifest?locale=en" data-collectionindex="0" data-manifestindex="0" data-sequenceindex="0" data-canvasindex="0" data-zoom="-0.1237,-0.0368,1.2475,0.7367" data-rotation="0" style="width:780px; height:400px; background-color: #000"></div>`
`<script type="text/javascript" id="embedUV" src="https://scholar.uc.edu/bower_includes/universalviewer/dist/uv-1.7.11/lib/embed.js"></script><script type="text/javascript">/* wordpress fix */</script>`

I've created a test web page and the window for the universal viewer appears, but not the image.  The javascript console indicates that it cannot find the file named jquery.min.js, and it appears to be looking in my local environment for file://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js.

### Expected behavior
Using the provided embed code on a webpage external to Scholar@UC will result in a functioning universal viewer with the image.

### Actual behavior
A blank universal viewer window appears.

### Steps to reproduce the behavior

1. Locate a public image work with a public attached file.
1. Click on the embed symbol in the lower left.

### Related work
#1867 

Suggest determining if this appears to be functioning in Hyrax 2.1 (nurax.curationexperts.com), but also looking for an UV configuration steps we might have missed, any whether any straightforward fix to our Scholar environment using Hyrax 1.x is also possible.

**Comment by scherztc** [comment]
Princeton has gemified the Universal Viewer.  It is this gem that hyrax 2 uses.  https://github.com/pulibrary/pul_uv_rails
