### ISSUE TITLE
Increase collection work type's boost weight

### ISSUE THREAD

**Issue by jayanthdeejay** [uclibs/scholar_uc#1881]
### Descriptive summary

We have implemented #1837 to boost the collection work type. It is boosting collection work type when browsing but not when a user performs search. Test in production by increasing the boost weight from 20 to a higher value to see if it makes any difference.

### Steps to reproduce the behavior

1. Hit Browse in Scholar homepage after logging in and the works that are displayed by default are collections as we are boosting them.
1. Perform search with some keyword like "iasdr". Currently, the collection work type shows up after it's member work and it should be the other way around.
1. Increase the boost weight in code below to see if it makes any difference.

### Related work

https://github.com/uclibs/scholar_uc/blob/cf071428988faf0a944f0e909fbead1913f2ae49/solr/config/solrconfig.xml#L113-L115

**Comment by hortongn** [comment]
@jayanthdeejay We changed the collection boost from `20` to `2000` and it worked.  Collections now always sort above works.  So you can go ahead and open a PR that makes that change in solrconfig.xml and closes this issue.  Thanks
