### ISSUE TITLE
Sort options on the People display need to work for User Name, User ID, and College & Department

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1895]
### Descriptive summary

The sort options on the People display don't fully work and it is not clear which columns can be sorted.

### Expected behavior

The sort options on the People display do work for User Name and College & Department.
User ID DOES work.

The carat should show up by default if a column is sortable.

User Name column should be labelled as 'Contributor'

### Actual behavior

The sort options on the People display don't work for UserName and College & Department.
User ID DOES work.

The carat should show up by default if a column is sortable.

### Steps to reproduce the behavior

1.  Visit : https://scholar.uc.edu/users?utf8=%E2%9C%93&uq=&sort=login&locale=en
2. Click Column Header.
### Related work

https://github.com/uclibs/scholar_uc/issues/1868

**Comment by newmanld** [comment]
Inconsistencies:
A presence of a down arrow when one clicks on a column title seems to indicate that the column can be sorted, but it does not show up unless you click on the column title.  Is this intuitive?
 The sort option under User Name (which we are renaming Contributor) doesn't work.
 The Sort option under Email address does work.
 The Sort option under College & Department does not work. 

'Works created' doesn't show the down arrow so presumably is not meant to be sortable.

I didn't write this up in the original statement of the issue - #1868 - , but I'm thinking we should remove Userid.  Clicking on either User ID or User Name goes to the User Profile.  But  I think one would expect clicking on an email address to  open an email window.  Regardless, the email address appears on the Profile.  Does it need to appear here?

**Comment by newmanld** [comment]
Ideally the sort on User Name should sort by Last Name, First Name.
