### ISSUE TITLE
Migrate DOIs to use Datacite

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1909]
### Descriptive summary

Sometime this summer we will need to change from CDL's EZID API to Datacite's EZ API.

The EZ API is designed to be compatible with the EZID API, though swapping configuration in our app is yielding a (hopefully) minor error that @jamesvanmil will wrangle.

Before we switch:
* Our Datacite license needs to be completed (still pending 2018-05-05)
* Datacite needs to implement reserve DOI functionality (per roadmap released on 2018-05-02 - need to test)

A PR for scholar will prepare us for the switch, and we should plan to deploy after the conditions above are confirmed satisfied

**Comment by jamesvanmil** [comment]
Having trouble implementing the _profile field - emailed datacite for advice

**Comment by jamesvanmil** [comment]
Response from Datacite:

> Unfortunately the DataCite EZ API doesn't support metadata in the format you provided, but you have to send DataCite XML instead. We know that people want to submit metadata in a key/value format like you tried, so it is something on our roadmap.
>
> The easiest way to try the API is to use "_status: reserved", as no metadata are required.

The next step is to look at modifying Hydra Remote Identifiers to deliver and XML payload.

**Comment by hortongn** [comment]
Move to https://github.com/uclibs/ucrate/issues/330
