### ISSUE TITLE
Trailing whitespace breaks user search 

### ISSUE THREAD

**Issue by flutterflies** [uclibs/scholar_uc#1910]
### Descriptive summary

When searching users on the people page in scholar trailing white space in the search string cause no user to be returned 

When searching "Katie"
<img width="455" alt="image" src="https://user-images.githubusercontent.com/12132647/39721026-20ca4a5a-520c-11e8-92a8-1871335fb297.png">

When searching "Katie "
<img width="466" alt="image" src="https://user-images.githubusercontent.com/12132647/39721062-383f5fa4-520c-11e8-9d6c-e85606dfe4e9.png">

### Steps to reproduce the behavior

1. Go to users page in scholar
1. search for an existing user, adding a space after the name

**Comment by changy66** [comment]
In the 'app/views/hyrax/users/_search_form.html.erb', I changed 'params[:uq]' to 'params[:uq].strip', it doesn't work correctly. looks like it still take "Katie " as input but it showed "Ketie" in the field. 
![image](https://user-images.githubusercontent.com/20506541/41179579-23212968-6b39-11e8-9b5d-e0e42879307d.png)

Maybe we need to change some files in the gem?

**Comment by hortongn** [comment]
Moved this issue to https://github.com/uclibs/ucrate/issues/277
