### ISSUE TITLE
Broken link to UC Use of IT Policy 

### ISSUE THREAD

**Issue by flutterflies** [uclibs/scholar_uc#1911]
### Descriptive summary

In our Terms of Use we have a link to the university's Use of Information Technology Policy. Following this link results in being directed to a university 404 page.

the link we have in scholar goes to http://www.uc.edu/content/dam/uc/infosec/docs/policies/Use_of_Information_Technology_Policy.pdf

but it looks like the correct link is http://www.uc.edu/content/dam/uc/infosec/docs/policies/Acceptable_Use_of_University_Information_Technology_Resources_9.1.3.pdf

### Steps to reproduce the behavior

1. go to https://scholar.uc.edu/terms?locale=en
1. click the link towards the bottom of the page for the Use of Information Technology policy

**Comment by hortongn** [comment]
Sent email to Info Sec on 5/31 asking if they can set up a redirect from the old URL to the new one.
