### ISSUE TITLE
FileSet missing depositor_ssim

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1917]
File sets are missing this expected value in the Solr document. We need to dig in to figure out why this is happening, and how we should/could manage occurrences.

This is impacting the stats import.

**Comment by scherztc** [comment]
scholar@libschpwl1:curate_uc$ bundle exec rake manifest:files
rake aborted!
ActiveFedora::ObjectNotFoundError: Couldn't find FileSet with 'id'=bc388046h

**Comment by scherztc** [comment]
There are 44 FileSets in production that don't have an owner or depositor:

05741v149 | woodmanc_phoenecia_thumb.png
bc386k33m | woodmanc_phoenecia_2015.mov
bc388c32f | Aniba_ITS.nex
bc388c340 | Aniba_psbD-trnT.nex
bc388c358 | Aniba_trnC-rpoB.nex
bc388c33q | Aniba_psbA-trnH.nex
bc388c36j | Aniba_trnS-trnG.nex
bc386j766 | woodmanc_dharmapops_2014.mov
bc386j61k | L1_HSV_movie.avi
wm117p50x | readme.docx
wm117p53r | L1_velocity_fields_images.zip
wm117p52g | L1_velocity_fields_data.zip
wm117p516 | L1_data.dat
wm117r802 | L1_HSV_movie-1.mpg
bc386p052 | woodmanc_stvrainswoods_2013.mp4
wm117q369 | woodmanc_stvrainswoods_thumb.png
86 | woodmanc_tableofelementsinstalled_2012.mov
57420017 | johnson1891.pdf
57420131 | kerl_s1869.pdf
57420174 | kirkham1857.pdf
57420352 | knox1809.pdf
57420416 | knox1809.pdf
57420441 | knox1809.pdf
57420484 | lewis1899.pdf
57420505 | lewis1900.pdf
57420662 | macleod1891.pdf
57420840 | picket1818.pdf
57420904 | powell1882.pdf
57420947 | quakenbos1851.pdf
57421005 | quakenbos1864.pdf
57421162 | roux1847.pdf
57421226 | scot1897.pdf
57421340 | smith1830.pdf
57421383 | spalding1906.pdf
57421404 | spalding1896.pdf
57421447 | sweet1886.pdf
57421561 | thompson1858.pdf
57421625 | tower1855.pdf
57421782 | wells1846.pdf
57421803 | welsh1896.pdf
57421846 | welsh1896.pdf
57421960 | woodbridge1899.pdf
57422061 | zander1869.pdf
57422125 | Experiment_3__Hetergeneous_Networks_in_Decline.csv

**Comment by hortongn** [comment]
That's interesting.  Looks like not having a depositor breaks them in the GUI as well.  If I try to view those file sets in the browser I get a "something went wrong" message.

We need to figure out if these are orphan file sets that just need to be deleted or if we need to fix them.  So maybe the next step is to see if they are attached to a work.  Do a `file.member_of` on each file set.

**Comment by scherztc** [comment]
Next step is to compare with migration manifest to determine proper depositor on File Set.

If we can't then use work depositor and work deposit date.

Loop through and set depositor and date_uploaded

**Comment by scherztc** [comment]
[Missing Depositor Table.xlsx](https://github.com/uclibs/scholar_uc/files/2085676/Missing.Depositor.Table.xlsx)

**Comment by scherztc** [comment]
@jamesvanmil @hortongn :  I set the depositors on all 41 of these FileSets.  Let's watch the analytics job and see if everything passes on Monday.

**Comment by hortongn** [comment]
Closing this since it looks like the changes resolved the stats rake task problems.
