### ISSUE TITLE
All descriptive metadata should be included in keyword search

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1925]
### Descriptive summary

The description field is not indexed in the keyword search.  I have verified this for the Media and Generic works work types - it may or may not be the case with all work types.  (Field may be called abstract on some work types.)

It appears that the abstract/description field is being indexed in the keyword search for Collections.

### Expected behavior
All descriptive fields on works and collections show pages should be indexed in the keyword search.

### Actual behavior
Some fields are not indexed.

### Related work

Link to related issues or prior related work here.
https://github.com/uclibs/scholar_uc/issues/155

**Comment by newmanld** [comment]
We should check that description is not the only omitted field, and create a test and/or write this up as a local override.

**Comment by hortongn** [comment]
Note: this may be because we are using `alt_description` instead of `description`.  It's possible that `alt_description` is not being indexed.

**Comment by hortongn** [comment]
After a fix is made in the code, we may need to do a full Solr reindex on production to make the `alt_description` field searchable on existing content.
