### ISSUE TITLE
Authentication: get UC Shibboleth to return needed values to test app

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#2]

**Comment by hortongn** [comment]
Values being returned so far from UC's test Shibboleth system:

Name = Glendon Horton
provider = shibboleth
uid = hortongn@uc.edu
name = Glendon Horton
eppn = hortongn@uc.edu
givenName = Glendon
sn = Horton

**Comment by hortongn** [comment]
I'm now retrieving the following attributes via Shibboleth.  Some other attributes are still missing/blank.  I need to investigate why.

cn = hortongn
displayName = Glendon Horton 
eppn = hortongn@uc.edu
givenName = Glendon
ou = UCL Digital Collections & Repositories
persistent-id = https://devlogin.uc.edu/idp/shibboleth!scholar-dev.uc.edu!z0I5+qc4ARxhuy46UYylpWa46Gg=
sn = Horton
street = 465 LANGSAM Mail Loc-0033
title = Software Applications Developer
uceduAffiliation = Staff
uceduPrimaryAffiliation = Staff
uceduUCID = M06942672

**Comment by newmanld** [comment]
It’s a start!  At some point we’ll want to query a student, and a staff and faculty member not in UCL, to compare.

**Comment by hortongn** [comment]
Confirmed that we are receiving all the attributes we need to implement central authentication.

cn = burkepk
displayName = Patrick Burke
eppn = burkepk@uc.edu
givenName = Patrick
ou = UCIT Middleware & Software Development
persistent-id = https://devlogin.uc.edu/idp/shibboleth!scholar-dev.uc.edu!Gpc0pTLVz6mXeUchfH1DSVP8E6c=
sn = Burke
street = G005H MSB Mail Loc-0574
title = Software Applications Developer
uceduAffiliation = Staff
uceduPrimaryAffiliation = Staff
uceduUCID = M06236954
mail = burkepk@ucmail.uc.edu
affiliation = 
remoteuser = 
telephoneNumber = 
uceduAcademicProgram = 
uceduFERPACode = 
uceduPrimaryCollege = 
uceduSISPersonID = 98936489
