### ISSUE TITLE
Develop way to generate sitemap.xml and RSS feeds that include site content

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#204]

**Comment by lawhorkl** [comment]
https://github.com/kjvarga/sitemap_generator might prove useful in generating dynamic site maps. It comes with a few rake tasks that could be run nightly that would allow it to expand as much as needed as the collections of works increases

**Comment by lawhorkl** [comment]
Going to work on trying to integrate the sitemap generator into our gem to add all works to the sitemap file
