### ISSUE TITLE
Redesign work input form

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#211]
Preliminarily, @jamesvanmil will review generic works, based on feedback from the metadata working group and the early adopters, and propose a design prototype.

**Comment by jamesvanmil** [comment]
Having a javascript issue here; perhaps a Turbolinks issue?

http://stackoverflow.com/questions/17600093/rails-javascript-not-loading-after-clicking-through-link-to-helper

**Comment by jamesvanmil** [comment]
I pushed up a fix to the javascript issue - @hortongn, would you pull a fresh copy of my branch on curate_fork and try the generic work submission again? The additional details and license terms should be toggle-able.

**Comment by jamesvanmil** [comment]
Planning to include the following use cases in this work:

[Submission 10 - Determining Creative Commons license](https://github.com/uclibs/scholar_use_cases/blob/master/terms-licenses-rights/TOU-rights_use_cases.md#submission-10---determining-creative-commons-license)

[Submission 34 - Input Form](https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-34---input-form--early-adopter)

**Comment by hortongn** [comment]
@jamesvanmil Yes, both of those toggles work for me now (Chrome on Mac).

**Comment by jamesvanmil** [comment]
To do:

* Implement Article
* Implement Dataset
* Implement Document
* Implement Image
* Refactor file submission hints (including format advise as needed)
* Change hint spacing in xs size

**Comment by jamesvanmil** [comment]
Closed with https://github.com/uclibs/curate_fork/pull/33

**Comment by newmanld** [comment]
For Use Case Submisson 10 - see issue 264.

This (now closed) issue should address Submission 34:  https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-34---input-form--early-adopter
