### ISSUE TITLE
Document when UC Error page displays on Scholar@UC in production

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#217]
Sometimes the UC Error page displays instead of an error page from our app.

We know that this happens when our app is down, but it may also happen
    with specific errors
    with communication delays

Research whether this is the case -- see if there are some known triggers used by UCit environment, and then determine whether any changes are advisable.

**Comment by hortongn** [comment]
This was resolved by turning off error pages on BIg IP
