### ISSUE TITLE
Person::Title is in the same index as Work::Title

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#225]
Our work titles and people titles are all being put into the desc_metadata__title_tesim index in Solr. We should rename the latter to job_title.

This'll be important if we ever implement an advanced search.

**Comment by newmanld** [comment]
Might however be useful if we offer a title sort in the drop down menu on the catalog - and for Profiles title sort would of course be name?

**Comment by scherztc** [comment]
@jamesvanmil Is this still something that we need to solve or did this get solved with the Scholar 3 upgrade?
