### ISSUE TITLE
Authentication: merge existing user accounts with UC 6+2's

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#228]

**Comment by hortongn** [comment]
I've looked at all 60 users on production Scholar and none of them currently have an email address following the six+2@uc.edu format.  So we will need to change **every** user's email address.

Several existing users do not have any content.  So all we will need to do for those users is change their email address.

**Comment by newmanld** [comment]
Let’s work with UCit to verify that UC identity management is consistent about returning 6+2@uc.edu<mailto:6+2@uc.edu>.

**Comment by hortongn** [comment]
I've sent a message to one of the identity management folks to verify the email address format.

**Comment by jamesvanmil** [comment]
Prior to beginning work to migrate, I think it'd be worthwhile to create a manifest of all people/works/files in the system, just incase it doesn't go 100% smoothly.

This could be done a small ruby script that we run on the server to loop through everything and spit out a report.

**Comment by hortongn** [comment]
I asked the identity management people if Shibboleth used the 6+2@uc.edu format for all users and got the reply below.  Based on their suggestions and discussing this with Linda and Thomas, I'll make some tweaks to use the M number instead of username@uc.edu for the UID and use the actual mail field in Shibboleth to get this mail address.  This change will be transparent for users except for the fact that everyone's email address will use the @ucmail.uc.edu format.  This means that we will not need to migrate most of the users to a new email address.  It will make our migration easier.

From the identity management people:
First, us at IDM discourage people from using the term 6+2. It ends up confusing people who do not have 8 characters in their name, or is not a combination of 6 letters of their last name. We encourage the use of the term username.

Second, the uid attribute is not actually an email address. It is known as a scoped identifier. So it will always be of the format username@uc.edu. So although it looks like an email address, it is not an email address and should not be used as an email address.

There is another attribute called cn (commonName) that is the username, which I can expose to you if you are interested in receiving that. Uid is good if you plan on having identities from multiple sources, but it can be used as a unique identifier for a user at UC. Having said that, we do allow username renames and we have about 10 a week. So if you are keying off of a value, I recommend the UCID (the attribute that currently starts with the letter M, but I discourage the term M Number). The UCID can also be released to you if you are not already receiving it

**Comment by hortongn** [comment]
We forgot that deploying the firstname/lastname changes would require migrating the names with today's deploy.  So I have completed that task.  All names are showing correctly on production.

**Comment by hortongn** [comment]
After setting provider='shibboleth' and uid='hortongn@uc.edu' on my user account, I was able to log in via shibboleth and linked to my existing account.

Since my account was an "existing" user account, Scholar did not automatically fill in my department, UC affiliation,etc.  So we will need to force an update when we do a migration so that existing users receive all of their Shibboleth attributes.

We will also want to "scramble" the passwords for existing users so they can only log in via Shibboleth.

**Comment by newmanld** [comment]
Thank you Glen!

**Comment by hortongn** [comment]
These are the users with email addresses that will change when we move to Shibboleth logins.  The next step is to determine which of them have works, delegates, etc. that need to be migrated.

* heather.norton@uc.edu
* stephen.matter@uc.edu
* john.wallrodt@uc.edu
* lora.arduser@uc.edu
* christine.hovanitz@uc.edu
* janine.hartman@uc.edu
* andres.perez-simon@uc.edu
* christopher.swoboda@uc.edu
* george.sarofeen@uc.edu
* kumar.vemaganti@uc.edu
* eric.inglert@uc.edu
* stephen.thiel@uc.edu
* eugene.rutz@uc.edu
* nan.niu@uc.edu
* changjoo.kim@uc.edu
* peter.poulos@uc.edu

**Comment by hortongn** [comment]
I've scrambled the passwords for all shibboleth users.  Existing and new users will need to use the UC central login.  I saved a copy of each user's encrypted password in case we have to reverse this process for some reason.

**Comment by hortongn** [comment]
I've added a new post to the Scholar Blog about UC Central Login.  It will take a bit for it to show up.

**Comment by hortongn** [comment]
I've opened a pull request (https://github.com/uclibs/scholar_uc/pull/497) that fixes a bug with UIDs and emails in the person and profile objects.  It also includes a commit to make sure shibboleth remains on for future deploys.

**Comment by hortongn** [comment]
Deleted the unneeded audituser@example.com and thomas.scherz@uc.edu accounts
