### ISSUE TITLE
Change the the default browse type to "Works" instead of "All"

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#232]

**Comment by jamesvanmil** [comment]
It looks like the tabs on the top of the catalog page aren't directly tied to Blacklight. A helper is setting the 'active' class on the tabs based on the URL parameters:

https://github.com/uclibs/curate_fork/blob/1a6a3fe57f44053c22d72fea85ea56a2425c876e/app/helpers/curate/catalog_helper.rb

I'm I'm understanding correctly, this means that we'd have to change index method on the controller to add the parameter, which means the URL for the catalog homepage would be as below, which feels a little too hacky:

https://scholar.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Work

I'll keep looking at this, though I'd appreciate feedback on this.

**Comment by jamesvanmil** [comment]
It's unclear what the goal is here, so we'll take this issue back to the DRTF to assess.

Do we just want to change the "Browse" button, or address broader search behavior?

**Comment by ntallman** [comment]
As the person who brought this up in the DRTF, I can clarify. The intent
was that the default catalog view (either seen by clicking the browse
button or being taken to it after logging in) show only include works, not
people or collections. In other words, pre-apply the 'work' limit.

**Comment by newmanld** [comment]
Nathan -- we realized that if default views of the catalog have the 'work' limit pre-applied, that limit is also pre-applied to keyword searches.  This may not always be intuitive.    We decided we needed to show a broader group what we are taking about -- ran out of time at our last d.r. t.f. meeting.

**Comment by jamesvanmil** [comment]
@ntallman, we're also wondering about the goal of defaulting to works. There may be cleaner ways to work towards that goal, such as hiding profiles for folks who haven't submitted content (in progress) or tweaking relevance.

**Comment by jamesvanmil** [comment]
Should we also remove Person from the "Type of Work? facets? It's supported in the bar along the top, and Person isn't a type of work.

**Comment by hortongn** [comment]
:+1: for removing "Person" from the Type of Work facet

**Comment by newmanld** [comment]
I think we need a broader strategy or vision for he Person interface itself -- where, how to present it, before understanding where or if to move this.  Hiding the profiles for those who haven't submitted content was a great start.  Also a place to get Early Adopter feedback -- some may appreciate seeing their Profile highlighted in the way it is today along with Works and Collections?  Or not?
