### ISSUE TITLE
Make changes to About and Help Menus recommended by Content Working Group

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#235]
The following are the Content Working Group's recommendations ratified by Digital Repository T.F. on 1/20/2015.  If necessary, break this into separate issues when this issue is pulled from the Backlog.

Button menus:
   * Change the Help! button to a Contact button (make contact a top-level menu item)

   * Create a new top-level menu item for Help

   * Move FAQ, File Format Advice, and Fair Use from About to this new Help menu.
 
   * Reserve About menu for policies and general project background information (consistent with other UCL apps -- UCLID, Summon)

FAQ page:
   * Sort alphabetically
   * Add linked-list of questions at top of page

About page:
   * Change last paragraph from "Contact us for more information about Scholar@UC" to the following:

Scholar@UC is currently operating in a closed-beta mode. A small group of early adopters are helping us to test the system and plan additional development tasks before a campus wide release. Regular updates about Scholar@UC can be found on [ScholarBlog: the blog for Scholar@UC] (http://libapps.libraries.uc.edu/scholarblog/blog/). For additional information, please [contact] (https://scholar.uc.edu/contact_requests/new) the Scholar@UC team.

**Comment by newmanld** [comment]
After discussion in the 2/2/2015 standup, dev team recommends that the Login button (which changes to the person's name with a drop down menu after login) be moved to the top right corner, within the horizontal line currently occupied by the UC menu.  This allows more room for the additional menu button (Contact), and it should prevent the wrapping of the button menu that currently occurs, on some displays, if the person has a long name.  

When the display shrinks to mobile size, the Login/Person menu would show up at the end of the list of menu options that are behind the three horizontal bars.

When available, we should point our sandbox to the branch referencing this issue, so that this approach can be shown to, and vetted by, the D.R. T.F.

**Comment by newmanld** [comment]
Patrick -- between your two branches, the D.R. T.F. is recommending the branch currently shown in our sandbox as port 3007 (feature/#235_Alt_Layout_1), but want to keep all the 'My Menus' together, and keep the Browse button as a simple one-click button.  So we are moving the entire menu that is behind the user's name (once logged in) to the top right -- not adding a new Browse drop down menu.

**Comment by hortongn** [comment]
Hiding the disabled "Policies" and "Project Info" menu items for now.
