### ISSUE TITLE
Embargo plus delegate: inconsistencies

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#250]
Testing on our sandbox yielded these inconsistencies, worth confirming with further tests:
 
A submitter (let's call them the owner) assigns someone to be their delegate.
  
Scenario 1:  As the delegate, I submit a work on behalf of the owner, and embargo that work.  While the work is embargoed:
 
* Someone who is not logged in does not find the work.  If they happened to know the url for the work, they would see an unauthorized message if they tried to go to it directly.
* The delegate can find the work from a search or browse, can edit the work, and can display an attached file.
* The owner however cannot find the work from a search or browse.  (And this is despite the fact that our app automatically assigned the owner to be an editor as well as the work owner.) 
* If the owner knows the url for the work, they can display the work show page.  But from the work show page they cannot display the attached file.
* From the work show page, the owner can edit the work (and presumably remove the embargo).   Assumption: The owner should be able to do the things they cannot do, because they are the work owner.
 
Scenario 2:  The owner submits a work and embargoes that work.  While the work is embargoed:
 
* Someone who is not logged in does not find the work.  If they happened to know the url for the work, they would see an unauthorized message if they tried to go to it directly.
* The owner can find the work from a search or browse, can edit the work, and can display an attached file.
* The delegate however cannot find the work from a search or browse.  
* If the delegate knows the url for the work, they can display the work show page.  From the work show page they cannot display the attached file.
* From the work show page, the delegate can edit the work (and presumably remove the embargo).  Assumption: The delegate should be able to do the things they cannot do, because as a delegate they should have access to all the owners works, consistent with non-embargoed private works.
 
Variation: As the owner, I returned to the work, edited it, and assigned my delegate to also be an editor of my work.  This did not allow the delegate to find the work, but it did allow them to display the attached file.
 
I have not tested how embargoes affect the rights of editors or members of editor groups (with delegates out of the mix).

Scenario 3:
After creating both of the works above, I created two new users, not connected to the owner or delegate as editors.  The first new user had similarities in the email address, both the delegate and new user had the same characters before the @ sign -- one being xxxxxx@ucmail.uc.edu and the other being xxxxxx@gmail.com.  Logged in as the new user with similar email address, I can see in the search results the embargoed work created by the delegate.  When I try to display the work, I see an 'Unauthorized' message.  

I created a second new user (nobody@nobody.com) without any similarity in email address, and logged in as that user I did not find either of the two embargoed works.  This too requires further testing, and confirmation as to whether the similarities in email address are key or coincidental.

**Comment by newmanld** [comment]
Per Scenario 3 above -- I logged in as the xxxxxx@gmail.com user, and changed my email address to be completely different.  I could no longer see the embargoed work created by the delegate with the formerly similar email address.  I then changed my email address back, and could see the embargoed work.  So -- this may go beyond embargoes, and need to be a separate issue from the other scenarios described here.  Access settings - whether private or embargoed - may not be looking at the full email address?

**Comment by scherztc** [comment]
Scenario #1 is resolved with PR:  https://github.com/uclibs/curate_fork/pull/34
Scenario #2 is resolved with PR:  https://github.com/uclibs/curate_fork/pull/34
Scenario #3 is a separate issue and involves how the rightsMetadata assignments are done through email address and the solr query behind the catalog view is looking to the owner/depositor email address in the properties datastream. The issue has been created.

**Comment by scherztc** [comment]
Glen confirmed that Scenario #2 is NOT resolved.  Scenario #2 involves delegates having edit access to all works (private/public/embargoed) for the  (past/present/future) submitted by an owner.  We might need to strategize on whether this reasonable and how we would accomplish this.

**Comment by scherztc** [comment]
Ideas:  
Past Works:  Worker that assigns delegate edit access to all owners works on delegate assignment.
Present /Future Works:  ???  On submission?

**Comment by newmanld** [comment]
Perhaps we should get the work Lukas is doing on https://github.com/uclibs/scholar_uc/issues/139 completed before returning to this bug.  As I recall, Lukas has now as part of this issue resolving the fact he discovered that once embargo expires, no one can seemingly edit the work.  But in general, delegates are currently meant to have edit access to all of an owner's works and files, whether embargoed, private or open access.

**Comment by scherztc** [comment]
Lukas can review my PR: https://github.com/uclibs/curate_fork/pull/34.  I think it is ready to merge.

I believe it covers the applications of visibility access and rights access in all of the delegate and embargo cases.  

I can help him take a look at #139 .

**Comment by jamesvanmil** [comment]
Next steps are to:

Resolve editor assignment on works created prior to delegate assignment.
Document all collisions of access and visibility rights, via spec feature tests.
