### ISSUE TITLE
Fix dummy namespace in image RDF class

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#254]
See: https://github.com/uclibs/curate_fork/blob/develop/lib/rdf/image.rb

Our image-specific metadata is using a dummy namespace `http://nd.edu/image#`, which could cause problems down the line. We should change this to a meaningful namespace (VRA?) and migrate the data for our image works to the new namespace.

**Comment by jamesvanmil** [comment]
I emailed our metadata folks about getting recommended mappings for these - not certain that they'd all just map over to VRA, or if we should reuse terms that we've applied elsewhere.

**Comment by jamesvanmil** [comment]
As part of the migration to Sufia, let's fix any RDF statements that aren't using standard predicates. E.g.:

https://github.com/uclibs/curate/blob/develop/lib/rdf/image.rb
https://github.com/uclibs/curate/blob/develop/lib/rdf/video.rb

**Comment by scherztc** [comment]
Closed by: https://github.com/uclibs/scholar_uc/pull/1157
