### ISSUE TITLE
Update Distribution License and Terms of Use

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#260]
See https://github.com/uclibs/scholar_uc/tree/license_update

**Comment by newmanld** [comment]
Changes are in response to Early Adopter Feedback.  See Submission 1 and 7:
https://github.com/uclibs/scholar_use_cases/blob/73ef1eef8e228302b17a9da05babd8005f4db93a/terms-licenses-rights/TOU-rights_use_cases.md#submission-1---intellectual-property--early-adopter
and
https://github.com/uclibs/scholar_use_cases/blob/73ef1eef8e228302b17a9da05babd8005f4db93a/terms-licenses-rights/TOU-rights_use_cases.md#submission-7---contingency-planning--early-adopter
