### ISSUE TITLE
Work Input Forms: Create Chooser dialogue for Creative Commons, etc. licenses - Early Adopter - Scholar_Use_Cases Submission 10

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#264]
See also Issue #238

See https://github.com/uclibs/scholar_use_cases/blob/73ef1eef8e228302b17a9da05babd8005f4db93a/terms-licenses-rights/TOU-rights_use_cases.md#submission-10---determining-creative-commons-license--early-adopter

As a: repository user

I want: to fill out a survey/use a tool to determine the Creative Commons or other license that fits my needs

So that: I choose the right type of license appropriate to my content and expectations

Dependency: first review choices with Content Working group appropriate to content type, in particular to datasets.

**Comment by jamesvanmil** [comment]
This solution seems really promising:

Demo: http://ufal.github.io/lindat-license-selector/

Code: https://github.com/ufal/lindat-license-selector

I'm hopefully that we can adapt to meet local needs. If we use this, I'd like to let the project owners know.

**Comment by crowesn** [comment]
<img width="936" alt="screen shot 2016-05-12 at 9 11 52 pm" src="https://cloud.githubusercontent.com/assets/1069588/15251155/0ab5038c-18f6-11e6-9bcc-a0f44f61b092.png">
<img width="934" alt="screen shot 2016-05-12 at 9 13 58 pm" src="https://cloud.githubusercontent.com/assets/1069588/15251158/0d368c8e-18f6-11e6-8862-40ace6d58637.png">

**Comment by newmanld** [comment]
Looks great.  A few notes:  

Article work type.  If I answer Yes - No -- Yes -- I get a list of licenses, and above the list is the phrase "Choose licenses present in your dataset:"  But I choose article work type, so dataset may be confusing here.

If I say Yes, No, No, I get the response "Can't choose a license.  You need additional permission before you can deposit the work!"  But what if I do have such permission?  Shouldn't there be a question - do you have permission, and if yes, further guidance?

With the very first question - "Is your work within the scope of copyright and related rights?" there is some very lengthy help text that appears if you mouse over the right spot.  I didn't detect this until I'd gone through the dialogue at least 10 times, so most may miss this help text.  And the help text is so lengthy that it doesn't all display and it isn't obvious how to see the rest of the text -when I try to mouse or arrow down, it disappears.  (using Google chrome on my Mac)

**Comment by crowesn** [comment]
Thanks for the comments, Linda. 

1. I'll fix the *Choose licenses present in your dataset* to include *work*.
2. There is a tooltip with a little bit of information about getting permission, it's pretty minimal though.
3.  Here is the full text from the javascript, should we cut it down?

>  'the scope of copyright and related rights': "<p>\nCopyright protects original works. Originality is defined as the author’s own\nintellectual creation. Therefore, mere statements of historical facts, results\nof measurements etc. are not protected by copyright, because they exist\nobjectively and therefore cannot be <em>created</em>. The same applies to ideas,\nmathematical formulas, elements of folklore etc. While quantitative data are\nusually not protected by copyright, qualitative data (as their creation\ninvolve some intellectual judgment) or language data are usually\ncopyrightable.\n</p>\n<p>\nApart from copyright in the data itself, a compilation of data (a dataset) may\nalso be protected by copyright as an original work. It is the case when the\nselection and arrangement of the dataset involves some degree of intellectual\ncreation or choice. This is not the case when the guiding principle of the\ncollection is exhaustivity and/or completeness. For example, while <em>My\nfavorite works of William Shakespeare</em> will most likely be an original\ncollection, <em>Complete works of William Shakespeare</em> will not, as it leaves\nno room for personal creativity.\n</p>\n<p>\nThe investment (of money and/or labor) into the making of the dataset is\nirrelevant from the point of view of copyright law; however, a substantial\ninvestment into the creation of a database may attract a specific kind of\nprotection, the sui generis database right. If your data and your dataset are\nnot original, but you made a substantial investment into the making of a\ndatabase, you can still benefit from legal protection (in such a case, answer\nYES to this question).\n</p>\n<p>Answer <strong>Yes</strong> if ...</p>\n<ul>\n  <li>selecting a license for language data (in most cases)</li>\n  <li>selecting a license for original (creative) selection or arrangement of the dataset</li>\n  <li>substantial investment went into the making of the database</li>\n  <li>you are not sure that the answer should be <strong>No</strong></li>\n</ul>\n<p>answer <strong>No</strong> if ...</p>\n<ul>\n  <li>your dataset contains only quantitative data and/or raw facts</li>\n  <li>your dataset is exhaustive and complete (or at least aims to be)</li>\n  <li>only if you are sure!</li>\n</ul>

**Comment by newmanld** [comment]
I think the text about the scope of copyright is too long to work in a hover tip here - it just doesn't all display.  I also see that the advice is specific to datasets - so it would be good if someone is using the dataset input form, but not as good otherwise.

**Comment by newmanld** [comment]
Font is not locked down on license chooser.  Not sure this matters, and I'm fine with ignoring.  I was able to get it to display in French Script.  
![image](https://cloud.githubusercontent.com/assets/3521707/15581321/c6e63a06-2339-11e6-8121-eaa4fb7bd2ec.png)

**Comment by jamesvanmil** [comment]
That looks so authoritative!

**Comment by newmanld** [comment]
I'm adding screenshots to document the look and feel of the license chooser.  The 'license wizard' option does not appear on mobile devices, or a pre-set screen resolution.
![licensechooser1](https://cloud.githubusercontent.com/assets/3521707/15875652/173a275a-2cd7-11e6-9b55-4c1a9acc5a1d.jpg)

**Comment by newmanld** [comment]
First screen of License Wizard:
![licensechooser2](https://cloud.githubusercontent.com/assets/3521707/15875842/0187f4fe-2cd8-11e6-88f5-8360798ee65c.jpg)

**Comment by newmanld** [comment]
If they answer 'Yes' to the question above:
![licensechooser3](https://cloud.githubusercontent.com/assets/3521707/15875902/50af70ac-2cd8-11e6-9f6b-b5eccd1809a1.jpg)

**Comment by newmanld** [comment]
If the submitter answers 'Yes' to the above:
![licensechooser4](https://cloud.githubusercontent.com/assets/3521707/15875949/91fba6a2-2cd8-11e6-92e8-87eb4968b561.jpg)

**Comment by newmanld** [comment]
If the submitter answers 'No' to the question above:
![licensechooser5](https://cloud.githubusercontent.com/assets/3521707/15875995/c2315664-2cd8-11e6-8719-1fb1a19dcb13.jpg)

**Comment by newmanld** [comment]
If the submitter answers 'No' to the question above the following list of two license possibilities will be shown.  If they select one it will pre-populate the drop-down list.
![licensechooser6](https://cloud.githubusercontent.com/assets/3521707/15876066/1eb80e6e-2cd9-11e6-9cda-c1c37caf0d47.jpg)
