### ISSUE TITLE
New Help Page - Creator's Rights - Early Adopter - Scholar_Use_Cases - Submission 2

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#265]
See https://github.com/uclibs/scholar_use_cases/blob/73ef1eef8e228302b17a9da05babd8005f4db93a/terms-licenses-rights/TOU-rights_use_cases.md#submission-2---copyright-guidance--early-adopter

As a: repository user

I want: more guidance on whether my copyrighted materials can be placed in the repository

So that: I can still preserve my own copyrighted materials

Done looks like: Implement new Creator's Rights page from Content Working Group as part of Help Menu and update Work input forms to link to this page as a new window or new tab.

**Comment by newmanld** [comment]
Keep Sherpa /Romeo link.  See also Issue 263.

Change the following paragraph on work input forms to link to this new page on Help menu, and to quote a snippet of that page (get text for snippet from Content Working Group):

> Please note, making something visible to the world (i.e. marking this as Open Access) may be viewed >as publishing which could impact your ability to:
> 
> Patent your work
> Publish your work in a journal

**Comment by newmanld** [comment]
Dependent on completing Issue 235 before adding new page to Help Menu.

**Comment by newmanld** [comment]
Patrick - I sent via email a docx file for the new page that is referred to in this issue.
 
This issue also includes some textual improvements to the input forms to be fully responsive to the use case.
 
*The first task is to add the new page under the Help Menu.   (The new Help Menu created once you close issue 235).   Please coordinate with Nathan Tallman on the content of this page, should you have any questions.   
 
Textual improvements to input forms (all work types):
*Keep Sherpa /Romeo link but make it open in a new window/tab rather than the same window. See also Issue 263, which I’ve now assigned to you as well.

*Create a new paragraph with a snippet from the new Creator’s Rights page or brief summary of that page, and include a link (that also opens in a new window/tab) to this new page.  Get the text for this from Nathan Tallman.   Use this new paragraph to replace the following paragraph on all input forms:

>Please note, making something visible to the world (i.e. marking this as Open Access) may be viewed >as publishing which could impact your ability to:

>Patent your work
>Publish your work in a journal
 
Please coordinate with James Van Mil if you have any questions about the code supporting the Input Forms.
 
Please let me know when you have a branch to look at – we’ll deploy to Larry and I’ll take the lead in reviewing it.

**Comment by ntallman** [comment]
####Text for Input Form
<b>Please note</b> that marking your work as Open Access could be considered publication. This may affect existing or potential publication agreements or patents. For more information, please consult our [Creator's Rights](https://scholar.uc.edu/creatorRights.html) page.

**Comment by ntallman** [comment]
The Digital Content Working Group has proposed new text to the DRTF. Because the Digital Content WG disagreed with the DRTF about maintaining the explicit link to SHERPA/RoMEO, please hold off on this issue until the DRTF has chosen it's preference.

**Comment by newmanld** [comment]
Patrick -- there's some back and forth in the two comments above which you can ignore so we can get the new page deployed and the text improved (with of course further improvements likely still to come).  Please continue to work on this issue and implement the following text on all input forms, replacing the current paragraph with the paragraph below.  (Replacing the paragraph that begins "Please note, making something visible to the world (i.e. marking this as Open Access) may be viewed >as publishing which could impact your ability to <...>")  Make all links in this paragraph open in a new/window or tab, so people don't lose their work on the input form.  

"Creator Rights" in the second sentence below should link to the new page.  SHERPA/RoMEO in the 3rd sentence should link to the same place as per current.

>Contributing to Scholar@UC may raise questions about your intellectual property rights. Please >consult the Creator Rights page for more information. For information on journal publisher copyright >policies, consult the SHERPA/RoMEO resource, a database of standard journal publisher policies.

**Comment by pburke77** [comment]
Linda,
I cannot find the document file that you mentioned in this issue.  If you are able, can you please resend it to me.

**Comment by newmanld** [comment]
The DR TF reversed it's earlier decision.  We will remove the SHERPA/RoMEO link and just have a link (in the same place on the input forms) to the Creator Rights page.  Use this text, and the second sentence should open up the Creator Rights page in a new tab or window:
>Contributing to Scholar@UC may raise questions about your intellectual property rights. Please consult the Creator Rights page for more information.
