### ISSUE TITLE
Consistency in supporting attaching multiple files - Submission_Use_cases - Submission 27; Submission 41

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#273]
Submission 26 is addressing the metadata. 

Resolve these inconsistencies

When creating a work
  File title derives from filename -- you can edit the file later to change that
   You can upload multiple files from the cloud but not from your PC.

When attaching a file to an existing work
   File title does not derive from filename - you have a blank field for it
   You cannot upload multiple files from the cloud or your PC.  
 
When editing a file, a user can replace with one from their local PC but not from the Cloud.

Users should be able to always upload multiple files
The file title should default to filename but the user should be to override it on the same screen.

**Comment by jamesvanmil** [comment]
I've taken a look at the multi-file issue. The background code is in place for multi-file upload, but it was simply not turned on in the form. Adding the parameter `input_html: { multiple: true }` to the file upload form allows users to select multiple files from the browser's file selection dialog.

I've successfully tested in an earlier version of Curate, but it looks like our implementation of virus scanning was build around one file - we'll need to refactor it a bit to assume one or more files.

**Comment by jamesvanmil** [comment]
This might be a good solution for handling multi-files and improving the UI at the same time:

https://blueimp.github.io/jQuery-File-Upload/basic.html

**Comment by newmanld** [comment]
See also bug - Issue #325

**Comment by newmanld** [comment]
Re-Assigning this to Patrick Burke but Patrick and @jamesvanmil should work together to review the work done so far by James on jquery tools.

**Comment by jamesvanmil** [comment]
Still working to assess feasibility of implementing w/o major refactoring.

**Comment by newmanld** [comment]
We have resolved these inconsistencies:

*When creating a new work, a content submitter can now upload multiple files from their workstation, as well as from the cloud. (Although the method of doing this from the workstation or from the cloud may not be intuitive.)

We have these remaining inconsistencies.  These will be written up in new issues.

*A content submitter cannot assign a file title when first creating a new work (unlike when attaching a file to an existing work).  They must edit the work later to do so.  

*When attaching a file to an existing work, and attaching from either the cloud or from the workstation, if a content editor leaves the Title field blank, Scholar@UC does not assign file name as file title (unlike when creating a new work).

*A content editor cannot upload multiple files at once (from either workstation or cloud) when attaching a file to an existing work.

*When editing a file, a content editor can replace with one from their local PC but not from the Cloud.
