### ISSUE TITLE
Switching visibility on attached file from Open Access / Embargo and vise-versa.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#281]
When editing a file:

An editor can switch from ( Open Access / Embargo ) to Private and vise-versa, but an editor can not switch between Open Access and Embargo.

**Comment by 13miciunasl** [comment]
Switching a work from Open Access to Embargo does not automatically embargo the attached files, but you can manually switch them. Neither a work nor a file can be switched directly from Embargo to Open Access. You can however switch a work from Embargo to Private, and then to Open Access. All other visibility switching works as expected.

**Comment by newmanld** [comment]
Thanks Lukas for this clarification.

**Comment by scherztc** [comment]
With Scholar 3, I am able to switch from Open Access to Embargo and vice-versa.
