### ISSUE TITLE
When a user changes their email address they loose access to delegated/owned works

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#285]
When I I logged in as the xxxxxx@gmail.com user, and changed my email address to be completely different:

I could no longer see the embargoed work created by the delegate with the formerly similar email address. I then changed my email address back, and could see the delegated work. 

Although both the owner and delegate have edit access to submitted work, the delegate is the only editor of a delegate submitted work.  If we also make the owner and editor this may solve the access problem.

We should also explore what gets changed in the datastreams when a user changes their email address.

**Comment by scherztc** [comment]
Will only apply to local users once Shibboleth is implemented.

**Comment by hortongn** [comment]
WIll be resolved by shibboleth implementation (removed user's ability to change email)
