### ISSUE TITLE
Change Routing to generate shorter,stable URL for works - Scholar_Use_Cases - Submission 10

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#286]
Consider best practices for SEO and usability

**Comment by scherztc** [comment]
/show/pid

Display on Show page.

**Comment by scherztc** [comment]
Possibly /work/pid

**Comment by newmanld** [comment]
It's desirable to get information about Sufia's direction here as it supports multiple work types.

**Comment by jamesvanmil** [comment]
For reference, the routes for Works and Files in Curate are set here: https://github.com/projecthydra-labs/curate/blob/68d7db006887eb52e3d46f38ac8814176ac8d620/lib/curate/rails/routes.rb#L24-L43

**Comment by jamesvanmil** [comment]
Dupd by #369
