### ISSUE TITLE
Test and document restoring a deleted work and its files 

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#297]
Soft delete will preserve deleted works and files in Fedora.  Develop and test the procedure for restoring deleted content so it appears again in Scholar

**Comment by jamesvanmil** [comment]
Started work on this, and we are (expectedly) unable to access the object via the Fedora admin console due to xacml policies. Thomas is following up to modify the policy appropriately.

**Comment by scherztc** [comment]
https://wiki.duraspace.org/display/FEDORA34/Fedora+XACML+Policy+Writing+Guide

**Comment by scherztc** [comment]
See: https://git.uc.edu/UCLIBS/config_vault/commit/dd5b79da51f6fe9bbf947b68cf6a5841c325e9e9

**Comment by scherztc** [comment]
Documentation:  https://github.com/uclibs/scholar_uc/wiki/Access-the-Fedora-Manager-Tools
