### ISSUE TITLE
Run rake solr:reindex for reindexing of subject facet.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#302]
Larry
QA
Production

We would like to do this as a team.

**Comment by hortongn** [comment]
@jamesvanmil @scherztc I ran rake solr:reindex on Larry.  However, the only subject facet listed was still just "music."  I edited and saved an existing work that had the subject "Publishing" and that then showed up in the list of subject facets.  So the rake task is not finding all of the existing subjects.  It's only after an existing work is saved again that the subject is then included in the facet list.

**Comment by jamesvanmil** [comment]
Have we successfully used `rake solr:reindex` elsewhere?

I'm poking around and I've found `ActiveFedora::Base.reindex_everything`. (Referenced in https://github.com/projecthydra/hydra-head/wiki/Migrating-to-hydra-head-6.0)

**Comment by hortongn** [comment]
I just happened to see a post on hydra-tech today where Mike Giarlo said that the solr:reindex rake task  "works in the background so you'll want Resque jobs running before running that task."  I don't think we had Resque running on Larry at the time I tried the rake task.  So I'll give it a shot again.

**Comment by hortongn** [comment]
I forgot that @scherztc just wiped Larry.  So I can't try to get the existing subjects to show up.  However, I ran the reindex task anyway and confirmed that a new resque job with a queue named "RESOLARIZE" was created.  So that confirms that the solr:reindex rake task does require background workers.

I will deploy develop to QA so I can test the reindex task there.

**Comment by hortongn** [comment]
@13miciunasl @scherztc I guess the solr:reindex task may be a good example of a rake task that kicks off background workers.  The code below has the examples:

https://github.com/projecthydra/sufia/blob/ecb49ae511e682833a25ceec320f3157c9ae5447/sufia-models/lib/tasks/sufia-models_tasks.rake#L3-L8

https://github.com/projecthydra/sufia/blob/7eaeef5e197b14b401e01fc52d55b1125a787f94/sufia-models/app/jobs/resolrize_job.rb

https://github.com/projecthydra/active_fedora/blob/a95a398f35a5f5579f670a74ed8d8ed07b8d4b82/lib/active_fedora/indexing.rb#L72-L79

**Comment by hortongn** [comment]
Running solr:reindex on Scholar-QA did find all of the existing subjects and they showed up in the subject facet.

We will need to run this on production the next time we deploy.

**Comment by jamesvanmil** [comment]
Would be be possible to make this a routine and scripted part of deploy? The need will probably arise in the future, and if it's not too expensive we could just do it every time.

**Comment by hortongn** [comment]
That's probably a good idea.  I don't think anything will prevent us from reindexing at the end of each deploy, but I'll think on it some more.  I guess we also have the option of reindexing nightly via a cron job, but I'm not sure if that would ever be needed.
