### ISSUE TITLE
Investigate automated code security scanning

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#311]
Start with looking at these resources?: https://hakiri.io/blog/ruby-security-tools-and-resources

**Comment by jamesvanmil** [comment]
https://codeclimate.com/ (some sample configs from UCSD: https://github.com/ucsdlib/DeveloperGuides/blob/master/templates/.codeclimate.yml)

**Comment by hortongn** [comment]
Ask Hydra community as well as local Ruby shops what tools they use.

**Comment by hortongn** [comment]
Found an excellent post from last summer on hydra-tech.

https://groups.google.com/forum/#!msg/hydra-tech/zRU7jEGGXz0/ap_YN9BXcvEJ

Matthew Critchlow asked the same question we have and got some really good responses.  I'll extract the details and will post here.

**Comment by hortongn** [comment]
Tools
_____

### Bundler audit
* https://github.com/rubysec/bundler-audit
* Stanford uses
* Can whitelist issues
* Uses the Ruby Advisory Database
* Fast
* `gem install bundler-audit`
* `bundle-audit update`
* `bundle-audit check`

### Brakeman
* https://github.com/presidentbeef/brakeman
    * Alberta: run nightly via CI
* Reporting available through gemnasium
* Specific checks can be skipped
* Specific files in our code can be skipped
* Confidence level assigned to each warning
* Config options can be stored in .yml
* Fast
* `gem install brakeman`

### Ruby Advisory Database
* https://github.com/rubysec/ruby-advisory-db
* "compiles all advisories that are relevant to Ruby libraries"

### Dawnscanner
* https://github.com/thesp0nge/dawnscanner
* Alberta: this doesn't check for anything more than brakeman

### Rack Attack
* https://github.com/kickstarter/rack-attack
* active blocker with whitelists and blacklists

### Tarantula
* https://github.com/relevance/tarantula
* pen testing
* crawls your app fuzzing data to see what breaks
* similar to hailstorm
* use a rake test to set up
* can whitelist rsponses
* ex: sql injection, xss

### OWASP OWTF
* https://github.com/owtf/owtf
* Alberta uses
* pen testing
* Runs on Linux - server
* web interface

### Retire.js
* https://github.com/RetireJS/retire.js
* Finds javascript libraries with known vulnerabilities
* command line and browser plugin

Services
--------

### Code Climate
* https://codeclimate.com
* automated code review
* analyzes code on github
* Github integration - can check like travis does
* Uses brakeman + others
* local version is free
* hosted costs money

### Gemnasium
* https://gemnasium.com
* Used at Penn State, Stanford, Alberta
* monitors a project's dependencies
* notifies of gem updates or security issues
* auto update
* Github integration
* Free for 2 private projects, 1 user
* Cost?
* Enterprise version available

### Hakiri
* https://hakiri.io
* Pen testing and known vulnerabilities
* monitors gem versions
* github integration
* Free and $

### Appcanary
* https://appcanary.com
* Runs on our servers
* Very little details on website
* No free version

**Comment by newmanld** [comment]
See also, per @lisa3711, snyk:  https://techcrunch.com/2016/06/23/snyk/
