### ISSUE TITLE
Resolve LDAP injections reported by Hailstorm

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#316]
Insert a model validation to return a consistent error message.

Create paramater validations for:

	page parameter
	per_page parameter
        email in contact form

If this doesn't resolve it then look to SOLR to limit acceptable values.

**Comment by hortongn** [comment]
We resolved this during our swarm with commit https://github.com/uclibs/curate_fork/commit/27f5fd6ffa3ff7bb494419dc0295ee46ae0fb5d9

**Comment by scherztc** [comment]
Deployed.
