### ISSUE TITLE
Provide link to Creator Rights page on work input forms

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#323]
On the work input forms, the DR TF has decided to remove the SHERPA/RoMEO link and have a link (in the same place on the input forms) to the Creator Rights page. Use this text, and the second sentence should open up the Creator Rights page in a new tab or window.  Scholar@UC does not need to be a link.

>Contributing to Scholar@UC may raise questions about your intellectual property rights. Please consult the Creator Rights page for more information.

**Comment by scherztc** [comment]
Closed with commit:  https://github.com/uclibs/scholar_uc/commit/ecfb9aecd1778c4b86382ca6aa9e623799324dd3
