### ISSUE TITLE
Confusion between file title and file name when attaching a file

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#325]
When attaching multiple files to a generic work, after submitting a work, and when first attaching an additional file, I entered a file title.  When I went to download this file, the file title, without suffix, was recognized by my browser (Chrome on a Mac) as the filename.  This was undesirable because without the suffix the downloaded file was less usable.  I found that if I left the file title field blank, when attaching a file, and later edited this file when editing the attached file, this confusion did not occur -- the filename was still the downloaded filename, but the file title appeared under the thumbnail on the work show page and elsewhere.  So, although this should be tested and replicated again, it appears that there is a bug with the option to allow a user to specify file title when first attaching an additional work, and file title and filename become confused.

To put this in story form:
As a content submitter, when attaching an additional file to an existing work, I want to be able to specify a file title that is different from the filename.  The file title should not become the filename when downloading the file.

See also issue #273

**Comment by jamesvanmil** [comment]
@newmanld I'm unable to replicate this issue. On my local machine I've entered a new work with three files.

1. File uploaded during Work submission
2. File attached after Work submission, Title field left blank
3. File attached after Work submission, Title field filled

Everything is working as expected:

![screen shot 2015-06-02 at 8 31 11 am](https://cloud.githubusercontent.com/assets/2651187/7935840/1bab4426-0902-11e5-90e8-d03f24078f0b.png)

**Comment by newmanld** [comment]
That’s odd because it’s been very consistent for me.  Normally I’m using Chrome on a windows machine.  Could it be browser specific?

Note that it is only case 3 that applies to the bug I’ve experienced multiple times, and in this case I’m seeing the problem when I download, in that the filename that is saved on my local machine is the title (without suffix) – such as ‘File 3’ and not the filename.

-- Linda

**Comment by jamesvanmil** [comment]
Confirmed bug! (Thanks!) Also confirmed that it's delivering the file with the pid, not the original filename. My goal will be to preserve the original filename, not the renamed file or the pid.ext.
