### ISSUE TITLE
Adding an external link sometimes generates an internal server error

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#328]
We cannot reliably reproduce the error, but the log from when it did show up is below.

I, [2015-05-05T13:34:42.660516 #21334]  INFO -- : Started POST "/concern/container/pv63g0766/linked_resources" for 10.40.2.14 at 2015-05-05 13:34:42 -0400
I, [2015-05-05T13:34:42.662406 #21334]  INFO -- : Processing by CurationConcern::LinkedResourcesController#create as HTML
I, [2015-05-05T13:34:42.662568 #21334]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"nCLi53gceFb5p8HIi3EcI5/BYKq0hvHtxbvpLHqmQ4k=", "linked_resource"=>{"url"=>"http://yahoo.com", "title"=>"Yahoo"}, "commit"=>"Add External Link to Generic Work", "parent_id"=>"pv63g0766"}
E, [2015-05-05T13:34:43.579745 #21334] ERROR -- : 
E, [2015-05-05T13:34:43.580571 #21334] ERROR -- : Curate caught a registered error: Rubydora::FedoraInvalidRequest
	See logger for details
	Backtrace:
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/rest_api_client.rb:26:in `block (2 levels) in <module:RestApiClient>'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/rescuable.rb:114:in `instance_exec'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/rescuable.rb:80:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/rest_api_client.rb:345:in `rescue in add_datastream'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/rest_api_client.rb:335:in `add_datastream'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/repository.rb:19:in `add_datastream'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/datastream.rb:293:in `block in create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:373:in `_run__99350038510667071__create__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/datastream.rb:292:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/datastream.rb:47:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/datastream.rb:306:in `block in save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:373:in `_run__99350038510667071__save__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/datastream.rb:304:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/datastream.rb:42:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/digital_object.rb:285:in `block in save_datastreams'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/digital_object.rb:284:in `each'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/digital_object.rb:284:in `save_datastreams'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rubydora-1.7.5/lib/rubydora/digital_object.rb:207:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/persistence.rb:154:in `persist'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/callbacks.rb:238:in `block in persist'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:393:in `_run__3410523711504422444__save__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/callbacks.rb:238:in `persist'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/persistence.rb:141:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/callbacks.rb:242:in `block in create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:373:in `_run__3410523711504422444__create__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/callbacks.rb:242:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/persistence.rb:11:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/active-fedora-6.7.8/lib/active_fedora/validations.rb:50:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate_fork-d3e319b75b83/app/services/curation_concern/base_actor.rb:56:in `block in save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate_fork-d3e319b75b83/app/repository_models/curation_concern/remotely_identified_by_doi.rb:47:in `apply_doi_assignment_strategy'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate_fork-d3e319b75b83/app/services/curation_concern/base_actor.rb:55:in `save'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate_fork-d3e319b75b83/app/services/curation_concern/base_actor.rb:24:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate_fork-d3e319b75b83/app/controllers/curation_concern/linked_resources_controller.rb:17:in `create'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/abstract_controller/base.rb:189:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:523:in `_run__1197603702225153473__process_action__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/notifications.rb:159:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/notifications.rb:159:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/abstract_controller/base.rb:136:in `process'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/abstract_controller/rendering.rb:44:in `process'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal.rb:195:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_controller/metal.rb:231:in `block in action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/routing/route_set.rb:82:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/routing/route_set.rb:50:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/journey/router.rb:71:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/journey/router.rb:59:in `each'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/journey/router.rb:59:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/routing/route_set.rb:676:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/flash.rb:241:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/cookies.rb:486:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.11/lib/active_record/query_cache.rb:36:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:373:in `_run__3347659747869538593__call__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.11/lib/rails/rack/logger.rb:38:in `call_app'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.11/lib/rails/rack/logger.rb:20:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/tagged_logging.rb:26:in `tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/tagged_logging.rb:68:in `tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.11/lib/rails/rack/logger.rb:20:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.11/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.11/lib/rails/engine.rb:511:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.11/lib/rails/application.rb:97:in `call'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

	Rendering error page: 500
I, [2015-05-05T13:34

**Comment by newmanld** [comment]
I've had this pattern hold up three times on QA.  It's not https vs http like I first thought.  But what seems to be the pattern may not really be the pattern -- may be more inconsistent still. 
1) cannot add external link when first adding work (which also has an image attached) - get an internal 500 error
2) can add external link after creating the work (sometimes after more than one try).
3) Once I accomplish step 2, I now can add an additional work with the same link, included in the form when first adding work - but not another, hitherto unused (at least in same browser session) link.

**Comment by newmanld** [comment]
Also, it appears that every time I received the internal 500 (when first adding a work) error the work was created, but without the link.

**Comment by newmanld** [comment]
I tried to recreate the problems above on QA and could not.  Several iterations of adding links worked - when first adding a work and when adding after a work was created.  Given that we never saw the error on our sandbox I'm wondering what was temporarily askew.  May attempt the same on production.

**Comment by newmanld** [comment]
Again I tried to recreate the problems above on QA and could not - using several browsers and both when first adding a work and when adding a link after a work was created.
