### ISSUE TITLE
A user should be able to remove a featured work from their profile...

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#330]
...when that work was submitted by another user.

**Comment by hortongn** [comment]
I was able to remove the link on Ted's profile while logged in as repository manager.  So this does appear to be a permissions issue.  This bug does NOT occur with regular collections.

**Comment by scherztc** [comment]
Hold for feedback from Early Adopters on whether highlighting other people's works on your individual profile is desirable.

**Comment by jamesvanmil** [comment]
@jamesvanmil - verify bug

**Comment by jamesvanmil** [comment]
Bug verified - @newmanld should we wait for resolution on the question of whether you can add other users' works to your collections before proceeding with fixing this? If we decide to narrow the meaning of a collection, we would presumably do the same for featured works on a profile (which are a type of collection), and wouldn't need to fix this.

![image](https://cloud.githubusercontent.com/assets/2651187/10919388/8d2b1612-8238-11e5-8798-1ce49f03b062.png)

**Comment by newmanld** [comment]
1) I think the optimal solution is to prevent users from adding other people's works to their profile pages, unless they are an editor for the work.  Profile pages will be the basis for content that we share with the Research Directory - doesn't make sense to me that other people's works would show up here?   However, this may likely require major modifications to the collections gem (which is deprecated and not used in the new hydra stack as I understand it), and if so, then this change is out of scope for 2.0.  
2) If out of scope for 2.0, then we can look at whether we can solve the bug itself while leaving capabilities the same. 
3) if that's not easy, remove Scholar 2.0 label.

**Comment by 13miciunasl** [comment]
As a reminder to myself: This is only a problem with Selected Works on the profile page. NOT an issue with regular collections or profile sections.

**Comment by 13miciunasl** [comment]
Actually, you can navigate to the collections/pid page of Selected Works and remove other peoples work from there. The issue seems to be in displaying the Remove button on the profile page.

**Comment by 13miciunasl** [comment]
@newmanld Not allowing a user to add another person's work to their profile page is doable, and so is allowing them to delete other people's work from their profile page. It seems like you prefer the first solution, but I just wanted to double check before moving on

**Comment by 13miciunasl** [comment]
Upon further investigation, there is more potential for problems in allowing someone to add another person's work to their profile and being able to later remove it. So I will go forward with the first solution of barring people from adding others' works to their profile.
