### ISSUE TITLE
Read-only access for group members

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#334]
Submission 7 - Read-only access for group members

As a: group manager

I want: to be able to set permissions for group members

So that: I can choose between read-only and editing access for group members

Done looks like: when group members login, they can only edit or read materials based on the levels I have specified

**Comment by newmanld** [comment]
Functionality should also address a single individual.  See also submission_use-cases.md Submission #43

**Comment by jamesvanmil** [comment]
Overlaps with https://github.com/uclibs/scholar_uc/issues/335 - Use case group is merging these issues, too.
