### ISSUE TITLE
Private with some exceptions

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#335]
Submission 43 - Private with some exceptions

As a: repository user

I want: to make my submission private but delegate permission to view my work to certain individuals

So that: I can share my work with a small audience until the item is ready for greater access

Done look like: The submission interface includes a mechanism for selecting who can view my work by my entering an email address.

**Comment by jamesvanmil** [comment]
I'm tackling this by abstracting the CurationConcerns::WithEditors code to handle both edit access and read access. This will also involve some changes to the Hydramata::Groups code, which stores knowledge about which groups it has access to.
