### ISSUE TITLE
Indexing in Google Scholar

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#336]
Submission 5 - Indexing in Google Scholar

As a: repository submitter

I want: my content to be discoverable through Google Scholar

So that: my work reaches more audiences

Done looks like: the repository I use is capable of indexing content consistent with Google Scholar recommendations, so that shortly after submission it is findable in Google Scholar

**Comment by jamesvanmil** [comment]
See #342

**Comment by hortongn** [comment]
See issue #204

**Comment by jamesvanmil** [comment]
This issue is too broad to be directly actionable. We're tackling Google Scholar indexing piecemeal, though other issues, such as: https://github.com/uclibs/scholar_uc/issues/342

**Comment by newmanld** [comment]
Sometimes we have broad issues to remind us of broader goals.  Should we create another mechanism for this kind of tracking?  (without of course, turning it into a waterfall style planning mechanism, antithetical to agile.)

**Comment by jamesvanmil** [comment]
Good point.

I think that milestones are generally better appropriate for that, but I don't think we can have more than one milestone per issue - I think this might be the type of organization that's going to be unavailable to us without a more robust system.

**Comment by jamesvanmil** [comment]
So for now, how about a tag?

**Comment by newmanld** [comment]
+1 to tag
