### ISSUE TITLE
Expose work metadata in meta tags

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#342]
Goals (please add whatever I'm missing):

* Highwire Press meta tags and others, as modeled/recommended here: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
* DOI, as recommended by Altmetrics folks:

>On the DOI issue: your DOIs need to be stored in a machine-readable metadata format that our bookmarklet can read. For example, in Dublin Core meta tags, like so:

>`<meta name="dc.identifier" CONTENT="doi:10.7945/C2Z596">`

**Comment by jamesvanmil** [comment]
See #336

**Comment by jamesvanmil** [comment]
Ran into this resource, just now: http://cookieshq.co.uk/posts/easy-seo-metatags-with-rails-4/

**Comment by hortongn** [comment]
Merged
