### ISSUE TITLE
Stress test QA under heavy load

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#343]
Whatever weakness(es) QA has, production will be the same.

**Comment by jamesvanmil** [comment]
I did some light research into this - there are some rails tools, but otherwise Apache JMeter seems to be a very common free/open solution for this: http://jmeter.apache.org/

Perhaps you could ask Darren about whether UCit has any tools for this, too?

**Comment by hortongn** [comment]
This is dependent on the RAM being added to the servers and the heap size increased in Tomcat

**Comment by hortongn** [comment]
Below is the user distribution across our "load balanced" environments during the two Scholar Camp days.  I think this definitely warrants us getting an explanation from UCit about how BigIP does load balancing.

Wednesday
qwl1: 5 users
qwl2: 17 users

Thursday
qwl1: 1 user
qwl2: 17 users

**Comment by hortongn** [comment]
At the Thursday Scholar Camp, The highest load average on qwl1 was 0.87.  The highest load average on qwl2 was 3.12 (enough load to fully occupy 3 CPUs at that moment).  

Neither of those are really alarming, but at the Wednesday session qwl2 hit a load average of 9.93.  Over the span of 5 minutes, the load average was 5.86 on qwl2.

**Comment by hortongn** [comment]
I would say that Scholar easily passed the stress test.  However, at our UCit meeting later this week we should ask them why the load balancer didn't work as expected.
