### ISSUE TITLE
Fixity checks

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#348]
Build the process to report (email - to Scholar@UC team?) if checksums of file content do not match the checksum generated on ingest.  Leverage checksum/fixity checking performed by Fedora.

**Comment by jamesvanmil** [comment]
Next step: need to research what Fedora is/should already be doing, including recalculating checksums and sending reports of problems.

**Comment by newmanld** [comment]
This is the place to start, I believe: [Fedora3 checksums](https://wiki.duraspace.org/display/FEDORA34/Checksums).  Note that automatic checksumming is off by default - so it may be that the checksums I see have been generated by FITS not Fedora?  Also that there is a method for overriding automatic checksums (for example if a file is too large for Fedora to do it efficiently) and a way to get information about whether checksums are matching using API-M function compareDatastreamChecksum.

**Comment by hortongn** [comment]
This is what we need to do to run fixity checks on content:
https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#fixity-checking

We should run this manually at some point and then possibly schedule it to run periodically.

I'm putting this issue in the "High priority" milestone so we remember to do it at some point in the near future.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/451
