### ISSUE TITLE
Add indexing of full text for supported file types

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#349]

**Comment by scherztc** [comment]
Hyrax uses Solr to extract text a you are aware. Solr uses Tika for extracting text from content.  Hyrax sends the content to  Solr, Solr passes the content to Tika and Tika passes the content to other parsers.  See this page for supported Tika formats: https://tika.apache.org/1.13/formats.html

Tika uses PDFParser for parsing PDFs specifically: https://tika.apache.org/1.13/api/org/apache/tika/parser/pdf/PDFParser.html

Is it possible your PDF is just an image?  We have not had text extraction work in ScholarSphere if the PDF is an image and not text.

It does look like PDFParser may be able to be configured to extract images, but I have never gone down that path.

**Comment by scherztc** [comment]
I then used PDF-Xchange Viewer to OCR the PDF image files, and Voila'...the indexing started working.

**Comment by crowesn** [comment]
This supposed to be working automatically - there was a bug fix backported to 1-0-stable at the end of June. https://github.com/samvera/hyrax/pull/1310

**Comment by crowesn** [comment]
Related: https://github.com/uclibs/scholar_uc/issues/1532

**Comment by crowesn** [comment]
Test and examine configuration. - Fix comes with Hyrax 1.0.3

**Comment by hortongn** [comment]
This appears to be working properly in scholar_uc as long as we are using Sidekiq.  I verified it works correctly in our server environment.

We eventually need to figure out why this doesn't work using the inline adapter.  However, I think we can move this issue to a post-3.0 milestone.

**Comment by hortongn** [comment]
Replaced with new issue #1645
