### ISSUE TITLE
Edit error pages and run scan to satisfy Hailstorm

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#351]
One page exists in the application
https://github.com/uclibs/scholar_uc/blob/develop/public/500.html

Another page exists in the Curate gem
https://github.com/uclibs/curate_fork/blob/develop/app/views/errors/500.html.erb

Ideas:
* Can the pages be renamed to something other than 500?
* Can the pages be combined into a single error page?
* What happens if the error pages removed?
* Images can possibly be used to convey information to the user.
* Can an email (with details) be generated when these pages are called?

The following text should not appear on the pages:

{CHS:regexp&type.=traversal-response}(System|java|javax|net|com|org)((\.[a-zA-Z0-9_]+)*\.)([A-Za-z])*Exception
{CHS:regexp&type.=traversal-response}(System|java|net|com|org)((\.[a-zA-Z0-9_]+)*\.)([A-Za-z])*Error
{CHS:regexp&type.=traversal-response}at System([.][a-zA-Z0-9_]+)+[\(]([a-zA-Z0-9 ,_]+)[\)]
{CHS:regexp&type.=traversal-response}at [a-zA-Z0-9_$]+([.][a-zA-Z0-9_$]+)+[(][a-zA-Z0-9_$]+[.]java[:]\d+[)]
{CHS:regexp&type.=traversal-response}<h2>HTTP Error \d+\.\d+ - (Internal Server Error|Forbidden|Not Found|Unauthorized)<\/h2>
{CHS:regexp&type.=traversal-response}<b>(Fatal error|Warning)<\/b>:.*\(.*\) \[.*\].*<b>[c-zC-Z]\:\\([a-zA-Z0-9_\-\s\.]+\\?)+</b> on line <b>\d*<\/b>
{CHS:regexp&type.=traversal-response}<b>(Fatal error|Warning)<\/b>:.*\(.*\).*<b>\/(var|etc|usr|srv|home|opt)(\/[a-zA-Z0-9_\-\s\./]+)+</b> on line <b>\d*<\/b>
{CHS:regexp}Server Error in '/(.)*' Application
[Exception in:
[ServletException in:
Internal Error
Internal Server Error
Expression Error
Servlet Engine Exception
Caught Exception
Internal Servlet Error
in memcpy ()
coldfusion.runtime
cannot convert the value
Runtime Error
Fatal error
Failed to parse
parser error
Backtrace
unhandled exception
Stack Trace
{CHS:regexp}StackTrace(?!\.)
Index was out of range. Must be non-negative and less than the size of the collection
Object reference not set to an instance of an object

**Comment by hortongn** [comment]
@newmanld @jamesvanmil @scherztc @pburke77 @13miciunasl 

Hailstorm was deleting our scholaruser account on QA because the "deactivate account" button made it too easy for the scan to click it.  After removing the deactivate account button and running Hailstorm again, we are getting a ZERO harm score for tests A-J.

I guess the next step is to disable the error page and see what the score is.

**Comment by newmanld** [comment]
Good work!  I think you are right about the next step Glen.
