### ISSUE TITLE
Disable error pages and run Hailstorm

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#352]
Turn off error pages by editing  config/environments/production and setting config.consider_all_requests_local to true

Record the new errors found when error pages are off

**Comment by jamesvanmil** [comment]
Need to examine Hailstorm results and turn them into issues.

**Comment by scherztc** [comment]
We ran sections A-J and got one vulnerability in section F.  So we have a HARM score of 100.  Hailstorm is not happy that when it tried to request a bogus page the 404 page listed the path to our app on the server (/srv/app/curate_uc).  We should be able to easily resolve it with a sanitized 404 page.  Will add as individual issue.
