### ISSUE TITLE
Create a set of "clean" data that can be loaded into the QA environment

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#353]
Includes different types of works and different types of users

Eventually extend this to an automated process

**Comment by jamesvanmil** [comment]
Place to start?: http://guides.rubyonrails.org/testing.html#the-low-down-on-fixtures

**Comment by jamesvanmil** [comment]
I've determined that fixtures aren't the way to go - their use is intended to be limited to testing environment.

Given that, and our needs for import, I think that the best solution would be a rake task that imports a blob of data from Fedora and reindexes it. Here's some thoughts on that topic:

* User accounts are complicated objects, with a component in the database. For creating sample data, we'd want to create these accounts and connect them to the People objects in Fedora. For import for the purpose of data recovery, it's probably reasonable to assume that we'll also have a backup of the application database to work from, and wouldn't want to create new user accounts.
* For sample users, we'll want a mixed of shibbolized and regular logins. Do we need to be able to login as the regular users? If so, do the passwords need to be secret?
* Would probably want to manually create all of the desired content and users, then export from Fedora and figure out the re-ingestion process.
* Need to fix the soft-delete reindexing issue first

Other thoughts?

**Comment by jamesvanmil** [comment]
This is awaiting other issues, so removing from the Sprint.

**Comment by scherztc** [comment]
Copy clean data.
fedora-rebuild
solr:reindex
