### ISSUE TITLE
Examine the cookies flagged by Hailstorm

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#354]
Ensure there is no secure data in the cookies

**Comment by 13miciunasl** [comment]
In the third instance of the cookie vulnerability, it looks like the password is posted. (Bottom line) Other than that I didn't see anything

HTTP Request:
POST /users/sign_in HTTP/1.1
Host: scholar-qa.uc.edu
User-Agent: Mozilla/5.0 (Windows NT 5.0; WOW64; rv:6.0) Gecko/20100101 Firefox/6.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Connection: keep-alive
Referer: https://scholar-qa.uc.edu/users/sign_in
Cookie:
_curate_app_session=bzlaUDRUTy9rdU50Y1gvNy9XQ1ZFRXlZQ0lzOE56cTAxWWpiUUlPZnBrYkVlK3VTMTEyanJHMmtKTnIzUkl2U3gyRS92RD
JQWlVYR3M3dUtCZ2hVNVo2bWtITmh4N0x1ZXJnNU5oYi85dWRWdExmNi9jL3RPc293a0VDRTNMUzBuYnBzVmVLM0dqSVZvWWtqa09oc05G
TVFmTWl5VFl6dkNsRzlqSEwxNEVtY0xDYXU1YWVxK1RSeUdONHFzeVhKSE1iYjByOEMwTTlKZFB6eWszZmlJWVJXOGtkcGI1Tmg4Z1h4UVI
wVVhsU3R6L0ZVcnVMd1VzYzNRT2dWNU4vLy0tWGphZHZ5VGZVSDlNTmxmUk5ZUC9PQT09-
-ede03cd53538cf8a138a4fb2e0655838cc87e93b; hydraq=3874859200.47873.0000
Content-Type: application/x-www-form-urlencoded
Content-Length: 210
utf8=%E2%9C%93&authenticity_token=VlQ4tj2maLRK0tCBrGzJpfOfVKmfi%2BjfPXPhFt1iua0%3D&user%5Bemail%5D=jsmith20%40kelev.biz&
user%5Bpassword%5D=********&user%5Bremember_me%5D=0&user%5Bremember_me%5D=1&commit=Sign+in

**Comment by 13miciunasl** [comment]
Tested on IE, Firefox, and Chrome on windows. All three flagged cookies do not appear to contain any secure data, starred-out or otherwise

**Comment by jamesvanmil** [comment]
All confirmed no issue.
