### ISSUE TITLE
Empty form div appearing on work show page

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#363]
The empty grey bar in the screenshot below should only be appearing when a collector or editor is logged in (with buttons), per https://github.com/uclibs/curate_fork/blob/develop/app/views/curation_concern/base/show.html.erb#L17-L31

It's appearing regardless, adding a functionless page element for non-logged-in users. (This is coming up as I'm working to add permalinks to the bottom of the work show page).

Note that though the content is set in the curation_concern/base/show partial, it's being rendered in a template. Not sure which, but one of these: https://github.com/uclibs/curate_fork/tree/develop/app/views/layouts

![image](https://cloud.githubusercontent.com/assets/2651187/8439758/fc770036-1f3b-11e5-81ef-bc9601d0451a.png)

**Comment by flutterflies** [comment]
Cannot reproduce in Scholar 3
