### ISSUE TITLE
File div on Work show page not wrapping for long titles and filenames

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#364]
See https://scholar.uc.edu/concern/articles/td96k248x

![image](https://cloud.githubusercontent.com/assets/2651187/8440085/0500ed3c-1f3e-11e5-8cb8-99931dea0991.png)

**Comment by lawhorkl** [comment]
added a fix that allows the file title to wrap, but if a title isn't delimited by underscores, or something else, the browser will have trouble wrapping them regardless.

**Comment by lawhorkl** [comment]
Finished pending a pull request
