### ISSUE TITLE
Redesign the new account creation terms of use page to be a welcome page

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#372]

**Comment by jamesvanmil** [comment]
* User should see the page every time they log in until they opt-out.
* Will replace the terms of use - will no longer require explicit or tracked acceptance of TOU.
* Text will be reused in another help page.

**Comment by jamesvanmil** [comment]
@newmanld @ntallman 

Currently, after the acceptance of the Terms of Use, the user ends up at the Profile edit page, because they're required to modify their account before using the system.

With the welcome page, the user may see it more than once, so it may make sense to route them somewhere else after the initial login. Obvious candidates for destination are:

* Profile show page
* Catalog (with recent works)
* New Work page
* My Works page

Given that a user is probably logging in to either modify a Work or submit a new Work, I'd lean towards the latter two. Any thoughts between these, or in support of other options?

**Comment by hortongn** [comment]
My gut says the user should be routed to the My Works page, but I don't have a strong opinion on that.

**Comment by newmanld** [comment]
I like the idea on an intelligent welcome page that knows if it is the first time the user is logging in, and displays text - only the first time - explaining why the user will be sent to their profile page. 

After the first time they login, like Glen I don't have strong opinions - the My Works page is a good choice - although we might want to confirm what it looks like if you have no works yet.  (I think it's just your profile.)  

We might want to pull Eira and Ted into this thread asking if any Early Adopter feedback suggests what they would like to see first.

**Comment by jamesvanmil** [comment]
Thanks, all. The My Works page is a little weak right now - if you have no works it just displays an empty catalog search. There might be an easy way to strengthen that page with a link to the New Work creation page.

**Comment by ntallman** [comment]
+1 for routing users to the My Works page instead of Welcome page, once they've viewed it the first time. (That is, until we can have a proper dashboard.)

**Comment by jamesvanmil** [comment]
That sounds like a decision to me. It'll be really easy to change the page, if it doesn't feel right (there's a special Devise method for specifying the past, post-login).

**Comment by newmanld** [comment]
I am wondering if we were thinking just from the point of view of someone we want to be a contributor.  But we will also be promoting the login as a way to get to any content restricted to UC.  So students will be logging in but we don't necessarily want to encourage them to contribute.  Does this argue for keeping the default view at the Catalog rather than either My Works or the New Work page?  Do we need to consider this from the point of view of both contributors and consumers?

**Comment by jamesvanmil** [comment]
@hortongn I can't remember if we're getting staff/student/faculty info from Shibboleth - it would be straightforward to set different landing page paths, if we are.

**Comment by jamesvanmil** [comment]
Spec work is pending, but this feature is now working. If we want to take 15-20 minutes out of the swarm tomorrow, I can demo.

**Comment by hortongn** [comment]
We do have access to a SHIBBOLETH_UCEDUAFFILIATION attribute that will tell us a user's status.  Mine currently says "Staff."  I don't think we are tracking or storing that attribute right now, but we certainly can if we need to do something like `if current_user.affiliation == "Staff"...`

I don't know how reliable that attribute is if someone changes from student to staff, etc.  I assume UC regularly updates that attribute.

**Comment by newmanld** [comment]
Discuss in swarm tomorrow whether destination should be different based on user status?

**Comment by scherztc** [comment]
Don't merge PR #62 on curate_fork until content is published behind place holders.
