### ISSUE TITLE
Fix permalink partials

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#383]
The work that was done on the app should actually also work in the gem. We can move the partial to the gem and get rid of the local override.

Also, I confirmed that the 'show' URLs are actually going to DOIs, so we should probably consider them permanent, and could change the wording accordingly.

**Comment by hortongn** [comment]
The CHANGELOG for this currently says "If a DOI has been minted for work, it is displayed as an alternative link."  What would be a more appropriate description for this as it stands right now?

**Comment by newmanld** [comment]
How about simply ‘An alternative, shorter URL is displayed at the bottom of each work, and on the show page for each file.’

No need to address in the Changelog, I think,  the question of whether we will decide later to change the word ‘alternative’ to ‘permanent’.

-- Linda

**Comment by jamesvanmil** [comment]
+1 on each point from Linda

**Comment by hortongn** [comment]
Merged
