### ISSUE TITLE
Minting DOIs on QA gives error

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#384]
When I tried to create an article on QA and requested a DOI, I got the following error.  Have the credentials changed?

Hydra::RemoteIdentifier::RemoteServiceError in CurationConcern::ArticlesController#create

response.code: 401 response.body: "error: unauthorized - authentication failure" request.uri: "https://xxx:xxx@ezid.cdlib.org/shoulder/doi:10.5072/FK2" request.payload: "_target: https://scholar-qa.uc.edu/show/2f760504n\ndatacite.creator: Glen Horton\ndatacite.title: Test\ndatacite.publisher: None\ndatacite.publicationyear: 2015"

**Comment by jamesvanmil** [comment]
I no longer have access to the config-vault, so I can't confirm

**Comment by jamesvanmil** [comment]
Just tested, and it's working. See: https://scholar-qa.uc.edu/works/images/2f768m25g
