### ISSUE TITLE
Get the Curate gem tests running with the Scholar app

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#389]
Instead of running the Curate gem tests against a dummy app, we should run them against our Scholar app.  This will let us catch situations where something in the app is overriding and breaking functionality in the gem.

**Comment by jamesvanmil** [comment]
There's a good starting point here: https://stackoverflow.com/questions/12499404/can-i-run-a-rails-engines-specs-from-a-real-app-which-mounts-it

**Comment by jamesvanmil** [comment]
I've spent some time fussing with this - there are some dependencies on shared examples and factories in the gem which aren't available when running the spec from the app. Could keep working on it, but I'm uncertain about how much more learning I'll need to do to make it work.

**Comment by jamesvanmil** [comment]
Next steps are to research testing practice with Sufia ar PSU and elsewhere, and to examine code in the App which may belong in the Gem.

**Comment by jamesvanmil** [comment]
We talked about this issue in swarm today and have a recommended approach on app vs. gem. I'm opening a new issue for some related groundwork. @newmanld - let's chat when you return to make sure we all agree. Closing this issue for now, and putting the new one into the current sprint.
