### ISSUE TITLE
The 404, 422, and 500 error pages are hard-coded to scholar.uc.edu

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#395]
When a user lands on one of the error pages like https://scholar.uc.edu/500.html the "Scholar@UC" logo has a hyperlink that is hard-coded to scholar@uc.edu.  So if someone on scholar-dev or scholar-qa lands on an error page and clicks the logo, they will end up on production scholar (probably without realizing it).

**Comment by newmanld** [comment]
This seems like something we should clean up as we deal with error pages in our security sweep.

**Comment by jamesvanmil** [comment]
Changing this issue to:

Make the page very simple - implementing branding and displaying the error, but not linking anywhere except the Scholar homepage.
