### ISSUE TITLE
Update Slider on opening page with new image

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#396]
As a member of the Communications Working Group, I want the first image in our 'slider' on the opening page to direct users to the Scholar Stories on our blog, and to highlight those stories with an image collage.

To do this:

Remove image and overlay text for ETDs (3rd image), making it easy to re-instate in the future.

Add new image to be new first image.  In the overlay text, the title should be 'Scholarly Works' and the subtitle 'Scholar@UC supports preservation and access for digital scholarly works.'

Maintain the existing action behind the 'Begin!' button.  Add new action, for this image only, that will use an image map or similar technique to provide a link behind two areas of text on the image itself - 'scholar stories' and 'read'.  This link will go to: http://libapps.libraries.uc.edu/scholarblog/category/scholar-stories/.  

The link should open in a new window or tab.

Provide 4 variations using 4 different images
    white background
    blue background
    green background
    gray background

With white background only, add a drop shadow that will provide an outline of the image (needs to be visible for the left, right and bottom sides).  This drop shadow will be part of the css for the slider no matter which image is displayed.

We will need to bring up the variations in our sandbox and decide which is most appealing, also verify that the overlay text and navigation arrows are positioned ok with the source image.
![scholarstories-blue](https://cloud.githubusercontent.com/assets/3521707/8855635/3b18dbb6-3134-11e5-91d7-7a0c86ff79b1.jpg)
![scholarstories-green](https://cloud.githubusercontent.com/assets/3521707/8855637/3b1c28ac-3134-11e5-96fd-28c515ad2128.jpg)
![scholarstories-grey](https://cloud.githubusercontent.com/assets/3521707/8855636/3b199c72-3134-11e5-8ddf-a9c313840a74.jpg)
![scholarstories](https://cloud.githubusercontent.com/assets/3521707/8855634/3b17d4e6-3134-11e5-8cb6-1b05d4e68bd1.jpg)

**Comment by newmanld** [comment]
Patrick - I will also email you these images.

**Comment by hortongn** [comment]
@newmanld @pburke77 @scherztc Patrick's branch is now up and running on http://larry.libraries.uc.edu:3001/

**Comment by newmanld** [comment]
Thank you!
________________________________

**Comment by scherztc** [comment]
There is a broken link with the Begin! button on Scholar Stories:

http://libapps.libraries.uc.edu/scholarblog/category/scholar-stories/

**Comment by newmanld** [comment]
Yes - this is a known situation.  Melissa has not yet published these stories.  But this is the category (scholar-stories) are in - you can see them if you log into ScholarBlog as an admin.
________________________________

**Comment by newmanld** [comment]
But more to the point, the link behind 'Begin' should not have changed.  Instead the word 'Read' and the phrase 'Scholar Stories' are to link to this category on the blog.
________________________________
From: Newman, Linda (newmanld)
Sent: Tuesday, July 28, 2015 5:44 PM
To: uclibs/scholar_uc; uclibs/scholar_uc
Subject: RE: [scholar_uc] Update Slider on opening page with new image (#396)

Yes - this is a known situation.  Melissa has not yet published these stories.  But this is the category (scholar-stories) are in - you can see them if you log into ScholarBlog as an admin.
________________________________

**Comment by newmanld** [comment]
Patrick - did you run into a blocker trying to link the text in the image itself to the ScholarBlog category, leaving the action behind the Begin! button alone?
