### ISSUE TITLE
Reboot production servers

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#401]
Our production servers have not been rebooted since October 2014.  We should submit a change request to reboot all of the boxes before we launch Scholar 1.0.  We don't want any nasty surprises when we reboot in the future.

**Comment by newmanld** [comment]
If it has not already happened, then this could be timed with our content moratorium as we migrate existing content to user's 6+2s.

**Comment by newmanld** [comment]
Determine a regular schedule for restarting Fedora service (and possibly others) on production.

**Comment by hortongn** [comment]
The production Fedora/solr servers will be restarted on 8/26 for cpu and memory upgrades.  Jim will also reboot libhydpwl2 at that time.  libhydpwl1 was already restarted less than a month ago.

So we can mark this issue done in 8/26

**Comment by hortongn** [comment]
All production servers have been rebooted recently without incident.  Closing this issue,
