### ISSUE TITLE
Add language to My Groups page

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#405]
# My Groups page

The DCWG recommends the following language me added to the My Groups page:

Groups are a set of users to through which you may easily grant the privilege to edit specified works.. For example, if you work with a group of researchers on a single work, you can create a group of those researchers and grant that group viewing and editing privileges. Groups are like delegates, but whereas delegates have all the powers of the person they represent, groups can only access/edit specific works.

**Comment by hortongn** [comment]
Merged
