### ISSUE TITLE
Create new Welcome page

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#408]
[Below is the content for a new welcome page.  The Digital Content Working Group also also recommends that this page be linked to from the Help menu. They did not specify where - let's put it at the top.  Please coordinate with work done for #372.   This should already be factored for one page if it is the first time users are logging in (after which the user is sent to their profile page) and a different welcome page if it is not the first time (after which the user is sent to the catalog).  Therefore, the first paragraph below should only be on the welcome page the first time the user logs in, and this is the only difference between the two pages.]

Next you’re going to edit your profile to make sure all your personal details are correct, but first please take a moment to review the help information below.

## Welcome to Scholar@UC

Welcome to Scholar@UC!  On this page, you will learn how to use Scholar@UC.

### What is Scholar@UC?
Scholar@UC is a digital repository that enables the University of Cincinnati community to share research and scholarly work with a worldwide audience and preserve it for the future.  Read more about the mission of Scholar@UC on the [About page](https://scholar.uc.edu/about_request).  Get the latest updates on development of Scholar@UC on our [Scholarblog](http://libapps.libraries.uc.edu/scholarblog/).

### What types of content should I submit to Scholar@UC?
Scholar@UC stores and preserves the scholarly output and creative works of UC faculty, staff, and students. Examples of appropriate content include, but are not limited to: [grey literature](https://en.wikipedia.org/wiki/Grey_literature), [pre-](https://en.wikipedia.org/wiki/Preprint), [post-](https://en.wikipedia.org/wiki/Postprint), and published versions of academic papers, manuscripts, senior design projects, posters, datasets, presentations, and other creative works. Content may be text, image, video, audio, or mixed-media in nature.  Learn more about types of content you can share on the [Collection Policy](https://scholar.uc.edu/coll_pol_request).

Students should work with a faculty member to share scholarly output and creative works, such a capstone projects.

### How do I get started?
After you have edited your profile page for the first time, you may share content by clicking on [Add New] from the menu.

### Where do I go for more information?
Under the Help button on the main Scholar@UC menu, you will find the following help topics:

- [FAQs](https://scholar.uc.edu/faq_request) – Answers to a variety of commonly asked questions
- [File Format Advice](https://scholar.uc.edu/format_advice_request) – Help with finding the right file format for the content you submit to Scholar@UC
- [Creator’s Rights](https://scholar.uc.edu/creators_rights_request) – Information on Copyright and Intellectual Property

#### Need Further Assistance?
[Contact the Scholar@UC Team](https://scholar.uc.edu/contact_requests/new).

**Comment by hortongn** [comment]
Merged
