### ISSUE TITLE
If File title is left blank, assign file name as file title.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#409]
As a content editor, when attaching a file to an existing work, and regardless of the file source (workstation or cloud), if I leave the file title field blank, Scholar@UC should assign the file name to be the file title.

**Comment by newmanld** [comment]
See https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-41---submitting-multiple-files---early-adopter

**Comment by newmanld** [comment]
this may also resolve #521?

**Comment by lisa3711** [comment]
More work on this today- however, cant reproduce an instance of a blank title?

**Comment by lisa3711** [comment]
Completed code: https://github.com/uclibs/curate/tree/bug/%23409_2_blank_title_default  Working on a spec test

**Comment by hortongn** [comment]
@lisa3711 If you can find 1/2 hour on our calendar Thursday, we can work on a spec.  It gets a bit tricky to add it to the existing spec because it's being stubbed and may not have everything you need to test your feature.

**Comment by lisa3711** [comment]
In working with Glen, I discovered I hadnt really read the issue carefully enough. The code I submitted did not really solve the stated issue. So, will work on this when I get back from vacation!

**Comment by hortongn** [comment]
@lisa3711 You should be able to resolve this by adding the following to Curate's app/repository_models/generic_file.rb:

        before_save :set_title_if_blank

        def set_title_if_blank
          self.title = [self.filename] if self.title == [""]
        end

When a file is attached or edited, if the title field is blank it will be populated with the filename right before the file is saved.  We can discuss this and a test when you get back.

**Comment by lisa3711** [comment]
I've successfully tested the above code and it works. I have a branch for it. Have to research spec tests and write that now.

**Comment by lisa3711** [comment]
Wednesday: read through rspec tutorials. Will try coding my test this afternoon, or tomorrow morning.

**Comment by hortongn** [comment]
@lisa3711 Since we didn't get a chance to meet today and I'm gone tomorrow, here is what I think will satisfy your spec for this issue.  I took the spec you posted in Slack and added the two "persisted..." lines.  Your code sets the title to the file name whenever the title is blank ([""]).  So this test sets a blank title, saves the file, and then expects to see the file name saved as the title.

        it 'has file_name as its title when title is blank' do
          persisted_generic_file.title = [""]
          persisted_generic_file.save!
          expect(persisted_generic_file.to_s).to eq(File.basename(__FILE__))
        end

This test should pass with your code and should fail if you were to remove your `before_save :set_title_if_blank`
