### ISSUE TITLE
Upload multiple files when attaching files to an existing work

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#411]
As a content editor I want to be able to upload multiple files  (from either my workstation or the cloud) when attaching a file to an existing work.

**Comment by newmanld** [comment]
See https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-27---input-form--early-adopter

**Comment by scherztc** [comment]
The Open JS uploader gives us this functionality in Scholar 3.
