### ISSUE TITLE
Embargo release task not releasing all works

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#415]
It looks like the embargo release task that runs nightly is only checking the first 10 works that are embargoed.  A parameter may need to be added to the solr query to force it to check all works/files.

**Comment by jamesvanmil** [comment]
I think this config parameter is tripping it up: https://github.com/uclibs/scholar_uc/blob/develop/config/search_config.yml#L3

**Comment by hortongn** [comment]
Merged
