### ISSUE TITLE
Document bug

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#418]
From Linda:

> I had a problem with the document work type.  First I noticed that the tip saying that you could upload multiple files at once with shift or control was not there, then I noticed that I could not in face select more than one document from my local device, then when I completed the input form and hit submit, I got our santized error message.  Tried this three times.  I switched to generic work and all was well (including the ability to upload multiple files from my desktop).  So although more testing is in order, I'm wondering if our document work type is screwed up somehow.

Need to replicate on Dev/QA

Questions:

* Is there data in Fedora from the failed attempts?

**Comment by jamesvanmil** [comment]
PR is in on Curate - I don't think this triggered anything in Fedora (The error was triggered at the virus-checking stage) @scherztc - do you agree?

**Comment by hortongn** [comment]
Merged
