### ISSUE TITLE
Resolve Fedora out of memory heap errors

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#423]
Recommendations so far:

1. Raise the amount of RAM available to Fedora to 6 gigs or more
1. Restart Fedora at least monthly
1. Make sure Hailstorm scans are throttled down to "normal"

**Comment by hortongn** [comment]
Increased the memory available to Tomcat from 1.5 gb to 4 gb.  This delayed problems with Fedora, but didn't completely resolve the issue.

**Comment by hortongn** [comment]
During Hailstorm runs, the Fedora server at times hit 2.85 CPU utilization.  The server would probably perform better with additional CPUs.

**Comment by hortongn** [comment]
Raise the amount of RAM available to Tomcat on dev and production

**Comment by hortongn** [comment]
Details on deployment environments for several Hydra projects can be found at https://wiki.duraspace.org/display/hydra/Deployment+Hardware+Information

(although it is somewhat dated)

**Comment by hortongn** [comment]
Below is a reply from Justin Patterson at Penn State about their Fedora environment.  It supports our opinion that Fedora needs more that 4 gigs of memory and needs to be restarted periodically.

"On all our environments we utilize the same memory allocations, in JAVA_OPTS we allocate 2 gig min and 6 gig max  for tomcat which in turn shares that with Fedora and Solr.  I don't think it would be uncommon for the error that your seeing  as you have stated. We have sometimes run into the "out of memory" scenario if the tomcat service has been up a long time (a couple months, but on occasion less) without being restarted as it tends to leak memory.   We are looking to move to Solr5 in the near future which will isolate Fedora as being the only entity living inside of Tomcat which should help some as well.   Solr5 becomes its own standalone service in Linux."

**Comment by hortongn** [comment]
We do have the DRC test and production servers automatically restart Tomcat every morning at 6am.  I forgot that we do that because we only get an email if the restart fails.  So restarting Tomcat nightly or monthly for our Hydra servers makes sense as well.

**Comment by newmanld** [comment]
But we don’t want to mask memory issues by an overly frequent restart.  (We were willing to do a shortcut with the DRC to deal with Tomcat.)  Let’s continue to find out how much RAM our partners are giving tomcat for Fedora 3 and how often they still restart.    But I agree that after optimizing memory, we will need to pick a frequency.  Would like to confirm that we won’t be potentially interrupting submissions in a destructive way (creating incomplete records) by this scheduled fedora process restart.

**Comment by hortongn** [comment]
The following upgrades will be made on 8/26:

Production Scholar@UC environment:

* Fedora server (libhydpfl1): increase to 4 CPUs, 8 gb RAM  (currently 2 CPUs, 4 gb)  
* Solr server  (libhydpsl1):  increase to 6 gb RAM     (currently 4 gb)

QA Scholar@UC environment:

* Fedora server (libhydqfl1):  increase to 4 CPUs,  8 gb RAM   (currently 2 CPUs, 6 gb)
