### ISSUE TITLE
Resolve Hailstorm Set E warnings

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#426]
Details on the three warnings:

Possible application exception vulnerability.
Server response status: 500
Injected item: GET: works
Injection value: %84
https://scholar-qa.uc.edu/catalog?utf8=%E2%9C%93&works=all&works=%84

Possible application exception vulnerability.
Server response status: 500
Injected item: GET: works
Injection value: %84
https://scholar-qa.uc.edu/catalog?utf8=%E2%9C%93&works=%84&q=testval

Possible application exception vulnerability.
Server response status: 500
Injected item: GET: works
Injection value: %84
https://scholar-qa.uc.edu
/catalog?utf8=%E2%9C%93&works=%84

**Comment by scherztc** [comment]
ArgumentError in CatalogController#index
invalid byte sequence in UTF-8

Rails.root: /Users/thomasscherz/Workspace/curate_fork/spec/internal

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"utf8"=>"✓",
 "works"=>"\x84"}

**Comment by scherztc** [comment]
https://gist.github.com/joost/ca4eda8f31655cf6095a

**Comment by scherztc** [comment]
http://blog.siami.fr/diving-in-rails-the-request-handling
