### ISSUE TITLE
Improve css on additional pages

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#430]
The Welcome/Help/Contact pages are picking up some styling from bootstrap/vanilla curate. For 1.0 we'll do some lazy fixes, but let's circle back and improve these.

**Comment by hortongn** [comment]
@jamesvanmil can you elaborate on what needs to be fixed in this issue?

**Comment by jamesvanmil** [comment]
It's been a little while, but IIRC, the styling on these pages is being applied ad-hoc, instead of being part of the overall framework for content across the application, so we're duplicating some style in the the CSS to get these pages to look like other content, instead of implementing them consistently.

**Comment by flutterflies** [comment]
Closing this issue as it is no longer relevant in Scholar 3.
