### ISSUE TITLE
No thumbnail for docx

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#439]
Discovered during test script run, with this file: http://homepages.uc.edu/~vanmiljf/foo.docx

The file was generated with Pandoc, so may not be 100% standard, but I expected to see at least a default thumbnail.

![image](https://cloud.githubusercontent.com/assets/2651187/9392033/331360a6-4748-11e5-8016-6051b6675805.png)

**Comment by newmanld** [comment]
I don’t think we’ve ever seen thumbnails from docx files (or *.doc files) or *.txt files.  I think we have always been getting the generic page image in a listing of files and the image with an X when looking at the show page.

But, if there is a way  with our current technology to generate a thumbnail for *.doc and *.docx files, that would be a welcome enhancement.

**Comment by jamesvanmil** [comment]
Done looks like:

A thumbnail is generated and displayed for Word files

Or, if that is going to take a long time to figure out:

Display the default thunbnail, and open an issue for generating thumbnails.

**Comment by hortongn** [comment]
@13miciunasl Some files to start looking at for your issue:

app/views/application/_thumbnail.html.erb
app/views/curation_concern/articles/_form_files_and_links.html.erb
app/views/curation_concern/base/_thumbnail.html.erb
app/views/curation_concern/documents/_form_files_and_links.html.erb
app/views/curation_concern/generic_files/_media_display.html.erb

**Comment by scherztc** [comment]
DOCX generate thumbnails in Scholar 3.
