### ISSUE TITLE
Examine use of turbolinks

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#469]
Turbolinks circumvents normal browser loading behavior, making a page appear static when it's loading assets in the background.

Let's examine the use of this to see if we should reduce or remove turbolinks.

**Comment by jamesvanmil** [comment]
We've decided to remove turbolinks and assess whether it improves interactions with bookmarklets and extensions (Altmetric, Zotero) and page responsiveness issues.

There are some notes about problems and fixes related to turbolinks on the parent repo:

https://github.com/projecthydra-labs/curate/pull/429
https://github.com/projecthydra-labs/curate/pull/431

**Comment by jamesvanmil** [comment]
Addressing #278 would resolve some concerns with turbolinks and page load delays

**Comment by lawhorkl** [comment]
I've disabled turbolinks on my local app, so far it hasn't had any negative effect on anything that I can see.

I'm going to run through the test script with it disabled and report any problems that I find

**Comment by lawhorkl** [comment]
Went through the test script, can't find any obvious issues.

**Comment by scherztc** [comment]
Make changes and create PR.

Remove from Gemfile
Remove from curate.js
