### ISSUE TITLE
New users seen when browsing, but not searching

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#478]
@ntallman created a new user account and added content.  He can be seen when browsing the list of people, but isn't found when searching for him (e.g. 'tallman')

I'm thinking that the Solr index isn't getting updated when a user suddenly becomes visible after adding their first content.  So they can be found when browsing, but not when searching.

**Comment by newmanld** [comment]
I’m seeing him now I think.  4 works found when searching ‘Tallman’ in keyword index, and 4 works found from ‘Tallman, Nathan’ as the Creator facet.

**Comment by hortongn** [comment]
To be clear, Scholar is not finding the person profile.  Nathan's works show up, but his person profile is not found when searching "tallman"

**Comment by hortongn** [comment]
Confirmed this bug on scholar-dev:

1. Added a new user account
1. Confirmed user could not be found by browse/search
1. Added a new work
1. Confirmed that user showed up in browse, but could not be found by search

I tried a `rake solr:reindex` to see if the user could be searched, but it didn't work.

**Comment by jamesvanmil** [comment]
Probably an issue with person metadata - I'll dig in this sprint.
