### ISSUE TITLE
Update 'About' info

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#484]
Currently has the text
>Scholar@UC is currently operating in a closed-beta mode. A small group of early adopters are helping us to test the system and plan additional development tasks before a campus wide release. Regular updates about Scholar@UC can be found on ScholarBlog: the blog for Scholar@UC. For additional information, please contact the Scholar@UC team.
which will soon be out-of-date.

pinging @ntallman on this issue: okay to just remove this text altogether, or should we replace it?

**Comment by newmanld** [comment]
Good catch!

**Comment by hortongn** [comment]
:clap: Yeah, good catch!

**Comment by newmanld** [comment]
This has been reviewed by Nathan and Ted.  Replace  last paragraph with this text:

The development of Scholar@UC is aided by a group of early adopters who help to prioritize new developments.  To join this group (or to directly suggest improvements) [contact the Scholar@UC team](https://scholar.uc.edu/contact_requests/new).  Regular updates about Scholar@UC can be found on [ScholarBlog: the blog for Scholar@UC](http://libapps.libraries.uc.edu/scholarblog).  For additional information, please [contact the Scholar@UC team](https://scholar.uc.edu/contact_requests/new).
