### ISSUE TITLE
Editor rights from additional editors on Works aren't granted to Linked Resources

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#485]

**Comment by newmanld** [comment]
@jamesvanmil please add detail about what  Linked Resources are in this context?

**Comment by jamesvanmil** [comment]
These are the external links attached to Works.

**Comment by jamesvanmil** [comment]
Also, when a delegate is submitting, the delegate is incorrectly noted as the owner, and the delegator is unable to edit the link.
