### ISSUE TITLE
Redesign End to End spec

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#490]
With the redesign of the terms of service page to be a welcome page, the End to End spec is out of date.

Let's redesign it to follow the [test script](https://github.com/uclibs/scholar_uc/wiki/Scholar@UC-Test-Script), adding the welcome page functionality.

After this is done, we should reassess the scope of the test script to make sure it focuses closely on things that are harder to test.

**Comment by scherztc** [comment]
Closed with PR https://github.com/uclibs/curate_fork/pull/76/files
