### ISSUE TITLE
Handle trailing whitespace in metadata fields

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#496]
While working with the manifests, we found some works that had trailing characters (probably newlines) in the titles which weren't being chomped. We should patch Curate to handle these, then clean up metadata as needed.

Pinging @ntallman - this might impact the work you do with BagIt and AP Trust, so just a heads up in case this isn't addressed before you start that work.

**Comment by jamesvanmil** [comment]
We should also tackle trailing/extra whitespace within all fields. Extra spaces in names, for example, are causing extra entries in the facet browse.

**Comment by lawhorkl** [comment]
By extra spaces in names do you mean the user's names or the titles of the field?

**Comment by lawhorkl** [comment]
Unable to replicate issue. Closing for future reference.

**Comment by jamesvanmil** [comment]
Not sure what else is going on - need to see where this impacts the UI.

**Comment by jamesvanmil** [comment]
@lawhorkl I found a work in production with a trailing carriage return in the title: https://scholar.uc.edu/works/images/zp38wd37c

Would you try to replicate this in your local dev environment?

**Comment by lawhorkl** [comment]
possible connection to reindex issue, \u000B and \v codes causing possible related problems
