### ISSUE TITLE
Enhance file upload interface

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#510]
Look at Blueimp Basic Plus widget options
http://blueimp.github.io/jQuery-File-Upload/basic-plus.html

Related #273 #278 #411 #262

**Comment by jamesvanmil** [comment]
In our earlier discussions about this, there was a difference in opinion about which version of the UI to use. For now, I'd focus on the simplest implementation, and we can demo alternatives using the demo site.

Of particular note (and identified as an issue by PSU's UX team) is the interfaces that require you to click the 'Upload' button before moving on.

**Comment by jamesvanmil** [comment]
Here's the commit where this interface was implemented in Sufia: https://github.com/projecthydra/sufia/commit/9b0e939f08b2571131097a7dcbe07ba8d0587170

It moved around a lot after implementation, ending up in this partial: https://github.com/projecthydra/sufia/blob/master/app/views/generic_files/upload/_form_fields.html.erb

**Comment by scherztc** [comment]
What about the possibility of just using browse_everything?  I know it has local file system support.  Not so sure about Windows file systems.

**Comment by hortongn** [comment]
This depends on #657

**Comment by scherztc** [comment]
Current progress:  https://github.com/uclibs/curate/commits/feature/absolute_uploader

**Comment by scherztc** [comment]
See also: https://github.com/KelvinSmithLibrary/absolute/commit/ae0e0e7375abf846b448b170d76ae34244806623

**Comment by scherztc** [comment]
We have the JS uploader in Scholar 3.
