### ISSUE TITLE
Document all overrides in the app

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#512]
* Document all overrides in the app
* Identify and open issues for functionality which should be a stand-alone gem (E.g. UC Shibboleth/Devise implementation; CSS styles (e.g. [Stanford](https://github.com/sul-dlss/sul_styles)))
* Open issues for each unit of functionality/override recommended to move to the gem
* Enhance documentations of overrides with justifications

**Comment by jamesvanmil** [comment]
I started work on this: https://github.com/uclibs/scholar_uc/wiki/App-vs-Gem

I'd like everyone's feedback before I open any issues or work on additional documentation. Thanks!

**Comment by hortongn** [comment]
* I agree with moving the Shibboleth functionality to its own UC-Shibboleth gem.  We will definitely want that functionality in other projects.

* I agree with extracting branding, color, etc. to its own gem.  Having one place to manage this makes sense.  

* As for everything else, I think if we are overriding something in the app I agree that we should probably just move it into the gem.  Maybe we should start this process off with converting curate_fork into a standalone Git repo (curate_uc?)

One thing to keep in mind though:  when we eventually move to a Sufia-based application, we will be back to doing lots of overrides in the app unless we fork Sufia and customize the gem.  We've got a while before we need to figure that out.
