### ISSUE TITLE
IMG ALT text must not be the same as the image file name.

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#516]
Change the ALT text to a description of the image.		

* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?&works=mine
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Person
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Person&f%5Bhuman_readable_type_sim%5D%5B%5D=Person
* ALT text: "?s=300"
https://scholar-qa.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Person&f%5Bhuman_readable_type_sim%5D%5B%5D=Person&works=mine
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Person&page=2
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Person&works=mine
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Person
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Person&works=mine
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?page=10
* ALT text: "?s=300" https://scholar-qa.uc.edu/catalog?works=mine

**Comment by jamesvanmil** [comment]
Starting with work on the catalog browse. I wanted the alt text to show whether the user was getting a thumbnail or a generic icon, but gravatar is complicating it.

To make it easy, I'll just say have them say "Thumbnail for #{Work Title}" or "Thumbnail for #{Person Name}"
