### ISSUE TITLE
The ARIA-LABELLEDBY attribute references a non-existent element ID

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#518]
Example:
<label class="checkbox inline-checkbox"><input id="group_member_edit_users_ids_" name="group_member[edit_users_ids][]" type="checkbox" value="{{value}}" /></label>

Problem pages: 
* https://scholar-qa.uc.edu/works/articles/new
* https://scholar-qa.uc.edu/works/datasets/new
* https://scholar-qa.uc.edu/works/documents/new
* https://scholar-qa.uc.edu/works/generic_works/new
* https://scholar-qa.uc.edu/works/images/new

**Comment by lisa3711** [comment]
Cant find this attribute on any of the pages listed above. New Scan?

**Comment by lisa3711** [comment]
I think we can close this as we aren't doing a new scan, and I could not find instances on any referenced pages.
