### ISSUE TITLE
Form controls with no programmatically determined name

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#519]
A programmatically determined name allows screen readers to tell the user what the control does. To add a name do one of the following:

* Use a LABEL element with the FOR attribute set to the ID of the form control
* Wrap a LABEL element around the form control
* Add an ARIA-LABELLED attribute
* Add a TITLE attribute
* Add an ARIA-LABEL attribute (not supported in all screen readers)

Problem pages:
* https://scholar-qa.uc.edu/collections/new line 240
* https://scholar-qa.uc.edu/collections/new?add_to_profile=true line 219
* https://scholar-qa.uc.edu/hydramata/groups/new lines 219 315
* https://scholar-qa.uc.edu/works/articles/new line 634
* https://scholar-qa.uc.edu/works/datasets/new line 595
* https://scholar-qa.uc.edu/works/documents/new line 616
* https://scholar-qa.uc.edu/works/generic_works/new line 593 645
* https://scholar-qa.uc.edu/works/images/new	line 703

**Comment by lisa3711** [comment]
I cant see where this is still an issue, short of going through every page. I'd like to close it and concentrate our issues for 3.0
