### ISSUE TITLE
Labels that refer to a non-existent control

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#520]
This happens when the FOR attribute doesn't exactly match a control ID, or targets a control NAME instead of a control ID.		

Problem pages:
* https://scholar-qa.uc.edu/collections/new line 237
* https://scholar-qa.uc.edu/collections/new?add_to_profile=true line 214
* https://scholar-qa.uc.edu/hydramata/groups/new lines 214 240
* https://scholar-qa.uc.edu/works/articles/new line 599
* https://scholar-qa.uc.edu/works/datasets/new line 560
* https://scholar-qa.uc.edu/works/documents/new line 581
* https://scholar-qa.uc.edu/works/generic_works/new line 558 619
* https://scholar-qa.uc.edu/works/images/new line 668

**Comment by lisa3711** [comment]
Closing this as well, as I tested pages above and did not get any errors related to above.
