### ISSUE TITLE
Pages with duplicate IDs which cause problems in screen readers

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#522]
Two or more elements on this page share the same ID, which cause problems in screen readers which use IDs for labeling controls and table headings. This also causes problems in JavaScript methods like getElementById and querySelector, which behave inconsistently when duplicate IDs are present. Change the ID so it is unique for each element.		

Problem pages:
* https://scholar-qa.uc.edu/catalog lines 534 538
* https://scholar-qa.uc.edu/hydramata/groups/new line 320
* https://scholar-qa.uc.edu/works/articles/new line 666
* https://scholar-qa.uc.edu/works/datasets/new line 627
* https://scholar-qa.uc.edu/works/documents/new line 648
* https://scholar-qa.uc.edu/works/generic_works/new line 625
* https://scholar-qa.uc.edu/works/images/new line 735

**Comment by lisa3711** [comment]
I checked these- and the line numbers are no longer valid. Will speak to Linda re getting another scan.

**Comment by lisa3711** [comment]
As stated above, I reviewed these pages and did not find any duplicate ID's.
