### ISSUE TITLE
Pages that have links to a PDF file should provide a link to download Acrobat Reader.

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#523]
You should include a link to download Acrobat Reader. When a web page requires that an applet, plug-in or other application be present on the client system to interpret page content, the page must provide a link to a plug-in or applet that complies with S1194.21(a) through (l).

**Comment by newmanld** [comment]
This seemed a little strange to me since most browsers are packaged with a PDF reader.  But this site says to provide a link to the 'accessible version' of Acrobat reader.  https://www.webaccessibility.com/best_practices.php?technology_platform_id=21
