### ISSUE TITLE
Can't add works to profile collection on QA

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#534]
While working to verify bug #330 I discovered that my profile on QA doesn't have any collections to add works to. After @scherztc wipes QA I'll try to replicate this.

**Comment by jamesvanmil** [comment]
From testing on dev (libhyddwl2), it looks like my profile collection is missing:

```ruby
> User.all.length
=> 2
> User.first.profile
  User Load (0.9ms)  SELECT `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1
=> #<Profile pid:"sufia:5q47rn79w", depositor:"scherztc@gmail.com", title:"Thomas Scherz", date_uploaded:Thu, 05 Nov 2015, date_modified:Thu, 05 Nov 2015, description:nil, creator:[], contributor:[], based_near:[], part_of:[], publisher:[], date_created:[], subject:[], resource_type:[], rights:[], identifier:[], language:[], tag:[], related_url:[]>
> User.last.profile
=> nil
```

**Comment by jamesvanmil** [comment]
@hortongn you've dealt a bit with accounts that didn't create properly - did you ever seen something like this?

**Comment by hortongn** [comment]
I haven't noticed this.  So you logged in via Shibboleth and experienced this?  What if you go to the local log in page https://scholar-dev.uc.edu/users/sign_in and and click the sign up link?  If you create a login that way is the profile there?

This can potentially be a bug in the Shibboleth code.

**Comment by jamesvanmil** [comment]
Just created a log manually - it looks like the profile was created.

Thomas just confirmed that he created his account on Dev with local login, not with Shibboleth.

**Comment by jamesvanmil** [comment]
Thomas just logged in with Shibboleth and confirmed the missing account.

**Comment by hortongn** [comment]
OK, I'll start looking into this.

**Comment by jamesvanmil** [comment]
I asked Jeff to log in today on production (since he didn't previously have an account) and we confirmed that the profile collection wasn't created

**Comment by hortongn** [comment]
I narrowed this bug down to missing content in the Person object.  When someone logs in via Shibboleth, the person and profile objects are created, but the person object is missing the hasProfile relation that points to the profile object.  So the application assumes there is no profile for that person and creates a new profile object when when the user edits their profile.

So the task now is to figure out why the relation is missing and how to fix it.  Should be a simple fix.

The good news is that we don't have a bunch of broken users in production Scholar.  Everything is fixed once they have saved their profile page.  We just have some extra, unattached profile objects that can eventually be removed.

**Comment by hortongn** [comment]
I've fixed this but I'm cleaning up the controller and making it a little easier to understand when we have to mess with it in the future.  One problem was that the profile was not being associated with the person.  The second problem was that the profile was not given edit rights by the user.  Shibboleth users will now see the "Add a section to my profile" button.
