### ISSUE TITLE
Make error notification emails configurable

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#538]
Off for: dev, qa

On for: production

**Comment by newmanld** [comment]
+1 – but after we do a quick review of the messages we’re now getting on QA to see if we learn anything from them?

**Comment by jamesvanmil** [comment]
They're all catching the same error, regarding invalid characters - no apparent value in examining the individual messages, yet

**Comment by hortongn** [comment]
Wouldn't we want the error emails on QA too?  If there's a problem we would want to catch it on QA (perhaps when running the test script) before deploying, right?

**Comment by jamesvanmil** [comment]
The test script would catch it without emails, because we're the users there - the value of deploying to production is in catching problems that our users are causing

**Comment by hortongn** [comment]
Right, but QA is configured to only return 404s via the gui when it encounters an error.  The emails might help us track down the actual error when the test script or Hailstorm is running.  It may save us from digging through log files.

Either way, I think making the emails configurable is an excellent suggestion.  We can decide which settings we use later.
