### ISSUE TITLE
Broken thumb for private file on public work

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#539]
A public work with only 1 file attached, *file access set to private*, shows a broken thumb in all views for non-owner.

**Comment by jamesvanmil** [comment]
We've replicated on Dev, but we're unable to replicate on QA.

Same workflow for both of these:

Dev: https://scholar-dev.uc.edu/works/articles/5q47rp55h
QA: https://scholar-qa.uc.edu/works/articles/jq089q948

Linda - can you replicate your steps on QA?
