### ISSUE TITLE
Removing a delegate doesn't remove delegate access to works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#54]
I ran though this on a local, fresh copy of Curate, so the PIDs below are not from Larry.

Overall, I think there are some fundamental problems with how the Delegate functionality was implemented, partly stemming from the two tiered Work<File structure of Curate submissions, and partly because both RELS-EXT and rightsMetadata are being used to record rights information. It's not clear to me how each of these is being used to provision access (I would probably need to do a much deeper dive into Hydra Access Controls and CanCan to understand those relationships).

I've bolded the comments below which I think represent problems in the implementation

Additionally, going back to the main issue which identified this problem, removing someone as a delegate shouldn't necessarily remove them as an editor. You may want to continue to collaborate with them. Should there be an option to allow them to retain access to your objects? 

---

Fresh curate dummy app with fresh jetty:

I've signed up James Van Mil and created an article

Fedora contains:

sufia:f7624c87n (Person - James Van Mil)
sufia:f7624c88x (Profile - James Van Mil)
sufia:f7624c896 (Article 1)
sufia:f7624c90z (Generic File 1)

I've signed up Foo Bar and assigned her as s delegate of James Van Mil.

Foo Bar ingested a new object. Fedora now also contains:

sufia:f7624c917 (Person - Foo Bar)
sufia:f7624c92h (Profile - Foo Bar)
sufia:f7624c93s (Article 2)
sufia:f7624c942 (Generic File 2)

Some interesting comments:
 * __Delegated Genric File (sufia:f7624c942) descMetadata indicates Foo Bar is the only creator - this is incorrect__
 * __Delegated Genric File (sufia:f7624c942) rightsMetadata indicates Foo Bar is the only editor - this is incorrect__
 * Delegated Genric File (sufia:f7624c942) properties indicate Foo Bar is the depositor - this is correct, but probably incidentally correct
 * Delegated Article (sufia:f7624c93s) descMetadata indicates James Van Mil is the only contributor - this is correct
 * Delegated Article (sufia:f7624c93s) rightsMetadata indicates James Van Mil and Foo Bar are both editors - this is correct (note that this isn't reflected in the interface)
 * Delegated Article (sufia:f7624c93s) properties indicates James Van Mil is the owner and Foo Bar is the depositor - this is correct
 * __Delegated Article (sufia:f7624c93s) RELS-EXT indicates that Foo Bar is the only editor - this is incorrect__

As James, I've removed Foo Bar as a delegate of James (which doesn't prompt any change in object metadata) and have tried to remove her as an editor, there was no change in the metadata.

Then tried removing Foo Bar as an editor and adding James (not previously explicitly listed), and RELS-EXT now lists both as editors.

As Foo Bar, then removed James as an editor, and now he's no longer able to edit the object that was submitted on his behalf. Additionally, James is now missing as an editor on rightsMetadata, and as an editor on RELS-EXT

**Comment by jamesvanmil** [comment]
Kick off worker?: al a https://github.com/uclibs/curate_fork/pull/22/files

**Comment by scherztc** [comment]
Created a remove_delegate_worker that launches when a delegate is removed from My Delegates.  This worker scan all works and attached files where the grantor is owner and grantee is an editor.  The worker then removes the grantee from editor access.

**Comment by hortongn** [comment]
Works as advertised.  Merged into develop branch.
