### ISSUE TITLE
Create new Welcome page for students

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#541]
See text  for new page below.  This has been vetted by D.R. T.F.   

This new welcome page will display, instead of the existing general welcome page, to those that UC Identity Management identifies as students, when
   first logging in (until checking the box to stop showing a Welcome page)
   when logged in, as a student, as the Welcome page linked to the drop-down Help menu.

If not logged in, or if logged but not identified as a student, the general welcome page linked to the Help drop-down menu should continue to display.

**Comment by newmanld** [comment]
## Welcome to Scholar@UC, UC Students
Welcome to Scholar@UC! On this page, you will learn how students can use Scholar@UC.

## What is Scholar@UC?
Scholar@UC is a digital repository that enables the University of Cincinnati faculty and staff to share research and scholarly work with a worldwide audience and preserve it for the future. It provides free access to material written, produced, and researched by the UC community.  Read more about the mission of Scholar@UC on the [About page](https://scholar.uc.edu/about_request). Get the latest updates on development of Scholar@UC on our [Scholarblog](http://libapps.libraries.uc.edu/scholarblog/).

## How can students use Scholar@UC?
Although only faculty and staff can submit content to Scholar@UC at this time, students can login and view material in the repository for research or classroom work. Scholar@UC is constantly growing and includes information like published articles, photographs, manuscripts, datasets, posters and much more.

In order to share scholarly output and creative works like capstone projects, students should work with a faculty member or advisor.

## How can I use material I find in Scholar@UC?
- **Is material in Scholar@UC copyrighted?** The material in Scholar is subject to a variety of copyright protections; just as when using material from other database and online sources, you will want to check on the copyright. When uploading material to Scholar@UC, submitters choose a content license or “access rights” for their content. An explanation of these licenses can be found on the [Creative Commons website](http://creativecommons.org/licenses/). Still confused about copyright?  See the UC Libraries’ [campus guide on copyright](http://guides.libraries.uc.edu/copyrightfair).
- **Citing materials in Scholar@UC:** Citing material in Scholar@UC is similar to citing resources found in other database and online. See the [campus guide on citing your sources](http://guides.libraries.uc.edu/citing).
- **Terms of Use:** For more information, see the Scholar@UC [Terms of Use](https://scholar.uc.edu/terms_request).

### Need Further Assistance? [Contact the Scholar@UC Team](https://scholar.uc.edu/contact_requests/new).

**Comment by newmanld** [comment]
Per discussion at the D.R. T.F.  @ntallman please also advise Content Working Group:

   Add very brief sentence referencing eTDs and the Graduate School at end of How Can Students Use Scholar@UC,  in same paragraph after "In order to share scholarly output and creative works like capstone projects, students should work with a faculty member or advisor."  Suggested: 
Graduate students should continue to work with the [Graduate School] (http://grad.uc.edu/student-life/etd.html) for submission of electronic theses and dissertations.    
    
   If not logged in, this page linked to the Help menu should be the general Welcome page:
https://scholar.uc.edu/welcome_page/new
   
   If logged in with a student identity, the Welcome page linked to the Help menu in this same position should be the Welcome page for students.

**Comment by hortongn** [comment]
provider: "shibboleth", uid: "sixplus2@uc.edu", ucstatus: "Student", ucdepartment: "Integration Services"

Rails console
 * ucstatus: Student

Rails Console set student
* u = User.last
* u.ucstatus = "Student"
* u.save

scholar_uc/app/views/welcome_page/_welcome_text.html.erb
