### ISSUE TITLE
Selecting facets causing search to be lost

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#546]
Start at scholar.uc.edu, and search for something, e.g., 'wall': https://scholar.uc.edu/catalog?utf8=%E2%9C%93&q=wall

When you select a facet, e.g., Image, the `q` param is lost: https://scholar.uc.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Image

**Comment by newmanld** [comment]
I just tried it with James' starting url - then choose image under Works - and query was not lost:
https://scholar.uc.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Image&q=wall&utf8=%E2%9C%93 

But - then I logged in, and I recreated the bug that James describes above.

**Comment by hortongn** [comment]
See https://github.com/uclibs/scholar_uc/issues/542#issuecomment-158208246

This may be a side-effect of our parameter sanitizing.

**Comment by 13miciunasl** [comment]
Checking an old commit shows that this was not an issue prior 12/1/2014, and is most likely caused by parameter sanitizing.
