### ISSUE TITLE
Collection show page - sort works by title

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#550]
As a Collection owner
   I want to be able to have the works in my collection display by default in alphanumeric sort order by title.
   So that the sort order is understood by users.
Done looks like:
    Works sort alphanumerically by title.  Ideally articles (A, An, The) should not determine the sort.  This can be English articles by default.  Articles can be language specific if a language other than English is specified in the descriptive metadata.

**Comment by newmanld** [comment]
Although not yet written up as a use case, submitted by content creator and a high priority for effective collection display.  I've verified with chair of Early Adopters Working Group that this is consistent with other use cases that should soon be written up relating to collections.

**Comment by newmanld** [comment]
If adding articles to a stoplist is a blocker, go ahead with alphanumeric sort order that includes articles and write up new issue for article stoplist.

**Comment by jamesvanmil** [comment]
@newmanld - do we want to apply the alphanumeric sort order to Profile collections, too?

**Comment by newmanld** [comment]
Yes, Profile collections should be sorted by title too – although if it is significant extra code, it would be justified to write this up as a separate issue.

**Comment by jamesvanmil** [comment]
Decided to write up as a new issue.
