### ISSUE TITLE
Add facets for College and Department, based on UC ID information for content owner

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#551]
As a user I want to see which works have been submitted associated with given colleges and/or departments

So that I can see the breadth and depth of contributions associated with academic structure.

Done looks like:  The college and department identified by UC Identity management for an owner of a work, collection or profile are used to create facets that appear after existing facets (Creator, Subject, Language, Publisher).

**Comment by newmanld** [comment]
I think that College and Department are recorded in one field in UC Identity Management (shibboleth)?  If so, we can experiment with - presenting as one facet - versus parsing the data into two facets.  Having this facet will be necessary for eTD import into Scholar@UC.

**Comment by hortongn** [comment]
Here are some examples of the college/department values for users in our production environment:

UCL Digital Collections & Repositories
A&S Anthropology
A&S Biological Sciences
A&S Biological Students
A&S History
CEAS - Energy
CEAS - Mechanical Eng
UCL CEAS Library (Engineering & App Sci)
UCL Archives & Rare Books Library
UCL Geolog-Math-Physics Library
UCL DAAP Library
UCL Electronic Resources
Professional Practice
A&F Field Operations Administration
A&F Housing & Food Svcs & Mainstreet Ops
Enterprise Application Services

**Comment by jamesvanmil** [comment]
Two notes on this:

* I've contacted HR about accessing the document which will give us all the department values across campus - after we have that I will work with the Metadata Group on how to map this data, and whether we'd like to create hierarchical facets.
* I also began to talk with the Metadata Group about how to handle changes - we agreed that we should attach the college and department facets to the works themselves, and set them with content from the owner on ingest. We haven't talked yet about how to handle changes in the owners college or department.

**Comment by jamesvanmil** [comment]
This is how you do pivot/hierarchical faceting: https://github.com/projectblacklight/blacklight/blob/1640c0cb4b1bd54c00c6ea647083e617dbb600d5/lib/generators/blacklight/templates/catalog_controller.rb#L78

**Comment by jamesvanmil** [comment]
Next step, wireframes:

1. using pivots and modals (folding?)
1. using pivots and no modals (and folding)
1. using colleges and departments
1. using colleges then departments

**Comment by jamesvanmil** [comment]
Okay some wireframes:

First the most complicated configuration, where you can click '+' to expand college facets to show 

![facets - most complicated](https://cloud.githubusercontent.com/assets/2651187/13306403/347e07d4-db31-11e5-9ad1-c16ad6a06b1b.png)
department:

And if you click *more Colleges >>*:

![facets - most complicated - modal](https://cloud.githubusercontent.com/assets/2651187/13306341/d281f0cc-db30-11e5-979f-5edfaa764e88.png)

This is also the most difficult layout, in terms of coding.

**Comment by jamesvanmil** [comment]
Next, the layout when the facets are staged, first *College* appears:

![facets - staged 1](https://cloud.githubusercontent.com/assets/2651187/13306419/6b7fdda2-db31-11e5-8d44-06f781088ea1.png)

Then *Department* also appears:

![facets - staged 2](https://cloud.githubusercontent.com/assets/2651187/13306421/778cf530-db31-11e5-9138-742aed976788.png)

And clicking *more...* on either would show a typical modal display.

**Comment by jamesvanmil** [comment]
Finally, a layout with both - I included a small help message on this layout:

![facets - non-staged](https://cloud.githubusercontent.com/assets/2651187/13306443/b444c7be-db31-11e5-9b99-1d5af96f28bd.png)

**Comment by jamesvanmil** [comment]
Per discussion today, we're going to:

* Use non-pivoted, staged approach
* Label the facets 'College' and 'Program/Department' (Linda will confirm whether this is okay to accommodate ETDs)
* Use a mapping to parse the terms provided by identity management to supply default values
* Set the facet field default values when we set up the form
* The fields will be editable only by the repository manager
* The fields will appear as un-editable string fields to an ordinary user
* The fields will be repeatable
* The fields will appear between Creator/Author and Description/Abstract fields in the work edit form
* The help information in the work edit form will briefly explain how these fields are populated
* The fields will be exposed as metadata on the work show form
* The person edit page will show contact instructions for reporting issues with the department field from identify management

**Comment by newmanld** [comment]
A variation to the point about the fields only being editable by the repository manager.  For the ETD work type only, which will be limited for input (and thus editing) to only the Graduate School login, when/if the Graduate School decides to do an online upload, we won’t be able to pre-populate the fields.  For the ETD work type only  we will want, I assume, to give to the Graduate School login only the ability to edit those fields.    See https://github.com/uclibs/scholar_uc/issues/387.

**Comment by jamesvanmil** [comment]
FYI here's a wireframe for the edit page - putting it here for later.

![college and department - work edit form](https://cloud.githubusercontent.com/assets/2651187/13647694/4163d8b6-e603-11e5-9530-0e4b2e17e9fa.png)

**Comment by jamesvanmil** [comment]
As work with the metadata working group proceeds, we're finding the OrgMaster data to be *very* messy, with a variety of departments that we likely wouldn't want to automatically add to the C&D facet metadata. I'm curious how the Research Directory have approached these sorts of questions, and whether we can use the data in the Research Directory to whitelist the C&D affiliations of our submitters.

**Comment by newmanld** [comment]
@jamesvanmil I think you'll see the same issue in Research Directory that you identified re differences in source data for Deans, ADs, and faculty.  Do a keyword search on 'Libraries' for example to see how people in our own org are described.    But we should touch base with Research Directory on this - I will send you contact in Slack.

**Comment by newmanld** [comment]
@jamesvanmil  - Please comment if this is up to date 
We are planning to pre-populate a department/program list (sometimes a department name, sometimes a program name) but allow the submitter to override with their own value not already in the list. 

We would not allow the submitter to override the name of the College.   

We will not show the Department facet in the interface until a College has been selected.

**Comment by jamesvanmil** [comment]
@newmanld that's the gist of things. Some of the nuanced challenges orient around how to handle departments (because in the case of COM, for example, there are over 500 values) and how to handle non-academic departments, as well as how to handle academic units which don't have an obvious college.

**Comment by newmanld** [comment]
@jamesvanmil - In the GUI, perhaps instead of a pre-populated list of >1000 values it should just be the department name associated with the owner/submitter, as provided to us by Shibboleth, with an opportunity for the submitter to override?  Otherwise we might have to provide a way to search the pre-populated list.  With this approach metadata librarians could also resolve variations on a post-coordinated basis?

**Comment by jamesvanmil** [comment]
Planning to proceed with this as a non-repeatable field. Will open a new issue for making it repeatable.

**Comment by jamesvanmil** [comment]
Because of some spec issues, we're implementing this as flat metadata. A nested solution should follow for Scholar 3.x
