### ISSUE TITLE
Find a new solution to include Scholar Blog posts on the home page

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#555]
The plugin we are using to pull in posts from the Scholar Blog RSS feed has been discontinued because Google has turned the API off.  We need a new solution to accomplish the same task.

**Comment by crowesn** [comment]
Latest indications show that Google Feed API service has been restored for the short term. John Mueller, Google Webmaster Trends Analyst, commented:
>The good news is that it's back, and we hope to keep it up & running! 
>The less-good news is that we haven't finalized a plan for the longer term. 
>We'll update here as we have more, but in the meantime, please do feel free to continue to use this API. 
[Source](https://developers.google.com/feed/forum?place=msg%2FGoogle-AJAX-Search-API%2FhAi_42yI_5w%2FcXarlM4qCQAJ)

I think the best course of action is:
1. Stick with the current implementation for now. Google staff have indicated that the feed will remain in service for the short term, while hinting at long-term plans for keeping it active.  
2. In case the Google API is terminated, jquery 1.5 can parse xml and we should be able to pull the feed without cross domain issues (the blog and our app are both on the uc.edu domain and share the same protocol). See [rss with jquery](http://stackoverflow.com/a/7067582).

**Comment by crowesn** [comment]
Played around with this and I've discovered that the straight jquery option will not work - the blog is not on https so we run into cross domain issues. 
Looking at implementing Feedjirra in the app following [Railscast pattern](http://railscasts.com/episodes/168-feed-parsing?view=asciicast)
