### ISSUE TITLE
Enable alphanumeric title sort in Sort By drop-down menu on the Catalog

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#573]
Partially replaces #561

**Comment by newmanld** [comment]
When viewing the catalog (from a browse or a search) the Sort By drop down menu does not apply and is not available when viewing 'All', but does appear when selecting Works, Collections, or People.   This issue would add 'title' to the list of sort options to Works and to Collections.  This has been expressed as a need by me and @ntallman for content currently being added to Scholar@UC.

**Comment by newmanld** [comment]
The 'People' could have a sort option for 'Name', but that should be in lastname, firstname order.  If/when this is considered, it can be written up as a separate issue.

**Comment by newmanld** [comment]
First step is to consider feasibility and whether this can fit into our Scholar 2.0 timeline - if not, change label to Scholar 3.0.

**Comment by newmanld** [comment]
If, in conjunction with #743, the drop-down menu is too long, consider removing 'date modified' while keeping 'date uploaded'.

**Comment by newmanld** [comment]
FYI see #225.  In addition to sort by title for works and collections, it may be possible/desirable to also add sort by title to the People tab, simply using the fact that Person Names are in the title index.  Ideally label should say name instead of title when viewing the People tab, but that may not be essential?

**Comment by jamesvanmil** [comment]
This should be easy by using a new index field just for sort (e.g., `catalog_sort_sim`) and adding the appropriate entry from each.

Question though: we're treating names as *FirstName LastName* for People, but the Creator for works is *LastName, FirstName* - this will make the sort behavior of names inconsistent, unless we put People names in the sort index as *LastName, FirstName*. Which is the lesser of two evils?

**Comment by newmanld** [comment]
I guess putting People names in the index as LastName, FirstName?  Seems that’s how users would expect a sort by name to work?
