### ISSUE TITLE
Rake solr:reindex not working

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#581]
It's queueing a worker, but nothing is being reindexed.

**Comment by jamesvanmil** [comment]
Probably will need to write a new task that runs ActiveFedora::Base.reindex_everything without a worker.

We also need to develop a method for running rake tasks as part of deploy.

**Comment by hortongn** [comment]
The current solr:reindex rake task is coming from https://github.com/projecthydra/sufia/blob/v3.4.0/sufia-models/lib/tasks/sufia-models_tasks.rake

**Comment by hortongn** [comment]
This is working in my local environment.  Will test it on QA on Thursday after Scholarcamp
