### ISSUE TITLE
Reserve DOI functionality

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#582]
We decided on this a little while ago - just remembering to open the issue...

EZID DOIs allow you set a status 'reserved' on new DOIs, which saves a pid without minting and promulgating the DOI. We want to implement this for embargoed/private works, only allowing DOI minting for accessible works.

We would also need to prevent people from changing works back to embargoed/private if they've minted a DOI, and a reserved DOI would need to be updated to minted if they switch to public.

**Comment by jamesvanmil** [comment]
Need to:

* modify hydra-remote_identifiers for updating (e.g., sending the request to an already created URI)
* add tracking about managing identifiers to work administrative metadata
* Clarify that DOIs for private/authenticated/embargoed works are 'reserved'
* Clarify that DOIs for public works may not be deleted
* Implement changing status to 'unavailable' for private/authenticated/embargoed/deleted works with managed DOIs (this will resolve to a tombstone generated by EZID)

**Comment by jamesvanmil** [comment]
@newmanld we previously agreed that we would restrict a work owner's ability to withdraw an item if they've minted a DOI, but as I work through this, I don't that we'll need to do that. In addition to the 'public' and 'reserved' statuses, there's also an 'unavailable' status, for which EZID will manage a tombstone page. This will be easier and friendlier to implement, so I'll plan to have our DOI status update to 'unavailable' for works with a 'public' status that are moving from open access back to restricted visibility.

**Comment by newmanld** [comment]
Seems totally appropriate if this is the mechanism (a tombstone page on EZID’s site) that meets DOI standards or best practices.

When we’ve implemented the changes for reserve DOIs or no longer unavailable DOIs, I wonder if we should add a general information page about DOIs – or more info in the FAQ – and/or tips that are linked to from the input and edit views – to explain these differences.

**Comment by jamesvanmil** [comment]
Yep - I've made some notes above about clarifying in the UI when a change in visibility will impact DOIs. I'm hoping to be able to do this in the input form, with a link to some FAQ content.

**Comment by jamesvanmil** [comment]
Here's what the tombstone looks like for one of my test objects. It does meet the requirements ber EZID's own guidelines:

![image](https://cloud.githubusercontent.com/assets/2651187/12680335/4507bcc2-c677-11e5-8b41-adb8b19311c2.png)
