### ISSUE TITLE
When you add a collection to your profile, it behaves like a profile section

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#584]
It doesn't not display like one, though, and probably shouldn't behave like one.

After adding the collection to profile:

![screen shot 2016-01-11 at 11 44 42 am](https://cloud.githubusercontent.com/assets/2651187/12239863/c73e994a-b858-11e5-99f2-1e95ca1b0288.png)

From profile page:

![screen shot 2016-01-11 at 11 43 38 am](https://cloud.githubusercontent.com/assets/2651187/12239877/d0c2047a-b858-11e5-9280-b79da99b81c0.png)

**Comment by scherztc** [comment]
With Scholar 3 you can't highlight a collection on your profile.  Can't recreate the problem.
