### ISSUE TITLE
Video Work Type:  Design and Implement Large File Ingestion for videos

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#593]

**Comment by scherztc** [comment]
In the Fedora 3 Hydrasphere there are four common implementations of large file support.

1. WGBH:  Create upload paths for each user on the web server.  Allow FTP access to those upload paths.  Modify the flie uploader inside of the application to see the \upload\username.  Keep file in Fedora and use current datastreams.  Analysis:  We might like a modified version of this if browse_everything handles most files

2. Duke:  Uses Jquery uploader to save file in remote location.  Adjusts content datastream and DownloadBehavior controller to see remote location.  Analysis:  This solution looks very difficult to integrate.  I think Duke was building a complete hydra head around this idea and not integrating it into a current repository.

3.  Amherst:  Uses HTML5API with client-side chunking of the large file through resumable.js and JQuery uploader.  Analysis:  This solution has the least dev ops over-head and would integrate well.  Not sure if it will be able to handle 100 GB files.  

4.  Browse_Everything:  Many believe that browse_everything has native large file support built into, since it doesn't use POST to get files.  Analysis:  This is untested and we would need to explore some of it's limits

**Comment by scherztc** [comment]
![img_3955](https://cloud.githubusercontent.com/assets/5084562/13468011/bcd00690-e06e-11e5-8ff5-768f5e148baa.jpeg)

**Comment by scherztc** [comment]
![img_3955](https://cloud.githubusercontent.com/assets/5084562/13468062/eb12d492-e06e-11e5-9ae0-f9e866b0045f.jpeg)

**Comment by hortongn** [comment]
Work will continue on this in issue #657
