### ISSUE TITLE
Research/Develop method for batch input into Fedora

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#599]

**Comment by newmanld** [comment]
See this information about batch adding objects from a CSV file (I assume this is to Sufia but that the scripts could be re-purposed for us.)

Quoting from https://groups.google.com/forum/#!topic/hydra-tech/5Ra14_7IIwo

> Here's an example of batch adding objects from a CSV file:
> 
> https://github.com/curationexperts/alexandria-v2/blob/master/bin/ingest-csv
> https://github.com/curationexperts/alexandria-v2/blob/master/lib/importer/csv_importer.rb
> https://github.com/curationexperts/alexandria-v2/blob/master/lib/importer/csv_parser.rb
> https://github.com/curationexperts/alexandria-v2/blob/master/lib/importer/factory.rb
> https://github.com/curationexperts/alexandria-v2/blob/master/lib/importer/factory/image_factory.rb
> https://github.com/curationexperts/alexandria-v2/blob/master/lib/importer/factory/object_factory.rb
>

**Comment by newmanld** [comment]
And from same thread, response from U. of Alberta:
Quoting from https://groups.google.com/forum/#!topic/hydra-tech/5Ra14_7IIwo

> We at University of Alberta has developed a batch ingest script from csv file, or any file format that can be transferred to JSON. And our script is at:
> https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/batch.rake
> We have also developed a script that would do batch ingest through Fedora 3' FOXML, but it's a pretty tailored solution to our particular IR case. 
>

**Comment by hortongn** [comment]
There may be good info here on batch/csv import into Hydra apps:
https://groups.google.com/forum/#!topic/hydra-tech/9oG4uZoBLsw

**Comment by jamesvanmil** [comment]
I've come up with the following for Rails Console work creation, with files:

```ruby
include ActionDispatch::TestProcess

cc = Article.new ## or whatever worktype
u = User.first ## or whatever user

attributes = {
  "files"=>
    [(fixture_file_upload 'log/development.log', 'image/png')],
  "linked_resource_urls"=>"",
  "title"=>"Butts",
  "creator"=>["1, User", ""],
  "college"=>"Other",
  "department"=>"Unknown",
  "abstract"=>"test",
  "publisher"=>[""],
  "date_created"=>"",
  "alternate_title"=>[""],
  "journal_title"=>[""],
  "issn"=>[""],
  "subject"=>[""],
  "coverage_spatial"=>[""],
  "coverage_temporal"=>[""],
  "language"=>[""],
  "bibliographic_citation"=>"",
  "requires"=>"",
  "note"=>"",
  "existing_identifier"=>"",
  "doi_assignment_strategy"=>"not_now",
  "editors_attributes"=>{"0"=>{"id"=>"sufia:t435hw65w", "_destroy"=>""}, "1"=>{"id"=>"", "_destroy"=>"", "name"=>""}},
  "editor_groups_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"", "title"=>""}},
  "visibility"=>"open", 
  "embargo_release_date"=>"", 
  "readers_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"", "name"=>""}}, 
  "reader_groups_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"", "title"=>""}},
  "rights"=>"All rights reserved"
}

CurationConcern.actor(cc, u, attributes).create
```

Seems to check out, even though I'm using a test class to stand in for the file upload. Would be easy to integrate into a GUI interface, or into a rake task. @newmanld @ntallman lets talk about balancing workflow features and development expediency.

**Comment by jamesvanmil** [comment]
* verifying checksums - after ssh, check that they match

**Comment by jamesvanmil** [comment]
My work to date on batch satisfies this.
