### ISSUE TITLE
Integrate ND Orchid gem

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#600]

**Comment by jamesvanmil** [comment]
First step is to begin design process

**Comment by crowesn** [comment]
I requested a key to the orcid sandbox api, using our integrations gmail account.

**Comment by hortongn** [comment]
See the commits below to see how Notre Dame integrated ORCID into their Curate.  The commits are in order with the first step at the top.

Adding orcid gem (This required updating devise.)
https://github.com/ndlib/curate_nd/commit/8565d727bca0387c946586b662c95331b3b11a5c

Installing orcid gem ($ rails generate orcid:install)
https://github.com/ndlib/curate_nd/commit/2025b18e1f562ac3c5969896905994a20e432192

Adding devise_multi_auth migrations ($ rake devise_multi_auth:install:migrations; $ rake db:migrate)
https://github.com/ndlib/curate_nd/commit/ea4c3412a96fa28e0b856882144a67073a603f17

Updating behavior to incorporate ORCID
https://github.com/ndlib/curate_nd/commit/9b8858455cbec105482432699e83296372b61cac

Working on CurateND with Orcid integration
https://github.com/ndlib/curate_nd/commit/6fbedc962df518ddf08bb907794cb8a65e7c91d0

Adding keys to the sandbox
https://github.com/ndlib/curate_nd/commit/84337e49e3af79995725ba3f97c0f34775398836

Adding ORCID with "verified" end to end behavior
https://github.com/ndlib/curate_nd/commit/224765bdf73cd0aede1b44f4ab7c0555e7af1d10

**Comment by hortongn** [comment]
The GitHub repo where integrated ORCID into Sufia can be found here:
https://github.com/ndlib/sufia_orcid/commits/master
