### ISSUE TITLE
EmbargoMailer doesn't apply to files coming out of embargo

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#613]
I believe we're sending emails only when Works are coming out of embargo - should we also consider Files coming out of embargo?

I can't recall whether this was intentional, or an omission in our design of this feature.

@newmanld - any thoughts on this?

**Comment by 13miciunasl** [comment]
@jamesvanmil Are you sure it doesn't apply to files? I thought I remember getting multiple emails every time I tested the mailer

**Comment by jamesvanmil** [comment]
Yeah I think you're right - I saw `work` [here](https://github.com/uclibs/curate/blob/develop/lib/tasks/embargo_manager.rake#L14) and thought it was limited - I see now that it's grabbing anything with the embargo date.
