### ISSUE TITLE
Fixing the profile hiding bug in the gem causes tests in the app to fail

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#625]
The fix we implemented for #553 in the Curate gem is breaking six tests in the application.  This didn't get noticed earlier because the application had not been tested against the updated version of the gem.

By fixing the profile hiding problem, some tests in the application no longer see a profile a user that does not have any works.  So the tests need to be revised.

**Comment by hortongn** [comment]
For an example of the failing tests see https://travis-ci.org/uclibs/scholar_uc/builds/108410572

**Comment by scherztc** [comment]
Closed with PR #621.
