### ISSUE TITLE
Add JP2 support to ImageMagick

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#626]
From Glen:

> A quick look seems to indicate that the version of ImageMagick that gets installed via the RedHat package doesn’t have proper JP2 support.  Looks like we need to download and compile ImageMagick with JP2 support turned on.

There was a failed characterization job for this file: https://scholar.uc.edu/works/files/wm117p39x

IT@UC help is needed with making this change on production web servers.

**Comment by hortongn** [comment]
A possible solution for us:
http://btmash.com/article/2014-05-12/installing-imagemagick-jp2-support-centos

**Comment by scherztc** [comment]
@jamesvanmil... Trying to determine the scope of this issue.  I was able to successfully upload this file :  There was a failed characterization job for this file: https://scholar.uc.edu/works/files/wm117p39x to https://scholar-dev.uc.edu/works/files/wp988k21z and didn't notice any characterization fails in : https://scholar-dev.uc.edu/admin/queues/failed

**Comment by scherztc** [comment]
Now I see it :  Worker
libhyddwl2:4268 on CHARACTERIZE at just now Retry or Remove
Class
 Sufia::Resque::MarshaledJob
Arguments
--- |
  BAhvOhRDaGFyYWN0ZXJpemVKb2IGOglAcGlkSSIUc3VmaWE6d3A5ODhrMjNo
  BjoGRVQ=
Exception
MiniMagick::Error
Error
Command ("identify -quiet -ping /tmp/mini_magick20160302-27147-16u87fh") failed: {:status_code=>1, :output=>"ICC Profile CS 52474220\nidentify: missing image channel `/tmp/mini_magick20160302-27147-16u87fh' @ error/jp2.c/ReadJP2Image/415.\n"}

**Comment by scherztc** [comment]
Mark Bussey has an issue:  https://github.com/curationexperts/goldenseal/issues/104

**Comment by newmanld** [comment]
See https://groups.google.com/forum/#!topic/hydra-tech/XO6muzsf7ks   per vulnerability announced here
https://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=29588
https://imagetragick.com/   - 

more reasons to compile custom version of ImageMagick with not only better jp2 support but the patch to configuration as recommended here?

**Comment by hortongn** [comment]
Procedure for compiling ImageMagick with JP2 support:
(note: we must use ImageMagick 6.8.7-10 to use jasper for JP2 support)

1. wget https://www.imagemagick.org/download/releases/ImageMagick-6.8.7-10.tar.xz
1. wget ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/6.7/x86_64/os/Packages/jasper-devel-1.900.1-16.el6_6.3.x86_64.rpm
1. sudo yum remove ImageMagick
1. sudo yum install jasper jasper-libs libtool-ltdl-devel
1. sudo yum install jasper-devel-1.900.1-16.el6_6.3.x86_64.rpm
1. tar -xf ImageMagick-6.8.7-10.tar.xz
1. cd ImageMagick-6.8.7-10
1. ./configure --prefix=/usr --with-modules --with-perl=/usr/bin/perl --with-jp2 --enable-shared --disable-static --without-magick-plus-plus
1. make
1. sudo make install
1. sudo ldconfig /usr/lib

**Comment by hortongn** [comment]
@scherztc At some point can you test conversion of JP2 images you know have been problematic?  The QA web servers should have an ImageMagick that can handle this format.  Once we know QA is fine we can roll out to other servers.

**Comment by hortongn** [comment]
ImageMagick is still failing on the thumbnail for JP2:

`Command ("identify -quiet -ping /tmp/mini_magick20160603-5611-hq5ucc") failed: {:status_code=>1, :output=>"ICC Profile CS 52474220\nidentify: missing image channel /tmp/mini_magick20160603-5611-hq5ucc' @ error/jp2.c/ReadJP2Image/421.\n"}`

**Comment by scherztc** [comment]
This is solved with Scholar 3. Can't replicate problem.
