### ISSUE TITLE
New Help Page: Documenting Data

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#628]
Per the Digital Content Working Group.

Page Title: Documenting Data
Page Location: Insert, alphabetically, into Help menu

Please also add the following [bootstrap warning alert](http://getbootstrap.com/2.3.2/components.html#alerts) to the Dataset work-type input form: "Please read the [Documenting Data](#) help page before submitting a dataset to Scholar@UC."

--------------------------------------------------

# Documenting Data

<blockquote>&ldquo;Data without context are inert, but data within contexts become information, knowledge.&rdquo;<br/> 
From: Changing the Subject: Art and Attention in the Internet Age By Sven Birkerts</blockquote>

Proper documentation provides the context that your data needs to persist through time, to integrate into new systems and to give you credit for your contributions in the form of data citations.  Where possible, you should contribute the following information along with your dataset:

1. **Complete Metadata** – Metadata aids Discovery and Reuse.  Scholar@UC requires metadata such as title of work, creator name, data submitted and description.  All text is searchable.  You should write a detailed description to increase discoverability of your content.  Also provided are additional metadata fields under the Show Additional Description link.  Here you can add in additional fields such as subject terms for search enhancement.  If you are following a suggested schema for your discipline, indicate that in the description or in the next document – the README file.

2. **README.txt File** – This is a text document that provides relevant information such as purpose of the project and the organizational structure or relationship of the files.  It explains terms that are unique to the dataset, keywords, omissions and errors.  If you are using a file naming convention, you can explain it in the readme file.  It is also the place to put additional details that were not included in the metadata, such as additional information about external storage of the data, metadata schema followed and researcher contact information.

	a. A good example can be found in the [Data ab Initio blog post README.txt by Kristin Briney](http://dataabinitio.com/?p=378) 

3. **Data Dictionary/Codebook** – This document explains all the variables and abbreviations associated with the dataset. 

	a. Links below to data dictionaries from The University of Texas at Austin’s Population Research Center ([data dictionary examples](http://www.utexas.edu/cola/redcap/Project-Examples.php)) and IRSA ([data dictionary example](http://irsa.ipac.caltech.edu/applications/DDGEN/Doc/dd_tbl.html)) provide two quick examples of data dictionaries.  

4. **Methodology/Protocol** – This document details the steps taken to collect the data.  If you submitted modified data instead of a raw data set, you can explain those steps in this document.  

### Additional Resources on Documentation for Data:

1. [ICPSR's Guide to Social Science Data Preparation and Archiving](http://www.icpsr.umich.edu/icpsrweb/content/deposit/guide/index.html)
2. [DataOne Best Practices](https://www.dataone.org/best-practices) 
3. [Mantra Research Data Management Training](http://datalib.edina.ac.uk/mantra/) 
4. [DataDryad FAQ](http://datadryad.org/pages/faq)
5. [Digital Curation Centre How-to Guides & Checklists](http://www.dcc.ac.uk/resources/how-guides)

**Comment by 13miciunasl** [comment]
New help page is implemented in the app, but since curate has been giving me issues the bootstrap warning on the dataset page is NOT done

**Comment by jamesvanmil** [comment]
PR for content is merged - still need to resolve aspect of issue for linking to help info

**Comment by jamesvanmil** [comment]
@newmanld will chat with Nathan about the link to the to page from the dataset create form.

**Comment by newmanld** [comment]
@jamesvanmil - I talked to @ntallman .  We can proceed with the alternate plan for a link (that does not use bootstrap warning alert) to the Documenting Data page from the Dataset work input form.  We should share a screenshot or otherwise provide access to @ntallman to the change in development on the input form.

**Comment by jamesvanmil** [comment]
Thanks! @ntallman what do you think about adding the message in the whitespace under "Submit Your Dataset" and before "Add Your File"?

<img width="1127" alt="screen shot 2016-03-31 at 12 40 05 pm" src="https://cloud.githubusercontent.com/assets/2651187/14183333/ceb967da-f73d-11e5-82ff-848317a16ccb.png">

**Comment by 13miciunasl** [comment]
Here are the first options that I spun up for the page design. Let me know how you feel about them (anyone)

![screen shot 2016-04-04 at 2 51 40 pm](https://cloud.githubusercontent.com/assets/9759017/14259670/ea36164e-fa75-11e5-90d2-061634414005.png)
![screen shot 2016-04-04 at 2 54 20 pm](https://cloud.githubusercontent.com/assets/9759017/14259672/ea3742e4-fa75-11e5-99fa-bb81ed903239.png)
![screen shot 2016-04-04 at 2 57 48 pm](https://cloud.githubusercontent.com/assets/9759017/14259671/ea36e1d2-fa75-11e5-8349-27726811ebba.png)
![screen shot 2016-04-04 at 2 58 05 pm](https://cloud.githubusercontent.com/assets/9759017/14259673/ea38687c-fa75-11e5-951d-59a64c1f1e13.png)

**Comment by ntallman** [comment]
The 4th option is my preference. Is the white space above/below it because it's an a header tag? I think it could be tightened up a bit. Thanks @13miciunasl!

**Comment by 13miciunasl** [comment]
I tightened it up a bit, but I think the two headers its sandwiched between cause the large white spaces
![screen shot 2016-04-04 at 3 23 25 pm](https://cloud.githubusercontent.com/assets/9759017/14260421/7409eb18-fa79-11e5-91d1-57da4f6a6b34.png)
![screen shot 2016-04-04 at 3 23 41 pm](https://cloud.githubusercontent.com/assets/9759017/14260422/740b845a-fa79-11e5-9512-09497f7b5d2f.png)

**Comment by newmanld** [comment]
I think the option @ntallman identifies, with the white space tightened, should be our starting place.  Let's see it on the screen in stand-up or swarm, just to be sure that the font size of the new text looks appropriate, and is mobile-friendly.

**Comment by 13miciunasl** [comment]
Here's two more styling options. At this point I don't think I can get rid of the extra white space without making major changes to the design of the page. If you don't like the way it looks because of that I can try out other places to put the text?
![screen shot 2016-04-05 at 10 47 40 am](https://cloud.githubusercontent.com/assets/9759017/14287671/9d200c14-fb21-11e5-99fe-d18ec17d05f4.png)
![screen shot 2016-04-05 at 10 48 18 am](https://cloud.githubusercontent.com/assets/9759017/14287672/9d207f28-fb21-11e5-88cf-05d4eb506c0a.png)

**Comment by ntallman** [comment]
@13miciunasl Lukas, can you try the second option, but instead of a line of text, put it in a header tag? Probably one size smaller than what "Submit Your Dataset" is. As normal text, I think it will be overlooked, even if it's bold or italicized.

**Comment by 13miciunasl** [comment]
Like this?
![screen shot 2016-04-05 at 11 47 50 am](https://cloud.githubusercontent.com/assets/9759017/14288352/47148ce8-fb24-11e5-8b17-dc495690f3ff.png)

**Comment by ntallman** [comment]
+1! Thanks!

**Comment by newmanld** [comment]
+1

**Comment by crowesn** [comment]
I wasn't paying attention while this was being developed but this seems little loud on the app. Is this going to be temporary?

<img width="1188" alt="screen shot 2016-04-11 at 12 29 52 pm" src="https://cloud.githubusercontent.com/assets/1069588/14434580/9142ffb8-ffe1-11e5-857b-5b06080fd18f.png">

**Comment by 13miciunasl** [comment]
For your viewing pleasure: 
![screen shot 2016-04-11 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/9759017/14436260/d98140de-ffe9-11e5-8db1-b4184373c9eb.png)
![screen shot 2016-04-11 at 1 32 02 pm](https://cloud.githubusercontent.com/assets/9759017/14436259/d980c9ec-ffe9-11e5-915d-450593585661.png)

**Comment by crowesn** [comment]
Can you push the yellow to your branch and I'll fire it up in the app?

**Comment by crowesn** [comment]
lol we're overriding all of the bootstrap alert classes and turning them grey. What do you think? 

![screen shot 2016-04-11 at 2 07 40 pm](https://cloud.githubusercontent.com/assets/1069588/14437385/ea4a5220-ffee-11e5-9fb8-740ac0c546e2.png)

**Comment by crowesn** [comment]
![screen shot 2016-04-11 at 2 25 41 pm](https://cloud.githubusercontent.com/assets/1069588/14437870/51962d9e-fff1-11e5-9f4f-47a883ee20b8.png)

**Comment by lisa3711** [comment]
Not to jump into the fray, 

<de-cloaking>

…but do they have to read that before submitting a dataset? I am thinking of the Dean’s directive to add more content and make it as easy as possible (the 5 minute survey vs the 15 survey example he gave).

With that in mind, I might change the language to  something along the lines of “For assistance in submitting a dataset… yada yada” , or “For more information…"

</de-cloaking>
<cloak>

**Comment by ntallman** [comment]
I prefer the yellow alert.

Lisa, regarding your comment, I feel very strongly that people do need to read it before submitting a dataset. Datasets need a high amount of curation to be useful into the future. If we make the bar too low for datasets and people upload raw datasets in unusable forms, we may be adding content, but it's not meaningful content that is really carrying the intellectual object into the future. It totally bypasses our mission for Scholar@UC. Most libraries to now allow self-deposit of datasets for this reason.

**Comment by lisa3711** [comment]
Thanks Nathan- Good to know!

**Comment by ntallman** [comment]
I've talked to the Research Services SI folks about the language we are using on the dataset work type to promote the Documenting Data page. They suggest the following language:

"If you would like guidance on submitting a dataset, please read the [Documenting Data](https://scholar.uc.edu/data_help_request) help page."

**Comment by lisa3711** [comment]
Like that language!

**Comment by newmanld** [comment]
Let's go with this revised language for the message.
