### ISSUE TITLE
Research Blacklight handling of RSS/XML

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#630]
Need to develop a way to generate RSS feeds for works in Scholar.
#204 sitemaps will be generated via. sitemap_generator, need a similar process for RSS

**Comment by lawhorkl** [comment]
http://ruby-doc.org/stdlib-2.0.0/libdoc/rss/rdoc/RSS/Maker.html might be a good possibility.

**Comment by jamesvanmil** [comment]
Changed issue title from: "develop a way to generate rss feeds"

**Comment by jamesvanmil** [comment]
Some notes here about Blacklight and RSS here: https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View

Further, we may need to talk more directly to Solr, and use responses to publish RSS or OAI fields.

**Comment by scherztc** [comment]
We have an RSS FEED in Scholar 3.
