### ISSUE TITLE
Stop trying to process (FFMPEG) uploaded videos

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#644]
Failed resque job related to .avi

Error
Unable to execute command "ffmpeg -i "/tmp/sufia:wp988k08d-content.020160217-25079-4cbr4.avi" -s 320x240 -vcodec libvpx -acodec libvorbis -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100 /tmp/sufia20160217-25079-15fr15m.webm" FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers built on Jan 29 2012 17:52:15 with gcc 4.4.5 20110214 (Red Hat 4.4.5-6) configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --enable-avfilter --enable-avfilter-lavf --enable-libdc1394 --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab libavutil 50.15. 1 / 50.15. 1 libavcodec 52.72. 2 / 52.72. 2 libavformat 52.64. 2 / 52.64. 2 libavdevice 52. 2. 0 / 52. 2. 0 libavfilter 1.19. 0 / 1.19. 0 libswscale 0.11. 0 / 0.11. 0 libpostproc 51. 2. 0 / 51. 2. 0 [avi @ 0xd6e670]Could not find codec parameters (Video: IV41 / 0x31345649, 256x240) /tmp/sufia:wp988k08d-content.020160217-25079-4cbr4.avi: could not find codec parameters

**Comment by hortongn** [comment]
I suspect we will need to compile our own version of ffmpeg instead of using the default.  I bet certain things we need are not built into the version we are using.  Just a guess.

**Comment by hortongn** [comment]
These are all of the optional components DCE uses when they are compiling a version of ffmpeg for Hydra: https://github.com/curationexperts/ansible-hydra/blob/master/roles/ffmpeg/tasks/main.yml

**Comment by hortongn** [comment]
Below is the latest error we received when ffmpeg tried to process a video in Scholar.  The **Unrecognized option 'b:v'**  error indicates that our ffmpeg version is out date.  Scholar is trying to use options that don't exist in the current ffmpeg version.  

Also, when we compile our own version of ffmpeg, we should enable the following options: `--extra-libs="-ldl" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264`

Unable to execute command "ffmpeg -i "/tmp/sufia:vh53wv75j-content.020160511-28616-4ktbo7.avi" -s 320x240 -vcodec libvpx -acodec libvorbis -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100 /tmp/sufia20160511-28616-10gin94.webm" FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers built on Jan 29 2012 17:52:15 with gcc 4.4.5 20110214 (Red Hat 4.4.5-6) configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --enable-avfilter --enable-avfilter-lavf --enable-libdc1394 --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab libavutil 50.15. 1 / 50.15. 1 libavcodec 52.72. 2 / 52.72. 2 libavformat 52.64. 2 / 52.64. 2 libavdevice 52. 2. 0 / 52. 2. 0 libavfilter 1.19. 0 / 1.19. 0 libswscale 0.11. 0 / 0.11. 0 libpostproc 51. 2. 0 / 51. 2. 0 Input #0, avi, from '/tmp/sufia:vh53wv75j-content.020160511-28616-4ktbo7.avi': Duration: 00:07:46.66, start: 0.000000, bitrate: 43381 kb/s Stream #0.0: Video: rawvideo, pal8, 512x352, 30 tbr, 30 tbn, 30 tbc Unrecognized option 'b:v'

**Comment by hortongn** [comment]
We need to discuss if we actually need ffmpeg for anything.  It's trying to run when we ingest a video, but we don't necessarily need to derivatives it wants to create.

**Comment by scherztc** [comment]
@hortongn Did we ever get this solved with AVI files in production?

**Comment by hortongn** [comment]
@scherztc Yes, this is no longer a problem for us.  Closing this issue.
