### ISSUE TITLE
Clickable Thumbnail on the Catalog Browse View

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#645]

**Comment by jamesvanmil** [comment]
It should link to the show page for the work.

**Comment by jamesvanmil** [comment]
To implement:

Copy the `title_link_target` assignment from the `_identifier_and_action` partial: https://github.com/uclibs/curate/blob/4d4fe09430b09182520d89c38bc08146704fcf8b/app/views/catalog/_index_partials/_identifier_and_action.html.erb#L2

Put it at the head of the `_thumbnail_display` partial: https://github.com/uclibs/curate/blob/develop/app/views/catalog/_index_partials/_thumbnail_display.html.erb

Then, where the `_thumbnail_display` partial is invoked for for people and collections, add an additional local for `title_link_target` (or `image_link_target`, if you rename it), setting it to the person or collection. See the example from where `_identifier_and_action` is invoked: https://github.com/uclibs/curate/blob/4d4fe09430b09182520d89c38bc08146704fcf8b/app/views/collections/_collection.html.erb#L6

Finally, wrap the image tags in the `_thumbnail_display` with link tags, using the `image_link_target` as the path for the link.

**Comment by crowesn** [comment]
I've got the feature working on this [branch](https://github.com/uclibs/curate/compare/feature/%23645-clickable-thumbnail).
Specs are still failing, will work with @jamesvanmil to resolve.
