### ISSUE TITLE
Send email to any new delegates, editors or members of groups

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#649]
As a submitter, I want to know if another submitter adds me as a delegate, an editor, or as a member of a group.  (Feedback from Scholar Camp 2016-03-02)

Done looks like: I receive an appropriately worded email whenever I have been added as a delegate, editor or member of a group, telling me the contact information of the person who assigned these rights to me, and the contact info for Scholar@UC if I have questions.

**Comment by lawhorkl** [comment]
![image](https://cloud.githubusercontent.com/assets/12615997/14642456/7dd2dd1c-0618-11e6-96a1-389692e337ce.png)

**Comment by lawhorkl** [comment]
To do list:
------------------
1.) Plan out model and the properties it needs
2.) Plan out controller and the actions that will be needed
3.) Research https://github.com/resque/resque-scheduler
3.) Generate, and populate both
4.) Test, test, test, test
5.) Look into separating this functionality into a gem

**Comment by lawhorkl** [comment]
idea for delaying emails: 

using resque-scheduler, make a property `initial-change` in the model that is set by the controller. The controller then launches a worker that, after N minutes checks that property. You then have an inverse action that can set that property to a predefined value to signify that the change was cancelled. In the worker checkin the property, if the change shows cancelled, the worker terminates. Else it tells the controller to send the email

**Comment by lawhorkl** [comment]
Gem name: resque-notify
Controller name: NotificationController
Model name: NotificationCache?

**Comment by jamesvanmil** [comment]
Call the model `Notifications` - that follows rails conventions

**Comment by jamesvanmil** [comment]
Actually just `Notification`

**Comment by lawhorkl** [comment]
@newmanld I figured I would give you a short update on the status of this issue: I've made the gem and went through the tests. The gem has been integrated successfully into Scholar and is performing well on a live test in Larry. If you wish you may preview it yourself at larry.libraries.uc.edu:3012 . 

Two blockers remain on this issue: 1.) Refactoring the process on which editors are assigned to works and 2.) Feedback and making the email format acceptable for the content management guys. @jamesvanmil and I have slightly deferring ideas about how to go about formatting the actual email however that is something I look forward to discussing with you when you get back. As for 1.) I will be continuing work on this blocker tonight and tomorrow and am optimistic of being able to have this finished by next week.

**Comment by newmanld** [comment]
@ntallmann - please see the note above and let us know if the Content Working Group can give @lawhorkl guidance on the content of this email.  Thanks!

**Comment by lawhorkl** [comment]
Here is a screenshot of how the email looks currently - Keep in mind I have not spent any time making it pretty as I hadn't gotten input from you guys yet.

![image](https://cloud.githubusercontent.com/assets/12615997/15482102/ed781ada-20fb-11e6-978b-950157a1de23.png)

**Comment by ntallman** [comment]
@lawhorkl the screenshot you have shows an ellipses which usually means some of the content is hidden.  Is there anything else in the message? Once I know the message is complete, I'll send it to the Digital Content Working Group. However, I can anticipate that we will want the message more customized. (e.g. Dear Jane, John Doe has added you as an editor of "The Smith Valey Forge Con" on Scholar@UC. You may edit this work at this <link> or by viewing "My Works" from the menu. Sincerely, Scholar@UC.)

**Comment by lawhorkl** [comment]
If you're referring to those three "dots" my gmail hides parts of emails that are the same as previous emails.

In this screenshot I expanded it so that you could see the full email. The message is complete.

Thanks!

**Comment by ntallman** [comment]
@lawhorkl The Digital Content Working Group has drafted three emails, one for each editor, delegate, and group. See [this google doc](https://docs.google.com/document/d/1QFL8n2uZ8t0UTgWi5hlpiUiGggVunfhdt468RNHKHUM/edit?usp=sharing) and let me know if you have questions.

**Comment by jamesvanmil** [comment]
I restructured the emails a little to allow related changes to be grouped into single emails.

**Comment by lawhorkl** [comment]
I've finally got everything situated with the emails how Nathan would like them formatted. There is still a small blocker in that I can't put a link to the works in the email, I'm assuming because of some include problem. I've hit my head on this for a few hours, if anyone would like to take a crack at it be my guest.

Once that is taken care of this should be ready to go.
