### ISSUE TITLE
Update CHANGELOG - **repeating issue**

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#652]

**Comment by hortongn** [comment]
Start of the changelog for 2.4:

* ORCID support: Users can now link their existing or new ORCID ID with their Scholar@UC profile.
* Use the new UC logo in the header
* Menu changes: Added guidelines for faculty advisors; added instructions for students and a new help page for student works; added accessibility information to the File Format Advice page; items in the Help menu are now sorted alphabetically.
* Prevent some trivial errors from generating notifications
* Bug fixes
    * DOIs can now contain square brackets without generating errors

**Comment by scherztc** [comment]
Closed by: https://github.com/uclibs/scholar_uc/pull/1165
