### ISSUE TITLE
Seed data automatically adds accounts and works when doing a db:reset

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#656]
The rake task we added to create accounts and works is automatically running when we do a db:reset to wipe QA.  QA needs to have no content when Hailstorm runs.  So we need to figure out how to exclude the seed data from being automatically added when QA is wiped.

**Comment by crowesn** [comment]
Instead of running ```db:reset```, I propose we break down that command and run the contained rake tasks separately, excluding ```db:seed```

i.e.
```
rake db:drop
rake db:create
rake db:migrate
```
[ref](http://stackoverflow.com/a/10302357)

**Comment by crowesn** [comment]
@hortongn Consider closing this?
