### ISSUE TITLE
Allow large files to be added to Fedora/Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#657]

**Comment by hortongn** [comment]
Copied one of Woodman's 100+ GB files to the DEV Fedora server and attempted to ingest it directly into Fedora.  After a couple of minutes Fedora returns the error "option --data-binary: out of memory".  I can see the free RAM on the server dwindle down to zero as Fedora attempts to ingest the file.  

So it's pretty clear that a Fedora server requires more RAM when attempting to ingest very large files.  I will attempt again with smaller files to see how large we can ingest with our current amount of RAM.

**Comment by hortongn** [comment]
Configuration changes needed to support ingesting large files:

On Fedora servers:
* Add the local IPv6 loopback address to the XACML policies.  This is needed to allow ingesting files from the command line on the Fedora servers (completed on QA already)
* Remove the deny-purge XACML policy.  This policy is preventing us from deleting content datastreams.  It will not have an effect on our soft delete configuration.  (completed on QA already)

On web servers:
* Adjust the fedora.yml file to include 'timeout' and 'open_timeout' options.  The settings can be '-1' for testing purposes, but we should agree on a reasonable timeout.  (temporarily set on QA)

**Comment by hortongn** [comment]
Procedure for ingesting files when they are too large to upload through the web interface.  This can be put into a script or adapted for batch ingest:

1. The user or the repository manager should create a work with the needed metadata.  

1. A "dummy" file should be attached to the work.  This could be any file, but it should be named the same as the permanent large file (example PID for purposes of these procedures will be *sufia:abcd1234* and example filename will *large_file.txt*)

1. Use SFTP or another method to copy the large file to a temporary location on the server (such as `/mnt/hydra/fedora/`)

1. On the Fedora server command line, delete the content datastream for the attached file object: 
    * `curl -i -XDELETE "http://localhost:8080/fedora/objects/sufia:abcd1234/datastreams/content" -u fedoraUser:fedoraPassword`
    * Replace sufia:abcd1234 with the actual PID.
    * Replace fedoraUser and fedoraPassword with the actual user and password.

1. On the Fedora server command line, upload the large file to the new content datastream:
    * `curl -i -H -XPOST -F file="@large_file.txt" -u fedoraAdmin:tesPdv4Vlr83l0yu "http://localhost:8080/fedora/objects/sufia:abcd1234/datastreams/content?dsLabel=large_file.txt&formatURI=&checksumType=SHA-256&altIDs=&mimeType=text/plain&controlGroup=M&versionable=true&dsState=A&flash=true"`
    * Replace sufia:abcd1234 with the actual PID.
    * Replace large_file.txt with the actual file name.
    * Replace text/plain with the actual MIME type for the type of file.
    * Replace fedoraUser and fedoraPassword with the actual user and password.

1. On one of the web servers, perform a Solr reindex.

1. On one of the web servers, enter Rails Console and re-characterize the large file
    * Sufia.queue.push(CharacterizeJob.new('sufia:abcd1234'))
    * Replace sufia:abcd1234 with the actual PID.

**Comment by hortongn** [comment]
Today UCit increased the RAM on the QA web servers from 4 GB to 8 GB each.  They also increased the RAM on the QA Fedora server from 8 GB to 12 GB.

After the RAM upgrades, I was able to successfully upload a 2.5 GB file using the web interface just like we would for smaller files.  I was also able to download that file back down to my computer.  The checksums for the original file and the downloaded file matched.

Before the RAM upgrade, uploading this same file resulted in a error.  So the upgrade has increased the size of files we can upload.  There are still some issues we need to address:

* Even though the file uploaded, the server still ran out of memory when it tried to characterize the 2.5 GB file.  UCit confirmed that they saw the QA web servers use up all available RAM while we were conducting our test.  The next step is for UCit to increase the web server swap space (virtual memory) to see if that allows the file to be characterized.

* During the file upload and then during the file download, there were pauses of several (5-8) minutes where the server did things in the background without giving any indication to the user that things were still being processed.  We need some way to alert the user to be patient.  This delay seems to be caused by the time it takes the application to transfer the large file from the web server to the Fedora server (or for downloads, from the Fedora server to the web server).  This delay could be very long for very large files.

* We probably still need to work with the JQuery uploader to optimize it for uploading large files (using chunking, etc.).  This could possibly dramatically reduce the memory requirements for uploads.

* Today's test only involves a single user uploading a single file.  Once we know how much RAM is needed to handle certain file sizes, we will need to figure out how many concurrent uploads we need to be able to handle.

**Comment by newmanld** [comment]
@hortongn - progress on identifying our pain points!

**Comment by hortongn** [comment]
Remaining todos:
1. Set the timeout: and open_timeout: values in fedora.yml
2. Continue testing with additional RAM and swap on QA

**Comment by hortongn** [comment]
On QA: 8 gigs of RAM and 132 gigs of swap are need for Fits to characterize a 32 GB file.

**Comment by hortongn** [comment]
May be able to tweak this file to customize which types or sizes of files we automatically characterize:
https://github.com/uclibs/curate/blob/develop/app/repository_datastreams/file_content_datastream.rb
