### ISSUE TITLE
files attached after work creation incorrectly set owners

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#667]
if you have a work and attach a file after work creation, it sets the owner of the file to the depositor of the work regardless of delegates.

**Comment by crowesn** [comment]
I found where the owner is being set for generic files 
https://github.com/uclibs/curate/blob/develop/app/services/curation_concern/generic_file_actor.rb#L33

The attach_file method takes a ```user``` argument for the current user, regardless of delegate status or ownership of the parent work. This makes me think that we probably have some files in production that are owned by delegates; will likely require some cleanup.
