### ISSUE TITLE
Delegates creating works have author as "firstname lastname"

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#672]
When delegates create a work, it populates the Author field with "firstname lastname" instead of "lastname, firstname."  This happens whether the delegate is creating a work on their own behalf or on behalf of the delegator.  This is probably a bug from when we split first and last names into separate fields.  For delegates it is probably still using the "name" field.

Once this is fixed, we will need to manually fix existing works that have the authors in wrong format.

**Comment by jamesvanmil** [comment]
Good catch - I think we can also depend on our metadata folks to make this change to older date.
