### ISSUE TITLE
Tiff mime:types not rendering thumbnail or viewer experience

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#676]
generic_file.image?

**Comment by hortongn** [comment]
We need to override this and add tif & tiff:
https://github.com/projecthydra/sufia/blob/v3.4.0/sufia-models/lib/sufia/models/generic_file/mime_types.rb#L31

**Comment by scherztc** [comment]
This works in Scholar 3.  Can't replicate problem.
