### ISSUE TITLE
Viewing a specific work generates an exception

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#677]
A specific work on production generates a exceptions when the show page is loaded:
https://scholar.uc.edu/works/images/zp38wd03j

The logs contain the error below when that page is viewed:

E, [2016-03-25T15:47:29.134664 #23837] ERROR -- : Curate caught a registered error: NoMethodError
	undefined method `pid' for nil:NilClass
	Backtrace:
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/helpers/curate_helper.rb:72:in `block in curation_concern_attribute_to_html'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/helpers/curate_helper.rb:60:in `each'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/helpers/curate_helper.rb:60:in `curation_concern_attribute_to_html'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/views/curation_concern/images/_attributes.html.erb:10:in `_vendor_bundle_ruby_______bundler_gems_curate_cf___ad___a__app_views_curation_concern_images__attributes_html_erb___3230231425721755034_70026624045940'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:278:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:47:in `render_partial'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:27:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/views/curation_concern/base/show.html.erb:8:in `_vendor_bundle_ruby_______bundler_gems_curate_cf___ad___a__app_views_curation_concern_base_show_html_erb___63910525893209960_70026683356820'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:17:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:42:in `render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:23:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:127:in `_render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/streaming.rb:219:in `_render_template'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:120:in `render_to_body'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:97:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:16:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
	/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/core_ext/benchmark.rb:12:in `ms'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:40:in `render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:233:in `default_render'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:161:in `to_html'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:154:in `respond'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:147:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/mime_responds.rb:330:in `respond_with'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/curate-cf124ad505a4/app/controllers/curation_concern/generic_works_controller.rb:95:in `show'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:533:in `_run__2661325574431115594__process_action__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/exception_notification-4.1.4/lib/exception_notification/rack.rb:32:in `call'
	/srv/apps/curate_uc/app/middleware/utf8_sanitizer.rb:32:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__2566297384743182588__call__callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block in call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:26:in `tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `tagged'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
	/srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
	/usr/lib/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by jamesvanmil** [comment]
As repository manager, I was able to get the file and review the metadata. Using the same, I failed to recreate the issues on QA.

Next step is to access rails console and invoke the helper that is throwing the error.

**Comment by jamesvanmil** [comment]
I've pinned down the error:

This line, which returns the name of the work owner, is returning `nil`: https://github.com/uclibs/curate/blob/4cfd320a4618d48a78d58ce10581fb83bdb3b26a/app/helpers/curate_helper.rb#L71

It's because caused because the work owner doesn't match the person depositor:

```ruby
> work.owner
=> "winslosr@mail.uc.edu"
> user.depositor
=> "winslosr@ucmail.uc.edu"
```

I'm not sure how this came about, but I suspect it has something to do with migrating accounts for shibboleth. @newmanld was Shane Winslow an early adopter?

A patch to hedge against this happening in the future would be to skip displaying this attribute if the look-up is `nil`. I hesitate to correct any data in production until we more fully understand why this problem arose. It's noteworthy that our users' emails addresses vary in format: some have `ucmail.uc.edu` and some just have `mail.uc.edu`. Does anyone know whay?

**Comment by jamesvanmil** [comment]
I updated the email addresses to read mail.uc.edu - we think this early adopter was actually a student, and when we migrated him for Shibboleth, we got the wrong email address.
