### ISSUE TITLE
Mailer error on local dev

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#680]
We're seeing errors about the mailers (on port 25) for local dev environments.

We are able to fix by uncommenting this line: https://github.com/uclibs/scholar_uc/blob/develop/config/environments/development.rb#L18

We should set a bamboo variable for this for the dev server, and add a version appropriate for local dev environments for `copy_config.sh`.

**Comment by scherztc** [comment]
Document FIX and move on.

**Comment by scherztc** [comment]
My test are now passing on scholar_uc without changing this setting.  I am going to close the issue with this documented work around.
