### ISSUE TITLE
Recreate the QA servers using Puppet

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#688]
Miscellaneous changes have been made to the QA server environments.  To make sure everything is proper, The QA servers should be wiped and recreated using updated Puppet scripts.

The affected servers are
- libhydqwl1
- libhydqwl2
- libhydqfl1
- libhydqsl1

IT@UC help is needed to wipe the servers and deploy the Puppet scripts.

**Comment by scherztc** [comment]
Done.
