### ISSUE TITLE
Upgrade servers to latest ruby 2.1.x release

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#689]
Download and compile ruby 2.1.9 (or latest 2.1.x version) on all Scholar web servers.

Affected servers are
- libhydpwl1
- libhydpwl2
- libhydqwl1
- libhydqwl2
- libhyddwl2

IT@UC help is needed to perform this task on production servers.

**Comment by flutterflies** [comment]
After the rebuild for Scholar 3, web servers should all be running Ruby 2.4
