### ISSUE TITLE
Make internal links responsive

### ISSUE THREAD

**Issue by jmeinken** [uclibs/scholar_uc#690]
Hi, I'm a developer with UC Center for Health Informatics.  I've been trying out Scholar@UC and have been very impressed with the idea and the implementation.  This is just a suggestion for you to consider.

I've noticed when clicking internal links that the browser's default behavior of showing a spinner in the page tab to indicate loading doesn't occur.  There were several times where the load time was slow and I wasn't sure whether I had successfully clicked the link/button.  It would be nice to have some sort of immediate response to indicate loading.  If your application setup prevents the default browser behavior, perhaps there could be a spinner or some other indicator appear on the page.

Tested in the latest versions of Firefox (45.0.1) and Chrome on Windows 7.

**Comment by flutterflies** [comment]
I am seeing browser loading indications with Scholar 3 in both Firefox 57 and Chrome 62 on MacOS 10.13
