### ISSUE TITLE
Change Apache log permissions to allow viewing

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#691]
The Apache log directory is owned by root, which means other users cannot browse the directory.

IT@UC help is needed to make the log directory viewable on production.

**Comment by hortongn** [comment]
We are waiting on UCIT to give us permissions to access the logs

**Comment by bng44270** [comment]
This has been resolved and a cron job has been added to verify folder permissions every day at 5 am.

**Comment by hortongn** [comment]
I've verified that we can access the apache logs on production.  Thanks @bng44270 !
