### ISSUE TITLE
Mount remote drive for saving content to APTrust bags

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#693]
A large amount of mountable storage is needed to be able to export content from Fedora to send to APTrust.

IT@UC help is needed to mount remote storage to the production Fedora server (libhydpfl1).  This same slice of storage should also be mountable on other production systems such as the DRC.

**Comment by scherztc** [comment]
Glen reported to Dennis Gavin and Bryan Newswanger.  Newswanger is working through problems on the new disk mount.

**Comment by hortongn** [comment]
@ntallman, we are mounting the libbag drives for most of our projects, but for Scholar we are doing the rsync copy.  Would you prefer we mount a drive instead?  Or leave it as is?
