### ISSUE TITLE
Student work type

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#697]
Proceeding with this with non-repeatable, free-text c&d facets

@newmanld - would you add the other new fields we need?

**Comment by jamesvanmil** [comment]
Notes:

* Not doing year of graduation/degree date
* Faculty Advisor/Sponsor (required)
* 'College' & 'Program or Department' (not required)
* Should have degree types (e.g. BS, BA, etc - direct them to use abbrev.)
* Required pull-down for additional worktype - pull from registered curation concerns
* Optional genre with (combine image and document lists)
* Help about: (scholarly product type/research presentations/awards) next to description

Added value (assess need after form is up):

* Look-up for advisor
* For degree - could help suggest values with typeahead or pulldown

**Comment by jamesvanmil** [comment]
@newmanld: for publisher - should we:

* Automatically set "University of Cincinnati" and not allow it to be changed
* Set "University of Cincinnati" as the default and allow them to change it
* Leave as blank, per the other work types?

**Comment by newmanld** [comment]
Publisher field -  I don't think we can lock it down to University of Cincinnati.   Some student works will be associated with grants and could conceivably have a publisher.

So I lean toward the same option used in the other work types, leaving it blank with the same help text as the other work types.  Still optional - only required for a DOI.
