### ISSUE TITLE
Editing object ownership

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#700]
`As:` repository manager

`I want to:` edit the owner of a work or collection

`So that:` I can handle transfer of content without involving the development team

Note that this assumes that file/link owners are kept in sync with changes in work owners - these are now being explicitly set as part of file create, but not on update.

This functionality will be useful in cobbling together a mediated deposit model, where students submit works with faculty advisors attached as editor, and the repository manager removes the student from the submission to prevent any modifications of the work.

**Comment by lawhorkl** [comment]
needs: specs

appears as repo manager
doesnt if not

make sure the change is successful

**Comment by lawhorkl** [comment]
@13miciunasl am I assigned or no? :p

**Comment by newmanld** [comment]
When this issue was closed, it only deals with works, not collections.  Collections don't have 'owners' but have an 'editor' - if that becomes something a Repo Manager needs to change, we will need to open a new issue.
