### ISSUE TITLE
Resolve double slashes in permalinks for profiles

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#709]
The 'Link to this page' information on a person profile has double slashes.  For example, https://scholar.uc.edu//people/5138jd91b   

The link still works, but the double slash doesn't seem correct.

**Comment by hortongn** [comment]
I'm reopening this issue because we discovered it was fixed in the Curate gem, but that partial is being overridden in the app and needs to be fixed there as well.  @13miciunasl can you do a quick commit to fix this so we can get this into the next deploy?
