### ISSUE TITLE
Create new UC test shibboleth logins

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#712]
Open a ticket with UC identity management to
* create logins for students (or one shared login)
* crete login for hailstorm

**Comment by newmanld** [comment]
Request has been initiated.  I asked for individual accounts for those on the team that do not yet have qa-shibboleth accounts, but indicated we could use generic accounts if that was preferred.

**Comment by newmanld** [comment]
I requested a due date of 5/9, because that is when we will start to build a deploy after the sprint ending 5/6.
