### ISSUE TITLE
Unused parameters passed to Capybara::Queries::SelectorQuery

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#713]
Seeing this warning while running specs on Capybara 2.7 (which we recently updated to) - the warning message is new, but I don't think the behavior is - opening this issue to double-check that there isn't a problem with our specs.

Here's an example of such a warning:

`Unused parameters passed to Capybara::Queries::SelectorQuery : ["Describe Your Work"]`

And where it's probably coming from?: https://github.com/uclibs/curate/blob/4d4fe09430b09182520d89c38bc08146704fcf8b/spec/features/end_to_end_spec.rb#L168

**Comment by scherztc** [comment]
@jamesvanmil Are we still getting this warning?

**Comment by scherztc** [comment]
Specific to curate specs.
