### ISSUE TITLE
Replace email with name for collections in catalog browse view

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#722]
Name should be displayed in natural order.

Display/Download Use Cases [Submission 17](https://github.com/uclibs/scholar_use_cases/blob/master/display_download/display_download_use_cases.md#submission-17---view-from-the-catalog-when-browsing-collections--early-adopter)

**Comment by newmanld** [comment]
See also #723.  If we cannot accomplish this without a lookup that would make the catalog browse unresponsive, consider removing the owner field from the citations for Collections on catalog browse, once we have added Collection Owner to the show page for Collections?

**Comment by jamesvanmil** [comment]
The best way to do this will probably be to dynamically add the name of the Person/Owner to the work as an additional metadata field, as a callback.

**Comment by lawhorkl** [comment]
i think i understand enough about this issue to take it on. would be good for me to mess with solr as well.

**Comment by lawhorkl** [comment]
@jamesvanmil the use case is contradictory. Should I replace the owner's email or display it alongside of it?

**Comment by newmanld** [comment]
@lawhorkl - you are correct that the Use Case is contradictory.  But I thought they wanted name and not email, and we don't publicly display email anywhere else except people profiles, as far as I know, so I would lean toward name only -- but @jamesvanmil - can we confirm this with Use Cases working group?

**Comment by jamesvanmil** [comment]
I've consulted the original early adopter session documentation, and it doesn't talk about having both. I think we should just replace the email with the owner.

I'll open a PR on the use case in the repo.
