### ISSUE TITLE
Research collection page load time improvements for large collections

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#730]
Using Solr instead of Fedora?

**Comment by crowesn** [comment]
Added new method to Collections ```members_from_solr``` which should quickly load line items for the collection show page. 

Outstanding functionality issues:

* Method only returns curation concerns; I hit a blocker attempting to integrate collection members in the response.
* New ```members_from_solr``` method addresses line item display speed only, still significant lag present when running other methods on collections, such as add or remove member.

Branch in progress: https://github.com/uclibs/curate/commit/fd55e73b70fa2a490fc26dac3c47761de4b4fca9

**Comment by jamesvanmil** [comment]
To do:

* Add collections to `Collection#members_from_solr`
* Add `collection_sim` to `Collection#to_solr`
* Add helper for collection path
* Organize helper and comment unused methods
* A few specs
