### ISSUE TITLE
Display of parent-child relationship on collection page

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#734]
Organizing Content Use Case [Submission 13](https://github.com/uclibs/scholar_use_cases/blob/master/organizing_content/organizing_content_use_cases.md#submission-13---display-of-parent-child-relationship-on-collection-page---early-adopter)

**Comment by newmanld** [comment]
If you are on a collection show page for a collection that is a member of a parent collection, see the parent collection linked.
