### ISSUE TITLE
Adding an item to a profile vs collection is unclear

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#735]
Organizing Content Use Case [Submission 14](https://github.com/uclibs/scholar_use_cases/blob/master/organizing_content/organizing_content_use_cases.md#submission-14---adding-an-item-to-a-profile--early-adopter)

**Comment by newmanld** [comment]
Add a label - to a name or profile collection appearing in the collection drop down selection list --  to make it clear that users are putting a work into a profile collection.

**Comment by jamesvanmil** [comment]
![image](https://cloud.githubusercontent.com/assets/2651187/14927490/42c578d2-0e20-11e6-899a-223c0645ed40.png)

It should be clear that my name is a profile

**Comment by crowesn** [comment]
Does this work, nah?
<img width="669" alt="screen shot 2016-05-24 at 11 45 18 am" src="https://cloud.githubusercontent.com/assets/1069588/15510410/260292b4-21a5-11e6-80d7-0ed739fde317.png">

**Comment by newmanld** [comment]
Big improvement!  (In screenshot - you have collection - not a profile section - called 'Test profile'?)

**Comment by jamesvanmil** [comment]
Is it just a coincidence that you named a collection "Test profile"?

**Comment by crowesn** [comment]
yes, sorry, it is a coincidence that the collection is name "Test profile".

**Comment by newmanld** [comment]
Everyone always has a Profile.  If they have no Collections or Profile Sections - should we repeat the headers ('Your Collections' and 'Profile Sections) with no content, or not show the headers?  (I think I lean toward the first option, to remind users they could create a Collection and/or a Profile Section.)

**Comment by crowesn** [comment]
Those headers don't show if they don't have content. See James' screenshot above.
With my change, the "Your Profile" would always show.

**Comment by newmanld** [comment]
But it would still have the header 'Your Profile'?

**Comment by crowesn** [comment]
Yes: 

<img width="699" alt="screen shot 2016-05-24 at 12 04 41 pm" src="https://cloud.githubusercontent.com/assets/1069588/15511004/bdb54a96-21a7-11e6-9e79-2ef8a3e9b9b9.png">

**Comment by newmanld** [comment]
OK.  Go for it!
