### ISSUE TITLE
Enable 'date created' as a sort option on Catalog Browse for Works

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#743]
This has been expressed as a need by me and @ntallman  for content currently being added to Scholar@UC.    This would only apply to Works - not Collections or People.  See also issue #573.  These two issues would create different options in the 'sort by' drop down menu for Works, Collections, and People.  At present all three categories have the same 'sort by' drop down menu.  

Two options would need to be added to the menu to sort 'date created' in ascending or descending order.  

Date created will be populated from an optional metadata field and so not all works will have this value.  Works without the value should still appear in the sorted list.  A strategy for handling empty values will be necessary.

Date created is the date when the contents of a work were created, not when those contents were uploaded.  It is an optional metadata field on all work types.  The help text suggests that it should be entered in YYYY-MM-DD format.

First step is to consider feasibility and whether this can fit into our Scholar 2.0 timeline - if not, change label to Scholar 3.0.

**Comment by newmanld** [comment]
If, in conjunction with #573 , the drop-down menu is too long, consider removing 'date modified' while keeping 'date uploaded'.

**Comment by jamesvanmil** [comment]
@newmanld @ntallman how would you like to handle works without a created date? Does it sort at the end, does it get excluded from the search, do we communicate this problem to the user somehow?

**Comment by newmanld** [comment]
@ntallman and I discussed this but didn't have a firm answer other than all works will need to be in the sort results.  That is, choosing 'date created' from the 'Sort By' drop-down list should not cause some works to disappear from the catalog browse.  One approach would be to use 'date uploaded' for purposes of sorting when there is no 'date created'.  Note that 'date uploaded' is a current sort option but is not metadata we expose on the work show page.  'Date created' is optional descriptive metadata exposed on the show page.  

The request is for a sort. An alternative approach to this issue is a facet.  May be worth discussing with @ntallman ?

**Comment by ntallman** [comment]
For now, I think we can go with Linda's suggestion of defaulting to 'date uploaded' if there is no 'date created' value. We can refine and iterate moving forward. Perhaps we can think about adding 'date created' to the list of fields that show up for every record (not within "show additional descriptive fields." Perhaps we can consult the metadata working group?

**Comment by jamesvanmil** [comment]
I'm worried that conflating fields is going to challenge users' understanding of what they mean. Can we kick this over to the metadata WG for consideration of these issues?

**Comment by ntallman** [comment]
Can the research task of what it take to implement continue as metadata WG considers this? Just trying to prevent a halt to velocity on the issue.

**Comment by newmanld** [comment]
+1 to @ntallman re research task, to determine if providing this sort option (with a default to date uploaded if date created is null?) is within scope for Scholar 2.0.  I've pointed out that right now three categories on the catalog view (works, collections, people) share the same sort options.  So part of the feasibility research (for this issue and issue #573 ) is looking at amount of work to have different sort options for different categories.  I've wondered if a facet would be easier, and with a facet the 'null' issue does not apply.

+1 to @jamesvanmil to ask Metadata WG if date created should remain hidden by default, as at some point we will have a 'sort by' and/or facet for this metadata, given the interest in it for a significant portion of content.  At present all non-hidden fields except publisher are mandatory.  A second question for Metadata WG could be whether date created should be mandatory, perhaps defaulting to date of work submission ('date uploaded').

**Comment by jamesvanmil** [comment]
chatted with @ntallman and we agreed that it would be good to explore this as a facet - after I get a new token I'll see how that field has been used in production

**Comment by 13miciunasl** [comment]
James asked me to review the dates of creation he pulled from production for inconsistencies in the formatting. 
Most are formatted yyyy-mm-dd or yyyy. 
There are many instances of single digit months not having the leading zero ("2016-5-6")
There are a few formatted as yyyy - yyyy ("1990 - 2006")
And finally a select couple as yyyy - mm ("2015-01")
Other than that there are also some unnecessary/leading/trailing white spaces.

**Comment by jamesvanmil** [comment]
@newmanld looks like the sort would be mostly intact - assuming that the leading `0` issue will be handled by metadata folks. Okay to proceed with the facet, or do we want a cleaner solution?

**Comment by newmanld** [comment]
Proceeding with a facet seems the best choice for now.  Let’s assume we will get more feedback when we have a branch to demo?

**Comment by 13miciunasl** [comment]
@newmanld I have a branch to demo! Here's a screenshot
![screen shot 2016-06-01 at 8 10 37 am](https://cloud.githubusercontent.com/assets/9759017/15713499/adf0bc6a-27e4-11e6-9fe2-4eb9c6ed7458.png)

**Comment by newmanld** [comment]
Excellent! – Can we bring a branch up on Larry?  I’ll then seed it with examples so people can get a hands on feel and send a message to the T.F. for comment.

**Comment by 13miciunasl** [comment]
@newmanld Finally got my branch running on larry at http://larry.libraries.uc.edu:3001

**Comment by newmanld** [comment]
@13miciunasl  I've added several works so that people can see how the facet will behave.  Looks pretty good to me.  I am wondering about our option labels on the 'more' popup. If space allows, would more descriptive terms such as ‘Alphanumeric Sort’ and ‘Frequency Sort’ be better?  Other ideas for better terminology?  (Would apply to all facets if we change.)

**Comment by 13miciunasl** [comment]
I agree that I don't like "more Date Createds" for obvious reasons, but I don't mind the word "more"

**Comment by newmanld** [comment]
I don't have a good alternative to 'more Date Createds' as the code presumably just picks up the facet name.  Doesn't bother me too much but might bother others.  But maybe just 'more' would be enough - on all facets?

But once you click on 'more' - the current 'Numerical Sort' might be misinterpreted when looking at dates - it is really a frequency sort.  Users would want to chose A-Z Sort, not Numerical Sort, to actually sort by date.  So I'm wondering about those labels.

**Comment by 13miciunasl** [comment]
@newmanld  At this point I am confident saying that without restricting user input, there is no clean/foolproof way to extract just the year or other part of the date. So I recommend one of two solutions: 1) use a masked textbox or other UI solution to get users always entering dates the same way, or 2) leaving the facet as-is where the user can enter the date however they want, but that would mean a lot of inconsistency in formatting. I know were still waiting on feedback, but I thought I would give you my final thoughts.

**Comment by jamesvanmil** [comment]
Per meeting about Schultz Archive - they see the simple implementation as valuable.

They had a lot of feedback about what would be ideal, and would be willing to re-engage if we look at this with Scholar 3.x

**Comment by jamesvanmil** [comment]
closed with https://github.com/uclibs/curate/pull/69
