### ISSUE TITLE
Error when adding content editors, changes editor to "True"

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#744]
My student assistant discovered that occasionally when adding an editor (individual or group) and updating a work, she gets an error page. When hitting the browser back button, the name of the individual or group is replaced with 'true'.

P.S. More whitespace is needed between active add/remove toggles and the help text.

![bug](https://cloud.githubusercontent.com/assets/549591/15080591/f62208e8-138c-11e6-922b-35b7893ee267.png)

**Comment by scherztc** [comment]
We are not using groups in Scholar 3.  Can not replicate.
