### ISSUE TITLE
Security - Resolve ImageMagick vulnerability

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#746]
See https://groups.google.com/forum/#!topic/hydra-tech/XO6muzsf7ks per vulnerability announced here
https://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=29588
https://imagetragick.com/ -

more reasons to compile custom version of ImageMagick with not only better jp2 support but the patch to configuration as recommended here?

**Comment by hortongn** [comment]
RedHat has released a fix for the ImageMagick vulnerability.  It should get applied to production servers on Monday, 5/16.  I will verify on that day.

**Comment by hortongn** [comment]
I confirmed that this fix has been applied via RedHat updates to both production web servers.
