### ISSUE TITLE
Add open data commons licenses

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#750]
- Add [Open Data Commons licenses](http://opendatacommons.org/licenses/) to the select list and the license wizard
- Add data as a distinct work-type to the license wizard
- Start wizard with question about what type of content submitted; use the Open Data Commons licenses to guide the data workflow
- License wizard question for share alike: “Do you require that those who use your data to create new works to issue their new works under a compatible license?”

Related #264

**Comment by jamesvanmil** [comment]
There's a generic need to update to 4.0 CC licenses too (while supporting the 3.0 licenses on already submitted works) - when whoever is working on this, can you please keep that in mind to see if the upgrade is easy?

**Comment by ntallman** [comment]
Another future task is to improve the language for the "All rights reserved" option. It's pulled from Wikipedia right now.
