### ISSUE TITLE
Remaining TurboLinks reference

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#751]
Users are not seeing this error, but the application log is complaining about a missing TurboLinks route.  The reference may be coming from https://github.com/uclibs/scholar_uc/blob/develop/app/views/layouts/application.html.erb#L9

We should remove that line.

**Comment by lawhorkl** [comment]
As per my recent issue we will be adding turbolinks back to Scholar and only enabling it on the work create/file add page. Because of this, this issue is now a nonissue.
