### ISSUE TITLE
names in group management page show as 'undefined' if user hasn't filled out profile

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#756]
This is probably a minor issue because of the unlikeliness of this happening, however I still don't think we want something like this in production: 
![image](https://cloud.githubusercontent.com/assets/12615997/15409810/72ef234a-1de4-11e6-8bc1-9f92f6d975b1.png)

**Comment by scherztc** [comment]
We are not using groups in Scholar 3.  Can't replicate problem.
