### ISSUE TITLE
Collections fail when they have too many works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#758]
When adding a new work to a collection in production, seeing an error page.

The work is loading, but the editor is not set, and the collection is not set.

Here is an example work that error’d: https://scholar.uc.edu/works/documents/05742028n

It's possible the collection got too large - I recall a problem with hailstorm where it was adding too many objects to a collection or group, and that causing the query to Solr to fail.

**Comment by hortongn** [comment]
The issue we had with Hailstorm dealt with a single user belonging to too many groups.  The Solr query became too long.  The details are at https://github.com/uclibs/scholar_uc/issues/503#issuecomment-167904986

**Comment by newmanld** [comment]
This reads like it could be two separate problems - an editor for a work could not be set; the work could not be made a member of a collection.  Hard to tell if the problem is with the work or the collection?  Hard to tell if it is a bug that can be reproduced?

**Comment by jamesvanmil** [comment]
Yeah - I think that's right - I bungled the description a bit. We're mostly sure that they both appears at the same time though, and are probably related. The best next step is to reproduce in production and look at the log for clues about the error, or to try to reproduce locally.

**Comment by newmanld** [comment]
We've determined that the Collection no longer displays because of too many works - 144.  We attempted to delete one work that was a member of the Collection, and the delete failed.  This work is https://scholar.uc.edu/works/documents/057420106.  The Collection is https://scholar.uc.edu/catalog?f%5Bcollection_sim%5D%5B%5D=sufia:05741w32f.  We need to determine in QA how to remove a work from a collection.  Do this in production on 057420106 and then complete the delete of the work  - which may temporarily allow the collection show page to display.  We should not add more works to this collection until we solve the underlying issue.  Solution may relate to #738

**Comment by jamesvanmil** [comment]
`Collection.members` and `GenericWorks.collections` seem to be the source of this problem. They're using code here:

```
active-fedora-6.7.8/lib/active_fedora/associations.rb", 242
```

I suspect that we could solve this by overriding these methods in our local models for works and collections to perform an alternative query to return the intended result of these calls (which is an array with all the expected objects).

**Comment by hortongn** [comment]
Edited the title of this issue to better reflect our new understanding of this problem.

**Comment by hortongn** [comment]
I'm still working on getting the Lucy Shultz Archive collection to display properly.  I full removed the work we tried to delete in our swarm last week, but the collection still fails.  I did some testing in the web-based Solr interface for production and verified that the collection still has 6 more works than it can handle.  If I remove 6 works from the Solr query the error goes away.  So my plan now is to create another collection (Lucy Shultz Archive part 2) and move some of the works there.

**Comment by newmanld** [comment]
Thanks! – It must be possible to continue to add a work to a collection 6-7 times after the collection show page stops displaying – and then it also becomes impossible to add more works.

**Comment by hortongn** [comment]
@ntallman @newmanld  I have fixed the misbehaving Lucy Shultz Archive collection.  Ten of the works from that collection have been moved to a new "Lucy Shultz Archive - part2" collection.  Both collections are owned by Julianna Peck.  I suggest keeping the number of works in a collection to no more than 140 for now.  

If we have to end up fixing more collections like this in the future, this is what I did on the Fedora server:

1. Make a copy of the content in the collection's RELS-EXT datastream: <br />`curl -i -u fedoraAdmin:password "http://localhost:8080/fedora/objects/sufia:05741w32f/datastreams/RELS-EXT" > temp_content.xml`
1. Edit the temp_content.xml file to remove some of the works in the collection.  Get it down to less than 140 works.
1. Delete the current RELS-EXT datastream from the collection object: <br />`curl -i -XDELETE "http://localhost:8080/fedora/objects/sufia:05741w32f/datastreams/RELS-EXT" -u fedoraAdmin:password`
1. Create a new RELS-EXT datastream that uses the new temp_content.xml: <br />`curl -i -H "Content-type: text/xml" -XPOST --data-binary @build.xml -u fedoraAdmin:password "http://localhost:8080/fedora/objects/sufia:05741w32f/datastreams/RELS-EXT?dsLabel=Fedora%20Object-to-Object%20Relationship%20Metadata&formatURI=&checksumType=Disabled&altIDs=&mimeType=application/rdf%2Bxml&controlGroup=X&versionable=true&dsState=A&flash=true"`
1. Switch to the web server and do a Solr reindex

**Comment by hortongn** [comment]
Something else for us to look into: There are supposed to be default settings within Solr and Tomcat that can limit the length of a Solr query.  We may be able to override these defaults.  Tomcat has a 'maxHttpHeaderSize' setting and Solr has a 'maxBooleanClauses' setting.  We may want to try these in a vagrant environment to see if it solve our problem.  There may be other settings or code that is limiting the query length as well.

**Comment by newmanld** [comment]
That would be a neat solution if response time is still acceptable!

**Comment by crowesn** [comment]
http://stackoverflow.com/a/2659995/4930216

We're prevented from changing blacklight request from get to post, we're pinned to a release that doesn't yet support it.

I'm going to look into tomcat/solr tweaks to up our request size limit.

**Comment by hortongn** [comment]
We are stuck with that version of Blacklight, but you may still be able to override something in Blacklight.  If you find the exact piece of Blacklight code you want to change, there should be a way to add a file to curate that overrides it (hopefully without breaking any tests).

**Comment by newmanld** [comment]
If an override to Blacklight is possible to allow post instead of get - might be better than just upping the request size limit?  We'd need to up that limit quite a bit.  Of course I' curious how post avoids the limit.

**Comment by hortongn** [comment]
GET requests are sent via the HTTP header and are limited to a certain number of characters (it varies by browser and server).  POST requests are sent via the HTTP body and don't have a hard limit.

**Comment by crowesn** [comment]
Looking now at reopening blacklight and making these changes: https://github.com/projectblacklight/blacklight/commit/8d44f82a55599502f7c04106a7a6612737a7cbc6

**Comment by jamesvanmil** [comment]
```ruby
active-fedora-6.7.8/lib/active_fedora/solr_service.rb:116:in `query'

    def self.query(query, args={})
      raw = args.delete(:raw)
      args = args.merge(:q=>query, :qt=>'standard')
      result = SolrService.instance.conn.post('select', :data=>args)
      return result if raw
      result['response']['docs']
    end
```
