### ISSUE TITLE
Assigning groups to works is failing, presumably after we reach a threshold of number of works

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#764]
When a group has been assigned to 144 works, we no longer can add that group to additional works.  Similar to #758 For an example of a group with this problem, see groups/sufia:ff3658727.

**Comment by ntallman** [comment]
Related to [#744](https://github.com/uclibs/scholar_uc/issues/744)?

**Comment by lawhorkl** [comment]
unassigning myself per @jamesvanmil 's instruction

**Comment by jamesvanmil** [comment]
Resolution of this issue depends on #758
