### ISSUE TITLE
Extra file title appearing in file list on work show page

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#765]
Directly below the file thumbnail appears an extra file title. Seems to be a value added to the file title field by FITS. EngCompText_hyde1899_page0001 is the name of the first tiff that was used to create this PDF.

https://scholar.uc.edu/show/ff365955s

![image](https://cloud.githubusercontent.com/assets/549591/15557440/fa58e922-22a0-11e6-8e58-2d642b38191d.png)

**Comment by scherztc** [comment]
This is solved with Scholar 3.
