### ISSUE TITLE
Google API client error on local and production

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#775]
Discovered that the browse everything dialog is broken on my local machine and in production, with 500 err and message ```cannot load such file -- google/api_client```

@scherztc this looks like an integration problem?

I think this is related to https://github.com/uclibs/scholar_uc/issues/773

Screen (production):

<img width="1253" alt="screen shot 2016-06-06 at 11 05 41 am" src="https://cloud.githubusercontent.com/assets/1069588/15826993/c1860d9c-2bd7-11e6-9a63-584b0bdaa939.png"> 

Err log from local: 
```
Processing by BrowseEverythingController#index as HTML
  Rendered /Users/crowesn/.rvm/gems/ruby-2.1.6@curate/gems/browse-everything-0.9.1/app/views/browse_everything/_providers.html.erb (
3.1ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.1.6@curate/gems/browse-everything-0.9.1/app/views/browse_everything/index.html.erb (10.2m
s)
Completed 500 Internal Server Error in 17ms

LoadError (cannot load such file -- google/api_client):
```

**Comment by crowesn** [comment]
Error is not present on QA.

**Comment by scherztc** [comment]
There is a 0.10.2 version of browse_everything:  

https://github.com/projecthydra/browse-everything/tree/v0.10.2

**Comment by scherztc** [comment]
Glen and I were able to pin google_drive (-> 1.0.6) and google-api-client (-> 0.8.6) and bundle update on production successfully.  I will add these pins to the gemspec file on the curate gem.
