### ISSUE TITLE
Creator not appearing in catalog index view for document work type

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#779]
Compare:

Articles - https://scholar.uc.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Document

Documents - https://scholar.uc.edu/catalog?_=1465579481647&f%5Bhuman_readable_type_sim%5D%5B%5D=Article

@newmanld Agree that all catalog index views should be the same, or should we ask Metadata WG to make recommendations for per-work fields?

**Comment by jamesvanmil** [comment]
FYI this came from the meeting about the Schultz Archive

**Comment by scherztc** [comment]
https://github.com/uclibs/curate/blob/1b7f3c0a3f1543befe47d960bdcec405fb789dbd/app/views/curation_concern/documents/_document.html.erb

**Comment by scherztc** [comment]
<% if solr_doc.has?('desc_metadata__creator_tesim') %>
          <dt>Author(s):</dt>
          <dd><%= render_index_field_value(document: solr_doc, field: 'desc_metadata__creator_tesim') %></dd>
        <% end %>
