### ISSUE TITLE
Bug: Changing Visibility is applying to attached files when the editor says no

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#780]
If the visibility of a work is changed, Scholar@UC asks the editor whether this change should apply to all attached files.  If the editor says 'No', the visibility of the attached files should not change.  This was functional in the past, but now is not - Scholar@UC ignores the editor's answer and always applies the visibility changes to all attached files.

**Comment by 13miciunasl** [comment]
Replicated the issue on dev, but am unable to on my local machine.

**Comment by newmanld** [comment]
Is being unable to replicate on local dev machine consistent with @crowesn report that ‘vanilla curate’ does not have the error?

**Comment by crowesn** [comment]
My comment re vanilla curate was for issue #789 , not this one.

**Comment by newmanld** [comment]
Thanks for that clarification @crowesn.
