### ISSUE TITLE
Implement new home page incorporating designer suggestions

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#781]
Elements from the attached two designs will be used to develop a new Scholar@UC home page
[ScholarAtUC-SplashPage-Revisions4-29-1D.pdf](https://github.com/uclibs/scholar_uc/files/309837/ScholarAtUC-SplashPage-Revisions4-29-1D.pdf)
[ScholarAtUC-SplashPage-Revisions4-29-3F.pdf](https://github.com/uclibs/scholar_uc/files/309836/ScholarAtUC-SplashPage-Revisions4-29-3F.pdf)

**Comment by crowesn** [comment]
Size: 32

**Comment by crowesn** [comment]
![Uploading FireShot Capture 002 - Scholar@UC - http___localhost_3000_.png…]()

**Comment by crowesn** [comment]
![splash_screen](https://cloud.githubusercontent.com/assets/1069588/17832439/e4ac02b6-66d0-11e6-9532-9d517d42d82f.jpg)
