### ISSUE TITLE
Files selected from BrowseEverything are not being reported on the input form

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#789]
Files selected through BrowseEverything used to be reported on the input form by number of files selected, alerting the submitter that something had happened.  This message no longer appearsl

**Comment by crowesn** [comment]
FYI, this appears to be working in vanilla curate: 

<img width="1227" alt="screen shot 2016-06-13 at 2 50 53 pm" src="https://cloud.githubusercontent.com/assets/1069588/16019408/d7d0af9a-3176-11e6-9ea8-608ce9c7e698.png">

**Comment by scherztc** [comment]
Alright... After exploring different version of browse_everything and getting no response, I decided to put turbolinks back in.  Huzzah!  The item count returned.  So... This is an effect of removing turbolinks.

**Comment by scherztc** [comment]
We should be able to handle turbolinks on a per-page basis (see: https://stackoverflow.com/questions/22326473/rails-4-disable-turbolinks-in-a-specific-page)
 stackoverflow.com

Rails 4: disable Turbolinks in a specific page
I'm trying to make a JS snippet work in a concrete page with Rails 4 and Turbolinks. I've tried with the standard solution:<script type="text/javascript"> var ready = function() { ... 
 
We’d need to assess which pages we’d want to disable it for (where long delays are possible, and some page responsiveness is important)

**Comment by scherztc** [comment]
There is now a TurboLinks 5.  https://github.com/projecthydra/browse-everything/commit/48f65b0a5f4fbfb8aae87b15d3b4ba1ccf4ae7b3

**Comment by lawhorkl** [comment]
@scherztc I enabled turbolinks on my test app again but I did not see the item count return.

![image](https://cloud.githubusercontent.com/assets/12615997/17027031/4939d8a6-4f30-11e6-89ab-b0c1c66828d1.png)

**Comment by jamesvanmil** [comment]
Need to:

* add a spinner to work and file submit pages
* pin turbolinks in the dummy app generator
