### ISSUE TITLE
Thumbnails for PDFS are not generated on our Dev and QA systems

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#790]
This may have to do with an attempt to recompile ImageMagick, which has not yet been done on production.

**Comment by scherztc** [comment]
Solved this on DEV with installation of ImageMagick 6.7.2.  OSD and LORIS still have problems.

**Comment by scherztc** [comment]
Fixed with https://github.com/uclibs/scholar_uc/issues/1735
