### ISSUE TITLE
Assess the source of delays on the catalog browse page

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#792]

**Comment by lawhorkl** [comment]
Doesnt seem to be related but found a weird error in the stack, might be worth going back to take a look
![image](https://cloud.githubusercontent.com/assets/12615997/16129457/cb7f65a2-33d2-11e6-948c-da504209790a.png)

**Comment by lawhorkl** [comment]
@jamesvanmil 

The first two sources of delay that I can find is 

1.) The javascript on the page. With all of the JS we have to load on the application, the time it takes for the browser to compile the JS takes up anywhere from 1/3 to 1/6 of the load time depending on the page. This drag on the load is consistent on every page in the application and finding a way to streamline or to get rid of any excess JS that the application doesn' actually need to work will yield better load times throughout Scholar.

2.) On the catalog browse view of the application, the fedora call to `@document_list` which is a hash of all works returned by the filters and facets takes up a whopping 60% of the load time on the page and is, I believe the primary cause of the delay.

I will update this if I find anything else.

**Comment by hortongn** [comment]
Deciding not to resolve this for Scholar 2.x
