### ISSUE TITLE
Profiles with selected works break for non-logged in users

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#793]
If a user has added works to their profile, only logged in users can properly view the profile page.  Other users get a Page Not Found.

The actual error is:

    NoMethodError in Curate::PeopleController#show
    undefined method `email' for nil:NilClass
    <%= list_items_in_profile_section(@person.profile, terminate=false, options={:display_contributors=>false}) %>

I think this bug was introduced during our last deploy with PR https://github.com/uclibs/curate/pull/63.   That introduces code that uses `current_user.email` and `current_user` is only available when a user is logged in.  That's probably why the page errors when non-logged in users try to view profile pages.  That's just a preliminary guess.

**Comment by lawhorkl** [comment]
@hortongn you were right - a simple nil? check fixed it.
