### ISSUE TITLE
Alternate request method for files too large to download

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#799]
Perhaps using  f.file_size, research whether we can detect files stored in Fedora that are in our current scholar 2.x stack are too big too download.  Current proposed threshold is 3 GB.  Assume that either FITS will inform the  f.file_size value, or if files are manually loaded into Fedora bypassing the GUI and bypassing FITS, we will manually enter the file size in this value.    Once a file above this threshold is detected, work and file show pages should show a Request instead of a Download button.  Draft a form which users could use to submit a request.  Similar to the contact us form, it should pick up user's email address if user is logged in, and otherwise query user for this information but also offer a recaptcha challenge.

**Comment by hortongn** [comment]
@13miciunasl: see changes below

- I said you didn't need to edit `/spec/internal/config/routes.rb` in the test app, but I forgot you do need to add the routes to `/lib/curate/rails/routes.rb`.  So edit that file and add a new line similar to the help_request line (but with "file_request" instead) at https://github.com/uclibs/curate/blob/develop/lib/curate/rails/routes.rb#L47 You can just add the new line below line 47 and you may need to restart the test app after that change.

- Rename `app/controllers/file_request_controller.rb` to `app/controllers/file_requests_controller.rb` (add an "s" to request)

- Right now the file requests controller is complaining about a missing `end` on your create method.

**Comment by 13miciunasl** [comment]
My current blocker is that in the file_requests_controller it receives the PID of the file requested in the 'new' method, but by the time the 'create' method is called the controller no longer knows the PID. See curate branch feature/#799-request-large-files
