### ISSUE TITLE
Research method for detecting files too big to upload through Hydra GUI in Fedora 3

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#800]
Assume that our threshold for uploading files through Hydra and the web servers is 3 GB, in the Scholar 2.x stack environment.  Research a method for identifying and blocking these files whether coming from the workstation or Browse Everywhere.  

Possible help identified by @ntallman: 
http://stackoverflow.com/questions/1601455/how-to-check-file-input-size-with-jquery
http://stackoverflow.com/questions/7497404/get-file-size-before-uploading

**Comment by lawhorkl** [comment]
looks like jquery will be our best bet - The uploader that lets you use browse everything already has what we need to determine the file size for uploaded files.
