### ISSUE TITLE
Prevent manager emails from being displayed as depositor on file show page

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#803]
We're exposing the file depositor on the file show page. If the repository manager submits a file this attribute will show users the repository manager's email, which we would prefer not to expose.

**Comment by newmanld** [comment]
Although we've discussed whether to show depositor (which is in some cases delegate) on the file show page, let's leave it alone, but just suppress the information if the depositor is a repository manager, parallel to the solution used in https://github.com/uclibs/scholar_uc/issues/795

**Comment by 13miciunasl** [comment]
At this point I am looking for feedback to see if my current implementation (which makes a fedora call in the file view) is entirely appropriate. See curate branch feature/#803-hide-manager-file-show for reference.
