### ISSUE TITLE
Private collections exposed if a member of public collections

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#808]
If a public collection is a member of a private collection, it is exposed on the public collection page under **This collection is a member of the following collections:**. The link will not work, returns an unauthorized message.

See example [here](https://scholar.uc.edu/collections/sufia:pg15bf014). ("Lucy Schultz Archive (complete)" is a private collection, owned by me.) Screenshot below that shows what I mean. The link goes to a public collection that is a member of a private collection. The screenshot shows that the private collection name is exposed in the "this collection is a member of" section.

![image](https://cloud.githubusercontent.com/assets/549591/16621889/dfb563e4-4365-11e6-9eb4-ecf982931b83.png)

**Comment by newmanld** [comment]
Looks like we do not have a comparable bug with Works.  When not logged in, and viewing a work within the private collection Nathan identified above, I do not see the private collection listed on the work show page.

**Comment by newmanld** [comment]
This bug may have been introduced when we closed https://github.com/uclibs/scholar_uc/issues/734
