### ISSUE TITLE
export metadata from Scholar@UC to metadata librarians

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#809]
As a metadata librarian I would like to regularly receive a copy of all descriptive metadata in Scholar@UC, organized by work, in a format such as xml or csv.

**Comment by jamesvanmil** [comment]
We could easily modify the existing manifest reports to include descriptive metadata for works. Retrieval would still be manual from the server, but it would be straightforward.

**Comment by jamesvanmil** [comment]
We could then also add a new cron task to run the rake command to generate the reports and email them to our metadata folks, to automate it.

**Comment by jamesvanmil** [comment]
An update is complete - I've sent an export of data to our Metadata librarians, with a request for feedback. After I receive that, I'll open a PR
