### ISSUE TITLE
Prevent collection icon from appearing if you can't collect the object

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#810]
If I'm logged in, I can get to the interface to add all works and collections to collections, even though I'm not able to add that object to a collection.

**Comment by newmanld** [comment]
This is happening if a user has no collections and no profile sections, then they should not see the folder icon beside a work they do not own, or they should see a message that they have no collections to add this to.  Have to be sure that a solution does not slow down the catalog browse.

**Comment by newmanld** [comment]
I think we introduced this when we closed https://github.com/uclibs/scholar_uc/issues/330
Before then, even if you had no collections and had no profile sections, you could add someone else's work to your main profile page - now that is not the case.

**Comment by lawhorkl** [comment]
@jamesvanmil i found maybe a related issue. In curate when you submit a work, the owner attribute is set to nil: 
![image](https://cloud.githubusercontent.com/assets/12615997/17449541/41a76770-5b29-11e6-9dc1-b347d361d2db.png)

**Comment by lawhorkl** [comment]
I checked the properties in the datastream and its set in properties.... 
![image](https://cloud.githubusercontent.com/assets/12615997/17449687/391be21a-5b2a-11e6-9a4d-da796d0cf877.png)

In the descMetadata datastream, it matches the Article data here exactly.
