### ISSUE TITLE
Research: evaluate feature difference between curate and sufia

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#819]
Size: 2

**Comment by 13miciunasl** [comment]
Sufia features (Linda's list)

DOIs  (we use EZID)
Work types (more than generic)    
Repository manager  (We have a special user that can edit all works - was told at some point in the UX group led by M. Tribone that this may not exist?)
Versioning of files exposed to UI
Email system that can trigger emails with specific events
CC license chooser (should be easy to plug in where others might just put a link to a help page.)
ORCID integration with user profiles (this is still in process for our version of Curate)
IIIF display of images (we're using Loris and Open Sea Dragon and have a view on the show page as well as a full screen option)
