### ISSUE TITLE
Schultz Collection updates

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#827]
Per @ntallman, we need to:

1. Change subject "Lucy Shultz Archive" to "The Lucille M. Schultz 19th Century Composition Archive" throughout Scholar
1. Change subject "Lucy Schultz Archive" to "The Lucille M. Schultz 19th Century Composition Archive" throughout Scholar
1. Make all works with collection "Lucy Schultz Archive" (then we can delete the other two collections)
1. Make all works with subject "Lucy Schultz Archive" owned by Russel Durst
1. Remove all editor groups

To-do:

1. Set the merged collection title to - The Lucille M. Schultz 19th Century Composition Archive
1. Make Russell the owner of the resultant merged collection
1. Add wp988k18n to the collection

**Comment by newmanld** [comment]
James - Russel Durst just stopped by my office and we reviewed the needed changes that are listed above.  

I would like to add two bullet points 
* Make Russell Durst (not the current student owner) the owner of the resultant merged collection.
* Change the title of the resultant merged collection to be the same as the subject heading:  The Lucille M. Schultz 19th Century Composition Archive

Are points 1a and 1b redundant? 

Point 4 - is this referring to this work:
            https://scholar.uc.edu/show/wp988k18n
And are we wanting to add wp988k18n as a related work on all other works in the collection?  If so, should the related work look like the related work reference here already in place:  https://scholar.uc.edu/show/057420972   ?
Or does point 4 refer to something else?
If the former, won't that make the show page for this one work (wp988K18n) rather long, with 'Referenced By' links listed for every work in the collection?
