### ISSUE TITLE
Ldp::HttpError on Work creation on Scholar 3.0 on Curly.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#829]
Ldp::HttpError in CurationConcerns::WorksController#create
STATUS: 500 java.util.NoSuchElementException at com.google.common.collect.Iterators$1.next(Iterators.java:80) at

**Comment by crowesn** [comment]
Size: 4

**Comment by scherztc** [comment]
Make sure that we are using Fedora 4.5.1.  For development we need to make sure that we are using the latest version of the fedora_wrapper gem in our application.

Task:  bundle update
