### ISSUE TITLE
Deploy style changes to curly for Scholar 3.x

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#834]

**Comment by scherztc** [comment]
Size : 2

**Comment by lisa3711** [comment]
1. Button Color:
/* Line 4554 */
Old Code:
```
**.btn-primary, .add**
{
  color: #ffffff;
 background-color: #337ab7;
  border-top-color: #2e6da4;
  border-right-color: #2e6da4;
  border-bottom-color: #2e6da4;
  border-left-color: #2e6da4;
}
```
**Suggested new Code:**
```
.btn-primary, .add
{
color: #ffffff;
background-color: #e00122;
border-top-color: #D90000;
border-right-color: #D90000;
border-bottom-color: #D90000;
border-left-color: #D9000;

}
```
2. Home page image:
old_main_tulips.jpg

**Comment by lisa3711** [comment]
1. Modify :/app/asseets/stylesheets/sufia.css to include @import style/theme.scss
2. inside  stylesheets folder, add a  folder called style, and then a file called theme.css.scss
3. make appropriate button and link class changes to overwrite
4.Possibly overwrite home page image: old_main_tulips.jpg Current home page image

**Comment by scherztc** [comment]
/Users/thomasscherz/.rvm/gems/ruby-2.1.5/gems/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_buttons.scss
