### ISSUE TITLE
Search within collection not working for Collection with Sub-collections.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#837]
Search within collection - the feature we implemented with #738 - is not working from a show page of a parent collection with sub-collections.  The catalog browse is empty.  For an example see Global Marine Biodiversity Archive at https://scholar.uc.edu/collections/sufia:wm117q83p.

**Comment by jamesvanmil** [comment]
When @crowesn and I were working on speeding up the collections show page, we noticed that the `colleciton_sim` field wasn't indexed for subcollections, so we added it.

Would be good to confirm, but I think that this is fixed with this merged PR: https://github.com/uclibs/curate/pull/84

**Comment by jamesvanmil** [comment]
Confirmed that this is fixed with #730

**Comment by newmanld** [comment]
I'm re-opening this issue.  Although the Catalog browse is no longer empty, the 'Search within collections' feature does not work (in the way that I think users would expect) for a parent collection - none of the facets are populated from the members of a sub-collection, and the keyword search does not include the members of a sub-collection.  I'm not pulling the deploy of the fix we have so far, which is better than before, or the feature, which is still very useful for anything but a Collection with sub-collections.  And including keyword index and facet results for all members of a collection in this catalog browse may not be simple, so may be out of scope for 2.x.   But this bears some research as to whether 1) a better solution is in sight, or 2) whether the 'search within collections' button should be removed from a Parent Collection, or 3) other solution?

**Comment by jamesvanmil** [comment]
To achieve this we could index nth-parent collections of any object. This is complicated for a two reasons:

1. We would need to guard against recursion when indexing circular collection members
1. If items are added to a collection, then that collection is added to another collection, we would need to update all associated works (this isn't hard with solr, but may be more challenging with ActiveFedora interceding).

We could also do this by constructing a search query for the "Search within this collection" button that includes pids for sub-collections. This would be less demanding, but we would still need to guard against recursion.

@newmanld - is your preference for handling any depth of nesting? A clear alternative would be to just replicate the amount of nesting that we see on the collection show page - I'm not certain, but I think this only goes one layer deep - should double check that...

**Comment by newmanld** [comment]
@jamesvanmil - I'm not sure either about the depth of nesting that is shown on the show page.  The ideal but  impractical solution is to handle any depth of nesting.  Open to ideas.  

For truth in advertising purposes, we could simply change the name of the button on all Collection show pages, for example - 'Search within this Collection' to 'Browse this Collection'?
