### ISSUE TITLE
Auto assign owner as editor in addition to delegate as editor

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#848]
This is a low priority, and may not be resolved in 2.x.

Current behavior (should be confirmed by others):
* A delegate submitting a work on behalf of an owner is automatically entered as an editor of the work.
* The owner is not listed as an editor but has actual edit access anyway.
* If the delegate assigns the owner as an additional editor, the owner receives an email that quotes their own name, not the delegate's name, which is confusing.  ("<your name> has added or removed you as an editor to the following works in Scholar@UC:")
* If the owner removes the delegate, the owner's name automatically replaces the delegate's name as an editor.  However, this isn't always quick - I was able to edit a work that still had my former delegate's name listed as an editor, and not my own, immediately after removing the delegate.  When I cancelled and then re-edited the work, my name appeared as editor.

Proposed behavior:
* A delegate submitting a work on behalf of an owner is automatically entered as an editor of the work.
* The owner is also automatically entered as an editor of the work.
* The owner does not receive an email saying that they have added themselves as an editor.
* When the owner removes the delegate, the delegate is removed as an editor, the owner remains as an editor.

**Comment by jamesvanmil** [comment]
Fix this by listing the owner as text near the editor form when a delegate is submitting on the owner's behalf - e.g. with JQuery
