### ISSUE TITLE
Text being displayed differently on work show page and catalog index page.

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#850]
Compare: https://scholar.uc.edu/catalog?utf8=%E2%9C%93&q=schultz+taught+things

> Things Taught is a &quot;book of questions without direct answers&quot; that &quot;seeks to acquaint [students] with the world.&quot;

And: https://scholar.uc.edu/works/documents/05742051f

> Things Taught is a "book of questions without direct answers" that "seeks to acquaint [students] with the world."

**Comment by lawhorkl** [comment]
just saw this on my email, looks like an issue with HTML scrubbing. Appending html_safe to the output may fix.


Kyle Lawhorn
Vice President | Cybercrime Cats
Student Software Developer
University of Cincinnati Libraries
CECH | IT:Cybersecurity

________________________________
