### ISSUE TITLE
Include Clermont and UCBA in Student Works drop-down

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#851]

**Comment by newmanld** [comment]
Clermont, Blue Ash and Law

**Comment by lisa3711** [comment]
With Sean's help, thought I had this. However, apparently not. I commiited my work to this branch:
[https://github.com/uclibs/curate/tree/feature/%23851_add_colleges](https://github.com/uclibs/curate/tree/feature/%23851_add_colleges)

On this page, errors, as below : .../app/helpers/curate_helper.rb

For Student work I get error:
TypeError no implicit conversion of Nil into array
(line 193)

On Generic Works, get error:
TypeError: no implicit conversion of Nil into hash. (line 178)

So- researched this and worked in console to see if I could identify problem... I can make the console do what i want, but not curate. 

If anyone has time or suggestions, let me know. I feel like its something stupid.

**Comment by lisa3711** [comment]
From: /curate/blob/develop/config/college_and_department.yml

Issue should match this:

- Student works:
  - current_colleges_for_degrees + additonal_current_ Colleges **-Libraries**

- Generic works:
  - current_colleges_for_degrees+additional_current_colleges 

- ETD's: 
   - current_colleges_for_degrees+legacy Colleges
