### ISSUE TITLE
Add ORCID integration

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#854]

**Comment by crowesn** [comment]
Size: 16

**Comment by scherztc** [comment]
https://github.com/VTUL/data-repo/pull/5

**Comment by crowesn** [comment]
This was implemented pretty smoothly with the orcid gem, partially I think because Scholar 3x doesn't yet have shibboleth integration. Was it @hortongn who set up shibboleth previously?

See also #937

**Comment by crowesn** [comment]
Change ORCID university account name to "University of Cincinnati"

**Comment by scherztc** [comment]
Deploy to scholar-dev.uc.edu.  Document.  Updated ORCID Application Profile.  Callback_URL ....

**Comment by crowesn** [comment]
Holding for #954
