### ISSUE TITLE
Research Sufia ingestion

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#855]

**Comment by crowesn** [comment]
Size: 4

**Comment by 13miciunasl** [comment]
[Untitled Diagram.pdf](https://github.com/uclibs/scholar_uc/files/430367/Untitled.Diagram.pdf)

**Comment by 13miciunasl** [comment]
![sufia_ingestion_flowchart](https://cloud.githubusercontent.com/assets/9759017/17858348/5752338e-6853-11e6-9c7e-99d41cdc4fae.png)

**Comment by 13miciunasl** [comment]
[Sufia Submit form](https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/base/_form_progress.html.erb)
[CurationConcernsController](https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb)
[Sufia WorksControllerBehavior](https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/works_controller_behavior.rb)
[CurationConcerns base_actor](https://github.com/projecthydra/curation_concerns/blob/master/app/actors/curation_concerns/actors/base_actor.rb)
[Sufia CreateWithFilesActor](https://github.com/projecthydra/sufia/blob/8815463ed58fdf61921dcbe0ecdd0f41671107e6/app/actors/sufia/create_with_files_actor.rb)
[Sufia AttachFilesToWorkJob](https://github.com/projecthydra/sufia/blob/master/app/jobs/attach_files_to_work_job.rb)
[CurationConcerns file_set_actor](https://github.com/projecthydra/curation_concerns/blob/master/app/actors/curation_concerns/actors/file_set_actor.rb)
[CurationConcerns file_actor](https://github.com/projecthydra/curation_concerns/blob/3678692b1d8958147356a9d6e2aef210b2d7931f/app/actors/curation_concerns/actors/file_actor.rb)
[CurationConcerns ingest_local_file_job](https://github.com/projecthydra/curation_concerns/blob/c71be6167f52292cd20e021e58509fe20c75a0e7/app/jobs/ingest_local_file_job.rb)
