### ISSUE TITLE
Research Sufia partials / overrides

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#857]

**Comment by crowesn** [comment]
Size: 2

**Comment by crowesn** [comment]
[Guide on engine overrides](http://edgeguides.rubyonrails.org/engines.html#overriding-views)

**Comment by scherztc** [comment]
During swarm last week we discussed when to fork the SUFIA gem.  In an effort to keep our code in sync with the hydra community, we are going to hold off on forking the gem until necessary.  Most of our initial issues can be resolved with application over-rides.  We do expect at some point to have to fork the gem.

**Comment by scherztc** [comment]
_controls.html.erb	
_flash_msg.html.erb	
_ga.html.erb	
_head_tag_extras.html.erb	
_logo.html.erb	
_masthead.html.erb	
_toolbar.html.erb	
_user_util_links.html.erb
