### ISSUE TITLE
Pin Sufia to release in github

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#865]

**Comment by crowesn** [comment]
Score: 2

**Comment by scherztc** [comment]
Make sure we at least have the version of SUFIA with File Manger and Admin Sets built in.  I am checking with Mike Giarlo on whether that is 7.1.0 or not.

**Comment by scherztc** [comment]
After talking with Justin, I would keep our application pinned to master.  I want to explore these two features.
