### ISSUE TITLE
Research pros / cons of multi and single work type modeling

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#873]

**Comment by crowesn** [comment]
Score: 8

**Comment by crowesn** [comment]
Look at community chatter re fancy forms, ui

**Comment by scherztc** [comment]
File Pathing and Google scholar and site indexing.

**Comment by scherztc** [comment]
This link may come in handy for AJAX form generation:  https://groups.google.com/forum/#!msg/hydra-tech/-C18LZhIBIA/FqgtBEiKBgAJ

**Comment by scherztc** [comment]
See this recent thread on Hydra Tech about multiple work types in SUFIA:  https://groups.google.com/forum/#!topic/hydra-tech/5UmaR1oTITY

**Comment by scherztc** [comment]
We are going to go with multiple work types in Scholar 3.0.  We are going to work with the Hydra community to finalized the UX work.
