### ISSUE TITLE
Research Fedora 4 object structure, datastreams, etc

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#874]
Prep for migration, multiwork to single.

**Comment by crowesn** [comment]
Score: 8

**Comment by scherztc** [comment]
In Fedora 4, datastreams have lost their importance as we can now store metadata in RDF graphs via LDP.

**Comment by scherztc** [comment]
The direction AF is headed is to parse these descriptive files and place the resulting metadata as RDF on a node. For example, in Hydra::Works, we parse a FITS file and place RDF triples on the fcr:metadata node of the file. For more complex xml schemas where there aren't clear conversions from the XML to the RDF, you can still store the xml file just like any other. However, to utilize its metadata, you're presented with an indexing problem.

**Comment by scherztc** [comment]
Here is what a sufia submitted work looks like in Fedora 4: http://curly.libraries.uc.edu:8984/rest/dev/hm/50/tr/78/hm50tr78v

**Comment by scherztc** [comment]
Here is the object in Fedora4 for the attached file (child object): http://curly.libraries.uc.edu:8984/rest/dev/70/79/57/70/707957706

**Comment by scherztc** [comment]
SPARQL Queries:  https://wiki.duraspace.org/display/FEDORA40/SPARQL+Recipes

**Comment by scherztc** [comment]
[F4-Hands-on.pdf](https://github.com/uclibs/scholar_uc/files/503644/F4-Hands-on.pdf)

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/wiki/Fedora4-Structure-and-Sparql-Examples
