### ISSUE TITLE
Manual testing with product owners

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#875]
Share test script, create google doc for them to submit feedback.

**Comment by crowesn** [comment]
Score 2

**Comment by scherztc** [comment]
Feedback Document: https://docs.google.com/document/d/14XpsL_3QbpltUQOXO2SEInIx7mfsfQN3-1m586Psjws/edit
Use Case Trello Board: https://trello.com/b/IRACCuwi/use-cases

**Comment by scherztc** [comment]
All of the items for the feedback document have been turned into Use Cases on the trello board.
