### ISSUE TITLE
Confirm: What happens when I generate a 2nd work type?

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#876]
If I create a second curation concern via the work generator, what happens? Needs testing in the UI. Do things break? Are the 2nd through nth curation concerns ignored/hidden? Do they magically work (not likely)? We should document what the current behavior is so we can ticketize the remaining work.

I generated a new work type called 'snowflake'.

There are 2 'Create work' links on the dashboard. They share a hover animation but can be clicked on separately. They link to different routes (/concern/generic_works/new and /concern/snowflakes/new).
There are also 2 'New Work' links under the 'Works' menu item in the top bar.
On each 'new work' page there is no indication of what kind of work you're creating. Expect 'Create new Work' and 'Create new Snowflake'.
On Create new Snowflake page metadata help text is missing.
On 'My Works' works listing, the filter by work type groups both objects into the same category, called 'Work'. Expect one for 'Work' and one for 'Snowflake'. Same on search results page.
In Batch Create there is no way to tell what kind of work will be created. Should 'resource type' be tied to 'work type' in some way? Should 'work type' be added to the files upload form? After uploading I can see that both were created as Snowflakes.
I tested create work, batch create, and search. I added some works to a collection. I poked around a little. I didn't run into any fatal errors. Let me know if there is some other functionality you're concerned or curious about.

https://github.com/projecthydra/sufia/issues/2435

**Comment by lisa3711** [comment]
This is something different than I thought. Have to talk to Thomas about what we want to achieve with this issue. 


For further discussion:
- Create Work

- Click "Additional Fields"

- (Last Choice) Resource Type:
Audio
Book
Capstone Project
Conference Proceeding
Dataset
Dissertation
Image
Journal
Map or Cartographic Material
Masters Thesis
Part of Book
Poster
Presentation
Project
Report
Research Paper
Software or Program Code
Video
Other

**Comment by scherztc** [comment]
https://github.com/projecthydra/sufia/issues/2199
