### ISSUE TITLE
DOI minting for works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#877]

**Comment by scherztc** [comment]
Size:  16

**Comment by jamesvanmil** [comment]
Making good progress on this, keeping track of problems/needed dependencies here:

* Need support for `/show/#{pid}` URLs (as with Curate) - I don't think this needs PO review, as we're committed to supporting the this path from Scholar 2.0
* Default Sufia allows multiple identifiers - Scholar 2.0 did not. If we want to maintain multiple identifiers we'll need to add a new property for DOIs
* I'm adding several properties to the work - will need proper predicates for these
