### ISSUE TITLE
Repository manager

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#878]
Does Admin Sets have any bearing on this?

**Comment by scherztc** [comment]
Size: 4

**Comment by crowesn** [comment]
https://github.com/projecthydra/sufia/issues/2439

**Comment by crowesn** [comment]
![screen shot 2016-09-15 at 3 00 11 pm](https://cloud.githubusercontent.com/assets/1069588/18563313/341d7f3a-7b55-11e6-8e6c-3d8f877836cd.png)
![screen shot 2016-09-15 at 3 00 23 pm](https://cloud.githubusercontent.com/assets/1069588/18563312/341c9aca-7b55-11e6-8c25-e422e1c179b4.png)

**Comment by crowesn** [comment]
wiki: https://github.com/uclibs/scholar_uc/wiki/Administrative-User

**Comment by crowesn** [comment]
Still waiting on specs/factory infrastructure.

**Comment by lawhorkl** [comment]
I could put the factories in a new branch and push them up. Still working on specs.

**Comment by scherztc** [comment]
Checkout Curly's Admin features related to Admin Sets: http://curly.libraries.uc.edu:3000/admin/admin_sets

Must use admin@example.com

**Comment by crowesn** [comment]
Admin role and UI seems to be in flux with the Sufia Developers - wondering if we should hold this.
