### ISSUE TITLE
Migrate static help pages

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#885]
Depends on #884

**Comment by scherztc** [comment]
Size: 2

**Comment by crowesn** [comment]
To set up the splash page, I added a `page_requests_controller` and view directory. You can use this following the pattern in scholar 2.x

[link](https://github.com/uclibs/scholar_uc/blob/release-3/initial_commit/app/controllers/page_requests_controller.rb)

**Comment by lisa3711** [comment]
As I understand, I am waiting on #884? 
Sufia has pages under - /app/views/static ...[https://github.com/projecthydra/sufia/tree/master/app/views/static]
