### ISSUE TITLE
Implement email notifications in Scholar 3

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#886]
Need to review Scholar 2 email functionality and current Sufia notification/email decide what's important to port.

Includes:
- New user emails
- Change manager notification emails

**Comment by scherztc** [comment]
Email on creation or first login.
Email on editorship/proxy role.
Email on embargo.

**Comment by lawhorkl** [comment]
possible tie in point:

app/controllers/concerns/sufia/dashboard_controller_behavior.rb

**Comment by lawhorkl** [comment]
we dont even need the change manager gem as from reading mailboxer's docs say: https://github.com/mailboxer/mailboxer

**Comment by lawhorkl** [comment]
test more on embargoes and proxy actions

**Comment by lawhorkl** [comment]
investigate dashboard behavior more about what does and does not get sent

send email to @ntallman about new email content in scholar 3

**Comment by lawhorkl** [comment]
report from dashboard testing:

Behavior on proxy batch create:
* Generates a notification for each work created and a separate one for when the work is transferred to the proxied owner.
* Location of batch create:

Behavior on non-proxy batch create:
* Generates a notification for each work created.

**Comment by scherztc** [comment]
Size: 4

**Comment by lawhorkl** [comment]
We will probably need to wait for Shibboleth integration for the welcome email

**Comment by jamesvanmil** [comment]
Currently blocked by #1137
