### ISSUE TITLE
Migrate contact form

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#888]

**Comment by crowesn** [comment]
Size: 4

**Comment by crowesn** [comment]
Scholar 2.x:
![screen shot 2016-09-27 at 3 04 57 pm](https://cloud.githubusercontent.com/assets/1069588/18887821/cea682c8-84c3-11e6-9f96-7394128d101f.png)
Sufia:
![screen shot 2016-09-27 at 3 05 06 pm](https://cloud.githubusercontent.com/assets/1069588/18887820/ce9bb4d8-84c3-11e6-8f6b-f164bfc49c6f.png)

**Comment by crowesn** [comment]
Waiting for feedback from POs: https://trello.com/c/rgJLd3E9

**Comment by crowesn** [comment]
Decision to omit issue type dropdown.

**Comment by crowesn** [comment]
https://github.com/projecthydra/sufia/issues/1587
