### ISSUE TITLE
Able to add works to collections I cannot access

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#893]
On the collections tab for a work, I see collections that I do not own, and I'm able to select one as a collection for my work and save the work.

**Comment by scherztc** [comment]
Size: 8

**Comment by scherztc** [comment]
Hydra community did some work on sufia and collections, please confirm that bug still exist.

**Comment by crowesn** [comment]
Related https://github.com/projecthydra/sufia/issues/2451

**Comment by crowesn** [comment]
Looks like this is resolved in Sufia 7.3

**Comment by crowesn** [comment]
This is resolved in Sufia 7.3
