### ISSUE TITLE
Add College and Department metadata

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#895]
If feasible, best to pursue with nested metadata.

Complete implementation depends on addition of Shibboleth authentication and associated user uc department in the account information.

Related https://github.com/uclibs/scholar_uc/issues/787

**Comment by scherztc** [comment]
See : https://github.com/projecthydra/sufia/wiki/Customizing-Metadata#customizing-the-work-type-to-include-a-controlled-vocabulary-property

**Comment by hortongn** [comment]
Relevant work in Curate: https://github.com/uclibs/curate/commit/b900b10be2c300e6bb921dc8cec5ca1126bd6724
