### ISSUE TITLE
IIIF display of images

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#898]
When the file is an image type, display the image with OpenSeadragon.

This will require a redesign of the work show page to make room for the viewer.

**Comment by scherztc** [comment]
Look into iiif manifest. (XML)
What can we do with it?

**Comment by scherztc** [comment]
Looks like we are going to need a triple store to do the searching necessary for loris image retrieval.

https://github.com/loris-imageserver/loris/pull/208

https://wiki.duraspace.org/display/FEDORA40/External+Triplestore

**Comment by scherztc** [comment]
You also need to set up the Camel routes to update the triplestore index when resources in Fedora change.

**Comment by scherztc** [comment]
That is the property you will be searching by, whose value should match the identifier passed to Loris. E.g. if you have http://my.image.server.edu/iiif/abc123/[other IIIF parameters] and abc123 is the value of an identifier that you have established for all the images in your repo,  say "myns:uid", you will set this configuration value to "myns:uid".

[12:52]  
Depending on the way you are structuring your images you can also pass a completely customized query.

**Comment by scherztc** [comment]
Blazegraph : https://superb-dca2.dl.sourceforge.net/project/bigdata/bigdata/2.1.1/blazegraph.jar

java -server -Xmx4g -jar blazegraph.jar

**Comment by scherztc** [comment]
Size: 8

**Comment by scherztc** [comment]
This is what they use in Hyku:  https://github.com/projecthydra-labs/hyku/commit/64792dea613eb0ab0b1faf583a89e407dfe605e7

If we are going to use RIIIF then we will need clean up strategies for caches:  https://groups.google.com/forum/#!topic/hydra-tech/cdppQubRJak

**Comment by scherztc** [comment]
https://github.com/projecthydra-labs/hyku/commit/4304a3954fe38b841335eebb813b1e61abaec05b
