### ISSUE TITLE
Permit actions from the catalog browse?

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#902]
In Scholar 1/2, a user could add works to the collection and navigate to edit works from the catalog views. 

In Sufia neither action is possible:
- Works must be added to collections from either the collection edit view (where the user is required to identify the work by pid), or from the work-edit/collections view tab (where a list of collections is displayed), or in a batch from the "My Works" dashboard view.
- Works may be edited from the work show view, or via a menu on the "My Works" dashboard view

**Comment by crowesn** [comment]
Size: 4

**Comment by lawhorkl** [comment]
current ui:

![image](https://cloud.githubusercontent.com/assets/12615997/19047894/d6512d4a-8971-11e6-8d22-5056017735c3.png)

proposed changes: (pending)

**Comment by scherztc** [comment]
How about something like this?  This is how we do it in Curation_Concerns.
![screen shot 2016-10-03 at 3 34 41 pm](https://cloud.githubusercontent.com/assets/5084562/19051010/1c6cf504-897f-11e6-9760-e5889bbfe166.png)

**Comment by lawhorkl** [comment]
Whatever works is OK with me. Better to check with the POs on trello/slack

**Comment by crowesn** [comment]
This seems like it's part of a larger conversation about catalog/browse vs. dashboard/control.

**Comment by scherztc** [comment]
In Scholar 3 (Sufia 7.3) management of works is done in the dashboard.
