### ISSUE TITLE
Add search bar to catalog view

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#904]
Currently only able to change the search by going to the root page - no search bar appears at `/catalog`/.

Clicking "Start Over" on the catalog view should lead to a view with full search abilities.

**Comment by lawhorkl** [comment]
i cant find any issue in sufia for this so ill see what i can do

**Comment by crowesn** [comment]
Size: 4

**Comment by scherztc** [comment]
When Sean re-ployed sufia without the splash page, we got the search bar back on the catalog view.
