### ISSUE TITLE
Collection titles displaying with quotes and brackets when adding works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#907]
When adding works to a collection from the "My Works" dashboard view, the collection titles are being displayed as:

["Title1"]
["Title2"]

This fix should be contributed to projecthydra/sufia.

**Comment by lawhorkl** [comment]
ill take this as an easy starter into working with sufia

**Comment by jamesvanmil** [comment]
Probably good to start by seeing if there's an issue open yet: https://github.com/projecthydra/sufia/issues

**Comment by lawhorkl** [comment]
@jamesvanmil looks like they already closed it:

https://github.com/projecthydra/sufia/issues/2405

**Comment by jamesvanmil** [comment]
Thanks! Closed with https://github.com/projecthydra/sufia/pull/2543
