### ISSUE TITLE
Feature tests for the application

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#908]
Development team should determine the appropriate level of application-level testing for features implemented in Sufia.

**Comment by scherztc** [comment]
Size:  8

**Comment by lawhorkl** [comment]
@scherztc and I talked we'll use the manual test script as a starting point.

**Comment by lawhorkl** [comment]
@crowesn ive pushed my progress so far to https://github.com/uclibs/scholar_uc/tree/maintenance/%23908-application-feature-tests

I'd have more if I were not facing the issues I have been this morning.

**Comment by crowesn** [comment]
http://stackoverflow.com/a/19105050/4930216

**Comment by lawhorkl** [comment]
handing this off to @crowesn
