### ISSUE TITLE
Add file edit permissions for added editors

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#910]
Added editors are able to edit work metadata and add new files to a work, but they are unable to edit attached files - even those attached files which they added.

**Comment by scherztc** [comment]
Next steps are to research about whether this should be happening and check with community about use of this function.

**Comment by scherztc** [comment]
Size: 8

**Comment by crowesn** [comment]
This is a know issue tagged for fix in 7.3.0 - https://github.com/projecthydra/sufia/issues/2820
