### ISSUE TITLE
page footer should stay at bottom of page

### ISSUE THREAD

**Issue by lawhorkl** [uclibs/scholar_uc#921]
the page footer in the UI should stay at the bottom of the page. 

i have experience in doing this sort of thing with bootstrap already, so ill go ahead and fix this up myself.

![image](https://cloud.githubusercontent.com/assets/12615997/18392202/ed851ffe-767e-11e6-8a77-60a0f3fdaf4c.png)

**Comment by scherztc** [comment]
Since this is a UX improvement, I want these to go through the POs (trello) before making it into github.  I am closing this to move it into the proper channels.
