### ISSUE TITLE
Strategy for handling download requests for file > 3 GB

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#930]
Scholar won't let users directly download files over 3 GB.  We will eventually start receiving emails from users requesting to receive those files.  So we need to procedure for fulfilling those requests.

We can extract the file from production Fedora, but we need to put the file somewhere that the user can access it.

**Comment by scherztc** [comment]
Globus might help here.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
