### ISSUE TITLE
set up issue and pull request templates

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#934]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by hortongn** [comment]
Sufia's .github templates: https://github.com/projecthydra/sufia/tree/master/.github

**Comment by crowesn** [comment]
>Tip: You must create your template in your repository's default branch. Templates created in other branches are not available for collaborators to use.

**Comment by crowesn** [comment]
Size: 2
