### ISSUE TITLE
Add Shibboleth integration

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#937]
Needs to play nice with ORCID gem: https://github.com/omniauth/omniauth/wiki/Managing-Multiple-Providers

Related #895 
Depends on https://github.com/uclibs/scholar_uc/issues/954

**Comment by crowesn** [comment]
Size: 16

**Comment by scherztc** [comment]
When should we deploy Scholar 3 to DEV?

That will require some updates to DEV web server.  redis-server, solr, fedora, ..
