### ISSUE TITLE
Research malware detection / clamav

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#952]
Look at stubbing for test suite.

**Comment by scherztc** [comment]
Size: 4

**Comment by hortongn** [comment]
Got virus scanning switched on.  Scholar catches it if I try to upload a test virus file.  However, it errors on the detect.  So I'll look into fixing that.

Sufia keeps newly uploaded files private until everything is processed by background workers.  So I'm assuming that if a virus is detected we want the file to stay private and a notification sent to the user/admin.
