### ISSUE TITLE
Start wiki page to document differences from vanilla Sufia

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#953]
Agreed in PO meeting that we should document features and enhancement that deviate from core Sufia, including a description of the change and technical details about how it was implemented.

**Comment by scherztc** [comment]
Size: 2

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/wiki/Scholar@UC-differences-from-vanilla-Sufia
