### ISSUE TITLE
Deployment: Get DEV server environment prepared

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#954]
Research, document requirements, etc.
Look at [requirements](https://github.com/uclibs/scholar_uc/wiki/sufia-7-Developer-Notes) associated with Sufia 7 in sandbox.

Document steps to upgrade so that we can make changes to puppet scripts.

**Comment by hortongn** [comment]
This is done except for a few small pieces.  Those pieces now have their own issues: https://github.com/uclibs/scholar_uc/issues/1547 https://github.com/uclibs/scholar_uc/issues/1360 https://github.com/uclibs/scholar_uc/issues/1061 https://github.com/uclibs/scholar_uc/issues/1059
