### ISSUE TITLE
Make it easier for devs to create admin users in development mode

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#959]
In Scholar 2.x we can make an admin user in development just by creating a manager@example.com user.  It sounds like we can make it just as easy in Scholar 3.x to do the same.  We can commit an `admin` section to our app's config/role_map.yml file and add an email address like `manager@example.com` to it.  

If we do that and commit the necessary hydra-role-management gem and abilities changes, then whenever we need an admin user we can just create a manager@example.com user.  No need to go through all the steps of creating the role each time we start a new branch.

**Comment by crowesn** [comment]
Size: 2
