### ISSUE TITLE
Change labels on "View Collections" and "View Works" buttons in the Dashboard.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#961]
### Descriptive summary

As a: User. I want: to change the labels of the buttons on the dashboard to say "View My Collections" and "View My Works" instead of “View Collections” and "View Work".  This label is a more accurate description of where the button takes the user. 
### Expected behavior

View My Works ->  My Works
View My Collections ->  My Collections
### Actual behavior

Label says:  "View Collections" and "View Works"
### Steps to reproduce the behavior
1. Visit Dashboard
### Related work

https://trello.com/c/PDRQpyO0/17-as-a-user-i-want-a-clearer-label-the-button-says-view-collections-so-that-is-better-represents-where-it-is-taken-us-to-my-collec

**Comment by crowesn** [comment]
Size: 2
