### ISSUE TITLE
Make rights attribute non-repeatable

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#966]
On a work you should only be able to set one rights statement - you are currently able to add multiples rights

**Comment by crowesn** [comment]
https://github.com/projecthydra/sufia/wiki/Customizing-Metadata#making-a-default-sufia-field-non-repeatable

**Comment by newmanld** [comment]
See https://github.com/projecthydra/sufia/issues/1287

**Comment by newmanld** [comment]
Looks like about to be a PR on projecthydra/sufia#1287.  Can we pull down the same code?

**Comment by scherztc** [comment]
Score: 4
