### ISSUE TITLE
Light cleanup on styles

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#967]
### Descriptive summary

Do a light cleanup of some of the style elements in the form input, etc.
1. Remove fill on #add-field button in the submission form
2. Add UC logo to the upper left-hand corner
3. Play with fonts

**Comment by scherztc** [comment]
Fixes https://trello.com/c/QNxgf4YD/7-as-a-user-i-want-to-have-a-clear-and-obvious-add-another-button-on-the-submission-form-criteria-approval-of-po-and-dev
