### ISSUE TITLE
Default to Public Visibility on Work creation

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#976]
As a content submitter/owner and repository manager.  I want the input form to default to the public visibility status, as it does in Scholar 2.x. So that: I am encouraged to submit public works, and I won't keep something private accidentally.

https://trello.com/c/0jmpYSL3/55-as-a-content-submitter-owner-and-repository-manager-i-want-the-input-form-to-default-to-the-public-visibility-status-as-it-does-

**Comment by crowesn** [comment]
Size: 2
