### ISSUE TITLE
Generate all work types

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#979]
~* Change Work to Generic Work~
* Generate:
  * Article
  * Image
  * Document
  * Student Work
  * ETD
  * Dataset
  * Video

For now, we'll stick with default metadata - will add all the fields and predicates after metadata SME review.

**Comment by crowesn** [comment]
Did we want to wait for 7.3 to run this?

**Comment by crowesn** [comment]
We could split this: 
* Rename work > generic_work
* Generate other worktypes once supported.

**Comment by crowesn** [comment]
Set up shared_examples for specs.

**Comment by scherztc** [comment]
Size: 8
