### ISSUE TITLE
Replace Work model/structure with GenericWork

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#982]
### Descriptive summary

Change Work model name to GenericWork.

1. `rails destroy sufia:work Work`
1. `rails generate sufia:work GenericWork`
1. Clean up specs

### Related work

Related: #979 

Size: 4

**Comment by scherztc** [comment]
How do you feel about Resource?

**Comment by crowesn** [comment]
I don't hate it.

**Comment by newmanld** [comment]
If GenericWork is going to stand in contrast to other work types, then I'd advocate for 'Other'.  All the other work types are also resources and works.  But if we end up with only one work type, then the mention of the work type should disappear from the UI altogether, it seems.

**Comment by crowesn** [comment]
After some discussion, we'll close this issue and stick with *Work* work-type for our default curation concern. We can potentially revisit when multi-work types are implemented in next sufia release.

**Comment by scherztc** [comment]
This is a screen shot from the latest version of sufia (7.2)  I think this might be a reason to rename our first work type to Generic Work.   The drop down menu uses the term New Work to expose a modal where you select the type of Work.  (i.e. Generic Work.)

![screen shot 2016-11-30 at 5 12 34 pm](https://cloud.githubusercontent.com/assets/5084562/20773563/6aab2c1c-b720-11e6-9f11-62ca75c40a4a.png)

I am going to re-open this issue.

**Comment by scherztc** [comment]
Resize: 8
