### ISSUE TITLE
Implement sitemap functionality. 

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#984]
### Descriptive summary

Implement sufia's sitemap functionality. 

### Expected behavior

Implement sufia's sitemap functionality. 

### Actual behavior

Necessary for search engines
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by scherztc** [comment]
Size: 4

**Comment by newmanld** [comment]
Although not necessary for Beta test, this does seem necessary for the production version of 3.0, in order to have search engines effectively index.  So I've moved to the Scholar 3.0 Migration milestone, instead of the Scholar 3.1 milestone.

**Comment by crowesn** [comment]
This should be built-in to Hyrax now, research solution.
Thoughts? @lawhorkl
