### ISSUE TITLE
Ability to create a work with only an external link URL

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#986]
### Descriptive summary

As a content submitter/owner. I want to: be able to submit works that have no files attached, as I can in Scholar 2.x. So that: I am able to create a work that references an external related work with an External Link URL, but does not have it's own attached files.

**Comment by crowesn** [comment]
There is now a [config setting](https://github.com/projecthydra/sufia/blob/f190a1bee78dbafca47e0e3c9dae327a98e2b198/lib/generators/sufia/templates/config/sufia.rb#L78) in sufia to disable the file requirement.

After flipping this setting, the file indicator is removed from the requirements widget
<img width="434" alt="screen shot 2016-11-16 at 2 56 31 pm" src="https://cloud.githubusercontent.com/assets/1069588/20363382/fc401e9a-ac0c-11e6-981f-f6a549f50861.png">

--

I noticed that after this change, we're still seeing flash notice about `files being processed` (even though there was no file attached. Also, there is a flash style notice at the bottom of the page stating that there are no files attached. The `files being processed` notice strikes me as confusing.

<img width="1067" alt="screen shot 2016-11-16 at 2 58 06 pm" src="https://cloud.githubusercontent.com/assets/1069588/20363514/7807c8e8-ac0d-11e6-9581-1348a7152d1b.png">

**Comment by crowesn** [comment]
Flash notice is set [here](https://github.com/projecthydra/sufia/blob/df5c2d19a84fe0a5012e5bb21973bfebd5ca92d4/app/controllers/concerns/sufia/works_controller_behavior.rb#L55)
