### ISSUE TITLE
Add catalog view sort by title

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#989]
### Descriptive summary

Add control to sort collections by title in catalog view.

### Related work

[Trello card](https://trello.com/c/ybueX4Ad/26-as-anyone-i-want-to-be-able-to-sort-the-catalog-view-by-title-so-that-i-can-better-discover-my-works-criteria-approval-by-po-and)

**Comment by crowesn** [comment]
* Don't use arrows to show active sort, use (A-z, z-a)
* Append title option to end of list
* Look at curate for inspiration

**Comment by scherztc** [comment]
Size : 2

**Comment by scherztc** [comment]
This is handled by the catalog_controller.rb : https://github.com/projecthydra/sufia/blob/d3e52e8bcbf5b5700c5e61057b236969306ef66e/lib/generators/sufia/templates/catalog_controller.rb

Although it is easy to configure the catalog_controller to use title for sorting, there is a solr architecture problem with multi-valued fields.  See error: 

RSolr::Error::Http - 400 Bad Request Error: 'can not sort on multivalued field: title_tesim','code'=>400}} 

This is different from curate, where title was a single valued field.  Sufia allows for multiple titles for a work.

**Comment by lisa3711** [comment]
Can I work with you on this?

**Comment by scherztc** [comment]
We can follow University of Alberta's issue:  https://github.com/ualbertalib/HydraNorth/commits/1263_sufia_migrate

**Comment by scherztc** [comment]
See this PR for Sufia 6: https://github.com/ualbertalib/HydraNorth/pull/1229/files

**Comment by scherztc** [comment]
rake solr:reindex is also broken in sufia 7.2 :  https://github.com/projecthydra/sufia/issues/2774

**Comment by scherztc** [comment]
Adding to the agenda for our Metadata meeting

**Comment by scherztc** [comment]
We will keep the title as multi-valued in the model.
We will hide the extra title fields on the input form.
We will add an alternate title to the model and form.
