### ISSUE TITLE
Add on-demand orcid sign-up to the orcid gem

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#996]
### Descriptive summary

Add a button that directs the user to the orcid sign-up page using a custom URL to populate the name and email fields.

### Expected behavior

On click, the user is sent to the orcid website where their name and scholar email address are already populated for them. After completing the form, the user is redirected back to Scholar and their new orcid ID is authenticated.

### Steps to reproduce the behavior

1. https://members.orcid.org/create-records
1. https://members.orcid.org/api/customize-oauth-login-screen
1. https://members.orcid.org/logos-web-graphics

### Related work

Issue #985

**Comment by scherztc** [comment]
Size: 4
